### ISSUE TITLE
Private comments in templates

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#10]
From: http://sourceforge.net/tracker/?func=detail&aid=3487205&group_id=509826&atid=2072662

It would be nice to have an opportunity to hide comments from showing up on production.

Reasons:
- template documentation
- hiding code of temporarily turned off functionalities

Suggested syntax:
< !--- private comment -- >
(one more dash in opening tag, means that comment is private)

Behaviour:
Such comment will be stripped out during parsing.

**Comment by eruiz** [comment]
Hi Daniel, I'm not sure which is the XML parser used to load templates, but perhaps it has an option to ignore comments, then the output won't write the XML comments because the Reader ignored them.

Regards

**Comment by danielfernandez** [comment]
The problem with that approach is that sometimes comments in templates should appear in the final result, and that way the user would not be given the possibility to do it.

Establishing a new syntax is my preferred solution.

**Comment by danielfernandez** [comment]
This is covered by #183.
