### ISSUE TITLE
Restrict calling methods in Class<?>

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#1021]
Further advancing on the restrictions to be applied on some objects and classes in Standard Expressions, objects of the `Class<?>` class should be restricted so that of all methods declared in `java.lang.Class` itself (_"declared methods"_) only the following should be allowed to be called:

- `getName`
- `isAssignableFrom`
- `isInstance`
- `isInterface`
- `isPrimitive`
- `isRecord`
- `isAnnotation`
- `isArray`
- `isEnum`

All other methods declared in `java.lang.Class` are now forbidden.

**Comment by Viserius** [comment]
@danielfernandez I am curious about this change, since it would allow .getName() to get the fully qualified class name, but it does not allow calling .getSimpleName to get just the name of the class

**Comment by ArnaudLec** [comment]
I'm also curious about this change. I understand that some methods should probably never be called but as Viserius pointed out, I'm failing to understand why `getSimpleName` and also `getCanonicalName` are forbidden when `getName` is allowed.
