### ISSUE TITLE
Modify ElementNameProcessorMatcher to enable non-prefixed element names

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#103]
Currently, ElementNameProcessorMatcher requires the element name (if set) to include the dialect prefix name.

So that processors can be created that match the entire element (element processors) but look for a set of specific configuration-oriented attributes inside the tags they apply to, it would be nice if the addition of the dialect prefix to the element name in this matcher is considered optional.

**Comment by tduchateau** [comment]
+1 ;-)
