### ISSUE TITLE
Precedence conflicts between dialects

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf#105]
Hi!

It could be great to "abstract" the dialect's precedence and make it relative to existing dialects, in order to avoid conflicts.
So all the dialect's processor would be linked (e.g. with new constructors which would allow to increment/decrement their precedence relatively to other ones) but there would be no conflict at all.

Thanks!

**Comment by danielfernandez** [comment]
Note: this should be implemented avoiding direct compile-time dependencies among dialects (therefore declaring dependencies using dialect class names and not dialect class objects).

**Comment by danielfernandez** [comment]
This is already a part of the new Processor and Dialect APIs in Thymeleaf 3.0. See #399 and #401

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
