### ISSUE TITLE
New appending attribute for inline style.

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf#107]
Hi, it could be sometimes useful to have appending attribute for inline style. Something like `th:styleappend` that can work same way like `th:classappend` but appends to inline style attribute.

**Comment by danielfernandez** [comment]
Good idea Michal. If you feel like preparing a pull request for thymeleaf 2.1... ;-)

**Comment by danielfernandez** [comment]
Updated 2.1.3-SNAPSHOT
