### ISSUE TITLE
Remove empty lines from generated HTML document.

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf#108]
Hi, it could useful to have feature to remove empty lines from generated HTML document by Thymeleaf. Empty lines occurring after using `th:remove` attribute. It could be made implicitly or one can turn this feature on in configuration. Motivation - sometimes size of generate document matters.

**Comment by rymsha** [comment]
I agree this might be a good feature of thymeleaf because it knows dom tree of templates it can reconstruct page without un nided empty spaces and html comments with nearly zero performance drop.
So, solutions like https://code.google.com/p/htmlcompressor/ could be avoided.

**Comment by danielfernandez** [comment]
Note: the best way to do this seems to be an implementation of `ITemplateWriter`. Queued for 3.0.

**Comment by bingozzzz** [comment]
I defined  an custom ITemplateWriter to remove empty lines.

``` java
public class SkipSpaceLineXhtmlHtml5TemplateWriter extends AbstractGeneralTemplateWriter {
...

    @Override
    protected void writeText(final Arguments arguments, final Writer writer, final Text text) 
            throws IOException {
        char[] contents = text.unsafeGetContentCharArray();
        String contentString = new String(contents);
        if(contentString!=null && !contentString.isEmpty() && contentString.trim().length() == 0){
            return;
        }else{
            super.writeText(arguments, writer, text);
        }
    }

    @Override
    public void writeNode(final Arguments arguments, final Writer writer, final Node node) 
            throws IOException {
        super.writeNode(arguments, writer, node);
        if (node instanceof Element) {
            writer.write("\n");
        }else if (node instanceof Comment) {
            writer.write("\n");
        } 

    }


}
```

lTemplateWriter configuration:

``` java
public class SkipSpaceLineTemplateModeHandlers {



    // We have to set a maximum pool size. Some environments might set too high
    // numbers for Runtime.availableProcessors (for example, Google App Engine sets
    // this to 1337).
    private final static int MAX_PARSERS_POOL_SIZE = 24;

    public final static ITemplateModeHandler XML;
    public final static ITemplateModeHandler VALIDXML;
    public final static ITemplateModeHandler XHTML;
    public final static ITemplateModeHandler VALIDXHTML;
    public final static ITemplateModeHandler HTML5;
    public final static ITemplateModeHandler LEGACYHTML5;


    public final static Set<ITemplateModeHandler> ALL_TEMPLATE_MODE_HANDLERS;



    static {

        final int availableProcessors = Runtime.getRuntime().availableProcessors();
        final int poolSize = 
                Math.min(
                        (availableProcessors <= 2? availableProcessors : availableProcessors - 1),
                        MAX_PARSERS_POOL_SIZE);

        XML = new TemplateModeHandler(
                "XML",
                new XmlNonValidatingSAXTemplateParser(poolSize),
                new XmlTemplateWriter());
        VALIDXML = new TemplateModeHandler(
                "VALIDXML", 
                new XmlValidatingSAXTemplateParser(poolSize),
                new XmlTemplateWriter());
        XHTML = new TemplateModeHandler(
                "XHTML", 
                new XhtmlAndHtml5NonValidatingSAXTemplateParser(poolSize),
                new SkipSpaceLineXhtmlHtml5TemplateWriter());
        VALIDXHTML = new TemplateModeHandler(
                "VALIDXHTML", 
                new XhtmlValidatingSAXTemplateParser(poolSize),
                new SkipSpaceLineXhtmlHtml5TemplateWriter());
        HTML5 = new TemplateModeHandler(
                "HTML5", 
                new XhtmlAndHtml5NonValidatingSAXTemplateParser(poolSize),
                new SkipSpaceLineXhtmlHtml5TemplateWriter());
        LEGACYHTML5 = new TemplateModeHandler(
                "LEGACYHTML5", 
                new LegacyHtml5TemplateParser("LEGACYHTML5", poolSize),
                new SkipSpaceLineXhtmlHtml5TemplateWriter());

        ALL_TEMPLATE_MODE_HANDLERS =
                new HashSet<ITemplateModeHandler>(
                        Arrays.asList(
                                new ITemplateModeHandler[] { XML, VALIDXML, XHTML, VALIDXHTML, HTML5, LEGACYHTML5 }));

    }


    public static Set<ITemplateModeHandler> getITemplateModeHandler(){
        return SkipSpaceLineTemplateModeHandlers.ALL_TEMPLATE_MODE_HANDLERS;
    }

}
```

spring mvc view configuration:

``` xml
    <bean id="templateEngine" class="org.thymeleaf.spring3.SpringTemplateEngine">
        <property name="templateResolver" ref="templateResolver" />
        <property name="templateModeHandlers" ref="skipSpaceLineXhtmlHtml5TemplateWriter" />
        <property name="messageSource" ref="messageSource"></property>
        <property name="additionalDialects">
            <set>
                <bean class="com.embracesource.base.mvc.thymeleaf.UtilDialect" />
            </set>
        </property>
    </bean>
    <bean id="skipSpaceLineXhtmlHtml5TemplateWriter"
        class="xx.SkipSpaceLineXhtmlHtml5TemplateWriter"
        factory-method="getITemplateModeHandler"></bean>

```

**Comment by rodionovsasha** [comment]
There is no more public method org.thymeleaf.dom.Text#unsafeGetContentCharArray in new version (2.1.4.RELEASE).

What about the following approach:

@Override
    protected void writeText(final Arguments arguments, final Writer writer, final Text text) throws IOException {
        final char[] textChars = text.getContent().toCharArray();
        if (StringUtils.hasText(CharBuffer.wrap(textChars))) {
            writer.write(textChars);
        }
    }

**Comment by danielfernandez** [comment]
Thymeleaf 3.0 now includes a **Post-Processor API** (see #400 and #401). A whitespace-collapsing utility looks like the perfect use case for a post-processor, provided by a custom dialect.

Will close this as declined, as I don't think it should be a part of the core or the Standard Dialects.

**Comment by cruftex** [comment]
+1 for keeping it open.

I think Thymeleaf should have a standard solution for this. In what artifact it is included, is another discussion. We might take a look at this and do a contribution, so additional hints and +1 are welcome :)

**Comment by H-Lo** [comment]
Really sad decision.  Perfect case would be that the engine does NOT create emply lines at all, and not that we have to write additional software to fix those bad practice of creating empty lines.

**Comment by H-Lo** [comment]
If I put this snippet on a page, I expect no empty line because there is nothing to show.
<script th:if="${ wannaShow == false }">
alert("Hello world!");
</script>

**Comment by yerodriguez** [comment]
I came across same issue with Thymeleaf output: it had a lots of white space.
The solution provided by @bingozzzz does not work on 3.0.

I resolved by creating a custom class implementing IPostProcessorDialect  and in that Dialect I referenced a custom Template Handler (extending AbstractTemplateHandler). The work of removing empty text is taken care of by the impl of the AbstractTemplateHandler.

See below:



public class CustomTemplateHandler extends AbstractTemplateHandler {  
	  @Override
	  public void handleText(IText text) {
		if(text.getText() != null && !text.getText().isEmpty() && text.getText().trim().length() == 0) {
		  // Remove unused space
		  return;
		} else {
		  super.handleText(text);  
		}
	  }  
}

public static class CustomTemplateProcessor implements IPostProcessorDialect {
    
    @Override
    public String getName() {
      return "CustomTemplatePostProcessor";
    }
    
    @Override
    public Set<IPostProcessor> getPostProcessors() {
      Set<IPostProcessor> processors = new HashSet<>(); 
        processors.add(new PostProcessor(TemplateMode.HTML, CustomTemplateHandler.class, Integer.MAX_VALUE));
      return processors;
    }
    
    @Override
    public int getDialectPostProcessorPrecedence() {
      return 0;
    }
  }

TemplateEngine templateEngine = new TemplateEngine();
templateEngine.addDialect(new ThymeleafProcessor.CustomTemplateProcessor());

**Comment by sagarvilas** [comment]
@yerodriguez I have somewhat similar requirement and decided to follow the same approach as yours but how do you manipulate Itext in handleText method, IText is immutable.

**Comment by H-Lo** [comment]
@sagarvilas Please try with this:

```
import org.apache.commons.lang3.StringUtils;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.io.PrintWriter;
import java.util.Arrays;
import java.util.function.Predicate;
import java.util.stream.Collectors;

import jakarta.servlet.Filter;
import jakarta.servlet.FilterChain;
import jakarta.servlet.FilterConfig;
import jakarta.servlet.ServletException;
import jakarta.servlet.ServletRequest;
import jakarta.servlet.ServletResponse;
import jakarta.servlet.http.HttpServletRequest;
import jakarta.servlet.http.HttpServletResponse;

@Component
public class CustomHttpServletResponseFilter implements Filter {

    public static final String  CR           = "\r";
    public static final String  LF           = "\n";
    public static final String  CRLF         = CR + LF;
    public static final Pattern CRLF_PATTERN = Pattern.compile(CRLF);

    @Override
    public void doFilter(
        final ServletRequest request,
        final ServletResponse response,
        final FilterChain chain
    ) throws IOException, ServletException {

        final ServletResponse newResponse =
            (request instanceof HttpServletRequest)
                ? new CustomHttpServletResponseWrapper((HttpServletResponse) response)
                : response;

        chain.doFilter(request, newResponse);

        String text = newResponse.toString();
        if (text == null || text.isEmpty()) {
            return;
        }

        if (!(newResponse instanceof CustomHttpServletResponseWrapper)) {
            return;
        }
  
        try (final PrintWriter writer = response.getWriter()) {

            // remove empty lines
            text =
                Arrays.stream( CRLF_PATTERN.split( text ) )
                    .filter( Predicate.not( StringUtils::isBlank ) )
                    .collect( Collectors.joining( CRLF ) );
                
            // trim each line
            text =
                Arrays.stream( CRLF_PATTERN.split( text ) )
                    .map( String::trim )
                    .collect( Collectors.joining( CRLF ) );
                                
            writer.write(text);
        }

    }

}
```

**Comment by sagarvilas** [comment]
@H-Lo thanks for your answer but it is completely unrelated to my question.

**Comment by yerodriguez** [comment]
Hi @sagarvilas,

The solution described here does not change the object but excludes it from processing.
https://github.com/thymeleaf/thymeleaf/issues/108#issuecomment-761724887

CustomTemplateHandler checks if the IText object fits specific exclusion criteria and excludes from template processing if it is the case; however, if the current IText element should not be excluded, it continues to process it.

Wondering if you have a specific use case other than this one.

**Comment by sagarvilas** [comment]
Hi @yerodriguez this is my usecase.
`org.thymeleaf.standard.processor.StandardTextTagProcessor#produceEscapedOutput` method performs `XmlEscape.escapeXml10` on `th:text` in case of XML template. I do not want it to be escaped, I know there is an option to use `th:utext` for un-escaped text but I have too many templates scattered over places to find and fix them all. My idea was to use the `IPostProcessorDialect` to un-escape the text after the processor has performed the escape, but I can not find a good example of how to achieve this. So far this is what I have done. Implemented `IPostProcessorDialect`, implemented a custom `IPostProcessor` to be returned by `IPostProcessorDialect,getPostProcessors()` extended `AbstractTemplateHandler` and overridden the `handleText` method, now I want to un-escape the text in IText.

**Comment by H-Lo** [comment]
@sagarvilas Well I wouldn't say unrelated because it does remove emtpy lines - that's a solution I created after thymeleaf rejected idea of doing it while rendering. At lease someone will be happy with it as I would be if I had a chance to find it here instead of inventing it.

**Comment by yerodriguez** [comment]
> Hi @yerodriguez this is my usecase. `org.thymeleaf.standard.processor.StandardTextTagProcessor#produceEscapedOutput` method performs `XmlEscape.escapeXml10` on `th:text` in case of XML template. I do not want it to be escaped, I know there is an option to use `th:utext` for un-escaped text but I have too many templates scattered over places to find and fix them all. My idea was to use the `IPostProcessorDialect` to un-escape the text after the processor has performed the escape, but I can not find a good example of how to achieve this. So far this is what I have done. Implemented `IPostProcessorDialect`, implemented a custom `IPostProcessor` to be returned by `IPostProcessorDialect,getPostProcessors()` extended `AbstractTemplateHandler` and overridden the `handleText` method, now I want to un-escape the text in IText.

Two options come to mind:
1. in your existing handleText override, create new instance of IText using existing instance and modify text at this point (getText)
2. Extend AbstractTextProcessor and overide doProcess() to modify text

**Comment by sagarvilas** [comment]
@yerodriguez thanks for the suggestion, I opted suggestion 2, though 1 option sounds intuitive, I was surprised by the effort required to achieve a small change. Thanks  for taking time to answer the question.
