### ISSUE TITLE
Thymeleaf comments

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf#110]
I'm missing feature in Thymeleaf that provide you comments in your source code. HTML comments is not suitable because they remain in generated HTML document.

**Comment by ultraq** [comment]
I thought for a moment that this feature had already been implemented (I remember some talk about this in the forums a few months ago), but I looked through the current list of issues and found the original issue / feature request, set for Thymeleaf 2.1: https://github.com/thymeleaf/thymeleaf/issues/10

**Comment by kreuzman** [comment]
Thanks Emanuel for link I missed this one. That way I'm closing this issue.
