### ISSUE TITLE
Node selectors

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf#111]
Hi!

Some useful methods already exist for server-side DOM manipulation/selection : addChild, extractChild, getFirstChild, ...
Also it would be very useful if you could add some other methods, a bit like jQuery selectors.

<hr />

```
List<Node> getNodesByAttributeValue(String value)
```

Examples : 

<ul>
<li>I want all nodes that have a "foo" CSS class</li>
<li>I want  the node that has a given HTML id</li>
</ul>

<hr />

```
List<Node> getNodesByName(String name)
```

Example : 

<ul>
<li>I want all div nodes inside the node from which the method was called</li>
</ul>

<hr />

```
boolean contains(String stringToTest)
```

Example : 

<ul>
<li>I want to know if the current Node/Element contains the string inside any of its child Text nodes</li>
</ul>

<hr />

```
Node getLastChild()
```

Not far from the existing getFirstChild ;-)

<hr />

Lots of examples can be found [here](http://api.jquery.com/category/selectors/)

**Comment by danielfernandez** [comment]
This are nice ideas for 3.0, when the existing DOM implementation and utilities will undergo a major overhaul.

**Comment by danielfernandez** [comment]
The new architecture in Thymeleaf 3.0 does not work on a DOM model anymore, so this is no longer valid.
