### ISSUE TITLE
Add some sort of case/switch/decode expression to the Standard Expression language

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#112]
It would be nice to be able to do something similar to a "case"/"switch" expression, like:

```
<div th:class="${someVariable} ??
                         'avalue' : 'anexpression', 
                         ${anotherValue} : #{otherexpression}">
```

**Comment by sukhokri** [comment]
Hello, although the topic is quite old, may I ask if it is still possible to try contributing an implementation of this feature? If yes, could you, please, assign this to me? The helping tips would also be very appreciated.

**Comment by danielfernandez** [comment]
Ahoj Kristina, thanks for your interest.

The classes supporting the Thymeleaf Standard Expression system live at the `org.thymeleaf.standard.expression` package. Specifically, this would be a _complex_ expression (note there are simple and complex ones). Every complex expression is executed in two phases: _parsing_ and _executing_, the former being in charge of identifying whether a fragment of expression is actually of the type we are looking for (in this case, a switch), and the latter obviously in charge of executing the expression on the data.

We are right now in the process of releasing 3.0 (right now in BETA02) so this feature being a syntax change it would probably not be released until at least 3.1.0. Right now we still don't have a branch for 3.1 development, but we should be creating it soon after 3.0.0 goes GA. For the moment, working on your local fork of the `3.0-dev` branch should be just fine.

Of course, don't hesitate asking for any information you might need.

**Comment by sukhokri** [comment]
Thank you for your reply. I will get to it as soon as possible.

**Comment by sukhokri** [comment]
Hello, excuse me for long silence. Would you be so kind as to check the code I commited: https://github.com/thymeleaf/thymeleaf/pulls? I'd probably need to fix something, so I'm asking for your guidance. Thank you :)

**Comment by danielfernandez** [comment]
Thanks Kristina. Please allow us some days. We've just published Thymeleaf 3 and there's still quite a lot of urgent doc work to do (and a conference to prepare :)). We'll review your code as soon as possible.

**Comment by tburny** [comment]
I just stumbled upon this and took a look at the code. Maybe it would be wise to add some unit tests? This would prove your code to be (probably) correct :)
