### ISSUE TITLE
Preserve formatting when iterating (th:each)

### ISSUE THREAD

**Issue by cheleb** [thymeleaf/thymeleaf#113]
&lt;ul&gt;
  &lt;li th:each="str: ${list}" th:text="${str}"&gt;My item&lt;/li&gt;
&lt;/ul&gt;

Outputs: 

&lt;ul&gt;
  &lt;li&gt;One&lt;/li&gt;&lt;li&gt;two&lt;/li&gt;&lt;li&gt;three&lt;/li&gt;
&lt;/ul&gt;

Rather than (more readable):

&lt;ul&gt;
  &lt;li&gt;One&lt;/li&gt;
  &lt;li&gt;two&lt;/li&gt;
  &lt;li&gt;three&lt;/li&gt;
&lt;/ul&gt;

**Comment by ultraq** [comment]
Fix committed in the Thymeleaf 2.1-dev branch, which is very similar to the solution you proposed in your forum thread: http://forum.thymeleaf.org/Issue-113-patch-td4025593.html

Commit: 26933aced617e517606b8190c8cb12af862163a6

**Comment by cheleb** [comment]
Cool, thanks a lot, I will be able to remove my xslt step that was
formatting output  :)

On Mon, May 27, 2013 at 1:13 PM, Emanuel Rabina notifications@github.comwrote:

> Fix committed in the Thymeleaf 2.1-dev branch, which is very similar to
> the solution you proposed in your forum thread:
> http://forum.thymeleaf.org/Issue-113-patch-td4025593.html
> 
> Commit: 26933achttps://github.com/thymeleaf/thymeleaf/commit/26933aced617e517606b8190c8cb12af862163a6
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thymeleaf/thymeleaf/issues/113#issuecomment-18493668
> .

## 

"Computers are useless. They can only give you answers."
- Pablo Picasso -
