### ISSUE TITLE
Add equalsIgnoreCase to #strings utility object

### ISSUE THREAD

**Issue by sorayasl** [thymeleaf/thymeleaf#119]
Utility object #strings used in expressions does not contain the method:

equalsIgnorecase(stringA, stringB)

which would be quite useful, for example, to be used in th:if expressions

**Comment by ultraq** [comment]
I noticed there isn't an `equals()` method for `#strings` either, but I believe you can use the `equals()` and `equalsIgnoreCase()` methods of the `String` object itself:

```
<div th:if="${stringA.equalsIgnoreCase(stringB)}">
  ...
</div>
```

**Comment by danielfernandez** [comment]
Implemented by https://github.com/thymeleaf/thymeleaf/pull/130

Emanuel, you are right you could use the methods at the `String` class, but these new methods are null-safe, which the String-instance based ones aren't.
