### ISSUE TITLE
Escaping all data by default to enforce security

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf#122]
According to security reports like "OWASP Top Ten"

```
https://www.owasp.org/index.php/Category:OWASP_Top_Ten_Project
```

injection and XSS problems are the main vector of security vulnerabilities in web applications.

Avoiding this attacks has always been a responsability of the web developer.

However, a view technology like Thymeleaf can enforce better practices about security.

Thymeleaf currently escapes all printed values unless you use th:utext. Taking this approch to the limit, escaping could be performed everywhere (in every ${}, #{} or *{} expression). If a developer wants unescaped data, another syntax should be used.

For example, for printing escaped data we would use

```
th:text="${foo}"
```

and for printing unescaped data we could use

```
th:text="$~{foo}"
```

(instead of current th:utext).

That syntax for unescaped values can be improved, of course.

**Comment by rymsha** [comment]
This change will break all currently written code.
Moreover I don't see it necessary, because as th:text and other th: do it already. The only way to write something unescaped is to use utext. But when you use at least  HTML5 mode thymeleaf thows exception (so XSS won't work)

**Comment by danielfernandez** [comment]
Note for future evaluation: the idea would be to replace the current division between `th:utext` (unescaped) and all the other `th:*` (escaped) so that the new division depends on the specific simple expressions being used inside the attribute processors, not the names of the attribute processors themselves.

**Comment by JavaProgress** [comment]
This is great jmiguelsamper.  Thanks very much
