### ISSUE TITLE
StandardMessageResolver should default to included files' properties

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#13]
In the standard message resolution mechanism, properties are not explored for the included fragments, and they are only for the including template.

This might cause the repetition of properties in messages files between the included and including templates.

What could be done is to (optionally) add the Node itself to the message resolution request, so that if the Node contains information about the template where it comes from this information could be used for defaulting. That way, if a message key is not found in the including template, the included one will be tested before returning a defaulted string.

**Comment by yacota** [comment]
Let me share an example to try to fully understand the point of this issue

some_dir/fragment.html
some_dir/fragment_es.properties
some_dir/template_that_includes_fragment.html
some_dir/template_that_includes_fragment_es.properties

What I understand is that StandardMessageResolver when resolving message keys for/"inside" the included fragment will look up first in template_that_includes_fragment_es.properties (as a specialized message) and if not present fragment_es.properties should be used.
So the hole point is that the message key should be present in fragment_es.properties but can be specialized, right ?

**Comment by danielfernandez** [comment]
Currently, only `template_that_includes_fragment_es.properties` is looked up. No search is done at all for a `fragment_es.properties` file.

This ticket intends to make this change so that `fragment_es.properties` is looked up in second place, before considering the search as failed. That way each fragment can be auto-contained in terms of internationalization (by including its own messages), but at the same time the includ_ing_ templates can override these messages.

Note however that all of this is only for non-Spring environments. When Spring is used, it's Spring who takes care of the whole message externalization system.

**Comment by yacota** [comment]
Crystal-clear, I think that this is a VERY interesting "issue"/improvement :)

BTW, we are actually adding to SpringTemplateEngine org.thymeleaf.messageresolver.StandardMessageResolver as a  messageResolver while leaving SpringResourceResourceResolver as a default one.
It would be pretty cool if we could also add a new  FragmentMessageResolver there

**Comment by ultraq** [comment]
(Just adding myself into the comment chain so I can see how this gets resolved, if ever, as I've basically given-up on a related issue here: https://github.com/ultraq/thymeleaf-layout-dialect/issues/36)

**Comment by danielfernandez** [comment]
This has been just implemented into Thymeleaf 3.0.0, thanks to a refactoring on the Message Resolution API. See #421.

Note however there is a modification to what is explained in comments above: the `template_that_includes_fragment.properties` file will be searched BEFORE `fragment.properties`, and not afterwards.

The reason for this is that the including template should be given the opportunity to _overwrite_ any messages specified as _defaults_ at the fragment. This is actually consistent with the way message resolution works in Apache Wicket, on which the `StandardMessageResolver` mechanism was based.
