### ISSUE TITLE
More processor configuration

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf#135]
Hi!

It would be a great addition to be able to configure whether a processor should be executed when the node processing is starting (i.e. before children) or when it is ending (i.e. after children).

**Comment by rlespinasse** [comment]
+1

**Comment by jmiguelsamper** [comment]
Another way of saying that is that Processors could follow the <b><a href="http://www.corej2eepatterns.com/Patterns2ndEd/InterceptingFilter.htm">Intercepting Filter</a></b> desing pattern, which is the pattern followed by Servlet filters and Spring interceptors.

**Comment by danielfernandez** [comment]
The new architecture in Thymeleaf 3.0 does not work on a DOM anymore, so there is no way to access the _processed_ results of an element (after this element has been processed). However, Dialects in 3.0 can specify Post-Processors, which --though not working on DOMs anyway-- are useful for offering a view on the template results, after applying the processors. See #400 

Closing this as declined.
