### ISSUE TITLE
change #strings.capitalizeWords and #strings.capitalize 

### ISSUE THREAD

**Issue by sunil0791** [thymeleaf/thymeleaf#136]
i feel that it would be better if capitalizeWords and capitalize methods convert the incoming String object to lowercase before performing the capitalize operation.
As of now, i am forcefully converting the bean class variable to lowerCase before rendering it to view and then calling capitalizeWords method of #strings.(which i don't want to do).

Please provide your thoughts on this to make better use of thymeleaf.

**Comment by danielfernandez** [comment]
These methods mirror what the equivalent `capitalize()` and `capitalizeWords()` methods in Apache commons-lang's `StringUtils` class do, and these do not affect the capitalization of any other letters in the word, as you can see in http://commons.apache.org/proper/commons-lang//apidocs/org/apache/commons/lang3/StringUtils.html

Commons-Lang is a quite well-known and very used library, so I think it is better to follow the principle of least surprise here and just behave in an equivalent way.
