### ISSUE TITLE
Error rendering angularjs condition statements within a data attribute

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf#141]
<pre>
data-ng-class="{'error': newUserForm.firstName.$invalid  && newUserForm.firstName.$dirty}"
</pre>

Appears that Thymeleaf cannot handle the '&&' statement and throws the exception: org.thymeleaf.exceptions.TemplateInputException

**Comment by danielfernandez** [comment]
The markup standards establish that you should escape every `&` sign inside the value of an attribute, so you should be writing `&amp;&amp;` instead of `&&` there.

**Comment by ghost** [comment]
Sorry, missed that in the docs. Really appreciate the rapid feedback and should have thought of it. 

Thanks
Josh
