### ISSUE TITLE
New join utility method

### ISSUE THREAD

**Issue by tduchateau** [thymeleaf/thymeleaf#142]
Hi,

I would need a new `join(collection, separatorChar)` method in `#arrays`, `#lists` and `#sets` objects.
What do you think? Interested in a pull request?

Regards,
Thibault

**Comment by danielfernandez** [comment]
Hmm... isn't this covered by `#strings.arrayJoin(array, separator)`, `#strings.listJoin(array, separator)` and `#strings.setJoin(set, separator)`?

It was placed in `#strings` instead of `#lists`, etc. because it is a String-specific feature.

**Comment by tduchateau** [comment]
Shame on me. 

Thanks Daniel! :-)
