### ISSUE TITLE
TemplateRepository.getTemplate shouldn't throw an exception

### ISSUE THREAD

**Issue by opensource21** [thymeleaf/thymeleaf#143]
`org.thymeleaf.TemplateRepository.getTemplate(TemplateRepository.java:247)` throws an exception if the template isn't found. The problem is that with this the idea of ordering the template-resolver in Spring with `resolver.setOrder(1);` is useless.

**Comment by danielfernandez** [comment]
The `setOrder(...)` mechanism at the ViewResolver is thought for specifying which templates are resolved by each resolver by means of their `viewNames` property, which allows the specification of patterns on view names to determine which resolver is in charge of resolving them: `admin/*`, `user*.html`, etc.

**Comment by opensource21** [comment]
You are right. Found this spring function not very intuitive, but that's not the fault of thymeleaf.
