### ISSUE TITLE
AbstractAttributeModifierAttrProcessor shouldn't remove element attributes with same name as modified attribute

### ISSUE THREAD

**Issue by jamcole** [thymeleaf/thymeleaf#144]
I hope this is the correct place to report this :)

Near the end of processAttribute() in AbstractAttributeModifierAttrProcessor, it removes the element attribute, but if you're using a null dialect to process attributes, not just those with a prefix, it inadvertently removes the attribute value you've modified.

I discovered this when making a dialect and processor to append a timestamp / buildnumber to all "src" and "link href" elements on a page for cache-busting between versions of my app.

Basically, the line:
element.removeAttribute(attributeName);
Should be wrapped with an if to skip (and refactored a bit probably) if modifiedAttributeName.equals(attributeName).

I have a workaround for now, in my extended class, I do the following:
<code>
@Override
protected void doAdditionalProcess(Arguments arguments, Element element, String attributeName) {
    element.setAttribute("_temp_:" + attributeName, element.getAttributeValue(attributeName));
}
@Override
protected boolean recomputeProcessorsAfterExecution(Arguments arguments, Element element, String attributeName) {
    String tempAttr = "_temp_:" + attributeName;
    element.setAttribute(attributeName, element.getAttributeValue(tempAttr));
    element.removeAttribute(tempAttr);
    return false;
}
</code>

**Comment by danielfernandez** [comment]
I've just added to 2.0.17-SNAPSHOT a protected method in `AbstractAttributeModifierAttrProcessor` called `shouldRemoveAttribute(...)` which allows subclasses to determine whether the attribute has to be removed after execution.
