### ISSUE TITLE
Resolving messages in @{#{url}} doesn't work

### ISSUE THREAD

**Issue by opensource21** [thymeleaf/thymeleaf#145]
I tried 3 versions
1. `@{#{url.user.list}}`
2. `@{__#{url.user.list}__}`
3. `@{#{url.user.list(1)}}`

Version 2 and 3 work as expected: Read the url from messages and then creates the url. Version 1 creates an URL which contains `#{url.user.list}`
See http://forum.thymeleaf.org/How-is-the-order-of-execution-td4025946.html

**Comment by danielfernandez** [comment]
Fixed by https://github.com/thymeleaf/thymeleaf/pull/146, added to 2.0.17-SNAPSHOT.
