### ISSUE TITLE
Double underscore removed and exception processing &#95; code

### ISSUE THREAD

**Issue by adobarro** [thymeleaf/thymeleaf#147]
Double underscore are removed when its expression is processed:

``` html
<span th:attr="atributo='test__1__'">blabla</span>
```

generates

``` html
<span atributo="test1">blabla</span>
```

instead of

``` html
<span atributo="test__1__">blabla</span>
```

Also if we replace the underscore by &#95; it doesn't work in situations as:

``` html
<img th:src="@{images/test&#95;&#95;9&#95;&#95;.png}"/>
```

resulting in the exception

``` log
[TemplateEngine] (TemplateEngine.java:1173) - [THYMELEAF][http-8080-1] Exception processing template "mobile": Could not parse as expression: "@{images/test&#95;&#95;9&#95;&#95;.png}" (mobile:49)
```

.

**Comment by danielfernandez** [comment]
I've added `\_\_` as a way to escape `__`

**Comment by josketres** [comment]
Why is the template engine removing double underscores?
Is there any way to fix this? Adding the possibility to escape is only a workaround!
This is very annoying for projects using [BEM](http://getbem.com/introduction/)

**Comment by danielfernandez** [comment]
@josketres double-underscores are the markers for _expression preprocessing_ in Thymeleaf Standard Expressions. See http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#preprocessing

**Comment by josketres** [comment]
ok, thanks for the clarification! 👍  it's still not nice for projects using BEM 😩

**Comment by seunggabi** [comment]
## My solution
```
name.replaceAll("__([^_]+)__", "$1"),
```
