### ISSUE TITLE
Parameter with more than one value

### ISSUE THREAD

**Issue by eruiz** [thymeleaf/thymeleaf#15]
Add support to create an URL that contains one parameter with more than one value

The goal is to process the parameter with String[] ServletRequest.getParameterValues(java.lang.String)

Examples:

  @{~/getsomething(p1='value1',p1='value2',p1='value3')} 
  @{~/getsomething(p1=${p1Values})}    (here where p1Values is a model attribute with an array or list of values.)

**Comment by danielfernandez** [comment]
The syntax:

```
@{~/getsomething(p1=${p1Values})} (here where p1Values is a model attribute with an array or list of values.)
```

...was already valid in 2.0.x versions of Thymeleaf.

The syntax:

```
@{~/getsomething(p1='value1',p1='value2',p1='value3')} 
```

Will be valid in 2.0.9 too. A fix has been added to the code trunk, and a new 2.0.9-SNAPSHOT has been published. This feature will go into 2.0.9
