### ISSUE TITLE
Inline javascript removes javascript code up to 1st ;

### ISSUE THREAD

**Issue by eruiz** [thymeleaf/thymeleaf#16]
The inline javascript removes javascript code up to 1st ;

Example;

```
messages.push( /*[[#{  OGNL EXPR }]]*/ );
```

Will output:

```
messages.push( 'AN STR' ;
```

Note that Thymeleaf removed   )     that result in a not valid javascript expression.

Regards

Enrique

**Comment by danielfernandez** [comment]
Hi,

This is in fact a feature, documented at the JavaScript Inlining section in the tutorials.

The aim of it is to provide a way to create JavaScript code that can be executed both statically (without executing Thymeleaf) and dynamically (after processing a template with Thymeleaf). That way:

```
var expr = /*[[#{ OGNL EXPR }]]*/  'This is my static expression!';
messages.push(expr);
```

The above code is perfectly correct JavaScript that can be executed statically. And when the template is processed, you will get:

```
var expr = 'AN STR';
messages.push(expr);
```

Nevertheless, I'm open to suggestions for new/better ways to do this (always maintaining backwards compatibility) for Thymeleaf 2.1.

Regards,
Daniel.

**Comment by eruiz** [comment]
Hi,

Thanks for clarifying.

Regards
