### ISSUE TITLE
Parsing Void Elements (br, hr, link, meta etc.) should still work without end tags

### ISSUE THREAD

**Issue by vcatalano** [thymeleaf/thymeleaf#160]
I noticed that Thymeleaf breaks on void elements that do not have a closing tag such as `<br>`. However, `<br>` is a perfectly valid HTML5 element. I think the parser should handle these elements gracefully and not break when encountered.

**Comment by ultraq** [comment]
(Could you please edit your post to have the code within the markdown open/close code markers?)

What kind of error do you get when you have self-closing elements?  I have plenty of self-closing `<link/>`, `<meta/>`, and `<br/>` tags in my own pages and haven't got errors from them before.

**Comment by danielfernandez** [comment]
@ultraq, I think @vcatalano is talking about unclosed standalone elements like `<a href="hello.html">`, which are allowed by HTML5. But github just ate his code examples.

Currently, thymeleaf uses a tuned SAX XML parser underneath, so this isn't allowed unless you use the `LEGACYHTML5` template mode, which applies a tag balancer before executing the thymeleaf parser.

Thymeleaf 3.0 will switch its main parsing system to attoparser [http://www.attoparser.org] and support these empty (or _standalone_) non-closed elements for better legacy integration.

Remember nevertheless that writing non-XML-well-formed code in HTML5 is not recommended at all, as it reduces the processability of the code, and that as a best practice this kind of code should only be allowed for legacy integration (basically, for avoiding rewriting HTML4 code).

**Comment by 4dz** [comment]
We are having a problem with this as well - as it means we can have a HTML developer provide valid HTML which then breaks when we add it to a Thymeleaf based website.

See http://www.w3.org/TR/html5/syntax.html#void-elements
Void elements only have a start tag; end tags must not be specified for void elements.
[which are], area, base, br, col, command, embed, hr, img, input, keygen, link, meta, param, source, track, wbr

So the comment above is wrong (though i wish it were not): as is Thymeleaf's web page http://www.thymeleaf.org/fromhtmltohtmlviahtml.html --  as, according to the HTML5 spec you are NOT ALLOWED to close some tags, and having a closing tag (or self closing) is invalid HTML5.

**Comment by danielfernandez** [comment]
@4dz Actually, it's only closing tags what is forbidden for void elements in HTML5. Self-closing void tags are allowed. 

So, put in code, the following is not valid HTML5:

``` html
<img src="something.png" alt="something.png"></img>
```

But these two are allowed (and the first one preferred, for the reasons explained in the article you link to):

``` html
<img src="something.png" alt="something.png" />
<img src="something.png" alt="something.png">
```

In fact, if this wasn't so, HTML5 would break backwards compatibility with all previous XHTML 1.0/1.1 code, which would be quite a tragedy ;)

You can test these examples at http://html5.validator.nu/

**Comment by 4dz** [comment]
Thats sort of true:

In HTML5, &lt;div/> means &lt;div> -- the / is ignored.  It does not mean &lt;div>&lt;/div>
Same goes for &lt;img /> -- the / is ignored, so it means &lt;img> not &lt;img>&lt;/img>

**Comment by 4dz** [comment]
good point though! to all intents and purposes it's fine to have a /> in a void element.

Still be nice to get thymeleaf working with valid HTML5:- there is the LEGACYHTML5 mode, which is named oddly as its not legacy, but it seems to help?

**Comment by johnlauer** [comment]
I would second the need for allowing tags like <br> without requiring the /. It makes it really hard to move from JSP to Thymeleaf. For the sake of adoption, please allow these types of tags. If anything, let Thymeleaf stick in the slashes if it wants to. Make our developer lives easy and more folks will adopt Thymeleaf.

**Comment by 4dz** [comment]
For our purposes, we tend to rely on the LEGACYHTML5 mode.

**Comment by eduardocasas** [comment]
I find this really annoying and IMHO it is a key point. Is this going to be fixed?

**Comment by ghillert** [comment]
Any updates on this? Dealing with some templates that are being generated via Grunt. This is a major annoyance.

**Comment by jmiguelsamper** [comment]
Work on Thymeleaf 3.0 has already begun and it will support this syntax, as it will not rely anymore on XML parsers.

Thymeleaf 2.1.X won't have support for this.

**Comment by eduardocasas** [comment]
Finally. That's great!

**Comment by danielfernandez** [comment]
This is covered by the new parsing mechanisms in Thymeleaf 3.0. See #390.

Already in `3.0.0-SNAPSHOT`

**Comment by cescoferraro** [comment]
I am trying to update to 3.0.0.ALPHA03 because of this issue but it is breaking Spring Boot. 
Any pointers?
https://gist.github.com/cescoferraro/6015f0d142bcd4570c71

**Comment by danielfernandez** [comment]
Thymeleaf 3.0.0 (current version is `3.0.0.BETA01`) is very new, and many dialects have not updated to the new APIs yet. Specifically, you (or Spring Boot) seem to be using @ultraq's Layout Dialect, which does not work with 3.0 yet.

I'm afraid you will have to wait some time for dialect integrators to update to 3.0. Or avoid any non-standard dialects in the meantime… 

More info: http://forum.thymeleaf.org/Thymeleaf-3-0-0-BETA01-just-published-td4029294.html

**Comment by cescoferraro** [comment]
thanks @danielfernandez !

**Comment by ultraq** [comment]
And I've just started work towards updating the layout dialect for Thymeleaf 3 - I'm getting lots of questions about it!
