### ISSUE TITLE
Documentation for th:object precedence

### ISSUE THREAD

**Issue by ugate** [thymeleaf/thymeleaf#161]
Looking at the [precedence section of the docs](http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#attribute-precedence) there doesn't seem to be a definition for `th:object`.

**Comment by ultraq** [comment]
Added to the docs (will be regenerated when Thymeleaf 2.0.17 is available).  `th:object` precedence is just before `th:with`.
