### ISSUE TITLE
EnumMap not working in templates

### ISSUE THREAD

**Issue by jirubio** [thymeleaf/thymeleaf#164]
Having a template fragment like this:

```
<div th:each="entry :${map}" th:text="${entry}"></div>
```

that just iterates the map and prints its values.
When passing a normal map to the template:

```
Map<String,String> map = new HashMap<String, String>();
map.put("one", "1");
map.put("two", "2");
model.put("map",map);
```

The resulting output is:

```
<div>two=2</div><div>one=1</div>
```

which is fine.
But if you pass an EnumMap:

```
Map<TimeUnit,Integer> map = new EnumMap<TimeUnit, Integer>(TimeUnit.class);
map.put(TimeUnit.DAYS, 1);
map.put(TimeUnit.HOURS, 2);
model.put("map",map);
```

This is the result:

```
<div>DAYS=1</div><div>DAYS=1</div>
```

The first entry of the map is repeated and the second doesn't even appear.
It should be no difference, EnumMap and HashMap both extend from the same parent class.

**Comment by danielfernandez** [comment]
Solved in 2.0.18-SNAPSHOT, see the referenced commit above.

Apparently, the iterator returned by `EnumMap.entrySet().iterator()` reuses the same instance of `Map.Entry<?,?>` in every iteration, just modifying its contents each time. As thymeleaf created a list with these iterated `Map.Entry<?,?>` objects... it actually added to the list the same object, several times. With only the last iterated values on it.

This behaviour of `EnumMap` is undocumented (or at least I wasn't able to find anything about it), and in my understanding breaks the intuitive contract of `EnumMap.entrySet()`, which should return an actual set with different instances of `Map.Entry<?,?>`, one for each value (a `Set` will never, by contract, contain the same object more than once). But anyway, I've added a workaround for this scenario.

**Comment by danielfernandez** [comment]
See the test added here: https://github.com/thymeleaf/thymeleaf-tests/blob/20130610/src/test/resources/attrprocessors/each/each06.thtest 

Works now in 2.0.18-SNAPSHOT

**Comment by jirubio** [comment]
Great! and thanks for the explanation. I have looked at the code of EnumMap and for me the way the iterator works is also buggy. As for the workaround other option that could be simpler is to use EnumMap.entrySet().toArray() that returns different instances for each entry on the map.
