### ISSUE TITLE
2.0.17 Breaks Javascript Inline

### ISSUE THREAD

**Issue by dharrigan** [thymeleaf/thymeleaf#168]
Hi,

Just upgraded to thymeleaf 2.0.17, now it's breaking a bit of Javascript inline:

This is in my thymeleaf inline file

 messages: {
                emailAddress:{
                    required: /_[[#{frontend.signin.emailAddress.required}]]_/ 'Email address is required',
                    maxlength: /_[[#{frontend.signin.emailAddress.toolong}]]_/ 'Email address is too long',
                    pattern: /_[[#{frontend.signin.emailAddress.invalid}]]_/ 'Email address is invalid'
                },
                passphrase: {
                    required: /_[[#{frontend.signin.passphrase.required}]]_/ 'Passphrase is required',
                    minlength: /_[[#{frontend.signin.passphrase.tooshort}]]_/ 'Passphrase is too short',
                    maxlength: /_[[#{frontend.signin.passphrase.toolong}]]_/ 'Passphrase is too long'
                }
            }

When rendered, I now have:

  messages: {
                emailAddress:{
                    required: 'Email address is required!',
                    maxlength: 'Email address is too long!',
                    pattern: 'Email address is invalid!' 'Email address is invalid'
Uncaught SyntaxError: Unexpected string
                },
                passphrase: {
                    required: 'Passphrase is required!',
                    minlength: 'Passphrase is too short!',
                    maxlength: 'Passphrase is too long!' 'Passphrase is too long'
                }
            }

Notice the duplicate entries.

This was working in 2.0.16 without change. Please note that the "Uncaught syntax error: Unexpected String" was just a copy + paste from Chrome's javascript viewer and not rendered by Thymeleaf. 

Referenced here to: http://forum.thymeleaf.org/2-0-17-breaks-Javascript-Inline-td4026207.html

-=david=-

**Comment by danielfernandez** [comment]
Confirmed. This was unintentionally introduced when #157 was fixed in 2.0.17.

**Comment by danielfernandez** [comment]
See associated test. Works OK in 2.0.18-SNAPSHOT: https://github.com/thymeleaf/thymeleaf-tests/blob/20130615/src/test/resources/attrprocessors/inline/inline03.thtest

**Comment by dharrigan** [comment]
w00t :-) Thank you Daniel :-)

-=david=-

On 14 June 2013 23:22, Daniel Fernández notifications@github.com wrote:

> See associated test. Works OK in 2.0.18-SNAPSHOT:
> https://github.com/thymeleaf/thymeleaf-tests/blob/20130615/src/test/resources/attrprocessors/inline/inline03.thtest
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/thymeleaf/thymeleaf/issues/168#issuecomment-19484854
> .

## 

I prefer encrypted and signed messages. KeyID: B20A22F9
Fingerprint: 110A F423 3647 54E2 880F ADAD 1C52 85BF B20A 22F9

"It is not usually until you've built and used a version of the program
that you understand the issues well enough to get the design right." - Rob
Pike, Brian Kernighan.

No trees were harmed in the sending of this message, however, a number of
electrons were inconvenienced.

**Comment by dharrigan** [comment]
Hi,

Still a bug however, in 2.0.18-SNAPSHOT:

var myDomainName = /_[[${myDomainName}]]_/ 'https://www.mydomain.com';

Renders as:

var myDomainName = 'https://www.mydomain.com'//www.mydomain.com';

It appears that having a : (colon) seems to cause issues.

-=david=-

**Comment by dharrigan** [comment]
I'll create a new issue that refers to this.

**Comment by huxi** [comment]
Any ETA for a 2.0.18 release?

**Comment by danielfernandez** [comment]
@huxi we should be releasing 2.0.18 in two/three weeks. In the meantime, if you need any of its features you can use 2.0.18-SNAPSHOT following the instructions at http://www.thymeleaf.org/faq.html#use-snapshot

**Comment by huxi** [comment]
Ok, thanks.

It's not that urgent. 2.0.16 works fine for now. I just asked to have a rough idea when to check for the new version.
