### ISSUE TITLE
Remove leniency flag from IDialect

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#177]
The current existence of the `lenient` flag in `IDialect` will probably be an obstacle for the correct implementation of HTML5 `data-`-related features in thymeleaf dialects, because of the less flexibility this attribute at the dialect level forces to.

Removing it should not affect developers basing their dialect implementations on `AbstractDialect` instead of directly implementing `IDialect`.

**Comment by tduchateau** [comment]
+1 ;-)

**Comment by danielfernandez** [comment]
Related tests: https://github.com/thymeleaf/thymeleaf-tests/tree/20130804/src/test-21/resources/engine21/xmlns

**Comment by danielfernandez** [comment]
Added to 2.1.0-SNAPSHOT
