### ISSUE TITLE
How can i changes the sax parser to another html parser.

### ISSUE THREAD

**Issue by phw4u** [thymeleaf/thymeleaf#179]
[sorry.. i am not good english. maybe you hard to read my post. ]

umm... 
My development enviroment is  "osgi" and use "angular.js" for javascript framwork in the ui. 

the angular.js code generally use like below. 
(it is a google sample code : http://docs.angularjs.org/api/ng.directive:ngSwitch ) 

```
<!doctype html>
<html ng-app>
  <head>
    <script src="http://code.angularjs.org/1.0.6/angular.min.js"></script>    <script src="script.js"></script>  </head>
  <body>
    <div ng-controller="Ctrl">
      <select ng-model="selection" ng-options="item for item in items">
      </select>
      <tt>selection={{selection}}</tt>
      <hr/>
      <div ng-switch on="selection" >
        <div ng-switch-when="settings">Settings Div</div>
        Home Span
        default
      </div>
    </div>
  </body>
</html>
```

But maybe you know, i got some SAXParseExceptions  because a parser using thymeleaf is very very strict to use html structure. (i think a sax is not suitable parser for html. ) 

In the thymeleaf manual, i can find a legacyhtml5 mode and use it. But sadly it doesn't work in osgi enviroment cause  use `ClassLoader.getClass(xxx)`.  And another problem is nekoHtml. It has problem that result html is not pretty-print.(all html tags in only one line. .....but.. it's not important problem. ) 

So i want to change the SAX Parser to another flexible html parser. 
I think  htmlcleaner(http://htmlcleaner.sourceforge.net/) is well. 

Would you like to give some guide to change parser from sax? 

and...is there any plans to add flexible parser in next version? 

thanks ^^

**Comment by ultraq** [comment]
I don't know if there's an 'easy' way to switch the parser (like some configuration option), but recently I saw that all of the logic for parsing a Thymeleaf template using SAX was done in the `org.thymeleaf.templateparser.xmlsax.AbstractNonValidatingSAXTemplateParser` class.  Start at the `parseTemplate(...)` method and you can see at what point it starts using SAX to convert the template into a Thymeleaf `Document` object.  Somewhere in there you might be able to replace the SAX stuff with a parser of your choice.

**Comment by phw4u** [comment]
ok. 
First, I will find that code in AbstractNonValidatingSAXTemplateParser.
Thanks ultraq.

**Comment by danielfernandez** [comment]
Thymeleaf allows the modification of the parsing system by letting the user configure the available **template modes**. A template mode defines how a parser should be interpreted, and for such thing it allows the specification of a parser (that converts a template into DOM) and a writer (that converts the resulting DOM into the HTML/XML/whatever result).

You should therefore look at the `ITemplateModeHandler` interface here: https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-2.0.17/src/main/java/org/thymeleaf/templatemode/ITemplateModeHandler.java
