### ISSUE TITLE
Add DOM simple expressions

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#180]
Create a new type of simple expressions like `~{...}` for selecting subtrees of templates. At first thought, its syntax could be similar to that of current "th:include/th:replace", like:

```
~{sometemplate:://div/p}
```

It would also be great to have these expressions relative to the current node (the node where the expression is being executed):

```
~{::title/text()}
```

Then the context variables created by these expressions could be used at any point, resulting in fragments of template (of the original template, not the already processed one) being inserted, like:

``` html
<div th:replace="${mydomsubtree}">...</div>
```

See a complete example in test syntax:

``` html
# ------------------------------------------------------------
%INPUT
<head th:include="basic_template :: header(~{::title/@text},~{::link})">

  <title>Some wonderful page</title>

  <link href="css/bootstrap.min.css" rel="stylesheet" />
  <link href="themes/smoothness/jquery-ui.css" rel="stylesheet" />

</head>
# ------------------------------------------------------------
%INPUT[basic_template]
<head th:fragment="header(pagetitle,links)">

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title th:text="${pagetitle}">A template prototyping title</title>

  <link th:replace="${links}" />

</head>
# ------------------------------------------------------------
%OUTPUT
<head>

  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8"/>
  <title>Some wonderful page</title>

  <link href="css/bootstrap.min.css" rel="stylesheet" />
  <link href="themes/smoothness/jquery-ui.css" rel="stylesheet" />

</head>
# ------------------------------------------------------------
```

Note that this kind of feature should solve #3.

**Comment by danielfernandez** [comment]
These expressions will be made possible by the new syntax in DOM Selectors implemented in #202

**Comment by doctore** [comment]
Hi.

First thanks for your work. Would it be possible to include this functionality in the next version? Since it would be very interesting for those who, like me, we have several "levels of head" and, for now, there is no simple way to include a "head father" within another "head son".

Thanks.

**Comment by ultraq** [comment]
One of the referenced issues (https://github.com/thymeleaf/thymeleaf/issues/3) mentions that this feature will be for Thymeleaf 3.0 (no idea when that will happen though especially since 2.1 isn't all that old yet) as the layout dialect provides some of these features for those looking for an interim fix.

**Comment by danielfernandez** [comment]
Implemented as **Fragment Expressions** for Thymeleaf 3.0. See #451
