### ISSUE TITLE
Parser-level comment blocks

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#183]
Parser-level comment blocks are code that will be simply removed from the template when thymeleaf parses them. They should look like this:

``` html
<!--/* This code will be removed at thymeleaf parsing time! */-->
```

Thymeleaf should remove absolutely everything between `<!--/*` and `*/-->`, so these comment blocks can be used for displaying code when a template is statically open, knowing that it will be removed when thymeleaf processes it:

``` html
<!--/*--> 
  <div>
     you can see me only before thymeleaf processes me!
  </div>
<!--*/-->
```

This might come very handy for prototyping tables with a lot of `<tr>`'s, for example:

``` html
<table>
   <tr th:each="x : ${xs}">
     ...
   </tr>
   <!--/*-->
   <tr>
     ...
   </tr>
   <tr>
     ...
   </tr>
   <!--*/-->
</table>
```

**Comment by danielfernandez** [comment]
Added to 2.1.0-SNAPSHOT

**Comment by danielfernandez** [comment]
Some related tests: https://github.com/thymeleaf/thymeleaf-tests/tree/20130805/src/test-21/resources/engine21/parsing

**Comment by harbulot** [comment]
Would this syntax inadvertently cause problems for comments such as this?

```
<!-- These requests are mapped in the servlet to /* -->
```

(I mean, anything that legitimately contains `/*`.)

In addition, one of the good things about Thymeleaf is that you're guaranteed to turn well-formed XML into well-formed XML (as far as I know). Using this block exclusion, you could have problems:

```
<table>
    <tr>
  <!--/*-->
    </tr>
    <tr>
    </tr>
  <!--*/-->
</table>
```

This would become invalid XML:

```
<table>
    <tr>
</table>
```

The suggestion in issue #10 (3 dashes in `<!---`) would not present these problems.

Hiding XML fragments can probably already be done using `th:remove`, although it's not necessarily as convenient for blocks.

Perhaps an approach similar to [Genshi](http://genshi.edgewall.org/wiki/Documentation/xml-templates.html), by having `<th:...>` elements too would help (although I'm not sure how a browser would load this without understanding such an element:

```
<table>
    <tr>
    </tr>
    <th:remove>
    <tr>
    </tr>
    </th:remove>
</table>
```

**Comment by harbulot** [comment]
I've just tried this and Firefox, Chrome and IE (latest versions) are capable of ignoring the `<test:remove>` element while displaying its content.

``` xml
<!DOCTYPE html>
<html xmlns:test="http://example.org">
<head>
</head>
<body>
    <table>
            <tr><th>Test 2</th></tr>
            <tr><td>1</td></tr>
        <test:remove>
            <tr><td>2</td></tr>
            <tr><td>3</td></tr>
        </test:remove>
    </table>
</body>
</html>
```

If Thymeleaf had a `<th:remove>` element, which it would be capable of processing to remove the content from the output, I would suggest this is a cleaner solution to the problem of removing blocks (the part of issue #57 that was merged into this issue), since it would keep the XML well-formed.

**Comment by danielfernandez** [comment]
> Would this syntax inadvertently cause problems for comments such as this?
> 
> ```
> 
> ```

Nope. Thymeleaf specifically looks for the `<!--/*` and `*/-->` sequences, without any whitespaces. So your _normal_ comments should be perfectly safe, if you just don't write those sequences (in the same way that you cannot write `--` in the middle of a comment because the HTML parser will consider it ended)

As for using an element like `<th:remove>` instead of a comment, it has two problems:
1. Extra elements, even if ignored by most browsers, might affect the way CSS stylesheets are applied because they actually modify the DOM structure. This can have a negative influence in static prototypes, and is one of the reasons thymeleaf bases 99% of its standard dialects in attributes only (except for the new `th:block`, which is in fact meant to be used inside comments).
2. Extra elements, even if ignored by browsers, are not ignored by IDEs and can cause nasty code validation warnings during development. For example, Eclipse or IntelliJ would be all the time complaining that a `<test:remove>` element is not allowed in an HTML document inside a `<table>`...

Comments don't have any of these issues :-)

**Comment by harbulot** [comment]
But what about `<!--/*-->` in the middle of a `<tr> <!--/*-->  </tr>`?
One of the good things about XML->XML transformations is that it prevents users from shooting themselves in the foot, which is possible with a number of other template languages. (I'm certainly not saying XML is the best thing in the world :-), but I think the clean, XML-based syntax of Thymeleaf is one of its strong points compared with other template systems.)

In my experience Eclipse doesn't complain about elements it doesn't know such as `<test:remove>` inside a `<table>` or somewhere else, as long as `xmlns:test` is properly declared. (I haven't tried with IntelliJ.)
I must admit I have a bit more experience with Genshi (in Python), and it's never been a problem (even in Eclipse). (I think Genshi and Thymeleaf are reasonably similar, although they're used with different languages.)

This being said, I haven't really used static prototypes, so what you're saying about CSS/DOM with a new element could really be an issue for those who rely on this indeed, I understand.
