### ISSUE TITLE
Support for Spring field formatters

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf#191]
[Field formatters](http://static.springsource.org/spring/docs/3.2.x/spring-framework-reference/html/validation.html#format) are a feature introduced in Spring 3 which allows automatic formatting and parsing of data types.

For example, you can show all your Date objects like "Saturday 20/Jul/2013" or all your Currency objects like "35.50 €".

This is really nice for maintainability, avoiding repetition of formatting code in every view or bean. Formatters also are used for form field parsing.

Currently Formatters work perfectly with Thymeleaf inside forms, provided you use the th:field attribute processor.

This issue is a feature request for supporting formatters outside forms.

See related forum post: http://forum.thymeleaf.org/Formatting-with-Spring-Formatter-td4026363.html

**Comment by opensource21** [comment]
+1

**Comment by dnezic** [comment]
+1

**Comment by danielfernandez** [comment]
This is related to thymeleaf/thymeleaf-spring3#19

**Comment by cachescrubber** [comment]
+1

**Comment by danielfernandez** [comment]
This has been implemented at thymeleaf/thymeleaf-spring3#19
