### ISSUE TITLE
Create a th:ref attribute for in-template reference of elements

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#196]
A new `th:ref` attribute should help referencing elements in the template from anywhere in the template at parsing time. Something like:

``` html
<div th:ref="countrySection">...</div>
```

When executed, the processor for this attribute should simply do nothing and dissapear.

**Comment by danielfernandez** [comment]
This `th:ref` processor should be implemented as a no-op processor simply removing the attribute from its host element, and an implementation of `DOMSelector.INodeReferenceChecker` should be created in order to being able to select elements by their `th:ref` attribute (working as a _reference_, not a mere attribute) in DOM Selector expressions as specified at #202

**Comment by danielfernandez** [comment]
As a consequence of moving #68 to milestone 3.0, for the reasons explained in that ticket, this is also moved to 3.0.

**Comment by danielfernandez** [comment]
This has been implemented and is already available in `3.0.0-SNAPSHOT`

**Comment by javafuns** [comment]
Is there any way to set 'ref' attribute ? th:ref does nothing.
