### ISSUE TITLE
Expressions with protocol relative URLs

### ISSUE THREAD

**Issue by ugate** [thymeleaf/thymeleaf#204]
A common practice for CDN hosts is to provide links that drop the <b>http:</b>/<b>https:</b> /etc. prefix so that the URL will inherit the current protocol. In such a case Thymeleaf mistakens the URL to be context relative and adds the path to the beginning of such links. For example:

``` html
<script th:src="@{//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js}"></script>
```

renders:

``` html
<script src="/my-app//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
```

instead of the desired:

``` html
<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
```

A workaround would be to use a literal string.

**Comment by danielfernandez** [comment]
Updated 2.1.0-SNAPSHOT. Added tests (see commit above).
