### ISSUE TITLE
Replacement still broken in 2.0.18

### ISSUE THREAD

**Issue by huxi** [thymeleaf/thymeleaf#207]
The following code

``` js
<script type="text/javascript" th:inline="javascript">
    /* <![CDATA[ */
    jQuery(document).ready(function ()
    {
        var foo = new Foo({
            fooUrl:/*[[@{/fooservice/foo/}]]*/              "http://10.200.55.223/fooservice/foo/",
            barUrl:/*[[@{/barservice/bar/}]]*/                     "http://10.200.55.223/barservice/bar/"
        });
    });
    /* ]]> */
</script>
```

is converted to

``` js
<script type="text/javascript" xml:space="preserve">
    /* <![CDATA[ */
    jQuery(document).ready(function ()
    {
        var foo = new Foo({
            fooUrl:'/foobar/fooservice/foo/'//10.200.55.223/fooservice/foo/",
            barUrl:'/foobar/barservice/bar'//10.200.55.223/barservice/bar/"
        });
    });
    /* ]]> */
</script>
```

But it should be

``` js
<script type="text/javascript">
    /* <![CDATA[ */
    jQuery(document).ready(function ()
    {
        var foo = new Foo({
            fooUrl:'/foobar/fooservice/foo/',
            barUrl:'/foobar/barservice/bar'
        });
    });
    /* ]]> */
</script>
```

**Comment by danielfernandez** [comment]
Actually, this is a new problem. The inlining engine sees those `//` and considers them to be the start of a comment, which it must respect.

And why does it consider it a comment if it is inside a literal? Because you are using double-quotes for your literal instead of single-quotes, which is what it expects. That's a bug, obviously, it should take care of both double and single quotes.

So you have two workarounds:
1. Use single-quotes.
2. Escape your `//` like `\/\/`

**Comment by huxi** [comment]
But it is manipulating the comment in some way...
It's removing the leading "http://

I reverted to 2.0.16 for now - which works as expected.

**Comment by huxi** [comment]
I just realized that 2.0.16 is also printing

``` html
<script type="text/javascript" xml:space="preserve">
</script>
```

i.e. it also writes the `xml:space` - this isn't correct in my report above.

**Comment by danielfernandez** [comment]
> But it is manipulating the comment in some way...
> It's removing the leading "http://

As I said, it is considering `//` the start of a comment, and it is preserving it from there on (from the `//`, so it is removing `http:`).

The simplest solution for you is using single-quotes, IMHO. This works perfectly, and you will benefit from all the javascript inlining fixes in 2.0.18.

As for the `xml:space`, that has nothing to do with inlining, but with XHTML. If the `xml:space` attribute is considered required in `<script>` tags by the XHTML spec and you are applying an XHTML DTD, it is being automatically added.

**Comment by danielfernandez** [comment]
Updated 2.0.19-SNAPSHOT and 2.1.0-SNAPSHOT.

Added test with your specific code: https://github.com/thymeleaf/thymeleaf-tests/blob/20130821/src/test-common/resources/engine/attrprocessors/inline/inline11.thtest

**Comment by huxi** [comment]
Ah, I see regarding `xml:space`.
Thanks for your incredible support! Your speed is amazing!
