### ISSUE TITLE
#lists should have a sort-method

### ISSUE THREAD

**Issue by opensource21** [thymeleaf/thymeleaf#208]
I think it's often very useful sort a list. At the moment I must do it in the controller. Would be nice to have the possibility to call `Collection.sort` via `#lists.sort`

**Comment by opensource21** [comment]
Just to make it clear the issue `#28` in  thymeleaf/thymeleaf-spring3 was closed because I think it was the wrong issue-list. This issue is still open.

**Comment by sunil0791** [comment]
I am just giving a thought. If we sort once, all the place where the arraylist object is used would have been sorted. So,    would it be good to do it in thymeleaf. Else, should we have a method which creates the copy of list and may be we can then sort that list.

**Comment by opensource21** [comment]
I have a deeper look into this issue. The only use case I see is to call `th:each="${#list.sort(myList)}"`. If so I think it's better to create an `th:ordered="${myList}` or `th:eachSorted` `th:sortedEach`. It's moire complicated to implement, but I guess it's more useful.

**Comment by danielfernandez** [comment]
In my opinion, a utility method would be more useful than new attributes. Mainly because of being a more versatile solution, allowing its usage for example in th:with attributes (so that we can iterate the list twice or more times if needed)

Besides, it wouldn't be easy to be able to specify a comparator object with the current syntax of th:each...

**Comment by opensource21** [comment]
The `th:with` example is indeed a good argument. `th:order` can then easily realize by an own dialect replacing the the attribute.

**Comment by opensource21** [comment]
Please merge https://github.com/thymeleaf/thymeleaf-tests/pull/2 too.

**Comment by opensource21** [comment]
I didn't find the xml-file for the eclipse-plugin, so I couldn't adjust this file. Can someone give me a hint?
Furthermore I don't know how to adjust the documentation.

**Comment by ultraq** [comment]
Documentation is in the [thymeleaf-docs](https://github.com/thymeleaf/thymeleaf-docs) project.  In the root folder you'll find the markdown (.md) files corresponding to each of the 3 guides/tutorials that are available on the website.  HTML and PDF versions are generated from those markdown files using the Gradle build script.  Setup/installation instructions for generating the HTML/PDF versions are in the project readme.

**Comment by opensource21** [comment]
So I added the documentation see https://github.com/thymeleaf/thymeleaf-docs/pull/1. As far as I understand the eclipse-plugin must not be changed.

**Comment by ultraq** [comment]
Pull requests for the code and doc updates were accepted.  We'll figure out what to do for the Eclipse plugin XML files once 2.1.0-beta2 goes out: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/30
