### ISSUE TITLE
Cannot create URL with query string only

### ISSUE THREAD

**Issue by igo** [thymeleaf/thymeleaf#209]
Following statements doesn't work, thus cannot create links that only change parameters:
`@{(p1)}`
`@{~(p1)}`
They should generate link like `?p1`

**Comment by danielfernandez** [comment]
In such case, you will need to use `#` as the URL base, which will work as you expect.

I've created a test file in order to explain how this works: https://github.com/thymeleaf/thymeleaf-tests/blob/20130831/src/test-common/resources/engine/features/link/link09.thtest

**Comment by igo** [comment]
Unfortunately this is something totally different. `#?param` is not the same as `?param`

**Comment by danielfernandez** [comment]
Support for URLs like `@{''(p1)}` has been added to 2.0.19-SNAPSHOT and 2.1.0-SNAPSHOT. 

Note however that an URL like `@{~(p1)}` cannot be valid, because a no-base URL is by definition relative, and not server-relative.

**Comment by CrazyOrr** [comment]
Hi, @danielfernandez What about query params? Can we add/replace/remove specific query params based on the current ones? Like mentioned in this question: http://stackoverflow.com/questions/17504965/thymeleaf-url-construction
