### ISSUE TITLE
LegacyHTML5 template mode produces incorrect output for th:include and th:substituteby

### ISSUE THREAD

**Issue by apazzolini** [thymeleaf/thymeleaf#212]
When using the LegacyHTML5 template mode, attempting to include a another file without specifying a fragment results in incorrect output.

The `NekoBasedHtmlParser` is too aggressive in its conversion, and will add in unnecessary wrapper objects. Here's an example:

_a.html_

``` html
<html>
    <head>
    </head>
    <body>
        Some text
        <div th:substituteby="b.html" />
        More text
    </body>
</html>
```

_b.html_

``` html
<span>
    include text
</span>
```

This would produce the following output with the extraneous wrapper

``` html
<html>
    <head>
    </head>
    <body>
        Some text
        <html>
            <head>
            </head>
            <body>
                <span>
                    include text
                </span>
            </body>
        </html>
        More text
    </body>
</html>
```

If you include a fragment directly, the extra tags are not present.

Thanks! (Using Thymeleaf 2.0.17 by the way)

**Comment by danielfernandez** [comment]
Thanks Andre.

The way nekoHTML performs its markup balancing operations is a bit obscure, but let's see if this thing of adding an extra HTML structure can be configured without breaking other scenarios. Should be able to return just a markup fragment...

In the meantime, as a workaround you could use a DOM selector in your "substituteby", thought it isn't exactly a beautiful solution:

``` html
<div th:substituteby="b.html :: [//body/span]" />
```

or, better:

``` html
<div th:include="b.html :: [//body]" />
```

**Comment by ultraq** [comment]
(Just inserting myself into the conversation to keep notified of changes.  The Layout Dialect loosened up some of it's own template checks because of this very issue.)

**Comment by apazzolini** [comment]
I can confirm that the following works:

``` html
<div th:include="b.html :: [//body]" />
```

It successfully parses out all of the incorrect HTML / HEAD / BODY tags. It's not ideal, but we can work with that for now until we can get our RTE to produce valid XHTML so that we can switch back to the non-legacy mode. Thanks!

**Comment by danielfernandez** [comment]
According to http://nekohtml.sourceforge.net/settings.html, the `http://cyberneko.org/html/features/balance-tags/document-fragment` should help avoiding this behaviour, without completely losing the benefit of neko's HTML tag balancing operations.

**Comment by danielfernandez** [comment]
Updated 2.1.0-SNAPSHOT and 2.0.19-SNAPSHOT
