### ISSUE TITLE
Inefficient implementation of org.thymeleaf.util.IdentityCounter is a performance bottleneck for large templates

### ISSUE THREAD

**Issue by rustamm** [thymeleaf/thymeleaf#218]
Used profiling tools to track performance issues in my project and seen following picture:

![isalreadycounted](https://f.cloud.github.com/assets/5218959/1261139/502637f8-2c25-11e3-8ba9-b37027995ae3.png)

Current implementation of IdentityCounter is too slow - isAlreadyCounted method has linear-time performance depending on the number of counted objects. I rewritten it to work with constant-time performance, and it gave us almost 10x speed improvement.

Pull request will follow soon.

**Comment by danielfernandez** [comment]
Sounds really good. Thanks. Please remember to read and accept (a github comment will do) the guidelines for contributing when you do your pull request: https://github.com/thymeleaf/thymeleaf/blob/2.1-master/CONTRIBUTING.markdown

**Comment by rustamm** [comment]
I've read the guidelines and I accept them by making this comment.

**Comment by ultraq** [comment]
:+1:

**Comment by danielfernandez** [comment]
Merged into 2.1.0-SNAPSHOT
