### ISSUE TITLE
Javascript inlining problem - Multidimensional arrays

### ISSUE THREAD

**Issue by kaanozdokmeci** [thymeleaf/thymeleaf#22]
``` javascript
<script type="text/javascript" th:inline="javascript">
    /*<![CDATA[*/
        var appId = /*[[${app.id.toString()}]]*/ 'dummy-app-id';  
        var currentThemeId = 1;
        var currentColorId = 1;
        var colorLists = [["#A3AFDE","#DEFAB1","#3C5F1B"]];
    /*]]>*/
</script>
```

Inlining the javascript causes colorLists to become "#A3AFDE","#DEFAB1","#3C5F1B".
Can I somehow prevent this behavior without moving the colorLists variable to another script block?

**Comment by danielfernandez** [comment]
The following fix has been applied to source trunk and 2.0.9-SNAPSHOT: When inlining, if the expression between [[...]] is not a valid Standard Expression, it is output without modification, including the double-brackets.
