### ISSUE TITLE
Fine tune applicability of conversion service

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#222]
**EDIT: Definitive implementation is explained in #223**

Based on the issue explained by user "cachescrubber" here: http://forum.thymeleaf.org/Formatting-with-Spring-Formatter-td4026363.html#a4026867 it looks as a good idea to try to fine tune when the conversion service should be used for String conversion and when it shouldn't.

Scenarios as the `th:href` one explained there seem at first incompatible with the application of the conversion service, which is currently being applied in every processor producing String text output.

A first approach to better determining when conversion should be applied or not could be based on dividing attributes and expression types between "convertible" and not, always trying to automatically apply conversion in the smallest amount of scenarios as possible (given the fact conversion should be manually executable). For its implementation, a combination of processor logic and Standard Expression Context (applied when evaluating expressions) should be enough.

For example:
- Conversion should never be applied in `@{...}` expressions.
- Conversion should never be applied in preprocessing. Given the normal uses of the preprocessing mechanism, this sounds sensible, and besides, will provide an opt-out mechanism in scenarios where conversion is applied by default but shouldn't, in a specific scenario.
- Conversion should only be automatically applied in the following processors (and not in the rest of them):
  - `th:text`
  - `th:utext`
  - `th:value`
  - `th:alt`
  - `th:title`
  - (Maybe other text-oriented attributes like `th:abbr`?)
  - (Maybe date-oriented attributes like `th:datetime`?)

_(The second two points remain open for discussion)_

Besides, the conversion service should always be made available as a context bean, so that it can be manually executed.

**Comment by danielfernandez** [comment]
After some thinking, IMO this could be a feasible specification:
- Expression pre-processing: never apply conversion.
- Simple expressions (components of Standard Expressions):
  - Link expressions (`@{...}`): never apply conversion.
  - Message expressions (`#{...}`): only apply conversion to parameters, not to message keys.
  - Literals and tokens: never apply conversion.
  - Variable/Selection expressions (`${...}`, `*{...}`): depending on context (i.e. depending on the attribute processor the expression is being executed from, see below).
    - **EDIT**: When in a Spring form, and depending on the attribute processor the expression is being executed from, `*{...}` expressions should additionally try to obtain their data from the Spring `BindStatus`, and apply the corresponding `PropertyEditors`.
- Conversion should only be applied for this attribute processors:
  - th:text
  - th:utext
  - th:value
  - th:alt
  - th:title
  - th:placeholder
  - th:label
- Conversion should not be applied for text inlining (should be done manually if needed).

**EDIT: Another way of explaining the same, maybe simpler**
- The conversion service will only be applied to expressions inside the following attribute processors:
  - th:text
  - th:utext
  - th:value
  - th:alt
  - th:title
  - th:placeholder
  - th:label
- In such cases (when in the attributes above), the conversion service will only be applied to:
  - Parameters (not message keys) in Message Expressions (`#{...}`).
  - Variable/Selection expressions (`${...}`, `*{...}`). When in a Spring form, `*{...}` expressions will also try to apply BindStatus-based property editors.

**Opt-In: Manual conversion**

The conversion service (the `IStandardConversionService` object) will be made accessible by means of a `#conversions` expression utility object, allowing the manual execution of conversions like:

``` html
   <div th:attr="myNewText=${#conversions.convert(myObject, 'String')}">...</div>
```

**Opt-Out: How to avoid conversion if needed?**

How would we allow users to specify that an expression such as this, should not be converted?:

``` html
   <div th:text="${user.id}">...</div>
```

There are at least two ways: 1st, using preprocessing, which will convert the result of such preprocessing into a String without using the conversion service, before the `th:text` attribute processor determines whether conversion is needed (there's no need to convert String -> String):

``` html
   <div th:text="__${user.id}__">...</div>
```

And 2nd, manually executing `toString()` on the target, with the same effect:

``` html
   <div th:text="${user.id.toString()}">...</div>
```

**Comment by ultraq** [comment]
How are you thinking of being able to turn this feature on/off?  I think there are far too many attribute processors to try do it on a processor by processor basis.  Maybe a flag in the expression, eg: ${!...} ?  What would the default behaviour be then?

**Comment by danielfernandez** [comment]
@ultraq actually, if you see the list in my comment above, I think there are only 7 attributes meant to output _arbitrary text_ (not simply _Strings_). And those should be the only attribute processors in which it actually makes sense that the default behaviour is applying the conversion service. As for how to turn it off... preprocessing or `toString()` should do, as explained above.

For the rest of processors/expressions, no conversion at all (until manually executed).

**Comment by cachescrubber** [comment]
Since the main focus of the conversionService is data binding, it should be automatically applied in 
- form-binding (as always)
- The parameter part of @{...} expressions.

It should probably be not applied to
- The path part of @{...} expressions.

simply because it has great potential to break existing code.

Please consider it as the default for *{...} expressions. Why? It is already a mechanism to provide a short-cut to print selected object properties.

```
<div th:object="${session.user}">
    <p>Name: <span th:text="*{firstName}">Sebastian</span>.</p>
  </div>
```

And, it would be super easy to use the more advaced conversion service access, where the enclosing entity is inspected for further formatting information (usually by means of annotations like @DateFormat, or @NumberFormat). Please see my forum post, and the code supplied by User Antibrumm (http://forum.thymeleaf.org/Formatting-with-Spring-Formatter-tp4026363p4026793.html).

As for the rest of the processors, I would vote for a consistent behaviour, providing easyly accessible opt-in or opt-out.

Opt-out: I think you come up with some decent recommendations (using the preprocessor or toString()). Maybee use the #strings utility object, eq. ${#strings.out(variable}? On the other hand, propbably many people expect it to be extremly short (like ultraq suggests, ${!...}..

Opt-In:

The way I currently do it, using a Helper object passed in the model (2.0), or using the new bean access syntax (2.1), eq. ${@fh.print(variable)} is perfectly okay for me.

Even better would be a new thymeleaf supplied utility object (as you suggested, #conversions) which is automatically set up. The suggested conversions utility should provide a simplyfied access to the conversion service taking into account, that as a template developer, we will almost always want Object-To-String conversion.

 Lars

**Comment by danielfernandez** [comment]
@cachescrubber thanks for your comments!

> Since the main focus of the conversionService is data binding, it should be automatically applied in
> - form-binding (as always)
> - The parameter part of @{...} expressions.

Conversion will always be applied to form binding, this has been working like that since Thymeleaf 1.0, because Spring applies the conversion service to form-bound data even before it reaches thymeleaf's code (so, actually, there is no way we could even opt-out from this :-)).

As for parameters... I don't think it should be applied to parameters in `@{...}` expressions. And the reason is basically the same as for the path. If you have a not-pretty URL like:

``` html
<a th:href="@{/users/edit(userid=${user.id})}">...</a>
```

You'd be running into the same problem as with `@{|/users/${user.id}/edit|}`. So it's much safer IMO to just allow users to use `#conversion.convert(...)` for the parameters they specifically want to be converted.

> Please consider it as the default for *{...} expressions. Why? It is already a mechanism to provide a short-cut to
> print selected object properties.
> 
> ```
>  <div th:object="${session.user}">
>    <p>Name: <span th:text="*{firstName}">Sebastian</span>.</p>
>  </div>
> ```
> 
> And, it would be super easy to use the more advaced conversion service access, where the enclosing entity is
> inspected for further formatting information (usually by means of annotations like @DateFormat, or
> @NumberFormat). Please see my forum post, and the code supplied by User Antibrumm
> (http://forum.thymeleaf.org/Formatting-with-Spring-Formatter-tp4026363p4026793.html).

Yes, well, actually, from my specification above, being output from a `th:text` your code should already be using the conversion service. 

But now you mention it, I see an potential enhancement there: currently, even if the conversion service would be applied, property editors and form-binding specific conversions (like the annotation-based ones you mention) would not be used in `th:text="*{property}"`, because `th:text` does not apply them (the only one that does so is `th:field`). So, probably we should be looking into adding BindStatus-based conversion to all `*{...}` expressions in the 7 attributes listed above (`th:text`, `th:utext`, `th:value`, etc.), when inside a Spring-enabled form. I'm editing the specification in the comment above with this.

> Opt-out: I think you come up with some decent recommendations (using the preprocessor or toString()). Maybee
> use the #strings utility object, eq. ${#strings.out(variable}? On the other hand, propbably many people expect it 
> to be extremly short (like ultraq suggests, ${!...}..

Actually, there already is an equivalent to that `#strings.out(variable)`, which is `#strings.toString(variable)` :-)

> The way I currently do it, using a Helper object passed in the model (2.0), or using the new bean access 
> syntax (2.1), eq. ${@fh.print(variable)} is perfectly okay for me.

Well, in a Spring environment, you can also access the conversionService bean itself with `${@conversionService.convert(...)}`, but I suggested the creation of `#conversions` because we need a more general solution, both for Spring and not-Spring based environments.

**Comment by danielfernandez** [comment]
I've edited the specification in my comment above ( https://github.com/thymeleaf/thymeleaf/issues/222#issuecomment-26082347 )  to try to explain it in a much simpler way.

**Comment by cachescrubber** [comment]
> As for parameters... I don't think it should be applied to parameters in @{...} expressions. And the reason is basically the same as for the path. If you have a not-pretty URL like:
> 
> <a th:href="@{/users/edit(userid=${user.id})}">...</a>
> You'd be running into the same problem as with @{|/users/${user.id}/edit|}. So it's much safer IMO to just allow users to use #conversion.convert(...) for the parameters they specifically want to be converted.

Not exactly. There is indeed a difference. If the userid is not part of the url's path, but a url encoded request parameter instead, it will be converted back an forth by spring. To stay with your example:

```
/users/1.345/edit => fail.
/users/edit?userid=1.234 => success.
```

This is what I meant with "data binding". Spring will pass request parameters through the conversionService, whether they are GET request params or POST data. But it apparently does not do it for path variables (meaning @PathVariable).

I think

```
/users/edit?userid=1.234
```

is equivalent to 

```
<form method="post" action="/users/edit">
    <input type="hidden" name="userid" value="1.234"/>
</form>
```

**Comment by danielfernandez** [comment]
> Spring will pass request parameters through the conversionService, whether they are GET 
> request params or POST data. But it apparently does not do it for path variables 
> (meaning @PathVariable).

I see your point. Let me dig a bit deeper into how Spring would really create this URLs using their JSP tag library, so that I can better tune this part of the spec...

**Comment by cachescrubber** [comment]
@danielfernandez: thank you for taking that time - better to double or tripple check such a crucial piece of code.

I'll check github and the forum to test and give feedback with whatever you come up with.

**Comment by opensource21** [comment]
Be careful to format the messages. Messages has an own formatting syntax.

**Comment by danielfernandez** [comment]
@opensource21 what do you mean?

**Comment by danielfernandez** [comment]
After doing some tests and even looking quite carefully into Spring's JSP tag library source code, I can say Spring's JSP tag for creating URLs (`<spring:url>`, which mirrors the standard JSTL `<c:url>`) **does not** apply conversion neither to URL paths nor URL parameters.

The only way to do so is to do it manually, using `<spring:eval>` or `<spring:transform>`.

So thymeleaf should be safer (and more coherent with the Spring behaviour in JSP) not applying any conversions at all to `@{...}` expressions by default, and letting the user manually do it if required, using `#conversions.convert(...)`.

**Comment by opensource21** [comment]
@danielfernandez You wrote

> In such cases (when in the attributes above), the conversion service will only be applied to:
> Parameters (not message keys) in Message Expressions (#{...}).

But I have for example messages like this: `/user/edit/{0,number,##}`. So I declare in the message-source how to format the parameter. Or see http://kodejava.org/how-do-i-format-a-message-that-contains-date-information/. So in messages has a conversion service. It would be bad if you format the parameter first.

Another aspect I hope you have in mind: You can define at property-level formatter. So you can format a date user.birthday completely different than a normal date. I guess for `th:field` this is correct but, unsure for `th:text`.

Sorry I'm ill at the moment so don't have the time to test all the aspects.

**Comment by danielfernandez** [comment]
Closing this issue in favour of the implementation that has been finally decided, explained in #223
