### ISSUE TITLE
New double-bracket syntax for the application of the conversion service

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#223]
In order to regulate the use of the `IStandardConversionService` (and its Spring `ConversionService` counterpart, to which the standard service delegates), a new syntax should be established:
- For variable expressions: `${{...}}`
- For selection expressions: `*{{...}}`

This double-bracket syntax should be the only way to apply the conversion service to the expression results, therefore converting this service into an _exclusively opt-in_ service. Conversion will never be applied by default (contrary to what is being done in 2.1.0-beta2).

So given an `Integer`-to-`String` converter that adds commas as a thousands separator, this:

``` html
<p th:text="${val}">...</p>
<p th:text="${{val}}">...</p>
```

...should result in:

``` html
<p>1234567890</p>
<p>1,234,567,890</p>
```

**Spring bound object integration**

Besides, whenever the converted (_double-bracketed_) expression refers to a Spring-bound object (e.g. a form-backing bean) thymeleaf will not only apply the conversion service but also the property editors and also any formatting annotations. So given:

``` html
<form th:object="${obj}">
  <p>Date: <span th:text="*{{date}}">somedate</span></p>
</form>
```

If that `date` field in `${obj}` has an annotation like:

``` java
@DateTimeFormat(pattern = "yyyy-MM-dd")
private Date date;
```

The result will be:

``` html
<form>
  <p>Date: <span>1492-10-12</span></p>
</form>
```

**#conversions utility object**

Besides this double-bracket syntax, a new expression utility object will be added, allowing the manual execution of the conversion service whenever needed:

``` html
<p th:text="${'Val: ' + #conversions.convert(val,'String')}">...</p>
```

Syntax for this utility object:
- `#conversions.convert(Object,Class)`: converts the object to the specified class.
- `#conversions.convert(Object,String)`: same as above, but specifying the target class as a String (note the `java.lang.` package can be ommitted).

**Comment by danielfernandez** [comment]
Note this issue substitutes #222

**Comment by danielfernandez** [comment]
Added to 2.1.0-SNAPSHOT

**Comment by opensource21** [comment]
Please make sure that the documentation of a migration from 2.0 to 2.1 should contain a search for `"*\{(.*)\}"` replace with `"*{{$1}}"`.

**Comment by danielfernandez** [comment]
@opensource21 why? single-bracket expressions will work in 2.1 exactly as they do in 2.0... no need to modify them when migrating.

**Comment by opensource21** [comment]
@danielfernandez I guess I miss something, but my understanding is the following:
2.0 Only for th:fields with *{var} the value will be formatted.
2.1 For all expression single brackets-var will not convert. This should true for th:field too. So old code must be changed. Or is there an inconsistency?

**Comment by danielfernandez** [comment]
@opensource21 ok, I understand your point. Let me explain:

> 2.0 Only for th:fields with *{var} the value will be formatted.

Correct. Single-bracketted selection (`*{...}`) expressions are only formatted in form inputs, specifically in `th:field` attributes. This is something we cannot even opt-out, because it is done by Spring before thymeleaf retrieves the data from the form object.

> 2.1 For all expression single brackets-var will not convert. This should true for th:field too.

Single brackets will not convert, exactly. But that cannot be true for `th:field`, because, as explained above, Spring performs these conversions always. So single-brackets in `th:field` will convert always. 

> Or is there an inconsistency?

It depends. It is an inconsistency in the sense that single-brackets do not perform conversion, but when in `th:field` they do. But it is not an inconsistency in the sense that this is exactly how thymeleaf 2.0 works, so 2.1 is consistent with 2.0 and no code will need to be changed.

BUT: `th:field` will also allow double-brackets (`*{{...}}`), being the result exactly equivalent. So you can use double-brackets in `th:field` if you feel it improves the consistency of your code.
