### ISSUE TITLE
Add conditional th:remove

### ISSUE THREAD

**Issue by petergeneric** [thymeleaf/thymeleaf#224]
It would be useful to have a conditional form of th:remove, as originally described in http://forum.thymeleaf.org/Conditional-variant-of-th-remove-quot-tag-quot-td4025254.html

The use case described in that topic seems like a generally useful one (making a link only appear for admins, whereas non-admins would simply see the text)

**Comment by danielfernandez** [comment]
This will be implemented by allowing `th:remove` to take any Thymeleaf Standard Expression, as long as it returns one of the following literal values:
- `all`
- `body`
- `tag`
- `all-but-first`
- `none`

Which means a conditional removal could be implemented like:

``` html
<a href="/something" th:remove="${condition}? tag : none">Link text not to be removed</a>
```

This should be perfectly backwards-compatibly while adding the new functionality.

**Comment by danielfernandez** [comment]
Also note that `th:remove` could consider `null` a synonym to `none`, so that the following works exactly as the example above:

``` html
<a href="/something" th:remove="${condition}? tag">Link text not to be removed</a>
```

If `${condition}` is false, null will be returned, and thus no removal will be performed.

**Comment by danielfernandez** [comment]
Updated 2.1.0-SNAPSHOT
