### ISSUE TITLE
 randomAlphanumeric in #strings object

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf#227]
Shouldn't the org.thymeleaf.util.StringUtils.randomAlphanumeric() method be also in #strings (org.thymeleaf.expression.Strings) object?

**Comment by danielfernandez** [comment]
Hmmm yes. I cannot really remember why that method was implemented :$, but it could be useful for some sorts of non-static prototyping...

Can you take care of it? :)

**Comment by jmiguelsamper** [comment]
I came to it reviewing the ChangeLog. Yes, I'll fix it.
