### ISSUE TITLE
"th:remove" attribute still remains in output.

### ISSUE THREAD

**Issue by yseun** [thymeleaf/thymeleaf#234]
I need &lt;rotation&gt; tag if only the network is IPTV.
Removing &lt;rotation&gt; tag is successfull,
but else, "th:remove" attribute still remains in output.

template : (in case, network is "IPTV")
&nbsp;&nbsp;&nbsp;&lt;rotation th:remove="${network != 'IPTV'} ? all"/&gt;
I guess the following result :
&nbsp;&nbsp;&nbsp;&lt;rotation /&gt;
but, the result is :
&nbsp;&nbsp;&nbsp;&lt;rotation <b>th:remove="${network != &amp;#39;IPTV&amp;#39;} ? all"</b>/&gt;

**Comment by danielfernandez** [comment]
Fixed and updated in 2.1.1-SNAPSHOT.
