### ISSUE TITLE
Using the | (pipe / vertical bar) character causes expression parsing exceptions

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf#238]
From the forums: http://forum.thymeleaf.org/How-to-properly-escape-the-vertical-bar-td4027061.html

The developer wants to use the | character, but it looks like the `LiteralSubstitutionUtil` class gets at it first and then messes things up with it, causing a parsing exception to be thrown.

**Comment by danielfernandez** [comment]
Fixed. Updated 2.1.2-SNAPSHOT
