### ISSUE TITLE
Disabled Checkbox and Select multiple override model

### ISSUE THREAD

**Issue by Rouche** [thymeleaf/thymeleaf#241]
I have a checkbox disabled because a part of the form cannot be changed.

The value is Checked.

The checkbox seems to still generate the hidden field. 
When i submit, the Spring model is overriden with a False (checkbox) and Null (multiselect)

They should not be generated at all. (hidden on disabled fields)

**Comment by danielfernandez** [comment]
Verified. Note this affects the thymeleaf/thymeleaf-spring3 module and not this core one. Created thymeleaf/thymeleaf-spring3#41 referencing this ticket, which will be closed.

**Comment by danielfernandez** [comment]
Just in case you are not following thymeleaf/thymeleaf-spring3#41, This has been fixed and included into 2.1.2-SNAPSHOT and 2.0.20-SNAPSHOT.

**Comment by Rouche** [comment]
Dont worry i follow :)

caint wait to remove the Javascript fix!

Thanks!

**Comment by danielfernandez** [comment]
OK. Remember you can directly use snapshot releases if you want to test, by following the instructions here: http://www.thymeleaf.org/faq.html#use-snapshot
