### ISSUE TITLE
odd/even properties of iteration status variable are counterintuitive

### ISSUE THREAD

**Issue by makigumo** [thymeleaf/thymeleaf#243]
In `org.thymeleaf.processor.attr.AbstractIterationAttrProcessor.StatusVar` `isEven()` is calculated starting from zero, which will make the first iteration 'even'. In the real world you would expect the first iteration to be 'odd', as you usually start counting from 1. Thus I propose the following change in implementation.

``` diff
         public boolean isEven() {
-            return (this.index % 2 == 0);
+            return (this.count % 2 == 0);
         }
```

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
