### ISSUE TITLE
Replace fragment local variable is incorrect

### ISSUE THREAD

**Issue by zotheca** [thymeleaf/thymeleaf#245]
Local variables inside fragments are handled differently in th:replace than in th:include. In th:include the local variable can be overriden in sub fragments. With th:replace the local variable override is removed and the original value comes though.

Example:

``` html
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<head>
    <title>Local variable error</title>
</head>
<body>
    <div class="container">

        <p>Main include start</p>
        <div th:include=":: includeTemplate ('Main include')">
        </div>
        <p>Main include end</p>

        <p>Main replace start</p>
        <div th:replace=":: replaceTemplate ('Main replace')">
        </div>
        <p>Main replace end</p>

    </div>

    <div th:remove="all">
        Templates:

        <div th:fragment="includeTemplate (value)">
            <p>Include template value: <span th:text="${value}">Test</span></p>

            <div th:include=":: subIncludeTemplate ('Sub include')">
            </div>
        </div>

        <div th:fragment="subIncludeTemplate (value)">
            <p>Sub include template value: <span th:text="${value}">Test</span></p>
        </div>

        <div th:fragment="replaceTemplate (value)">
            <p>Replace template value: <span th:text="${value}">Test</span></p>

            <div th:replace=":: subReplaceTemplate ('Sub replace')">
            </div>
        </div>

        <div th:fragment="subReplaceTemplate (value)">
            <p>Sub replace template value: <span th:text="${value}">Test</span></p>
        </div>

    </div>

</body>
</html>
```

![replacelocalvariable](https://f.cloud.github.com/assets/6096044/1664487/220facea-5c28-11e3-9ff0-9cbc1b001562.png)

The cause seems to be in AbstractFragmentHandlingAttrProcessor on the line:

``` java
element.getParent().extractChild(element);
```

The extractChild overrides any existing local variables with the local variables from the parent.

The problem is found in version 2.1.0.

**Comment by danielfernandez** [comment]
Verified and fixed. Thanks a lot for the pointers, you've been really helpful!

Indeed, the bug was caused by `NestableNode.extractChild(...)` always replacing _all_ the local variables. I've modified it so that now it only adds those variables from its grandparent (new parent) that are missing, so that any child local variables are not overwritten.

Your example works OK now, and has been added as a test to the `thymeleaf-tests` repository.

2.1.2-SNAPSHOT has been updated with this fix.
