### ISSUE TITLE
xhtml11-thymeleaf-spring3-4.dtd cannot be validated

### ISSUE THREAD

**Issue by mpscheidt** [thymeleaf/thymeleaf#248]
<!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml11-thymeleaf-spring3-3.dtd">

is validated fine by the W3C validator, but

<!DOCTYPE html SYSTEM "http://www.thymeleaf.org/dtd/xhtml11-thymeleaf-spring3-4.dtd">

the W3C validator complains:
- Error (http://www.thymeleaf.org/dtd/xhtml11-thymeleaf-spring3-4.dtd) Line 446, Column 22: parameter entity "Flow" not defined
- Error (http://www.thymeleaf.org/dtd/xhtml11-thymeleaf-spring3-4.dtd) Line 446, Column 27: character ">" invalid: only delimiter "-", number, "ANY", "CDATA", "EMPTY", "O", "RCDATA" and parameter separators allowed

**Comment by danielfernandez** [comment]
Note: this issue should reference the non-Spring version of the DTD, namely `xhtml11-thymeleaf-4.dtd`.

The `thymeleaf-spring3` version is thymeleaf/thymeleaf-spring3#53 and the `thymeleaf-spring4` version is thymeleaf/thymeleaf-spring4#4. All three versions are affected.

**Comment by danielfernandez** [comment]
Updated 2.1.3-SNAPSHOT
