### ISSUE TITLE
Template Preprocessing and BEM CSS syntax

### ISSUE THREAD

**Issue by paulfairless** [thymeleaf/thymeleaf#249]
We're using the BEM notation for organising our CSS. This however has thrown up an issue with the preprocessing template syntax `__${something}__`

BEM stands for Block Element Modifier and requires you to structure your CSS as

``` css
.block{}
.block__element{}
.block--modifier{}
```

Now we are running into issues with the preprocessor and the `block__element` class names clashing. I understand we can escape the `__` however this results in templates that are particularly difficult to read.

Any ideas if we can change the token `__` to something else in thymeleaf?

**Comment by danielfernandez** [comment]
The `__` syntax is part of the core of the Thymeleaf Standard Expression processors. Unfortunately, it would be quite difficult (and provoke a lot of legacy code incompatibilities) to change it.

However, thymeleaf does make sure that preprocessing marks are not escaped (like `\_\_`), that they appear in pairs (`x__y__z` is preprocessed but `x__y,z` isn't), and that what is delimited between the `__` marks actually is a valid thymeleaf expression (if not, preprocessing is not applied).

This test pretty much summarizes the possibilities: https://github.com/thymeleaf/thymeleaf-tests/blob/20140507/src/test-21/resources/engine21/features/expression/expression03.thtest
