### ISSUE TITLE
use thymleaf without spring or servlet container

### ISSUE THREAD

**Issue by user20161119** [thymeleaf/thymeleaf#256]
How can use thymleaf without spring or servlet container to generate html content?
thanks

``` java
TemplateResolver templateresolver = new TemplateResolver();
        templateresolver.setPrefix("mail");
    //  templateresolver.setTemplateMode("HTML5");
        templateresolver.setCharacterEncoding("UTF-8");
        TemplateEngine templateEngine = new TemplateEngine();
        templateEngine.setTemplateResolver(templateresolver);

        // Prepare the evaluation context
        final Context ctx = new Context(Locale.ENGLISH);
        ctx.setVariable("name", "jianwen");
        ctx.setVariable("subscriptionDate", new Date());
        ctx.setVariable("hobbies", Arrays.asList("Cinema", "Sports", "Music"));

        // Prepare message using a Spring helper

        // Create the HTML body using Thymeleaf
        final String htmlContent = templateEngine.process("email-simple.html", ctx);
        System.out.println(htmlContent);
```

**Comment by danielfernandez** [comment]
This is probably more a question for the forum [ http://forum.thymeleaf.org ]. Anyway, there is an entire tutorial and example application devoted to using Thymeleaf without the need of using Spring. See it here: http://www.thymeleaf.org/documentation.html it's titled **Using Thymeleaf** and its companion application is the _Good Thymes Virtual Grocery_, which code lives here: https://github.com/thymeleaf/thymeleafexamples-gtvg

**Comment by Volodymyr128** [comment]
@danielfernandez  your example works with `ServletContextTemplateResolver`. All Thymeleaf doc is bounded to controllers and routing specific staff. As I understand the question, user asked you to provide something like this Velocity's example http://www.javaworld.com/article/2075966/core-java/start-up-the-velocity-template-engine.html. It generates template in few string of code without controller-specific logic
