### ISSUE TITLE
Incorrect replacing in script inlining

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf#257]
In Thymeleaf 2.1.2,

``` java
        ga('set', 'dimension1', /*[[${referrer}]]*/ '' );
```

when the "referrer" field is empty, Thymeleaf renders this as

``` java
        ga('set', 'dimension1', '' ;
```

Reported by Chrylis in the forum:
   http://forum.thymeleaf.org/Problem-with-script-inlining-td4027438.html

**Comment by danielfernandez** [comment]
Updated 2.1.3-SNAPSHOT
