### ISSUE TITLE
Improve logging

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#259]
Two actions to be taken:
1. Generalize logging so that no specific library is used (`slf4j`, currently). Instead, logging should be pluggable so that a different implementation can be also used if needed, and in order to avoid collisions with the logging technologies used by client applications. Default implementation should still be `slf4j`.
2. Extensions (processors, resolvers, etc.) should be allowed to use logging without the need to register their own infrastructure for this, using libraries that might collide with the ones used by Thymeleaf itself. These extensions should be directed towards using the generalized logging system mentioned above.

**Comment by balazsmaria** [comment]
Do you mean to use an own facade instead of the de facto standard facade?

**Comment by danielfernandez** [comment]
Closing as declined - after evaluation, slf4j still makes perfect sense as a default choice, and using a custom logging interface would add quite a lot of (probably unnecessary) clutter.
