### ISSUE TITLE
Create a #strings.default() method

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#263]
Sometimes it makes sense to have something like:

```
(${myString} and ${myString != ''})? ${myString} : 'somedefault'
```

This is not equivalent to any of these:

```
${myString} ?: 'somedefault'
${#objects.nullSafe(myString,'somedefault')}
```

Because the empty String would be evaluated as `true` in these cases. So a new method (with array_, list_ and set\* version) could be added to `#strings` in order to perform this with:

```
${#strings.default(myString,'somedefault')}
```

**Comment by willdavidwarren** [comment]
+1
