### ISSUE TITLE
Adding a "selected" attribute based on a condition is overly verbose

### ISSUE THREAD

**Issue by jsumners** [thymeleaf/thymeleaf#276]
Unless I'm missing something, adding a "selected" attribute (or one like it) when a condition is met is more complicated than it needs to be. As an example, the following is building a list of options for a select box. It is designed to pre-select an option based on a user's past choice:

``` html
<div th:each="gateway : ${gateways}" th:remove="tag">
  <option th:if="${gateway.extension != smsAddress.extension}"
               th:value="${gateway.extension}"
               th:text="${gateway.carrier}">A Carrier</option>

  <option th:if="${gateway.extension == smsAddress.extension}"
               th:value="${gateway.extension}"
               th:text="${gateway.carrier}"
               selected="selected">A Carrier</option>
</div>

<option value="0">Other</option>
```

Note that I have essentially the same code written _twice_ just because I can't do something like:

``` html
<option th:value="${gateway.extension}"
             th:text="${gateway.extension}"
             th:attrif="${gateway.extension == smsAddress.extension} ? selected='selected'">A Carrier</option>
```

**Comment by jmiguelsamper** [comment]
Hello,

I think you are looking for the th:selected attribute.

Try 
    th:selected="${gateway.extension == smsAddress.extension}"

If you have further doubts, you can use the forum at http://forum.thymeleaf.org/

**Comment by ghost** [comment]
So I don't think the question is laughable at all. What he needs is for the "selected" attribute not to be added at all, if option is not selected. Your solution will still render the selected attribute if the condition is false. Same with "required" attribute. HTML does not require a value to them to be recognized. So now without laughing at the question, is there a real solution?
