### ISSUE TITLE
Relative ${url} is not working

### ISSUE THREAD

**Issue by anil1712** [thymeleaf/thymeleaf#279]
Hi, I am using Spring Web MVC and <a href="http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html">Thymeleaf template Engine</a> and got stuck while creating url.

 I have a url this `http://localhost:8080/project/web/category/mobiles`
 and now I want to create relative url like this `http://localhost:8080/project/web/category/mobiles/store/samsung` 
or 
`http://localhost:8080/project/web/category/mobiles?min_price=10&max_price=100.` , 

so I use `${url}` but its not working. 

Ex: If url in address bar is: `http://localhost:8080/project/web/category/mobiles/store/samsung` 
then the url will be 

```
<a th:href="@{__${url}__/store/__${store.name}__}">Click to More</a>
//will produce: http://localhost:8080/project/web/category/null/store/samsung
//I want: http://localhost:8080/project/web/category/mobiles/store/samsung
```

If url in address bar is: 
`http://localhost:8080/project/web/category/mobiles/store/samsung?start=1&end=20`

```
<a th:href="@{${url}(page=${pgn})}">Click to More</a>
//will produce: http://localhost:8080/project/web/category/mobiles/store/samsung?page=1
//i want: will produce: http://localhost:8080/project/web/category/mobiles/store/samsung?start=1&end=20&page=1
```

Please check this issue and if am I doing something wrong and please provide any solution for this.

**Comment by jmiguelsamper** [comment]
Hello,

if you just want a relative URL you don't need any Thymeleaf syntax, just write

``` html
    <a href="store/samsung">
```

for the first example.

Or if you want to add parameters to current URL, you can use, for example

``` html
   <a th:href="@{${#httpServletRequest.requestURI}(foo='bar')}">
```

You can learn about Thymeleaf URL syntax in the section
   http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#link-urls

Please use the forums if you have any further questions
   http://forum.thymeleaf.org/General-Usage-f2234430.html

**Comment by anil1712** [comment]
your both examples are not working any more, the 1st one `<a href="store/samsung">` will append the `store` all the time in every request in href and the 2nd one `${#httpServletRequest.requestURI}` is showing no changes on url.

*I posted the same on <a href="http://forum.thymeleaf.org/Relative-url-is-not-working-td4027852.html">thymeleaf forum</a>, please give me some soution.
