### ISSUE TITLE
Feature Request: Safe Null Dereferencing

### ISSUE THREAD

**Issue by taypo** [thymeleaf/thymeleaf#281]
I could be like how grails does it. Like
${song?.video.thumbnail}

Above expression would not throw TemplateProcessingException when the video is null, if you reference it with the ?. operator.

What do you think?

**Comment by jmiguelsamper** [comment]
Hello,

that syntax is already supported in both OGNL and SpringEL, but the ? must be _after_ the element that can be null.

Regards.

**Comment by taypo** [comment]
That's great, thank you.
