### ISSUE TITLE
Not return value default with multi-language using #strings.defaultString

### ISSUE THREAD

**Issue by vitornp** [thymeleaf/thymeleaf#286]
Use:

``` html
<span th:text="${#strings.defaultString(str, #{text.uninformed})}"></span>
```

Return: Caused by: ognl.OgnlException: source is null for getProperty(null, "uninformed")

Use:

``` html
<li th:inline="text">
    [[${#strings.defaultString(str, #{text.uninformed})}]]
</li>
```

Return:

``` html
<li>
    [[${#strings.defaultString(document.number, #{text.uninformed})}]]
</li>
```

**Comment by kreuzman** [comment]
Hi you must use preprocessing expression to execute localized message (default value in your case) first.

So this will work for you.

```
<span th:text="${#strings.defaultString(str, '__#{text.uninformed}__')}"></span>
```

```
<li th:inline="text">
        [[${#strings.defaultString(str, '__#{text.uninformed}__')}]]
</li>
```

**Comment by danielfernandez** [comment]
Michal is right, you are trying to execute a Thymeleaf i18n expresion inside a Thymeleaf variable expression (which is executed by the OGNL engine, who does not know about `#{...}` expressions).

However, there's another possibility besides preprocessing: you can use the `#messages` utility object like:

``` html
<span th:text="${#strings.defaultString(str, #messages.msg('text.uninformed'))}"></span>
```

More about this `#messages` utility object here: http://www.thymeleaf.org/doc/html/Using-Thymeleaf.html#messages-1

**Comment by vitornp** [comment]
@kreuzman @danielfernandez thanks for the help!
