### ISSUE TITLE
Literal substitutions could not parse

### ISSUE THREAD

**Issue by vitornp** [thymeleaf/thymeleaf#288]
Use: 

``` html
<span th:text="|${country} (#{signal}${code})|"></span>
```

Return:
org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "|${country} (#{signal}${code})|"

**Comment by danielfernandez** [comment]
Thanks. This was a bug. It's now been fixed.

2.1.4-SNAPSHOT has been updated, including this fix.

**Comment by vitornp** [comment]
Thanks!

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.
