### ISSUE TITLE
Support of conditional statement for tag attributes.

### ISSUE THREAD

**Issue by davicdsalves** [thymeleaf/thymeleaf#292]
I have a requirement to load a javascript function on the body tag whenever a model variable is true, something that I would simple do like this with jstl:

```
<body <c:if test="${userCreated}"> onload="somejavascriptfunction()"</c:if> >
```

But from my understanding Thymeleaf works only with if conditions for tags, so in order to have a conditional body attribute I would need a whole conditional body tag, and that doesn't seems reasonable.
Is there any way to acomplish what I need?
So far the only solution I found was to do it like this

```
<script type="text/javascript" th:if="${userCreated}">
  $(document).ready(function() {
     somejavascriptfunction()
  });
</script>
```

**Comment by willdavidwarren** [comment]
I think you could do this fairly easily with `th:attr`. It would be something along the lines of:

``` html
<body th:attr="onload=${userCreated} ? 'somejavascriptfunction()' : ''">
```

**Comment by danielfernandez** [comment]
Actually, there is a `th:onload` attribute processor, and the _else_ part of a conditional expression is optional. So your expression could be as simple as:

``` html
<body th:onload="${userCreated}? 'somejavascriptfunction()'">
```

**Comment by danielfernandez** [comment]
By the way, you can know more about how Thymeleaf Standard Expressions work here: http://www.thymeleaf.org/standarddialect5minutes.html

**Comment by davicdsalves** [comment]
Thanks for your support guys. I will try what you suggested.
