### ISSUE TITLE
Local variables defined in the th:with attribute of a given tag cannot be used in the th:if attribute of the same tag

### ISSUE THREAD

**Issue by marcosabel** [thymeleaf/thymeleaf#293]
Hi guys,

The precedence values currently defined for thymeleaf attributes make imposible to use local variables in the th:if attribute. To better clarify the situation, in the following example the variable local will not be defined when evaluating the th:if attribute:

```
    <div th:with="local=${true}" th:if="${local}"></div>
```

I understand that the precedence values currently defined provide the advantage of not evaluating the th:with attribute when th:if evaluates to false, but I find "weird" the fact of not being able to use local variables in the th:if attribute. 

What do you guys think about this topic?

**Comment by Antibrumm** [comment]
For me the evaluation of `th:with` after `th:if` is ok as it is.
I use it quite often together and prefer that the variables are only evaluated if the children need to be rendered. 

So `th:if`/ `th:unless` are not evaluating all variables and throw half of them away directly afterwards.

You could however easily add your own processor `th:earlywith` by just extending the `th:with` processor and giving it a higher precedence than `th:if`.

**Comment by danielfernandez** [comment]
We are declining this. Preference order makes more sense the way it is, order of attributes cannot be used because HTML does not consider attributes ordered (and attributes cannot be duplicated in a tag) and scenarios like this can be solved by means of using the synthetic `th:block` tag.
