### ISSUE TITLE
Integration with CDI

### ISSUE THREAD

**Issue by vitornp** [thymeleaf/thymeleaf#299]
Possible integrate thymeleaf with CDI?

**Comment by danielfernandez** [comment]
Why not? In the same way you can define thymeleaf's relevant _beans_ in Spring using XML or annotations, you should be able to contruct and inject your thymeleaf objects using CDI...

**Comment by vitornp** [comment]
I have a class

``` java
@Named("linkTo")
@ApplicationScoped
public class LinkToHandler
...
```

Try to use:

``` html
<span th:text="${linkTo[EquipmentController].index}"></span>
```

I get an error https://gist.github.com/vitornp/50624276dacb632fa67f
