### ISSUE TITLE
AbstractStandardScriptingTextInliner swallows uncatched exceptions

### ISSUE THREAD

**Issue by Antibrumm** [thymeleaf/thymeleaf#301]
Just ran into a small issue which took me a while to find out whats happening. 
The `AbstractStandardScriptingTextInliner`is swallowing exceptions without any hint to the developer. 

Line: 290+  // If it is not a standard expression, just output it as original

I had an uncatched exception during the evaluation of the expression and as a result the JS started to fail. no hint on the server side at all.

Is there a reason why this exception is not failing the templating process as in any other attribute processor?

**Comment by danielfernandez** [comment]
Fixed, thanks a lot.

Updated 2.1.4-SNAPSHOT

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.
