### ISSUE TITLE
Evaluate the creation of a new extra component for JSR-310/jodatime support

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#302]
We should evaluate the possibility of creating a new extra for JSR-310 (Java 8's Date API) and jodatime. One is a Java8-only feature and the other one an external library, so at first it seems they shouldn't be in the core (_would there be a way?_)...

**Comment by ultraq** [comment]
Is this intended to be something that replaces the `#dates` utility object, such that it processes Java 8 dates / Joda dates instead of the standard Java ones?

**Comment by danielfernandez** [comment]
It would be nice if it could actually replace the _standard_ `#dates` object only when Java 8 is present, but not processing JSR-310 and JodaTime dates _instead_ of standard ones, but _besides_.

**Comment by odrotbohm** [comment]
Been running into this as well. Pretty much prevents us from using JDK 8 DateTime types in views which is a pity. Any ETA?

**Comment by danielfernandez** [comment]
Actually, we are starting the development of a small dialect to give support to JSR310 in a simple and modular way. Should be ready in a couple of weeks or less.

**Comment by jmiguelsamper** [comment]
The source code will be available at https://github.com/thymeleaf/thymeleaf-extras-java8time

At this moment all creation methods and a few of the formatting methods are implemented.

**Comment by jmiguelsamper** [comment]
Now 2.1.0-SNAPSHOT is in the Sonatype Snapshot Repository.

We'll still perform some testing and refactoring before releasing it into Maven Central repo.

**Comment by odrotbohm** [comment]
Works like a charm, thanks. Is there any reason this will be a 2.1.0 while core Thymeleaf is in 2.1.3 already? Do you version extras independently?

**Comment by danielfernandez** [comment]
Correct. The first two parts of an extra's `x.y.z` version correspond to the `x.y` version of the core such extra works with. The third `z` number is independent. Not doing so would force us to create new versions of every extra with each update of the core.

Extras link with the `x.y` part of the core's version because that's the level at which API changes in the core may occur.

**Comment by odrotbohm** [comment]
Gotcha, thanks. Makes version management a bit more complicated in Maven but understood. Thanks for the quick turnaround!
