### ISSUE TITLE
Strange th:object behavior in combination with th:remove="tag"

### ISSUE THREAD

**Issue by huxi** [thymeleaf/thymeleaf#303]
In a main template:

``` xml
<div th:replace="someTemplate::table(foo=${foo}, bar=${bar})">
    Content of someTemplate
</div>
```

In someTemplate:

``` xml
<table th:fragment="table(bar, foo)" th:if="${foo}" th:object="${foo}">
    <tr th:replace="otherTemplate::table(bar=${bar})">
        <th>A header</th>
        <td>Some data</td>
    </tr>
</table>
```

In otherTemplate:

``` xml
<table th:fragment="table(bar)" th:if="${bar}" th:object="${bar}" th:remove="tag">
    <tr>
        <th>Some other header</th>
        <td th:text="*{class}">Should be bar.class but is foo.class</td>
    </tr>
</table>
```

`otherTemplate` kind of "works as expected" meaning that the surrounding `<table>` is removed and only the contained `<tr>` ends up in `someTemplate`. But `*{class}` is printing the class of `foo` instead of the class of `bar`.

If I remove `th:remove="tag"` from `otherTemplate` then `*{class}` returns the class of `bar` as expected. Am I missing something or is this a bug?

**Comment by jmiguelsamper** [comment]
Hello,

In the first and second template the parameters are switched. Is that intentional?

```
th:replace="someTemplate::table(foo=${foo}, bar=${bar})"

th:fragment="table(bar, foo)"
```

**Comment by huxi** [comment]
Kind of. Calling a template with named arguments makes the order of them irrelevant. I don't think it makes a difference in this case but I should have switched them to avoid confusion.

**Comment by danielfernandez** [comment]
That was a bug. It's now fixed, thanks.

Updated 2.1.4-SNAPSHOT

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.

**Comment by huxi** [comment]
Thanks for the info!
