### ISSUE TITLE
Create an #uris expression utility class for URI/URL-related utilities

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#305]
A new `#uris` utility object could be useful in expressions for dealing with some common URI/URL-related operations.

Initially, it should offer escape/unescape operations for the diverse parts of an URI (path, path segment, query parameters, fragment identifiers), based on the [Unbescape](http://www.unbescape.org) library.

**Comment by danielfernandez** [comment]
Updated 2.1.4-SNAPSHOT.

**Comment by chrylis** [comment]
This class is not mentioned in the documentation.
