### ISSUE TITLE
Preserve single quote attribute declarations

### ISSUE THREAD

**Issue by jmiguelsamper** [thymeleaf/thymeleaf#313]
Javascript libraries are challenging us these days with their complicated syntaxes.

The following is valid XML (see point [10] of http://www.w3.org/TR/xml/#sec-common-syn):

``` html
    <div data-options='{"number" : 3}'></div>
```

but Thymeleaf (as of 2.1.3.RELEASE) will transform it to the invalid

``` html
    <div data-options="{"number" : 3}"></div>
```

As a workaround, a user could use

``` html
    <div data-options="{&quot;number&quot; : 3}"></div>
```

or even

``` html
    <div data-options="{'number' : 3}"></div>
```

if their JSON parser allows this syntax (not JSON standard).

As Javascript libraries are becoming more and more popular, maybe Thymeleaf should preserve the type of quotes used originally in the template.

Question asked at http://forum.thymeleaf.org/Thymeleaf-process-on-single-quoted-attributes-td4028320.html

**Comment by ultraq** [comment]
Might be a job for AttoParser in Thymeleaf 3.0 since XML (and thus the XML engine under the hood of Thymeleaf 2.1-) requires the double-quoted attribute values.

**Comment by RiZKiT** [comment]
Thanks god I found this issue today, I ran into the same problem and was afraid I'm the only one. And using escaped quotes is a temporary but ugly workaround and makes it hard to read the JSON.

@ultraq as OP already posted (here with an even more specific link http://www.w3.org/TR/REC-xml/#NT-AttValue) it seems totally valid to have single quoted attributes. It just feels unnaturally.

On the other hand, single quoted JSON is invalid **sic**.

**Comment by jgrtalk** [comment]
So, no solution yet?

**Comment by danielfernandez** [comment]
This situation will no longer happen in Thymeleaf 3.0, as the new underlying parser (attoparser) will preserve the original state of non-processable attributes: type of quotes, specification or not of a value, etc.

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
