### ISSUE TITLE
Final methods in TemplateEngine make it difficult to mock

### ISSUE THREAD

**Issue by whitneyh** [thymeleaf/thymeleaf#314]
All the process(...) methods in TemplateEngine are marked as 'final'. This makes creating a Mockito mock object for it difficult. Please consider removing this keyword from methods in this class.

**Comment by danielfernandez** [comment]
I understand your point. Thymeleaf v3 will actually make most of its structures implement interfaces so that they are easier to test or mock (e.g. `ITemplateEngine`).

**Comment by danielfernandez** [comment]
This is already so in Thymelaf 3.0, including an `ITemplateEngine` interface for the `TemplateEngine` class.

Already in `3.0.0-SNAPSHOT´

**Comment by T3rm1** [comment]
Over one year later, nothing has changed, 3.0 isn't out and we are still not able to mock Thymeleaf with Mockito. Why didn't you change the code? It's really easy and fast to do...

**Comment by karollewandowski** [comment]
If it's a blocker for you, you can use PowerMockito to mock final methods.

**Comment by markot6** [comment]
A workaround is create a temporary interface and a related implementation:

```
public interface ITemplateEngine {
    String process(String template, IContext context);
}
```

```
@Component
public class TemplateEngineWrapper implements ITemplateEngine {
    @Autowired
    private SpringTemplateEngine templateEngine;

    @Override
    public String process(String templateName, IContext context) {
        return templateEngine.process(templateName, context);
    }

}
```

Then, in the tested component instead of:

```
@Autowired
private SpringTemplateEngine templateEngine;

```

use:

```
@Autowired
private ITemplateEngine templateEngine;

```

Now, you can easily `mock(ITemplateEngine.class)` and its `process()` method.
