### ISSUE TITLE
Syntax for unescaped text inlining

### ISSUE THREAD

**Issue by ultraq** [thymeleaf/thymeleaf#316]
I was recently creating an XML template for an RSS feed that Thymeleaf could process, and instead of my usual of putting `th:text` attribute processors to feed into the text fields, I thought I'd put a `th:inline="text"` declaration at the top and do some inlining.  It worked quite well (since the important thing to me was having a good overview of the elements I was putting into the RSS feed, not static prototyping at all), but some sections I wanted to use CDATA (eg: the item `<description>` and `<title>` tags) since those fields could contain XML special characters or arbitrary HTML.

I couldn't put CDATA into the inline expressions since the XML parser would then interpret them as plain text and they wouldn't get processed, so I had to write a utility object to do it for me and call it from a `th:utext` processor.  This broke the flow of having everything as inline expressions.

An unescaped text inlining expression would have been useful here, so thoughts/opinions on creating one?

**
I just saw #310 and the linked issues.  Not sure how this might work if #307 is adopted though.

**Comment by danielfernandez** [comment]
This is covered by #394 in Thymeleaf 3.0
