### ISSUE TITLE
Dependency on ognl introduces dependence on old javassist version

### ISSUE THREAD

**Issue by matthauck** [thymeleaf/thymeleaf#317]
I was hoping to move to thymeleaf from struts2. One of the (minor) reasons to move away from struts2 was that it would avoid the dependency ognl:ognl:3.0.6 -> javassist:javassist:3.11.0.GA. The reason is that the 3.11 javassist library conflicts with version of javassist in hibernate 4.2+. This is blocking a move to thymeleaf for us for now at least, since we'd rather stay up to date with hibernate.

**Comment by jmiguelsamper** [comment]
You can exclude Javassist dependency from Thymeleaf like:

``` xml
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
            <version>2.1.3.RELEASE</version>
            <exclusions>
                <exclusion>
                    <artifactId>javassist</artifactId>
                    <groupId>org.javassist</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by matthauck** [comment]
I assumed that this would break the `ognl` library since it depended on it. Perhaps thymeleaf could add this exclusion to your own pom.xml so that this javassist does not transitively get passed on to consumers of thymeleaf?

**Comment by danielfernandez** [comment]
Actually, thymeleaf does _not_ use that version of javassist. Thymeleaf 2.1.3.RELEASE uses javassist 3.16.1-GA, and if I remember correctly we've been using it for some time (for thymeleaf javassist is not only an indirect dependency, but in fact a direct one -- we use a little bit of javassist code). See https://github.com/thymeleaf/thymeleaf/blob/2.1-master/pom.xml#L235-L253

So if you are fine with 3.16.1-GA, you should have no trouble. Did you actually test it?

Anyway, if you prefer a different version, or simply match it with the one needed by your hibernate version, simply set the dependency to your specific version using a `<dependencyManagement>` section in your pom.xml and you should be fine.

By the way, I'm assuming you don't use Spring... do you? If you use Spring, neither OGNL nor javassist are used at all, so you can actually remove OGNL itself from your classpath with a maven exclusion.

**Comment by matthauck** [comment]
As for whether I really tested it, I didn't get very far beyond analyzing its dependencies to see if it would solve the issue I was having with struts2. Strangely enough, gradle is resolving the dependencies differently with struts being on/off the compile dependencies for my project. This is what I saw:

```
+--- org.thymeleaf:thymeleaf:2.1.3.RELEASE
|    +--- ognl:ognl:3.0.6
|    |    \--- javassist:javassist:3.11.0.GA
|    +--- org.javassist:javassist:3.16.1-GA -> 3.18.1-GA
|    +--- org.unbescape:unbescape:1.0
|    \--- org.slf4j:slf4j-api:1.6.1 -> 1.7.5
```

(Note the different group name in ''javassist:javassist'', which makes this dependency even more difficult to work with because the class names still conflict, I believe, even across this group name change...)

Now with struts2 gone, I see this:

```
+--- org.thymeleaf:thymeleaf:2.1.3.RELEASE
|    +--- ognl:ognl:3.0.6
|    +--- org.javassist:javassist:3.16.1-GA -> 3.18.1-GA
|    +--- org.unbescape:unbescape:1.0
|    \--- org.slf4j:slf4j-api:1.6.1 -> 1.7.5
```

So... yeah, non-issue here I suppose.
