### ISSUE TITLE
please allow to iterate java.util.Enumeration

### ISSUE THREAD

**Issue by n0mer** [thymeleaf/thymeleaf#321]
Currently http://www.thymeleaf.org/doc/usingthymeleaf.html#iteration says the following:

> **Iterable values**
> Not only `java.util.List` objects can be used for iteration in Thymeleaf. In fact, there is a quite complete set of objects that are considered iterable by a th:each attribute:
> - Any object implementing `java.util.Iterable`
> - Any object implementing `java.util.Map`. When iterating maps, iter variables will be of class `java.util.Map.Entry`.
> - Any array
> - Any other object will be treated as if it were a single-valued list containing the object itself.

Please add support for `java.util.Enumeration`. Or please advice how to iterate properly to display all `${#httpServletRequest.attributeNames}`

The following code does not work properly:

``` html
        <div th:each="attr: ${#httpServletRequest.attributeNames}">
            <dl>
                <dd th:text="${attr}">name</dd>
            </dl>
        </div>
```

It produces the following output: 

> org.apache.catalina.core.ApplicationHttpRequest$AttributeNamesEnumerator@3b670cc3

**Comment by ultraq** [comment]
You can convert Enumerations to Iterables using the `Collections.list` method.  In Spring:

``` html
<div th:each="attr: ${T(java.util.Collections).list(#httpServletRequest.attributeNames)}">
```

In OGNL (ie: Thymeleaf without Spring):

``` html
<div th:each="attr: ${java.util.Collections.list(#httpServletRequest.attributeNames)}">
```

**Comment by n0mer** [comment]
@ultraq , thank for the quick response.

This solution will work, but it will create unnecessary in-memory ArrayList just for the sake of iteration.
Do you think this is the right way to iterate over `java.lang.Iterable` ?

And, can you please point to the right section of http://www.thymeleaf.org/doc/usingthymeleaf.html , where i can read more about type reference using "T" construct? I've searched through "using thymeleaf" by the word "convert" and found nothing so far.

**Comment by n0mer** [comment]
few more thoughts from http://stackoverflow.com/a/14979639/935546

> 1. There is no need to convert `Iterable` to `Collection` to use foreach loop - Iterable may be used in such loop directly, there is no syntactical difference, so I hardly understand why the original question was asked at all.
> 2. Suggested way to convert `Iterable` to `Collection` is unsafe (the same relates to `CollectionUtils`) - there is no guarantee that subsequent calls to the next() method return different object instances. Moreover, this concern is not pure theoretical. E.g. Iterable implementation used to pass values to a reduce method of `Hadoop Reducer` always returns the same value instance, just with different field values. So if you apply `makeCollection` from above (or `CollectionUtils.addAll(Iterator)`) you will end up with a collection with all identical elements.

Depsite the fact of http://alexruiz.developerblogs.com/?p=2519 , Iterable is currently the only way (AFAIK) to query for request attribute names in servlet api.

So, for my use case (to display the list of request attrs in error page) this is semi-okay - i'm ready to pay this memory penalty. But Thymeleaf should be usable in other use cases as well.

**Comment by ultraq** [comment]
> This solution will work, but it will create unnecessary in-memory ArrayList just for the sake of iteration.

True, I was just suggesting a workaround as we don't currently support `th:each` for Enumeration types.

> And, can you please point to the right section of http://www.thymeleaf.org/doc/usingthymeleaf.html , where i can read more about type reference using "T" construct?

That's actually in SpringEL, so http://docs.spring.io/spring-framework/docs/4.0.x/spring-framework-reference/html/expressions.html, section 7.5.8 shows its usage.

**Comment by n0mer** [comment]
thanks for pointing out to SpEL

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`

**Comment by n0mer** [comment]
:+1:
