### ISSUE TITLE
Merging of Dialects works incorrectly

### ISSUE THREAD

**Issue by arokhmistrov** [thymeleaf/thymeleaf#324]
version: 2.1.3-RELEASE
class: org.thymeleaf.Configuration

//line 637
final Map<Class<? extends Node>, Set<ProcessorAndContext>> nonSpecificProcessorsByNodeClass = new HashMap<Class<? extends Node>, Set<ProcessorAndContext>>(20);

//line 697
/\* Aggregate all the processors not assigned to a specific attribute or element name*/
nonSpecificProcessorsByNodeClass.putAll(dialectConfiguration.unsafeGetNonSpecificProcessorsByNodeClass());

The last line on code does not append processors to a set associated with specific node class, but overrides the set.

I've added two dialects in spring config:
bean class="com.github.mxab.thymeleaf.extras.dataattribute.dialect.DataAttributeDialect"
bean class="ch.mfrey.thymeleaf.extras.with.WithDialect"
But works only "WithDialect", because they both provide processors for a NestableAttributeHolderNode. And the latter one overwrites former.

**Comment by danielfernandez** [comment]
Thanks. Should be fixed now.

Updated 2.1.4-SNAPSHOT

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.4 has just been published, including this fix.
