### ISSUE TITLE
Open graphs tags issue

### ISSUE THREAD

**Issue by fedebalboa** [thymeleaf/thymeleaf#331]
Problems to render og: meta tags for facebook, g+ crawlers.

Thymeleaf parser exception.

When I added this open graph tags on the html: 

http://i.imgur.com/3YEBBP3.png

This is the result

http://i.imgur.com/2rWoAgw.jpg

thanks

**Comment by jmiguelsamper** [comment]
Thymeleaf expects well-formed HTML in your templates. Close the meta tags, as in
   <meta ... />

Regards,
   Zemi

**Comment by ultraq** [comment]
Forgot the example @jmiguelsamper :)

``` html
<meta property="" content=""/>
```

(note the / )

**Comment by jmiguelsamper** [comment]
Oh, I typed it, I forgot to use markdown syntax :-|

Thanks, anyway.

**Comment by fedebalboa** [comment]
yes, my mistake, thanks !!!
