### ISSUE TITLE
How can I render a string template

### ISSUE THREAD

**Issue by airclear** [thymeleaf/thymeleaf#334]
my template content store in database.

when I get the template content from the database ,how can  I use thymeleaf to render it?

**Comment by ultraq** [comment]
This is a good question for our forums: http://forum.thymeleaf.org/General-Usage-f2234430.html  You can have a search through there to see if the question might already have been answered.  I did a search for "string template" and I came across this which might give some clue to manually rendering templates: http://forum.thymeleaf.org/Easier-way-to-process-against-a-string-as-template-td4027556.html, or this one which suggests using a custom template resolver to look up templates in a database: http://forum.thymeleaf.org/Loading-thymeleaf-template-from-Database-td4025164.html

If you don't think your question has been answered in the forums yet, feel free to write a new post in the forums.
