### ISSUE TITLE
Thymeleaf upgrade issue

### ISSUE THREAD

**Issue by esanchezros** [thymeleaf/thymeleaf#347]
I am currently using version 2.1.2.RELEASE of Thymeleaf and wanted to upgrade to the latest version as it comes with several performance improvements.

So I upgraded thymeleaf version in the pom to 2.1.4.RELEASE and ran the website as usual. The problem now is that I can see one of Internet Explorer's conditional comment on the top left corner of the screen and the layout is no longer working as expected (looks like the stylesheets are not being imported):

```
<!--[if IE 8]> <![endif]-->
```

I cannot see any errors in the Console or in the logs. I have tried adding Thymeleaf's module for Internet Explorer conditional comments to the `TemplateEngine` but did not solved the problem.

Any thoughts or ideas will be much appreciated.

**Comment by danielfernandez** [comment]
Sorry for the big delay — somehow this ticket got untriaged and lost in the backlogs :( There are no known issues in 2.1.4 with IE conditional comments, so I will suppose you will have already found and fixed your problem by now. Will therefore close this ticket for the moment.
