### ISSUE TITLE
Big bug！ Namespace conflicts

### ISSUE THREAD

**Issue by airclear** [thymeleaf/thymeleaf#356]
I use spring4 ， 

page1: 

```
<div th:each="item : ${items}"><p th:text="${item.title}"></p></div>
```

model1 :   mv.addObject("items",arr);

page2;

```
<div th:each="item : ${items}"><p th:text="${item.title}"></p></div>
```

model2 :   mv.addObject("items",arr);

When i visit the page1, and then visit page2 ,It will throw a exception .... can not cast to java.util.Map ..

**Comment by jmiguelsamper** [comment]
There is nothing wrong in that piece of code, and no Thymeleaf bug known related to simple iteration. You should look for the error in other places, try to debug the content of your model attributes on the server side.

**Comment by airclear** [comment]
see #357
