### ISSUE TITLE
A th:block between a th:select and a th:option breaks the binding of its form parameter.

### ISSUE THREAD

**Issue by adobarro** [thymeleaf/thymeleaf#358]
Hello,  

If you have a th:block between a th:select and his th:option’s and you submit the form to the same page (or to a page with the same select-block-option structure) then the form won’t be selected with the right value. 

Example:

my_template_wrong.html:

``` html

..
<select th:field="*{ordering}">

  <th:block th:each="elem: ${T(MyEnumClass).values()}">

    <option th:value="${elem.name()}" th:text=“#{‘MyMessage.’ + ${elem.name()}}">my field</option>

  </th:block>

</select>
..

```

If we don’t use the th:block the combo will be correctly selected when submitted: 

my_template_without_block.html:

``` html

..
<select th:field="*{ordering}" th:each="elem: ${T(MyEnumClass).values()}">

    <option th:value="${elem.name()}" th:text=“#{‘MyMessage.’ + ${elem.name()}}">my field</option>

</select>
..

```

Thank you

**Comment by danielfernandez** [comment]
Fixed in 2.1. Does not affect 3.0.

Already in `2.1.5-SNAPSHOT`
