### ISSUE TITLE
Changing year when using dates.format

### ISSUE THREAD

**Issue by adamjames87** [thymeleaf/thymeleaf#361]
Version: 2.1.4.RELEASE

Hi,

When using dates.format the shown year is different to the unformatted date. Obviously this does not always occur but the following date seems to trigger this error

``` java
    @RequestMapping(value = "thymeleaf_test", method = RequestMethod.GET)
    public String test(Model model) {

        // Construct offending date
        Calendar calendar = new GregorianCalendar(TimeZone.getTimeZone("GMT"));
        calendar.set(Calendar.YEAR, 2014);
        calendar.set(Calendar.DAY_OF_MONTH, 29);
        calendar.set(Calendar.MONTH, Calendar.DECEMBER);
        calendar.set(Calendar.HOUR, 3);
        calendar.set(Calendar.MINUTE, 23);
        calendar.set(Calendar.SECOND, 48);

        Date date = calendar.getTime();
        model.addAttribute("date", date);
        return "test";

    }
```

Using this simple template

``` html
<!DOCTYPE html>
<html>
<head lang="en">
    <title></title>
</head>
<body>
    <span th:text="${date}"></span>
    <br/>
    <span th:text="${#dates.format(date, 'dd/MM/YYYY')}"></span>
</body>
</html>
</html>
```

The result is that the formatted date has a year of 2015 and not 2014 as I suspect it should be.

![thymeleafbug](https://cloud.githubusercontent.com/assets/44804/7160771/1e0012f0-e383-11e4-86cc-3915c3358379.png)

Thanks.

**Comment by Shredder121** [comment]
This is not a bug in thymeleaf, but YYYY is the [ISO 8601 standard of handling when a date falls in what year](https://en.wikipedia.org/wiki/ISO_8601#Week_dates).

To be precise, I'll quote an excerpt and convince you using that.

> If 1 January is on a Monday, Tuesday, Wednesday or Thursday, it is in week 01. If 1 January is on a Friday, Saturday or Sunday, it is in week 52 or 53 of the previous year (there is no week 00). 28 December is always in the last week of its year.

Since January 1st was on a Thursday, that week was week 01 of Year 2015. 29 December was also in that week, so it's in yearweek 2015.

If you want it to format to the correct date, then use `'dd/MM/yyyy'`.

Does this answer your problem?

**Comment by adamjames87** [comment]
Ah, my mistake. Thanks for the reply.

**Comment by Shredder121** [comment]
You are more than welcome. :smile:

**Comment by iyaso** [comment]
Thank you @adamjames87 , This helped me a lot :+1:
