### ISSUE TITLE
LegacyHtml5TemplateParser has threading issue, which may convert 'form' element to whitespace text 

### ISSUE THREAD

**Issue by tan9** [thymeleaf/thymeleaf#362]
`LegacyHtml5TemplateParser` has a strange threading issue. `<form>` `Element` in some html will be translate to `Text` (e.g. `"    \n"`) on threads exceeding the parser pool limit.

I created a test case here:
https://github.com/tan9/thymeleaf-legacyhtml5-parser-threading-issue-testcase

**Comment by tan9** [comment]
The `poolSize` was set to `3` in the test case, then we fire 20 concurrent executions using TestNg.
Only the first 3 parsed documents will be correct, the form element in remaining 17 documents will be translated to whitespace text.

**Comment by tan9** [comment]
When the problem occurs, only`<form>` element tag got disappeared, all its children remains in the right place.

**Comment by danielfernandez** [comment]
This seems to be a _nekoHTML_ issue, apparently some kind of bad cleanup of the tag balancing mechanism. I've reported it to the nekoHTML team here: https://sourceforge.net/p/nekohtml/bugs/162/
