### ISSUE TITLE
#uris method to get context prefix

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#363]
I'm trying to render Open Graph meta tags, which want an absolute URL. The `@{...}` rewriting feature produces URLs relative to the server root. I saw a discussion about the possibility of having the host part of the request available in `#uris` back when the expression helper was first discussed; would this be feasible to add?

**Comment by danielfernandez** [comment]
The problem with computing absolute URLs is that the web server isn't always really aware of what these URLs should look like. Many times web servers are behind proxies, and all the information the Servlet API can offer about how the application was called from the browser is actually only the last step in a chain of proxied calls. Sometimes proxies add a specific HTTP header which allows the reconstruction of the original browser-called URL, but sometimes they don't…

So unfortunately there is no reliable way to offer such a mechanism from Thymeleaf in a general way. However, Thymeleaf does offer the `#httpServletRequest` expression object (renamed in 3.0 to `#request`, though the old name is still available). That should allow users compute absolute URLs based on info from the `HttpServletRequest` in any way that might seem adequate once the specifics on the deployment of the application are known.
