### ISSUE TITLE
Send date parameter from html form to controller in thymeleaf

### ISSUE THREAD

**Issue by naveenkoch** [thymeleaf/thymeleaf#364]
Please follow this URL  http://stackoverflow.com/questions/29842584/send-date-parameter-from-html-form-to-controller-in-thymeleaf

**Comment by danielfernandez** [comment]
This looks like a Spring form-binding issue. If you want to perform Spring form binding (and therefore have the date formats apply between view and controller) you should be using `th:field`, not simply `th:value`, and also specifying your form bean in an enclosing tag with `th:object`. See the _Thymeleaf + Spring_ tutorial for more details.
