### ISSUE TITLE
Preprocessed expressions with exceptions silently return the literal expression

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#366]
I had the following expression in a Thymeleaf data tag:

`|__${work.title}__ by ${mainArtist.displayName}|`

This was incorrect because the property `title` did not exist, and when the expression `${work.title}` was evaluated in a standalone context, SpEL threw an exception:

```
org.springframework.expression.spel.SpelEvaluationException: EL1008E:(pos 5): Property or field 'title' cannot be found on object of type 'Work' - maybe not public?
```

However, when the expression was part of a preprocessed block (`__${work.title}__`), the exception thrown by the preprocessing was swallowed, and the literal expression was returned as the value.

**Comment by danielfernandez** [comment]
This has been verified to not happen anymore in the 2.1 (`2.1.5-SNAPSHOT`) and 3.0 (`3.0.0-SNAPSHOT`) branches.
