### ISSUE TITLE
Getting attributes of current element

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#372]
I'd like to be able to pass in an expression something like this:

```
data-th-with="selected='profile'"
```

and then in a downstream expression say something like

```
data-th-classappend="${selected == #element.id}? 'active'"
```

Is there any way to refer to "attributes of the current element"?

**Comment by danielfernandez** [comment]
This is equivalent to #72, which was postponed and put into the wishlist. Please see https://github.com/thymeleaf/thymeleaf/issues/72#issuecomment-144871041

I'm closing this as _declined_ in order to focus on #72 and not having repeated tickets for the same feature.

**Comment by chrylis** [comment]
:+1:
