### ISSUE TITLE
mechanism for registering global variables into a root eval context

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#375]
I have a large number of pages that all need to dynamically fill in a few values such as analytics keys. Right now, I'm manually grabbing these out of a Spring `@ConfigurationProperties` bean, but this is cumbersome (especially with the bean naming). It would be helpful to have a hook where I could acquire the template engine and register variables to be injected into the top-level evaluation context for all templates that it processes.

**Comment by cybrown** [comment]
This would be awesome

**Comment by danielfernandez** [comment]
Actually, the `ThymeleafViewResolver#setStaticVariables(Map)` method should allow you to do precisely this…
