### ISSUE TITLE
Modify StandardMessageResolutionUtils in order to build cache keys based on resourceName + templateName

### ISSUE THREAD

**Issue by yacota** [thymeleaf/thymeleaf#383]
Based on the same idea proposed in issue https://github.com/thymeleaf/thymeleaf/issues/380 I think that it would be great if Thymeleaf uses resourceName aside from templateName in order to build cache keys used in StandardMessageResolutionUtils

The information is already in the arguments that receives 

```
public static String resolveMessageForTemplate(
        final Arguments arguments, final String key, final Object[] messageParameters, 
        final Properties defaultMessages)
```

Just get it from 

```
arguments.getTemplateResolution().getResourceName()
```

**Comment by danielfernandez** [comment]
Together #423 and #421 should solve this, as the TemplateResolver now can be configured by means of the _template resolution attributes_, and then produce an `ITemplateResource` implementation that, when afterwards queried by the `StandardMessageResolver` for its `relative(...)` resources (the `.properties` files) will point to the right files in your multi-tenant scenarios…

**Comment by yacota** [comment]
Thanks
