### ISSUE TITLE
Documentation : Wrong signature on #strings.equals(str)

### ISSUE THREAD

**Issue by davinkevin** [thymeleaf/thymeleaf#385]
Hi, 

In the documentation at the following url (http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#strings) the following example seems to be wrong : 

```
/*
 * Null-safe comparison and concatenation
 */
${#strings.equals(str)}
${#strings.equalsIgnoreCase(str)}
${#strings.concat(str)}
${#strings.concatReplaceNulls(str)}
```

You only use one parameter to do a comparison, I think it should be : 

```
${#strings.equals(str, foo)}
${#strings.equalsIgnoreCase(str, foo)}
${#strings.concat(str, foo)}
${#strings.concatReplaceNulls(str, foo)}
```

Thanks

**Comment by ultraq** [comment]
Thanks for letting us know.  I'll update the docs project so that these get fixed the next time they're generated.
