### ISSUE TITLE
mechanism for adding global evaluator objects

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#387]
I have some utility methods (mostly formatters) that I want to be available to all of my templates globally. I know that I can manually add them to the evaluation contexts on a per-render basis, but I'd like a way to register an object with the `TemplateEngine` or a similar place to be added to the base processing context for all rendering.

**Comment by danielfernandez** [comment]
In 2.1, dialects implementing the `IExpressionEnhancingDialect` interface can add expression objects to be used in any expressions inside templates. See https://github.com/thymeleaf/thymeleaf/blob/2.1-master/src/main/java/org/thymeleaf/dialect/IExpressionEnhancingDialect.java

Thymeleaf 3.0 has a similar interface called `IExpressionObjectDialect` for the same purpose. See #401

**Comment by chrylis** [comment]
Exactly what I was looking for. It'd be helpful to have a link to this somewhere in the docs.
