### ISSUE TITLE
[MAJOR FEAT] New event-based template processing engine

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#389]
Thymeleaf 3.0 builds around a **completely new template processing engine**, codenamed _aurora_, developed with the aim of improving its execution performance and reducing its memory footprint, especially in scenarios that were heavily penalized until 2.1 like the generation of big amounts of output markup as a consequence of the execution of iterations on very large collections.

In order to achieve these goals, Thymeleaf 3.0 abandons most of its DOM-oriented processing mechanisms and turns into an **event-based template processor** that responds to template parser/cache events by processing the template markup or text and immediately producing its output, even before new events coming from input for the same template are processed. This results in streamlined processing, much more efficient than the Thymeleaf 2.1 processing architecture which required each of the phases --1. _parsing_, 2. _processing_, 3. _output_-- to be completely finished before the next phase could even start.

![aurora-01](https://cloud.githubusercontent.com/assets/1492299/9833746/c5f8a45e-59a3-11e5-8f8f-8b1bd8ea9a78.png)

The central component of this new processing engine will be the [`org.thymeleaf.engine.ITemplateHandler`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/engine/ITemplateHandler.java) interface, which will be implemented by every step in the processing chain and will define the _model of available events_ on which the template processors will be applied.
### The event model

The new event model in Thymeleaf 3.0 is defined by a series of interfaces at the [`org.thymeleaf.model`](https://github.com/thymeleaf/thymeleaf/tree/3.0-master/src/main/java/org/thymeleaf/model) package.

There are 11 interfaces modeling the basic template events, all extendig (at different depth levels) the [`ITemplateEvent`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/ITemplateEvent.java) interface:
- General events:
  - [`ITemplateStart`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/ITemplateStart.java) and [`ITemplateEnd`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/ITemplateEnd.java) are fired at the start and end of a template processing operation.
  - [`IStandaloneElementTag`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IStandaloneElementTag.java), [`IOpenElementTag`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IOpenElementTag.java) and [`ICloseElementTag`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/ICloseElementTag.java) are fired when a standalone, open or close tag are found during parsing.
  - [`IText`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IText.java) for all template texts not included as a part of any other event.
- Markup-only events:
  - [`IComment`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IComment.java) and [`ICDATASection`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/ICDATASection.java) are fired when a comment (`<!-- -->`) or a CDATA Section (`<![CDATA[ ]]>`) are found.
  - [`IDocType`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IDocType.java), [`IXMLDeclaration`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IXMLDeclaration.java) and [`IProcessingInstruction`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IProcessingInstruction.java) fired for `<!DOCTYPE ...>`, `<?xml ...?>` and `<?...?>`.

Also, there are 3 interfaces that allow working on **groups of events, a.k.a. models**:
- [`IModel`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IModel.java) which defines a _sequence_ of events, either generated during parsing/processing or programmatically by any dialect's processors. `IModel`s are the closest way of representing what Thymeleaf 2.1 would have treated as a template's DOM trees or subtrees, only `IModel`s are not trees are such, but sequences of events.
- [`IModelFactory`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IModelFactory.java) which defines factory objects that allow the creation of new events or entire models during the execution of processors.
- [`IModelVisitor`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/model/IModelVisitor.java) which allows the definition of _visitors_ that traverse entire _models_ in order to perform any operations needed by processors, following to the _visitor_ pattern.

Taking into consideration the existence of these `IModel`s, we can now have a more accurate look at the architecture diagram:

![aurora-02](https://cloud.githubusercontent.com/assets/1492299/9834431/6d3b92b2-59b8-11e5-8a1b-815075aa09c6.png)

From the diagram above we can see how Thymeleaf 3.0 allows the creation of _processors_ (grouped in _dialects_ as usual), executed in the _template processing phase_, that act both on specific _events_ (single `ITemplateEvent` instances) or on complete _gathered models_ (`IModel` instances containing sequences of `ITemplateEvent` events which output has being delayed in order to allow for processing first).

**Comment by danielfernandez** [comment]
Already in 3.0.0-SNAPSHOT

**Comment by willdavidwarren** [comment]
This is amazing @danielfernandez - really looking forward to 3.0!

**Comment by fahimmm** [comment]
Are there any performance stats or comparisons between thymeleaf 2.x and 3.0?

**Comment by danielfernandez** [comment]
@fahimmm see https://raw.githubusercontent.com/thymeleaf/thymeleaf-benchmarks/master/thymeleaf-benchmark01/thymeleaf-benchmark01.png
