### ISSUE TITLE
[MAJOR FEAT] Full HTML5 support, new parsing infrastructure

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#390]
**Thymeleaf 3.0 adopts a new parsing system** that enables it to accept HTML5 input without restrictions.

Thymeleaf 2.1 uses underneath a standard Java SAX parser –usually xerces or crimson, depending on the JVM and application server–, which it heavily configures and tweaks with tricks such as feeding it with a customized `java.io.Reader` implementation that changes the markup on-the-fly just before it is parsed. However, tweaking can only get you so far and **Thymeleaf 2.1 needs its users to write XML-well-formed HTML5 code** so that templates can be parsed. The only way to avoid this and allow non-XML-ized HTML code in 2.1 is to set the `LEGACYHTML5` template mode, which brings in the nekoHTML library in order to perform tag balancing operations before Thymeleaf's parsers actually kick in.

Even if we at the Thymeleaf Team love well-structured, XML-well-formed HTML5 code, we understand not everyone out there shares this love and would prefer Thymeleaf to accept HTML code including many perfectly-valid HTML5 syntaxes that are rejected by 2.1's XML parsers. So **the parsing system has been completely revamped for Thymeleaf 3.0**.

Thymeleaf 3.0 uses a new parser called **[AttoParser 2.0](http://www.attoparser.org)**. A new, event-based (not SAX-compliant) parser, AttoParser was developed by Thymeleaf's author and with Thymeleaf in mind — even if it can be used in many other scenarios.

![attoparser](https://cloud.githubusercontent.com/assets/1492299/9837854/97a37030-5a4c-11e5-96f2-c1550a8c460a.png)

AttoParser offers Thymeleaf 3.0 two important features:
- **Full support of both XML and HTML5 (_non XML-ized_) markup**, so that no external tag balancing operations are needed anymore.
- **Loss-free parsing**, so that markup at the processed output resembles the original template with the highest degree of accuracy.

So this is a completely valid template in Thymeleaf 3.0:

``` html
<div><img alt=logo th:src='@{/images/logo.png}'>
```
### _Validation-enabled_ parsing

On the other side, Thymeleaf 2.1 offers two `VALID*` template modes called `VALIDXHTML` and `VALIDXML` that **no longer exist in Thymeleaf 3.0**. The new parsing infrastructure offers no HTML or XML validation, i.e. no way of _validating that template markup adheres to a specified DTD or XML Schema definition during parsing_.
### No need for `<![CDATA[ ... ]]>` in `<script>` or `style`

Thymeleaf 2.1 required the contents of `<script>` tags to be wrapped in a CDATA Section, so that any `<` or `>` symbols used didn't interfere with XML-based parsing:

``` html
<script>
/*<![CDATA[*/
  var user = ...
  if (user.signupYear < 1990) {
    alert('You\'ve been here for a long time!');
  }
/*]]>*/
</script>
```

But thanks to the new parser in Thymeleaf 3.0, this is no longer needed and this kind of code can now look cleaner:

``` html
<script>
  var user = ...
  if (user.signupYear < 1990) {
    alert('You\'ve been here for a long time!');
  }
</script>
```

**Comment by danielfernandez** [comment]
Already included in `3.0.0-SNAPSHOT`

**Comment by shiliting** [comment]
very cool

**Comment by martinezrw** [comment]
How do we handle JavaScript that has components that look like inlining? 

for example `$("table").tablesorter({sortList:[[0,0]],sortMultiSortKey: 'ctrlKey'});`

This is resulting in 

> SEVERE: Servlet.service() for servlet [xx] in context with path [/xxxxxx] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "ServletContext resource [/WEB-INF/templates/enterprisesource/list.html]")] with root cause
> org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as expression: "0,0" (template: "enterprisesource/list" - line 83, col 41)

**Comment by danielfernandez** [comment]
@martinezrw adding some white space should do: `[ [0,0] ]`

**Comment by martinezrw** [comment]
It seems to be breaking the javascript, could we do something like`\[[ and \]]`to escape those tags?

**Comment by danielfernandez** [comment]
Whitespace inside an array definition like that shouldn't break javascript syntax... could you double-check that is the reason for it not working?

This works perfectly fine for me...

``` html
<!DOCTYPE html>
<html>
<head>
  <script>
    var f = function() {
        var value = {sortList: [ [0, 1] ],sortMultiSortKey: 'ctrlKey'}
        alert(value.sortList);
        alert(value.sortList[0]);
        alert(value.sortList[0][0]);
        alert(value.sortList[0][1]);
    };
    f();
  </script>
</head>
<body>
</body>
</html>
```

**Comment by martinezrw** [comment]
You are right, it was my fault it wasn't working. Thanks for the reply!
