### ISSUE TITLE
Set attributes dynamically

### ISSUE THREAD

**Issue by RALGIE** [thymeleaf/thymeleaf#392]
Hello, 

I want to parse attributes dynamically to the fragment and when the function doesn't have a "btnname" param. The attribute must not be added. 

I have the following code: 

``` html
<th:block th:replace=":: btn-dialog-active (btnname='button_with_name')" />

<div th:fragment="btn-dialog-active">
    <button th:with="attrname='name=\''+ ${btnname} + '\'', 
                myvariable=${(!#strings.isEmpty(btnname)) ? attrname : ''}" 
                th:attr="${myvariable}">Test btn 
    </button>
</div>
```

When I add this i get an exception: 

``` html
TemplateProcessingException: Could not parse as assignation sequence: 
"attrname='name=''+ ${btnname} + ''', myvariable=${(!#strings.isEmpty(btnname)) ? attrname : ''}" 
```

When I change "th:attr" to "th:text" the button text is: 

``` html
name='button_with_name' 
```

Why is it that this doesn't work? 

Best regards, 
Ralph Gielkens.

**Comment by danielfernandez** [comment]
The `th:attr` attribute expects an assignation sequence as value (`a=x,b=y`), not a simple expression like `${myvariable}`. Even if the contents of your `${myvariable}` have the shape of an assignation sequence, it would need two evaluations for that to work (first to convert your variable into the assignation sequence it has as value, second to execute the assignation sequence as such), so you'd need to use _expression preprocessing_, like:

```
th:attr="__${myvariable}__"
```

**Comment by tamb** [comment]
I'm attempting to use your answer in a ternary:
```
th:attr="__${attrs != null? attrs : null}__"
```

It doesn't work since you still need assignation at the end.  My workaround is:
```
th:attr="__${attrs != null? attrs : data-ignore=true}__"
```

It would be great if `th:attr` could accept `null` as well.  

To note.  If you are creating a fragment that can optionally take attributes, instantiating it might look like this:
```html
With attrs
<th:block th:replace="~{components/MyButton/MyButton :: MyButton(attrs='disabled=${1<2}')}"/>

WITHOUT attrs
<th:block th:replace="~{components/MyButton/MyButton :: MyButton}"/>

```

**Comment by tamb** [comment]
You can use the fragment syntax to create some nifty dynamic chunks of HTML.  It's super helpful if you want to make fragments that can have various load states.
