### ISSUE TITLE
[MAJOR FEAT] New syntax for textual template modes

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#395]
Thymeleaf 3.0 includes three new _textual_ template modes: `TEXT`, `JAVASCRIPT` and `CSS`. As their names imply, `JAVASCRIPT` and `CSS` are meant to be used for processing JavaScript and CSS templates, and the first one (`TEXT`) can be used for processing a template in mostly any format, including mere plain text or even HTML files that we don't want to treat as such.

These new template modes do not use the same syntax as the _markup_ ones (`HTML` and `XML`). The reason is, in a _textual_ template mode markup HTML/XML tags are not relevant because HTML/XML is not _parsed_ as such, so code like this would be possible:

``` html
   <img src="<th:block th:text="@{/images/logo.png}"/>" alt="logo" />
```

...but it would be a nightmare for a parser to try to tell the difference between a tag it has to process (`<th:block>`) and another one, containing the former, which it doesn't have to process at all (`<img>`).
### The Thymeleaf textual syntax

So Thymeleaf 3.0 adopts a new syntax for textual template modes, in which elements (i.e. _processable tags_) are declared as `[#name ...]` instead of `<name ...>`). A quick example based on the code snippet above:

``` html
   <img src="[#th:block th:text="@{/images/logo.png}"/]" alt="logo" />
```

...which is completely equivalent to the more concise:

``` html
   <img src="[# th:text="@{/images/logo.png}"/]" alt="logo" />
```

So we have now a way of expressing _elements_, without using HTML tags. Note how the syntax is similar in concept to the markup one, as we still have both **open+close elements** (i.e. elements with a _body_) and **standalone elements**:

```
  [#th:block th:each="item : ${items}"]
    - [#th:block th:utext="${item}" /]
  [/th:block]
```

...or, again, the completely equivalent (which we will use from here on):

```
  [# th:each="item : ${items}"]
    - [# th:utext="${item}" /]
  [/]
```

Note that **the textual syntax requires full element balance (no unclosed tags) and quoted attributes**. So to say, it's more XML-style than HTML-style.
### Inlined Output expressions

Inlined output expressions (see #394) are also available in _textual_ template modes, in both their escaped (`[[...]]`) and unescaped (`[(...)]`) form. So we could have more concise versions of the examples above:

``` html
  <img src="[# th:text="@{/images/logo.png}"/]" alt="logo" />
  ...
  [# th:each="item : ${items}"]
    - [# th:utext="${item}" /]
  [/]
```

Which, using inlined output expressions, could look like:

``` html
  <img src="[[@{/images/logo.png}]]" alt="logo" />
  ...
  [# th:each="item : ${items}"]
    - [(${item})]
  [/]
```
### Escaped output

All these three new _textual_ template modes allow the use of both `th:text` and `th:utext` attributes, or the equivalent inlined `[[...]]` and `[(...)]`. But _what does escaping mean in these template modes?_. The behaviour is different depending on the specific mode:
#### Escaping in `TEXT`

Escaped output in `TEXT` will be **HTML-escaped**. This makes it consistent with the behaviour of inlined `[[...]]` expressions in `th:inline="text"` blocks in Thymeleaf 2.1. So this:

``` html
<a href="[[@{/product(id=${p.id},type=${p.type})}]]">Product details</a>
```

...will do its job and adequately HTML-escape the attribute (note the `&amp;`):

``` html
<a href="/product?id=45&amp;type=normal">Product details</a>
```

Note however that this HTML-escaping will be applied in `TEXT` mode even when the template being processed does not represent an HTML document, so for most _real text_ uses of this mode (e.g. text emails), unescaped expressions (`th:utext` or `[(...)]`) are usually a better option.
#### Escaping in `JAVASCRIPT`

Escaped output in `JAVASCRIPT` mode will convert its output into escaped _JavaScript literals_, surrounded by single quotes. So if we have a `msg` variable with value `This is a 'textual' template mode`, and we use it in a `JAVASCRIPT` template like:

``` javascript
   var a = [# th:text="${msg}"/];
```

...or the _inlined_ equivalent:

``` javascript
   var a = [[${msg}]];
```

We will obtain:

``` javascript
   var a = 'This is a \'textual\' template mode';
```

Note how the surrounding quotes have been generated by Thymeleaf, and the text inside has been JavaScript-escaped. Also note how this is completely consistent with the way inlined output expressions worked inside `th:inline="javascript"` blocks in Thymeleaf 2.1.
#### Escaping in `CSS`

Escaped output in `CSS` mode will convert its output into escaped _CSS identifiers_. So if we have an `elemClass` variable with value `content+main`, and we want to use it in a `CSS` template in order to apply some styles to the elements with such `class`:

``` css
   .[# th:text="${elemClass}"/] {
      background-color: blue;
   }
```

...or the _inlined_ equivalent:

``` css
   .[[${elemClass}]] {
      background-color: blue;
   }
```

We will obtain:

``` css
   .content\+main {
      background-color: blue;
   }
```

We can observe how the `+` symbol has been adequately escaped in accordance with CSS escaping rules.
### Escaped element attributes

In order to avoid interactions with parts of the template that might be processed in other modes (e.g. `text`-mode inlining inside an `HTML` template), Thymeleaf 3.0 allows the attributes in elements in its _textual syntax_ to be escaped. So:
- Attributes in `TEXT` template mode will be _HTML-unescaped_.
- Attributes in `JAVASCRIPT` template mode will be _JavaScript-unescaped_.
- Attributes in `CSS` template mode will be _CSS-unescaped_.

So this would be perfectly OK in a `TEXT`-mode template (note the `&gt;`):

```
  [# th:if="${120&lt;user.age}"]
     Congratulations!
  [/]
```

Of course that `&lt;` would make no sense in a _real text_ template, but it is a good idea if we are processing an HTML template with a `th:inline="text"` block containing the code above and we want to make sure our browser doesn't take that `<user.age` for the name of an open tag when statically opening the file as a prototype.
### Extensibility

One of the advantages of this syntax is that it is just as extensible as the _markup_ one. The user can still define his/her own dialects with custom elements and attributes, apply a prefix to them (optionally), and then use them in textual template modes:

```
  [#myorg:dosomething myorg:importantattr="211"]some text[/myorg:dosomething]
```

Note that, as with the _markup_ template modes, the Standard Dialects include just one processable element (`[#th:block ...]`, which can also be used with an empty name `[# ...]`) and a set of processable attributes (`th:text`, `th:utext`, `th:if`, `th:unless`, `th:each`, etc.).
### Parser-level and prototype-only comment blocks

Thymeleaf 2.1 already included parser-level and prototype-only comment blocks. Parser-level comments delimited template fragments that wouldn't even be parsed, effectively allowing for template comments that would never be processed or appear in output (similar to JSP `<%-- comments --%>`):

``` html
  ...
  <!--/* This is a parser-level comment, that will never show up */-->
  <p>This is some text</p>
  ...
```

Prototype-only comments, on the other side, were fragments of template that would be considered _comments_ only when displayed statically by a browser (i.e. without Thymeleaf processing), but would be considered normal input by Thymeleaf for parsing and processing:

``` html
  ...
  <table>
    <!--/*/ <th:block th:each="p : ${products}"> /*/-->
      <tr>
        <td th:text="${p.name}">The name</td>
        <td th:text="${p.price}">The price</td>
      </tr>
      <tr>
        <td colspan="2" th:text="${p.description}">The long description</td>
      </tr>
    <!--/*/ </th:block> /*/-->
  </table>
  ...
```

But these syntaxes are markup-oriented (they are based on `<!-- ... -->` syntax), so they aren't completely adequate for non-markup templates.

Thymeleaf 2.1's JavaScript inlining (`th:inline="javascript"`) defined specialized syntaxes for both kinds of comments, when appearing inside JavaScript-inlined blocks:
- `/*[- ... -]*/` for _parser-level_ comments.
- `/*[+ ... +]*/` for _prototype-only_ comments.

Thymeleaf 3.0 not only supports these syntaxes, but in fact extends them to all _textual_ template modes in order to achieve better consistence with their corresponding _inlining modes_:

```
  ...
  /*[- This is a parser-level comment, that will never show up -]*/
  This is some text, or some javascript, or some CSS perhaps.
  ...
```

Note however that _prototype-only comments_ are supported only for `JAVASCRIPT` and `CSS` (this kind of coments would make no sense in `TEXT` mode):

```
  ...

  /*[+  alert('Hello, ' + [[${session.user.name}]] + ', this is actually working');  +]*/

  var f = function() {
  ...
```
### Text templates for plain-text email

A typical example of using the `TEXT` template mode could be a template for sending plain-text email:

```
Dear [(${customer.name})],

This is the list of our products:
[# th:each="p : ${products}"]
   - [(${p.name})]. Price: [(${#numbers.formatdecimal(p.price,1,2)})] EUR/kg
[/]
Thanks,
  The Thymeleaf Shop
```

Which, once executed would give us something like

```
Dear John Apple,

This is the list of our products:

   - Oranges. Price: 0,90 EUR/kg
   - Apples. Price: 0,75 EUR/kg
   - Bananas. Price: 1,04 EUR/kg

Thanks,
  The Thymeleaf Shop
```
### Natural scripting (JavaScript) and styling (CSS)

In Thymeleaf 2.1's _javascript inlining_ syntax, using _output expressions_ inside comments allowed for a certain degree of _natural scripting_, this is, scripts that worked OK both when open statically in a browser and when executed through the Thymeleaf template engine. For example, this:

``` html
<script th:inline="javascript">
    ...
    var username = /*[[${session.user.name}]]*/ 'Sebastian';
    ...
</script>
```

...which is valid JavaScript, and once executed could look like:

``` html
<script>
    ...
    var username = 'John Apricot';
    ...
</script>
```

Thymeleaf 3.0 adopts and extends this syntax, so that whenever an _output expression_ is found wrapped inside a comment in `JAVASCRIPT` or `CSS` template mode, it will remove the rest of the line until it finds any of `;,)}]`, a line feed or a `//...` single-line comment block.

Moreover, this operation is now performed at parsing time so that it won't have any impact at all on the engine's performance --when using the template cache--. The parser will effectively replace the snippet above with:

``` html
<script th:inline="javascript">
    ...
    var username = [# th:text="${session.user.name}"/];
    ...
</script>
```

Note this works not only with escaped output expressions (`/*[[...]]*/`), but also with their unescaped equivalents (`/*[(...)]*/`).
#### Applying comments to any element

Going further, in order to allow for a greater level of _natural scripting/styling_, Thymeleaf 3.0 not only allows wrapping _output expressions_ inside comments in `JAVASCRIPT` and `CSS`, but actually any element can be wrapped too:

```
  /*[# th:if="${user.admin}"]*/
     alert('Welcome admin');
  /*[/]*/
```

That alert in the code above will be therefore be shown when the template is open statically --because it is perfectly valid JavaScript--, and also when the template is run if the user is an admin. It is completely equivalent to:

```
  [# th:if="${user.admin}"]
     alert('Welcome admin');
  [/]
```

...which is actually the code to which the initial version is converted during template parsing. 

Note however that wrapping elements in comments does not clean the lines they live in as inlined output expressions do. That behaviour is reserved for inlined output expressions only.

So Thymeleaf 3.0 allows the development of complex JavaScript scripts and CSS style sheets in the form of _natural templates_, valid both as a _prototype_ and as a _working template_.
### Summary
- Three _textual_ template modes: `TEXT`, `JAVASCRIPT` and `CSS`.
- New syntax for elements in textual template modes: `[# ...] ... [/]`.
- Inlined output expressions allowed, both escaped (`[[...]]`) and unescaped (`[(...)]`).
- Intelligent escaping of JavaScript (as _literals_) and CSS (as _identifiers_).
- Parser-level (`/*[- ... -]*/`) and prototype-only (`/*[+ ... +]*/`) comment blocks.
- Natural templates applied to `JAVASCRIPT` scripts and `CSS` style sheets by means of wrapping elements and/or output expressions inside comments (`/*[# ...]*/`).

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`

**Comment by QiaoG** [comment]
<img src="[[@{/images/logo.png}]]" alt="logo" /> can not parse to <img src="/???/images/log.png" ...
why?

**Comment by QiaoG** [comment]
src="[[@{/images/logo.png}]]" can not parse to  src="/???/images/log.png" ... why?

**Comment by danielfernandez** [comment]
@QiaoG are you using the `TEXT` template mode for that tempalte?

**Comment by T3rm1** [comment]
How can you add a new line to th:utext in `TEXT` template mode?

**Comment by somaiah** [comment]
The text markup seems to have been broken in v 3.0.6.RELEASE. It works in 3.0.5.RELEASE.
I tried the code from here: https://blog.codeleak.pl/2017/03/getting-started-with-thymeleaf-3-text.html

And the result I get is: 
`Name: Spring
Link: http://spring.io
Tags:
[# th:each="tag : ${tags}" ]
[/]
`

In v3.0.5.RELEASE the markup is correctly processed as:
`Name: Spring Link: http://spring.io Tags: #framework #java #spring
`
