### ISSUE TITLE
th:switch doesn't work in head

### ISSUE THREAD

**Issue by adeptues** [thymeleaf/thymeleaf#397]
``` html
<th:block th:switch="${theme}">
          <link th:case="'mytheme'" rel="stylesheet" href="assets/mytheme.css"/>
          <link th:case="'default'" rel="stylesheet" href="assets/app.css"/>
          <link th:case="*" rel="stylesheet" href="assets/app.css"/>
      </th:block>

```

when parsing a template with the above code fragment in the `<head>` tag i get an exception with

```
org.thymeleaf.exceptions.TemplateProcessingException: Cannot specify a "th:case" attribute in an environment where no switch operator has been defined before. (index)
```

when clearly the th:switch has been defined before, this code is very similar to the example listed on the docs pages. So what am i doing wrong or is this a bug?

**Comment by danielfernandez** [comment]
Maybe you are using the `LEGACYHTML5` template mode? in such case, the tag balancer that executes before thymeleaf parses your code will close your `<th:block>` before the `<link>` tags, like:

``` html
<th:block th:switch="${theme}"></th:block>
          <link th:case="'mytheme'" rel="stylesheet" href="assets/mytheme.css"/>
          <link th:case="'default'" rel="stylesheet" href="assets/app.css"/>
          <link th:case="*" rel="stylesheet" href="assets/app.css"/>
      </th:block>
```

Unfortunately, this might not be compatible with `LEGACYHTML5`. Try using `HTML5` instead.

FYI, Thymeleaf 3.0 removes the `LEGACYHTML5` mode, offering a new `HTML` mode instead, which does not perform any explicit tag balancing (it does perform it implicitly), and would not close your `<th:block>` there, making it work OK. See #391

**Comment by danielfernandez** [comment]
Linked to #246
