### ISSUE TITLE
Relative/absolute links depend on Servlet API which is not available

### ISSUE THREAD

**Issue by ieugen** [thymeleaf/thymeleaf#398]
Hi,

I'm developing an application with Vertx and thymeleaf. I'm having issues with rendering pages that create links. It seems there is no easy way to integrate thymeleaf templates in other web frameworks that _do not_ implement Servlet API .

From waht I can tell, you need Servlet API to build links. If this is the only use case then maybe a solution where you put that information in the  non web Context can be found.

One solution could be to make the required information be in the normal context as pre-defined properties For Servlet containers you can let WebContext create those properties, for other contexts you can leave it to the owner of that context. 

This way you no longer depend on Servlet API, but you can still build proper URL's

Related issues and detailed explanation:
https://github.com/vert-x3/vertx-web/issues/161
https://github.com/ratpack/ratpack/issues/517

**Comment by danielfernandez** [comment]
This has been implemented by means of a new extension point called `ILinkBuilder`. See #458
