### ISSUE TITLE
feature: support Java 8 time classes

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#403]
I need to be able to render Java 8 times in the timezone associated with a record, but the Thymeleaf `DateUtils` is written for the pre-Java 8 date/time APIs. I suggest conditionally adding a `#datetimes` (or equivalent) template utility if the Java 8 classes are present.

**Comment by danielfernandez** [comment]
I think the **java-extras-java8time** should cover your needs: https://github.com/thymeleaf/thymeleaf-extras-java8time

Or is there something you miss there?

**Comment by chrylis** [comment]
I managed to miss that one, and it doesn't have a link on the Ecosystem page. Thanks!
