### ISSUE TITLE
TemplateResolverComparator's handling of 'null' order value

### ISSUE THREAD

**Issue by lukosan** [thymeleaf/thymeleaf#406]
In Thymeleaf 2.1.4:

```
    public int compare(final ITemplateResolver o1, final ITemplateResolver o2) {
            if (o1.getOrder() == null) {
                return -1;
            }
            if (o2.getOrder() == null) {
                return 1;
            }
            return o1.getOrder().compareTo(o2.getOrder());
        }
```

I don't think this should return -1 (and 1) when the values are null. I'd suggest that if the order property of an ITemplateResolver isn't set then it should be assumed to be maximum (i.e. Integer.MAX_VALUE).

For example, I have two ITemplateResolvers - one of them is scaffolded by Spring Boot and doesn't set the order value. The other one I'm instantiating myself and even though I set the order value to by 1 (as the javadoc suggests) it doesn't actually get used first because the above method will find a null value on Spring's ITemplateResolver and return -1, thereby sorting the collection such that Spring's ITemplateResolver is before mine.

**Comment by yacota** [comment]
I also discussed this issue with Spring Boot guys
https://github.com/spring-projects/spring-boot/issues/3575

**Comment by lukosan** [comment]
That's concensus enought for me. Is it worth me submitting a patch? i.e. is there a 2.1.5 release on the horizon or is all effort being thrown towards 3?

**Comment by ultraq** [comment]
Well, all the effort is towards 3, but I don't imagine we'd be dropping support for 2.1 any time soon.  A PR for 2.1 would be really nice, maybe even one for 3.  (Or one against 2.1, then one for 3 if it gets accepted.)

**Comment by lukosan** [comment]
Okay will do - do you want the PR against 2.1-master or 2.1-dev? I'll assume dev unless otherwise notified.

**Comment by ultraq** [comment]
`2.1-dev` will do, although I just noticed both branches are pointing to the same commit :)

**Comment by danielfernandez** [comment]
Thanks @lukosan. Your proposed changes look OK to me too.

I've added #407 in order to apply this modification to both the 2.1 and 3.0 development branches. Emanuel, I've assigned both to you ;)

@lukosan please read https://github.com/thymeleaf/thymeleaf/blob/3.0-master/CONTRIBUTING.markdown before making your contribution. We will need a comment on your PR ticket (or on this one) explicitly stating that you agree with the terms detailed there in order to accept your contribution. Thanks again.

**Comment by lukosan** [comment]
Just noticed MessageResolverComparator has a similar issue - you might want to open a ticket for that too (or you might not).

**Comment by danielfernandez** [comment]
Yes, `MessageResolverComparator` should be modified its behaviour too. Thanks.

**Comment by danielfernandez** [comment]
Updated `2.1.5-SNAPSHOT`
