### ISSUE TITLE
readd isInitialized() to easily allow creation and configuration of template engine in multiple steps

### ISSUE THREAD

**Issue by oliverlietz** [thymeleaf/thymeleaf#412]
This is useful in dynamic environments like OSGi.

```
    /**
     * <p>
     *   Checks whether the <tt>TemplateEngine</tt> has already been initialized
     *   or not. A <tt>TemplateEngine</tt> is initialized when the {@link #initialize()}
     *   method is called the first time a template is processed.
     * </p>
     * <p>
     *   Normally, there is no good reason why users would need to call this method.
     * </p>
     * 
     * @return <tt>true</tt> if the template engine has already been initialized,
     *         <tt>false</tt> if not.
     */
    public final boolean isInitialized() {
        return this.initialized;
    }
```

**Comment by danielfernandez** [comment]
I would need to understand this better: how would this be _needed_ in an OSGi environment, what for?

My concern is that, if this is added to `TemplateEngine` in 3.0, maybe it should also be added to the `ITemplateEngine` interface, and I wouldn't really like exposing an implementation detail as such through the most central interface of the library.

So, would you please explain why would an OSGi environment need to know whether initialization --which is performed the first time a template is processed-- has taken place or not? And... would it be needed at the interface or the implementation would be enough? My knowledge of OSGi is extremely limited…

**Comment by oliverlietz** [comment]
It needs not to be added to `ITemplateEngine` in my case ([Apache Sling Scripting Thymeleaf](https://github.com/apache/sling/tree/trunk/contrib/scripting/thymeleaf)). The `ThymeleafScriptEngineFactory` is responsible for the lifecycle of the `TemplateEngine` and the configuration:
- creates the `TemplateEngine`
- adds `ITemplateResolver`s
- adds `IMessageResolver`s
- adds `IDialect`s
- adds `ICacheManager` (TODO)

`ITemplateResolver`s, `IMessageResolver`s, `IDialect`s and `ICacheManager`s are implemented as [OSGi Services, they can appear and disappear anytime](http://www.osgi.org/Technology/WhatIsOSGi) (_dynamic_).

With not being able to check if the `TemplateEngine` is initialized it has to be created 5 times at least with Thymeleaf 3 (or let it throw exceptions). See the relevant code of [`ThymeleafScriptEngineFactory`](http://svn.apache.org/viewvc/sling/trunk/contrib/scripting/thymeleaf/src/main/java/org/apache/sling/scripting/thymeleaf/internal/ThymeleafScriptEngineFactory.java?r1=1664288&r2=1705867&diff_format=h) (starting at line 165).

To get a better overview you might look at [Sling Scripting Thymeleaf's documentation](https://sling.apache.org/documentation/bundles/scripting/scripting-thymeleaf.html) for `0.0.6` based on Thymeleaf `2.1.4.RELEASE`.

**Comment by danielfernandez** [comment]
Thanks for the explanation. Looking at your code, I understand you need a way to determine whether you need a new `TemplateEngine` instance or not, depending on whether the one you have has already been initialized or not (because it would not let you re-initialize it if it has already been initialized).

I will be adding the `isInitialized()` method in `TemplateEngine`.

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
