### ISSUE TITLE
Move Java compatibility up to Java 6

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#414]
The lack of `java.util.Properties#load(Reader)` method in Java 5 is causing some potential optimization problems in message processing, and as of today it seems there is not really much to worry about dropping support for Java 5 ( https://plumbr.eu/blog/java/java-version-statistics-2015-edition ), so we should be just fine moving to Java 6 in Thymeleaf 3.0

**Comment by ultraq** [comment]
Drop Java 5! :grinning:

**Comment by danielfernandez** [comment]
`3.0.0-SNAPSHOT` already uses this `java.util.Properties#load(Reader)`, so Java 6 will be required for Thymeleaf 3.0 from now on.

**Comment by ultraq** [comment]
FYI: we'll need to update our `CONTRIBUTING.markdown` files to update this line

> - All your code should compile and run in **Java 5.0.**

**Comment by danielfernandez** [comment]
Yup. Can you create a ticket on `thymeleaf-dist` for that? And also the `download.html` page on the website should be modified...

**Comment by ultraq** [comment]
Done: https://github.com/thymeleaf/thymeleaf-dist/issues/4

And yep, that'll be on my TODO list for the website too :)
