### ISSUE TITLE
There are no javadocs in some classes. 

### ISSUE THREAD

**Issue by sopehl** [thymeleaf/thymeleaf#416]
for instance org.thymeleaf.expressions.Ids class haven't got java documentation. in this package(s), there is no documentation. version 1.2.6.release

Best Regard

**Comment by danielfernandez** [comment]
Improving JavaDoc is an ongoing effort for all versions, we are continuously trying to add more docs with useful explanations to every class. However, most of the functionality in all relevant classes (like `org.thymeleaf.expressions.Ids`) is explained at the tutoriales.
