### ISSUE TITLE
include/replace do not respect if

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#417]
I am trying to include a "banner" module if and only if the `banner` variable is set:

```
<div data-th-if="${banner}" data-th-include="|widgets/banners/${banner}|" id="banner" />
```

but not passing a `banner` in the context results in an NPE evaluating the `include` expression. I would expect the `if` to suppress the inclusion attempt, as it does for other directives. Nesting the `include` inside a `div` that has nothing but the `if` works as expected.

**Comment by danielfernandez** [comment]
It is a matter of _processor precedence_. In this case, `data-th-include` has a precedence of `100` whereas `data-th-if` has a precedence of `300`. So `include` does always execute before `if` when in the same tag…

**Comment by chrylis** [comment]
Unless there are other intermediates that would be significantly disrupted, I suggest reconsidering that relative precedence. Intuitively, I expect the conditionals to be evaluated before include/replace.

**Comment by maxxyme** [comment]
OK but how are we expected to do this?
I have the same problem, I want to do something like:

```
    <header th:unless="${user.id}" th:replace="fragments/layout::header(#{title.user.new})"></header>
    <header th:if="${user.id}" th:replace="fragments/layout::header(#{title.user.edit(${user.id})})"></header>
```

But both header tags are displayed.

**Comment by danielfernandez** [comment]
If you are using Thymeleaf 3, you can directly apply a conditional that returns a different fragment expression depending on the result of the conditional expression:

```html
<header th:replace="${user.id}? 
                       ~{fragments/layout::header(#{title.user.edit(${user.id})})} : 
                       ~{fragments/layout::header(#{title.user.new})}">
</header>
```

Anyway, given in this case your fragments are actually the same and all that changes is an argument to your fragment, you could use a conditional directly in your fragment's argument, which was already allowed in Thymeleaf 2.1:

```html
<header th:replace="fragments/layout::header((${user.id} ? #{title.user.edit(${user.id})} : #{title.user.new}))"></header>
```

**Comment by maxxyme** [comment]
OK thank you very much!!!
Now you've written it, that seems so simple I'm feeling a bit dumb not to have thought about that.
(but I'm quite new to Thymeleaf, that's why)

The solution was even included in the documentation: http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#advanced-conditional-insertion-of-fragments
