### ISSUE TITLE
Allow to create an dialect without a prefix

### ISSUE THREAD

**Issue by klebermo** [thymeleaf/thymeleaf#418]
I wonder if anyone feels thymeleaf should allow the developer to create an dialect without a prefix, which will make possible use a processor in the HTML page from the view without it, allowing, by instance, override HTML tags and integrate them with the Java / Spring code, making the code a lot more clear. For example, if I have a processor for tag **nav**, I could make this tag retrieve the options for the navigation bar directly from the project, without specify each item direct on page. Or use this for override the form tags, making something like the Spring Form Tags, but with less code to write and more integrated to the Model layer.

**Comment by danielfernandez** [comment]
Actually, the idea is that you can specify a dialect with `null` prefix, and that will make thymeleaf apply your dialect's processors on tags/attributes without namespace. This should work both in 2.1 and 3.0.

If not, please feel free to open a bug issue ticket, thanks. I'm closing this question as answered for now.
