### ISSUE TITLE
Powerful feature of Template Inheritance should be implemented in Thymeleaft

### ISSUE THREAD

**Issue by cp10000** [thymeleaf/thymeleaf#427]
I have found that the powerful feature of Template Inheritance found in the tool Jinja2 should also be considered for Thymeleaf.   It's a powerful feature!   It allows the encapsulation of complexity in parent templates and allow child templates to differ only in what's different.   A library of parent templates can be created and creating child templates is only a matter of stating the difference.

**Comment by ultraq** [comment]
Template inheritance may not be in Thymeleaf's core, but I developed a dialect ([layout dialect](https://github.com/ultraq/thymeleaf-layout-dialect)) that can do that.  Even reading through Jinja2's docs on that feature, it read an awful lot like the readme of the layout dialect.

Would that be something that could help you out?

Looking through the feature list of Jinja2, the only thing it doesn't have is the ability to call the "super block".

**Comment by danielfernandez** [comment]
For more info on the several possibilities Thymeleaf offers for page composition, please have a look here: http://www.thymeleaf.org/doc/articles/layouts.html

I'm closing this question as answered for now.
