### ISSUE TITLE
Thymeleaf 3.0.0 AttributeName could contain the completeName too instead of `getAllCompleteNames`

### ISSUE THREAD

**Issue by Antibrumm** [thymeleaf/thymeleaf#429]
While updating the thymeleaf-with-dialect to version 3.0.0 I had my troubles working with the "declared" attribute names. I'm not sure if that is because `TemplateMode.HTML` is meant to be case insensitive or not. 

Anyway. From my dialect point of view a `variable` has to be written into the `engineContext` with the name given on the attribute, in a case sensitive way. I had some trouble matching the `AttributeName` and `completeName` as it depends if the developer uses the `prefix-` or `data-mode`.

```
        /*
         * Compute the new attribute name (case sensitive)
         */
        final String newVariableName;
        if (completeName.contains(":")) {
            // prefix version: 'with:varName'
            newVariableName = completeName.substring(this.dialectPrefix.length() + 1);
        } else {
            // data version 'data-with-varName'
            newVariableName = completeName.substring(this.dialectPrefix.length() + 6);
        }
```

It would be nice if we could get the case sensitive declaration directly from the AttributeNames. Or do I do something extremely stupid? :)

**Comment by Antibrumm** [comment]
I found a bit a nicer way of matching originally declared attributes with the AttributeNames. If i understand correctly that length of an attribute is not changing, just the case (in HTML mode). So a simple substring is enough. 

Never the less, I think it would be nice to be able to get the original value directly from an AttributeName, whatever the templateMode might be. The two correlated lists of completeNames and AttributeNames seems a bit odd.

**Comment by ultraq** [comment]
I've also had to add whole host of "utility" methods into my code to handle the variances between the XML and data- attribute declarations (eg: https://github.com/ultraq/thymeleaf-layout-dialect/blob/master/Source/nz/net/ultraq/thymeleaf/LayoutDialect.groovy#L88-L113).  Was never sure if other dialect devs needed similar things or if it was just me.

**Comment by danielfernandez** [comment]
Hmm... yes, I think `ElementAttributes` should definitely have some kind of `getName()`. Actually, it's a strange ommission. I can try to add it.

It cannot be added to `AttributeName` because objects of that class are not created for each attribute in each tag. Instead, they are a sort of _global definition_. They are kept in a repository, one for each possible attribute, and retrieved as a sort of _immutable metadata_ when `ElementAttributes` objects are populated for a specific tag.

**Comment by danielfernandez** [comment]
New `getCompleteName(...)` methods have been added to the `IElementAttributes` interface, which will return the original (complete) name an attribute had in the template, in a case-sensitive way.

Already in `3.0.0-SNAPSHOT`
