### ISSUE TITLE
Compare string with enum.

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf#43]
Ability to compare string with enum. When you try to compare in if statement (th:if="${day == 'MONDAY'}")  exception is thrown - org.springframework.expression.spel.SpelEvaluationException: EL1007E:(pos 22): Field or property 'MONDAY' cannot be found on null. You must use cast enum to string (th:if="${day + '' == 'MONDAY'}")  in not nice way. So explicit or implicit casting to string would be nice to have.

**Comment by danielfernandez** [comment]
Hi,

This is not a Thymeleaf feature, but a Spring EL one. When using Spring, every expression inside `${...}` is evaluated by the Spring EL expression engine.

The way you can access enums in Spring EL is this:

```
th:if="${day == T(my.package.MyEnum).MONDAY"
```

**Comment by kreuzman** [comment]
Hi,

thanks for reply I missed this one (that it's Spring EL feature)...Anyway what do you think about adding ${#strings.asString(str)} function? It can be useful also in other cases I think.

**Comment by danielfernandez** [comment]
That could be useful if you need to have a null-safe toString function. If there is no problem with nulls, Spring EL allows you to do:

```
${myVar.toString()}
```

The null-safe "toString()" function is a nice idea. I've added it here https://github.com/thymeleaf/thymeleaf/issues/45 as an enhancement for 2.0.12

**Comment by sagarhire** [comment]
Hi,I am trying to use th:if for string comparison but it's not working.
 th:if="${adapterScource.adapterName} == 'Excel' " th:text="${adapterScource.adapterCount}" 
 th:unless="${adapterScource.adapterName} == 'Excel' " th:text="0"
any help will be appreciated.

**Comment by kreuzman** [comment]
Hi _sagarhire_ I'm not sure what's your use case but I think you have wrong position of `}`. See example below it works fine for me.

``` html
<div th:if="${adapterScource.adapterName == 'Excel'}" th:text="${adapterScource.adapterCount}"/>
<div th:unless="${adapterScource.adapterName == 'Excel'}">0</div>
```
