### ISSUE TITLE
3.0.0.BETA01 - Custom Dialects need to include `StandardXmlNsTagProcessor`

### ISSUE THREAD

**Issue by Antibrumm** [thymeleaf/thymeleaf#430]
Hi
I'm in the process of updating my two dialects for version 3.0.0.BETA01 and as a side effect I had to include this processor myself in both dialects. Is this desired behavior? 

```
processors.add(new StandardXmlNsTagProcessor(this, TemplateMode.HTML, dialectPrefix));
```

**Comment by danielfernandez** [comment]
Yes. As of 3.0 there is no mechanism in the engine itself to continuously look for `xmlns` attributes and remove them. It becomes the responsibility of the dialects to do so. So your solution is correct.

**Comment by ultraq** [comment]
Ah, this one tripped me up too.  Thanks for pointing it out.
