### ISSUE TITLE
Nested javascript arrays throw TemplateProcessingException

### ISSUE THREAD

**Issue by seanhinkley** [thymeleaf/thymeleaf#432]
Inlined output expressions are great but get tripped up with nested javascript arrays.

consider this:

``` javascript
<script>
  var fizz = [[fizz, buzz], [foo, bar]];
</script>
```

The expression parser is trying to parse <code>fizz,buzz], [foo,bar</code>

Exception thrown at https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/standard/expression/StandardExpressionParser.java#L142

could a tag attribute be added when the parser comes across the inlined expression?  It looks like [AbstractStandardExpressionAttributeTagProcessor.doProcess](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/standard/processor/AbstractStandardExpressionAttributeTagProcessor.java#L53) could catch the TemplateProcessingException and suppress the exception if that attribute is set.

**Comment by danielfernandez** [comment]
Yes, that code will be considered an inlined expression and you will obtain an exception. But there are several ways to avoid it.

First, if you are inlining javascript inside an HTML template, you could just disable inlining by using `th:inline="none"`:

``` html
<script th:inline="none">
  var fizz = [[fizz, buzz], [foo, bar]];
</script>
```

And in the case you were actually writing a template in `JAVASCRIPT` template mode, or you just didn't want to disable inlining for an entire `<script>` tag in an `HTML` template and rather do it more locally, you could use a textual-mode element, like:

``` javascript
...
[# th:inline="none"]
  var fizz = [[fizz, buzz], [foo, bar]];
[/]
...
```

And of course, there is the possibility to write that array in another (still perfectly JavaScript-valid) way by simply adding a whitespace char between the two brackets:

``` html
<script>
  var fizz = [ [fizz, buzz], [foo, bar] ];
</script>
```
