### ISSUE TITLE
Make JavaScript and CSS serialization in the Standard Dialects configurable

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#435]
Both `JAVASCRIPT` and `CSS` template modes, as well as `javascript` and `css` inlining blocks (`th:inline`) perform their escaped text output (`th:text` attribute or `[[...]]` inlined output expressions) in the form of serialized values: string literals, numbers, booleans and dates. In the case of JavaScript, complex objects might also be output in JavaScript object syntax which, due to the nature of the data being output, can be considered JSON notation in practice (only data is to be output, keys will always be strings, no functions as values…).

The value serialization mechanism for both JavaScript and CSS could benefit from a certain degree of customization, so that users of the _Standard Dialects_ can specify the way values should be serialized and possibly adapt them to their needs, or use specific external libraries that allow specific configurations required by the users.

These extension points should be implemented as interfaces used by the `StandardDialect` class, and default implementations should be provided both for JavaScript and CSS.

In the case of the default implementation for JavaScript, the Jackson JSON serialization library should be searched in classpath and, if found, it should be used (see #81). If not found, the already-existing mechanism should be used, though with minor adaptations in order to bring its output syntax and that of Jackson the closer together possible (e.g. by outputting text literals surrounded by double quotes `"` instead of single quotes as in 2.1 `'`).

**Comment by danielfernandez** [comment]
Two new interfaces have been created in the `org.thymeleaf.standard.serializer` package:
- `IStandardJavaScriptSerializer`
- `IStandardCSSSerializer`

And methods `setJavaScriptSerializer(IStandardJavaScriptSerializer)` and `setCSSSerializer(IStandardCSSSerializer)` have been added to the `StandardDialect` class so that users can now customize the way values are serialized in `JAVASCRIPT` and `CSS` modes.

If not specified otherwise, the default implementations `StandardJavaScriptSerializer` and `StandardCSSSerializer` from the same package will be used. The former will check the availability of the **Jackson JSON processor** library in the classpath and, if available, delegate to it value serialization.

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`

**Comment by kasdega** [comment]
How does one configure/use this?

**Comment by danielfernandez** [comment]
@kasdega see https://github.com/thymeleaf/thymeleaf/issues/435#issuecomment-160007528

**Comment by kasdega** [comment]
Yep I see that and thank you for responding....maybe I'm just dense.  Do I put that in a config file?  I don't understand where exactly I would customize the way javascript is serialized.  Is there an example of this in use somewhere?

Do I create my own class that implements the IStandardJavascriptSerializer?  But then how do I set Thymeleaf to use that exactly?

Sorry for being slow here, just don't quite follow what I'd need to do.

**Comment by kasdega** [comment]
Here's what I tried:
```
		<property name="additionalDialects">
		  <set>
		    <bean class="org.thymeleaf.standard.StandardDialect">
		    	<property name="javaScriptSerializer" value="com.kasdega.thymeleaf.ThymeleafJavascriptSerializer" />
		    </bean>
		    <bean class="org.thymeleaf.extras.springsecurity4.dialect.SpringSecurityDialect"/>
		  </set>
		</property>
```
And here's the error I get:
Cannot convert value of type [java.lang.String] to required type [org.thymeleaf.standard.serializer.IStandardJavaScriptSerializer] for property 'javaScriptSerializer'

**Comment by danielfernandez** [comment]
Methods `StandardDialect#setJavaScriptSerializer(IStandardJavaScriptSerializer)` and `StandardDialect#setCSSSerializer(IStandardCSSSerializer)` are extension points for the Standard Dialect. You need to create your own implementation of these interfaces, as I see you've done in your second example.

The reason you have that error is because, when you use Spring's XML configuration, you cannot use the `value` property for setting an object value like this (`value` sets `String`s). You need to create a `<bean>` and set it into the `<property>`, either directly or by means of a `ref` attribute. Please refer to Spring documentation to see how to do this.

**Comment by kasdega** [comment]
I'm sorry to be a pain.  Hopefully someone will get something out of reading this.  I've tried several more iterations and versions and ideas.  Here's the closest I've gotten...I've implemented my own StandardDialect.  It compiles fine and seems to get to the point where its actually calling MyThymeleafJavascriptSerializer but then I get a class not found exception...
```
public class MyThymeleafDialect extends StandardDialect {
	public MyThymeleafDialect() {
		this.setJavaScriptSerializer(new MyThymeleafJavascriptSerializer());
	}
}

public class MyThymeleafJavascriptSerializer implements IStandardJavaScriptSerializer {
	private final ObjectMapper mapper;

	public MyThymeleafJavascriptSerializer() {
		this.mapper = new ObjectMapper();
                this.mapper.setSerializationInclusion(Include.NON_NULL);
	}
}
```
and configured as such
```
<snip>
	@Bean
	public TemplateEngine templateEngine() {
		SpringTemplateEngine engine = new SpringTemplateEngine();
		engine.setEnableSpringELCompiler(true);

		engine.setTemplateResolvers(getTemplateResolvers());
		engine.setAdditionalDialects(getAdditionalDialects());
		return engine;
	}
	
	private Set<IDialect> getAdditionalDialects() {
		Set<IDialect> additionalDialects = new HashSet<IDialect>();

		additionalDialects.add(new MyThymeleafDialect());
		additionalDialects.add(new SpringSecurityDialect());

		return additionalDialects;
	}
<snip>
```
And now loading any template gives:

SEVERE: Servlet.service() for servlet [springDispatcher] in context with path [] threw exception [Handler processing failed; nested exception is java.lang.NoClassDefFoundError: ognl/PropertyAccessor] with root cause
java.lang.ClassNotFoundException: ognl.PropertyAccessor

What am I doing wrong here?

**Comment by kasdega** [comment]
Eureka!  Ok I got this to work.  I created my own JavaScriptSerializer as previously mentioned.  Then I had to switch over from xml config to use Java config (not sure how to do this in xml).  Then I did this in the config:
```
	@Bean
	public TemplateEngine templateEngine() {
		SpringTemplateEngine engine = new SpringTemplateEngine();
		engine.setEnableSpringELCompiler(true);

		Set<IDialect> dialects = engine.getDialects();
	    StandardDialect dialect = (StandardDialect) dialects.stream()
	            .filter(d -> d instanceof StandardDialect)
	            .findFirst()
	            .get();
	    dialect.setJavaScriptSerializer(new MyThymeleafJavascriptSerializer());
		
		engine.setTemplateResolvers(getTemplateResolvers());
		engine.setAdditionalDialects(getAdditionalDialects());
		return engine;
	}
```
And I eliminated the instantiation of my own dialect.

Cheers!

**Comment by neramirez** [comment]
So, is not enough to add the jackson-databind dependency?
