### ISSUE TITLE
Infinite loop in 3.0.0 Beta

### ISSUE THREAD

**Issue by garpinc** [thymeleaf/thymeleaf#437]
org.thymeleaf.engine.WebEngineContext.ServletContextAttributesMap.size()

Method looks like this:
@Override
        public int size() {
            int size = 0;
            final Enumeration<String> attributeNames = this.servletContext.getAttributeNames();
            while (attributeNames.hasMoreElements()) {
                size++;
            }
            return size;
##         }

in while loop there is nothing to advance the enumeration hence it just stays in this loop.
It should instead be: 
@Override
        public int size() {
                return java.util.Collections.list(this.servletContext.getAttributeNames()).size();
        }

Since this is critical please dump a new Beta and let me know. Thanks.

**Comment by danielfernandez** [comment]
Oops. Unfortunately, `this.servletContext.getAttributeNames()` is an `Enumeration`, and therefore has no `size()` method. So the counting algorithm is the right one, but a call to `nextElement()` is definitely missing.

Will be fixed in a snapshot, as soon as possible.

> Since this is critical please dump a new Beta and let me know. Thanks.

:)

**Comment by garpinc** [comment]
I didn't imply it has a size().. I proposed using Collections.list which results in a list which then has corresponding size.. However perhaps it's more memory intensive so I agree with you.

**Comment by danielfernandez** [comment]
`3.0.0-SNAPSHOT` has just been updated with this fix. For more info on how to use a snapshot, please see http://www.thymeleaf.org/faq.html#use-snapshot
