### ISSUE TITLE
PORT - Possible infinite loop with Numbers.sequence

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#438]
**PORT** of #377 for the Thymeleaf 3.0 branch
## 

If I use this code

``` java
Numbers.sequence(5, 2, -1)
```

it's make an infinite loop.

**Comment by PawelJagus** [comment]
Unfortunately this fix breaks already existing reverse sequences in views. For example numbers.sequence(9,1) ends now with IllegalArgumentException. Not cool.
