### ISSUE TITLE
[MAJOR FEAT] Fragment Expressions

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#451]
Building on the idea explained at #180, Thymeleaf 3.0 will introduce a new type of _simple expressions_ for the Thymeleaf Standard Expression engine. These expressions are called **Fragment Expressions** and their main idea is that they _generalize_ the syntax that was already being used in `th:insert`/`th:replace`/`th:include` in order to be able to use _resolved fragments_ as any other kind of objects in the template execution context.

Their syntax is similar to that of other simple expressions, using the _tilde_ (`~`) as a selector char. So expressions such as these:

``` html
~{commons::main}
```

...will now not only be usable in `th:insert`/`th:replace`/`th:include` like:

``` html
<div th:insert="~{commons :: main}">...</div>
```

...but also as a part of other more complex expressions like:

``` html
<div th:insert="${user.admin}? ~{adm :: admintools} : ~{common :: basictools}">...</div>
```

...or even:

``` html
<div th:with="frag=~{footer :: #main/text()}">
  <p th:insert="${frag}">
</div>
```

All features available before Thymeleaf 3.0 in fragment insertion syntax are also available in _fragment expressions_, including:
- Same-template fragments: `~{::frag}`, `~{this::frag}`, ...
- Complete-template fragments: `~{main}`, `~{usermain}`, ...
- Variable-based resolution, `~{${templateName} :: ${fragmentName}}`
- Fragment parameters, both named and unnamed, like `~{common::details(${user.name})`, `~{::main(title=#{corp.title})}`

Besides, Thymeleaf 3.0 fully embraces the new _Markup Selector_ syntax provided by AttoParser 2.0, which builds on the previously existing syntax and largely extends it, providing new selection capabilities (see below).

**Fragments as parameters (layout)**

Now that _fragments_ (objects of class `org.thymeleaf.standard.expression.Fragment`) can be put into context just as any other variables, we can use them as parameters to another fragments, effectively turning fragment expressions into a **complete layout mechanism**.

For example, we might develop a _common template_ called `base.html`, containing the `<head>` tag we want to use for most of our application's pages, containing all the style and script imports we will need but allowing the specification of a _page title_ and some additional `<link>`s:

``` html
<head th:fragment="common_header(title,links)">

  <title th:replace="${title}">The awesome application</title>

  <!-- Common styles and scripts -->
  <link rel="stylesheet" type="text/css" media="all" th:href="@{/css/awesomeapp.css}">
  <link rel="shortcut icon" th:href="@{/images/favicon.ico}">
  <script type="text/javascript" th:src="@{/sh/scripts/codebase.js}"></script>

  <!--/* Per-page placeholder for additional links */-->
  <th:block th:replace="${links}" />

</head>
```

Then we could have a `main.html` template making use of the fragment above:

``` html
...
<head th:replace="base :: common_header(~{::title},~{::link})">

  <title>Awesome - Main</title>

  <link rel="stylesheet" th:href="@{/css/bootstrap.min.css}">
  <link rel="stylesheet" th:href="@{/themes/smoothness/jquery-ui.css}">

</head>
...
```

Note how those `~{::title}` and `~{::links}` parameters we are specifying in our `th:replace` will effectively _pass_ parts of the original template markup (`main.html`) on to the inserted fragment (`base.html`), where these parts can be themselves inserted into specific placeholders. So the end result will look like:

``` html
...
<head>

  <title>Awesome - Main</title>

  <!-- Common styles and scripts -->
  <link rel="stylesheet" type="text/css" media="all" href="/awe/css/awesomeapp.css">
  <link rel="shortcut icon" href="/awe/images/favicon.ico">
  <script type="text/javascript" src="/awe/sh/scripts/codebase.js"></script>

  <link rel="stylesheet" href="/awe/css/bootstrap.min.css">
  <link rel="stylesheet" href="/awe/themes/smoothness/jquery-ui.css">

</head>
...
```

**Compatibility with fragment insertion in older versions**

Even if the new fragment expressions bring a lot of flexibility to fragment insertion operations in Thymeleaf, this does not mean that old `th:include` or `th:replace` attributes need to be changed. So even if Thymeleaf 3.0 _recommends_ using specifying fragment insertion like this:

``` html
<div th:replace="~{commons :: main}">...</div>
```

...this does not mean that the previous, _unwrapped_ way of expressing fragments doesn't work anymore. So this will still work perfectly:

``` html
<div th:replace="commons :: main">...</div>
```

**Writing fragments as text, not as... fragments**

A new possibility that fragment expressions bring is using fragment expressions outside _fragment insertion_ attributes (`th:insert`/`th:replace`/`th:include`). Specifically, they can be useful in `th:text` and `th:utext` attributes:

``` html
<span th:utext="~{::title/text()}">...</span>
```

Note there are important differences between `th:insert`, `th:text` and `th:utext` when used with a fragment expression:
- `th:insert` will _process_ the inserted fragment (i.e. any `th:*` attributes in the fragment will get processed) while the others won't.
- `th:text` will _escape_ the inserted fragment (after converting it to a `String` if needed) while the others won't.
- `th:utext` will therefore be almost equivalent to `th:insert`, but nothing inside the fragment will ever get processed.

So we can revisit the example above and rewrite the _title_ of our `base.html` template, using a more elegant `th:utext` instead of the previous `th:replace`:

``` html
<head th:fragment="common_header(title,links)">

  <title th:utext="${title}">The awesome application</title>

  <!-- Common styles and scripts -->
  <link rel="stylesheet" type="text/css" media="all" th:href="@{/css/awesomeapp.css}">
  <link rel="shortcut icon" th:href="@{/images/favicon.ico}">
  <script type="text/javascript" th:src="@{/sh/scripts/codebase.js}"></script>

  <!--/* Per-page placeholder for additional links */-->
  <th:block th:replace="${links}" />

</head>
```

But note this will input the `<title>` tag coming from `main.html` inside the `<title>` tag in `base.html`, so we need to modify the expression by which we call the fragment from `main.html` in order to include only the title's _text body_ (`/text()`):

``` html
...
<head th:replace="base :: common_header(~{::title/text()},~{::link})">

  ...

</head>
...
```

**Fragment existence**

Fragment expressions do in general check the existence of the fragment they represent. But they do this in two different ways depending on when they are used:
- For fragment expressions used directly (i.e. not as a part of a complex expression) in attributes such as `th:insert`/`th:replace`/`th:include`/`th:text`/`th:utext`/... these expressions will **raise an exception** if the resolved fragment does not exist. This includes both the fragment's template not existing and also the specified fragment not existing in an existing template.
- For fragment expressions used as a part of complex expressions (conditionals, defaults, etc.) or also as parameters of other fragment expressions, these expressions will simply **evaluate to `null`** whenever the fragment or its container template do no exist. Note that this _nullity_ means that fragment expressions used as the condition of a conditional expression will evaluate to `false`.

Let's see some examples. These will raise an exception if template or fragment do not exist:

``` html
<div th:insert="~{commons :: main}">...</div>
<div th:insert="commons :: main">...</div>
<div th:text="~{commons :: main}">...</div>
```

However, when used as a fragment expression parameter, it will simply evaluate to `null`:

``` html
<!-- Call the fragment with a "title" parameter that does not exist: title=null -->
<div th:insert="~{commons :: header(title=~{::#maintitle})}">...</div>
...
<!-- Once "title" is null th:utext's behaviour will be to write nothing -->
<span th:utext="${title}">...</span>
...
<!-- But note that, with the same null, th:insert's behaviour will be to fail -->
<span th:insert="${title}">...</span>
```

Also, when used in a conditional or default expression the fragment will evaluate to `false` (because `null` is `false` in conditionals). Let's see a quite elaborate expression inserting a `base_{TYPE}` fragment depending on the type of user, but knowing that not all types actually exist in our template:

``` html
<div th:insert="~{commons :: |#base_${user.type}|} ?: ~{commons :: #default}">...</div>
```

**The EMPTY fragment**

If a nonexisting fragment will either fail or just return null, how can we make a fragment insertion expression _insert nothing_? In such case we can use the _empty fragment_ expression: `~{}`.

So we can modify the expression above to specify that, if no _base_ for the user type exists, we should simply insert _nothing_:

``` html
<div th:insert="~{commons :: |#base_${user.type}|} ?: ~{}">...</div>
```

Note that _inserting nothing_ is not the same as _doing nothing_. In this case, the `...` in the body of the `<div>` tag will actually get removed and the result will be:

``` html
<div></div>
```

With this, we can revisit our header template and take into account the possibility that the calling template might not have any `<link>`s to add:

``` html
<head th:fragment="common_header(title,links)">

  <title th:utext="${title}">The awesome application</title>

  <!-- Common styles and scripts -->
  <link rel="stylesheet" type="text/css" media="all" th:href="@{/css/awesomeapp.css}">
  <link rel="shortcut icon" th:href="@{/images/favicon.ico}">
  <script type="text/javascript" th:src="@{/sh/scripts/codebase.js}"></script>

  <!--/* Per-page placeholder for additional links */-->
  <th:block th:replace="${links} ?: ~{}" />

</head>
```

**The new fragment syntax**

Fragment expressions in Thymeleaf 3.0 allow the use of the powerful _markup selector_ syntax provided by AttoParser 2.0, Thymeleaf's new parsing library. This syntax builds on (and importantly extends) the fragment specification syntax available in Thymeleaf version 2.1, so that backwards compatibility is ensured.

For more detail on this syntax, read AttoParser's documentation for this syntax at http://www.attoparser.org/apidocs/attoparser/2.0.0.BETA3/org/attoparser/select/package-summary.html

As a Thymeleaf-specific adaptation, note that what AttoParser generically calls _reference-based matching_ is applied by Thymeleaf by considering the `th:fragment` and `th:ref` attributes as _references_. So the `%whatever` and `whatever` expressions will match any tags with `th:fragment="whatever"` or `th:ref="whatever"` (see #196 on `th:ref`).

Some very quick examples:
- `whatever` or `//whatever`: match any `<whatever>` tags, or any `whatever` references (`th:fragment="whatever"`, `th:ref="whatever"`) at any level in the markup hierarchy.
- `/whatever`: same as above, but only at the root level of the markup hierarchy.
- `foo/whatever`: same as above, but only as a direct child of an element/reference called `foo`.
- `foo//whatever`: same as above, but at any hierarchy level inside an element/reference called `foo`.
- `.whatever`: any tags with `class="whatever"`.
- `div.whatever`: any `<div>` tags with `class="whatever"`.
- `#whatever`: any tags with `id="whatever"`.
- `div#whatever`: any `<div>` tags with `id="whatever"`.
- `div#whatever/text()`: any text nodes contained as direct children of a `<div class="whatever">`.
- `input[type='text']: any`<input>`tags with`type="text"`.
- ...

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`

**Comment by gomyho** [comment]
hi,
I'm from china,i'm learning thymeleaf ,but when i use thyemleaf3.0 layout examples,it always throws exception,hope 4 solution.
In my project(spring boot1.4,spring-boot-starter-thymeleaf) template files like this:

```
+templates
  +layout
    -header.html
  +strategy
    -create.html
```

all content in _header.html_  (copy from   [ http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#template-layout](http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#template-layout))

```
<head th:fragment="common_header(title,links)">
    <meta http-equiv="Content-Type" content="text/html;charset=utf-8"></meta>
    <title th:text="${title}">shangpin coupon manager system console</title>
        <th:block th:replace="${links}" />
</head>
```

and content in _create.html_

```
<!DOCTYPE html>
<html  xmlns:th="http://www.thymeleaf.org">
<head th:replace="layout/header :: common_header(~{::title} ,~{::link})">
    <title>coupon-create</title>
    <link rel="stylesheet" th:href="@{/public/css/strategy.css}" />
    <link rel="stylesheet" th:href="@{/public/css/strategy.css}" />
</head>
```

when i visit [http://localhost/strategy/create](http://localhost/strategy/create),then it throws exception:

```
org.thymeleaf.exceptions.TemplateProcessingException: Could not parse as fragment selection: "layout/header :: common_header(~{::title} ,~{::link})" (strategy/create:3)
    at org.thymeleaf.standard.expression.FragmentSelectionUtils.parseFragmentSelection(FragmentSelectionUtils.java:106)
    at org.thymeleaf.standard.fragment.StandardFragmentProcessor.computeStandardFragmentSpec(StandardFragmentProcessor.java:72)
```

**Comment by danielfernandez** [comment]
@gomyho check your configuration, you are using Thymeleaf 2.1. The `FragmentSelectionUtils` class does not exist in 3.0.

**Comment by gomyho** [comment]
yes,i found that the default Tyemeleaf version is 2.x in spring boot1.4 ,and my example is for version3.x.

**Comment by gomyho** [comment]
yes,i found that the default Tyemeleaf version is 2.x in spring boot1.4 ,and my example is for version3.x.

**Comment by ricardorqr** [comment]
Hello guys,
I've been studying Spring Boot and Thymeleaf for one week ago and I'm receiving this message:

`2017-08-15 16:46:38.764  WARN 9648 --- [nio-8080-exec-5] n.n.u.t.expressions.ExpressionProcessor  : Fragment expression "admin/home" is being wrapped as a Thymeleaf 3 fragment expression (~{...}) for backwards compatibility purposes.  This wrapping will be dropped in the next major version of the expression processor, so please rewrite as a Thymeleaf 3 fragment expression to future-proof your code.  See https://github.com/thymeleaf/thymeleaf/issues/451 for more information.`

That is why I'm here. I read many times the above article but I couldn't understand. This is my main page.

```
<!DOCTYPE html>
<html lang="en" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:th="http://www.thymeleaf.org">
<head>
	<meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	
	<title>Final Project</title>
	
	<link rel="stylesheet" type="text/css" th:href="@{/css/login.css}" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" />
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container-fluid">
			<!-- Brand and toggle get grouped for better mobile display -->
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" 
					data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" th:href="@{/admin/home}">Final Project</a>
			</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
				<ul class="nav navbar-nav">
					<li><a th:href="@{/admin/preferences}">Preferences</a></li>
				</ul>
				
				<form class="navbar-form navbar-right" th:action="@{/logout}" method="get">
					<button class="btn btn-default btn-md btn-danger" name="registration" type="Submit">Logout</button>
				</form>
			</div>
		</div>
	</nav>
	
	<div layout:fragment="contentBody">
		<div class="container">
			<div class="panel-group">
				<div class="panel-heading">
					<div class="page-header">
						<br/>
						<h2><span th:utext="${userName}"></span>, welcome back!</h2>
					</div>
				</div>
				
				<div class="panel-body">
					<p class="admin-message-text text-center" th:utext="${adminMessage}"></p>
				</div>
			</div>
		</div>
	</div>
</body>
</html>
```

Above it is my main page which I'm gonna insert the other page. Next it is the page that I'll insert in the mais page.

```
<!DOCTYPE html>
<html lang="en" xmlns:layout="http://www.ultraq.net.nz/thymeleaf/layout"
	xmlns="http://www.w3.org/1999/xhtml" 
	xmlns:th="http://www.thymeleaf.org"
	layout:decorate="admin/home">
<head>
    <meta charset="utf-8"/>
	<meta name="viewport" content="width=device-width" />
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
</head>
<body>
	<div layout:fragment="contentBody">
		<br/>
	    <div class="page-header">
	        <h1>Users</h1>
	    </div>
	    <table class="table table-bordered">
	       	<thead>
	       		<tr>
	       			<th>ID</th>
	       			<th>Nome</th>
	       			<th>Last Name</th>
	       			<th>Email</th>
	       			<th>Status</th>
	       			<th></th>
	       		</tr>
	       	</thead>
	       	<tbody>
				<tr th:each="user : ${users}">
					<td th:text="${user.id}">123</td>
					<td th:text="${user.name}">Rico</td>
					<td th:text="${user.lastName}">Ribeiro</td>
					<td><a href="#" th:text="${user.email}">ricardorqr@gmail.com</a></td>
					<td th:text="${user.active}">
						<a class="btn btn-sm btn-primary" th:href="@{/edit/{id}(id=${user.id})}" >Edit</a>
						<a class="delete btn btn-sm btn-danger" th:href="@{/delete/{id}(id=${user.id})}">Delete</a>
					</td>
				</tr>
				<tr>
					<td>123</td>
					<td>Rico</td>
					<td>Ribeiro</td>
					<td><a href="#">ricardorqr@gmail.com</a></td>
					<td>1</td>
					<td>
						<a class="btn btn-sm btn-primary">Edit</a>
						<a class="delete btn btn-sm btn-danger">Delete</a>
					</td>
				</tr>
			</tbody> 	
		</table>
	</div>
</body>
</html>
```

Does someone know what wrong is?

**Comment by danielfernandez** [comment]
@ricardorqr please note this warning is being issued by the Layout Dialect, not Thymeleaf itself (that `ExpressionProcessor` is not a Thymeleaf class). Apparently, the Layout Dialect is warning you that it prefers you using the new *Fragment Expression* syntax (`~{...}`) instead of the old one (without the expression wrapping symbols).

**Comment by ricardorqr** [comment]
Hello @danielfernandez, thank you for answering me. Yes, that is my question. I've already tried to update for the new syntax, but still wrong. I really don't know what I am doing wrong. Can you explain to me what do I have to do?

**Comment by danielfernandez** [comment]
@ricardorqr Well, I suspect the Layout Dialect is expecting you to express `layout:decorate="admin/home"` as `layout:decorate="~{admin/home}"`, though this dialect is an external project and you could probably obtain further orientation in their own GitHub repos.

**Comment by ricardorqr** [comment]
Heeeeeeeeyyyyyy @danielfernandez buddy!!! It works!!! Now I don't have that message anymore. Thanks, man.

**Comment by dihardmg** [comment]
weleh weleh it work thanks @danielfernandez  👍

**Comment by bzw1204** [comment]
Excuse me, th:block can only be used in head?

**Comment by bzw1204** [comment]
Excuse me, th:block can only be used in head?
![image](https://user-images.githubusercontent.com/9693637/37701864-95e1f9b0-2d2b-11e8-8dc3-a66dd7519bbd.png)
![image](https://user-images.githubusercontent.com/9693637/37701875-9c4c41c0-2d2b-11e8-99e7-e9d9d500687a.png)

This is my code. After I did this, the request was wrongly reported.

**Comment by grath10** [comment]
@bzw1204 Can you offer any available detailed wrong information?

**Comment by RiZKiT** [comment]
@bzw1204 I cannot see any link tag in your index.html, but you reference it with `~{::link}`!?

**Comment by NikhilParmar47** [comment]
Hello Friends,

I facing below error and warning in spring boot version 2.1.7.RELEASE with thymeleaf.

WARN  is : 

layout:decorator/data-layout-decorator processor has been deprecated and will be removed in the next major version of the layout dialect.  Please use layout:decorate/data-layout-decorate instead to future-proof your code.

Error is :
[THYMELEAF][http-nio-9090-exec-8] Exception processing template "/signup": An error happened during template parsing (template: "class path resource [templates//signup.html]")

Anybody help me.

Thanks in Advance.

**Comment by grath10** [comment]
It seems that you do not need the '/'， try to return "signup" instead.

At 2019-09-06 14:10:39, "Nikhil Parmar" <notifications@github.com> wrote:


Hello Friends,

I facing below error and warning in spring boot version 2.1.7.RELEASE with thymeleaf.

WARN is :

layout:decorator/data-layout-decorator processor has been deprecated and will be removed in the next major version of the layout dialect. Please use layout:decorate/data-layout-decorate instead to future-proof your code.

Error is :
[THYMELEAF][http-nio-9090-exec-8] Exception processing template "/signup": An error happened during template parsing (template: "class path resource [templates//signup.html]")

Anybody help me.

Thanks in Advance.

**Comment by silkentrance** [comment]
Will preprocessing still be possible, e.g.

```
layout:decorate="__${basetemplate}__"
```

I am asking because right now I get the deprecation warning (thymeleaf:3.0.12-SNAPSHOT)

```
Fragment expression "__${basetemplate}__" is being wrapped as a Thymeleaf 3 fragment expression (~{...}) for backwards compatibility purposes.  This wrapping will be dropped in the next major version of the expression processor, so please rewrite as a Thymeleaf 3 fragment expression to future-proof your code.  See https://github.com/thymeleaf/thymeleaf/issues/451 for more information.
```
