### ISSUE TITLE
Deprecate unwrapped syntax for fragment insertion

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#453]
After introducing fragment expressions in Thymeleaf 3.0 (see #451), the legacy _unwrapped syntax_ for these fragment expressions (i.e. `th:replace` values without `~{...}`) should be marked as _deprecated_ in preparation for removing it in future versions of Thymeleaf.

This future removal will allow an important reduction of complexity in the expression parsing phase of `AbstractStandardFragmentInsertionTagProcessor`.

**Comment by ultraq** [comment]
We might need a good doc overhaul for this too :)

**Comment by danielfernandez** [comment]
Closed in 569e71b
