### ISSUE TITLE
Update XML resource files used for IDE integration

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#454]
Thymeleaf 3.0 adds some new attributes to the Standard Dialects, such as `th:insert` or `th:ref`.

The XML files in the `resources` folders in Thymeleaf core, Thymeleaf Spring3/Spring4 integrations and also extras like the SpringSecurity3/4 dialects might therefore need a check and (if needed) an update with any new attributes.

**Comment by danielfernandez** [comment]
@ultraq could you have a look at this one pls?

**Comment by ultraq** [comment]
Sure thing!

**Comment by ultraq** [comment]
Have just started this now, and holy cow do we have a lot of processors!

On a related note, that screencast of IntelliJ 16 reading the dialect schema files we created has me all :grin: https://twitter.com/serega_vasiliev/status/699522005012500480

With that in mind, I've started thinking that we need to move schema-related stuff into its own repo: https://github.com/thymeleaf/thymeleaf-extras-eclipse-plugin/issues/67

**Comment by danielfernandez** [comment]
Sounds sensible... a new repo or maybe even the Thymeleaf core?

BTW, what is the relation between the XML resources that go inside the Thymeleaf jar and the `.xsd`s in `thymeleaf-extras-eclipse-plugin`?

**Comment by ultraq** [comment]
The XML resources are just implementations of the XSD in the plugin project.  This was so that the Eclipse plugin (and now future IntelliJ versions) could ensure some kind of common language for reading dialect metadata statically.

**Comment by ultraq** [comment]
Documentation references will probably need an update once the Using Thymeleaf tutorial is updated for 3.0

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
