### ISSUE TITLE
Thymeleaf fails to parse valid HTML5 template with <meta> tag without closing slash.

### ISSUE THREAD

**Issue by UniK** [thymeleaf/thymeleaf#457]
Thymeleaf fails to parse HTML5 Template
with the meta tag (without '/' in front of closing '>'):

``` html
<meta charset="utf-8">    <!-- valid in HTML5 -->
```

Thymeleaf does parse the meta tag, if the tag is self-closing (with '/' in front of closing '>') which is fully optional in HTML5:

``` html
<meta charset="utf-8"/>    <!-- optional in HTML5 -->
```

And by the way: Thymeleaf should not parse following HTML4 markup if TemplateMode==HTML5 is specified.

``` html
<!-- Defining the charset in HTML4 --> 
<!-- Note: This is invalid in HTML5 -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
```

**Comment by ultraq** [comment]
I take it this is with Thymeleaf 2?  If so, then yeah, Thymeleaf 2 is an XML parser under the hood, and so tags and everything need to be balanced for it to work.  There's the (not so intuitively named) LEGACYHTML5 template mode you can use that'll bring in the nekoHTML tag balancer to do that automatically, but may bring other undesired effects if it can't figure out where to close tags.

Thymeleaf 3 however uses a new parser that can handle HTML5 syntax just fine.  It's still in development but is totally usable via the first beta or latest snapshot if you have the option of using an in-development version of Thymeleaf.
