### ISSUE TITLE
Elvis operator with date formatting

### ISSUE THREAD

**Issue by yvangg** [thymeleaf/thymeleaf#461]
I want to use the elvis operator with a Date field. The problem is that if i want to format that date, and if i use something like

`<td th:text="${#dates.format(object.dateField, 'dd/MMM/yyyy HH:mm')} ?: #{text.empty.date}">2012-10-08</td>`

I get an error. It will be awesome if the format operation will not fail if the date will be null.

**Comment by danielfernandez** [comment]
Applied null-safety to all methods (in which it made sense) in #dates, #calendars, #numbers and #153 

This is already in `3.0.0-SNAPSHOT`
