### ISSUE TITLE
Jackson closes writer by default

### ISSUE THREAD

**Issue by seanhinkley** [thymeleaf/thymeleaf#462]
Jackson by default closes streams (https://fasterxml.github.io/jackson-databind/javadoc/2.6/com/fasterxml/jackson/databind/ObjectMapper.html#writeValue-java.io.Writer-java.lang.Object-).  This is problemsome when writing lazy CharSequence instances (uses Servlet PrintWriter).  CharSequence instances that aren't lazy have no issue as they use a seperate Writer.

This

``` html
<!DOCTYPE html>
<html lang="en">
<body>
  content
  <script type="text/javascript" th:inline="javascript">
      var nowYouSeeMe = [[${b}]];
      var nowYouDont = 'foo';
  </script>
</body>
</html>
```

results in 

``` html
<!DOCTYPE html>
<html lang="en">
<body>
  content
  <script type="text/javascript">
      var nowYouSeeMe = {"name":"Name"}
```

**Comment by seanhinkley** [comment]
I can create a PR if you'd like.

https://github.com/seanhinkley/thymeleaf/commit/c5989690fd937123db62e280101bc8d6fbbc0019

**Comment by danielfernandez** [comment]
Confirmed. I'm wondering how the $%&·!! this could go through our JS serialization tests, which use Jackson :-|... maybe it's something in the `Writer`s used by the thymeleaf-testing library.

Anyway, I've tested it directly on a Tomcat server and you're completely right. A pull request would be awesome.

Thanks Sean.

**Comment by seanhinkley** [comment]
submitted the PR.  It looks like string writers don't much care about closed streams.

Users that provide IStandardJavaScriptSerializer to StandardDialect may have issues if they config ObjectMapper as a bean and reuse it.  I think @ResponseBody would use jackson and may be negatively impacted.  When I get a moment, I can check it out and let you know.  Worst case it may require a mention in the documentation.

**Comment by danielfernandez** [comment]
Thanks again. It might not pose a problem for Spring if the writer is closed anyway at the end of the response… but anyway, it would be nice to know for sure if this kind of interaction could pose any problems.
