### ISSUE TITLE
Text write from buffer - writer takes start/end not start/len

### ISSUE THREAD

**Issue by eiswind** [thymeleaf/thymeleaf#469]
`public void write(final Writer writer) throws IOException {
        Validate.notNull(writer, "Writer cannot be null");
        if (this.buffer != null) {
            // Using the 'buffer write' is the first option because it is normally faster and requires less
            // resources than writing String objects
            writer.write(this.buffer, this.offset, this.length);`

in Text should probably be 

`writer.write(this.buffer, this.offset, this.offset + this.length);`

at least this cures a bunch of StringIndexOutOfBoundsExceptions

**Comment by danielfernandez** [comment]
Thanks. However, unless I'm understanding correctly, you are referring to https://github.com/thymeleaf/thymeleaf/blob/d88e6b7dbf132b6b6f8c09567b1025a24194a3f1/src/main/java/org/thymeleaf/engine/Text.java#L201

And actually, `write(char[] cbuf, int offset, int len)` is the correct signature of that method in `java.io.Writer`. Or is there something I'm missing?

**Comment by eiswind** [comment]
Hi Daniel,
you are absoluteley right. Magnolias API was misleading me completely as they have an Appendable (mis-)designed as
`AppendableWriter extends Writer`

`@Override

public void write(char[] chars, int start, int end) throws IOException {

```
    appendable.append(new String(chars), start, end);

}`
```

now when thymeleaf uses this as Writer, everything goes wrong.
I think I can workaround by wrapping the Magnolia Writer.
