### ISSUE TITLE
Allow the specification of URI template patterns to be escaped as path segments

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#471]
Currently, the specification of URI template patterns at `StandardLinkBuilder` does always escape variable values as _URI paths_ (i.e. `/` are not escaped). This was so because it was implemented mimic'ing what Spring did at `UrlTag`.

However, Spring 4.1 added a way to specify template patterns so that they are escaped as _path segments_: `{/variable}`. See https://github.com/spring-projects/spring-framework/blob/master/spring-webmvc/src/main/java/org/springframework/web/servlet/tags/UrlTag.java#L302-L313

This should be added to the syntax allowed by `StandardLinkBuilder`

**Comment by jimmythomson** [comment]
@danielfernandez - did you want me to look getting a PR in for this? Happy to do so.

**Comment by danielfernandez** [comment]
Oh, I will fix this (and #470) before GA for sure, but of course if you can provide a PR it would be more than welcome :)

The idea is to mimic what Spring's `UrlTag` does to the maximum extent possible (even if Spring is not being used).

**Comment by jimmythomson** [comment]
Cool. I'll take a look over the weekend. I feel like I should try and contribute :)

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
