### ISSUE TITLE
Attribute combination/aggregation not working (in input element)

### ISSUE THREAD

**Issue by jasonm23** [thymeleaf/thymeleaf#472]
When I try to assign a combined attribute to an input element it is not transformed.

e.g.

```
<input type="text" th:id-value="user" th:value="${appUser.id}" />
```

and:

```
<input type="text" th:value-id="user" th:value="${appUser.id}" />
```

Transform to:

```
<input type="text" th:id-value="user" value="1" />
```

and: 

```
<input type="text" th:value-id="user" value="1" />
```

Is this expected behaviour? 

This tutorial suggests otherwise: http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#setting-more-than-one-value-at-a-time

**Comment by danielfernandez** [comment]
I'm afraid the standard dialects only include two _double output_ attributes: `th:alt-title` and `th:lang-xmllang`, as explained in the section of the tutorial you link. There is no `th:value-id`, nor is any combination of attributes allowed, sorry.

**Comment by jasonm23** [comment]
Ideally `id-name` or `name-id` would be useful for inputs/selects/form child elements.

**Comment by jasonm23** [comment]
(which was what I should have put in my original example)
