### ISSUE TITLE
about special character can not use in page

### ISSUE THREAD

**Issue by songpo** [thymeleaf/thymeleaf#476]
I can not use special character in my html page,like < >,
the error is “org.xml.sax.SAXParseException: 元素内容必须由格式正确的字符数据或标记组成。”

```
var fiveMap = {};
fiveMap['SOH'] = '01 ';
fiveMap['SOH<<≡'] = '01 0D 0D 0A ';

```

when i use gt; or &gt; 

```
var fiveMap = {};
fiveMap['SOH'] = '01 ';
fiveMap['SOHgt;gt;≡'] = '01 0D 0D 0A ';
```

it is show like this

```
<select class="form-control" name="sendHead">
         <option value="01 ">SOH</option>
         <option value="01 0D 0D 0A ">SOHgt;gt;≡</option>
</select>
```

i want show this

```
<select class="form-control" name="sendHead">
         <option value="01 ">SOH</option>
         <option value="01 0D 0D 0A ">SOH<<≡</option>
</select>
```

hope everyone can help me! 
thanks very much!

**Comment by songpo** [comment]
I already find the solution！
It's like this

```
<script type="text/javascript">
        /*<![CDATA[*/
                var fiveMap = {};
                fiveMap['SOH'] = '01 ';
                fiveMap['SOH<<≡'] = '01 0D 0D 0A ';
        /*]]>*/
</script>
```

**Comment by danielfernandez** [comment]
That's right. Thymeleaf 2.1 requires your JavaScript blocks to be enclosed in `<![CDATA[...]]>` if their bodies contain HTML-significative characters such as `>`, `<`, etc.

Note also that Thymeleaf 3.0 improves its parsing system regarding `<script>` blocks and would not require you to do this.
