### ISSUE TITLE
Update documentation for Thymeleaf 3

### ISSUE THREAD

**Issue by omazurashu** [thymeleaf/thymeleaf#478]
Hi team,
just checked the site and didn't find the documentation about how to use Thymeleaf 3 except migration guide.

Believe that for community it will be useful to have it.
Are you plan to update it in near future? Current version BETA02 is feature-complete, so maybe it is a time to do that.

Anyway thanks for your hard work and good luck :)

**Comment by danielfernandez** [comment]
Yes, of course we will. But it will take a bit of time :-)

Fortunately, from the users' standpoint almost everything said in the tutorials for 2.1 is still valid (except a couple of things that can be easily found at the migration guide) so most users should be able to transition seamlessly during the time it takes us to create new, updated tutorials and guides.

Also, javadoc has been vastly improved in Thymeleaf 3.0, and that should help too! :-)
