### ISSUE TITLE
th:fragment seems to be executed inline with rest of document

### ISSUE THREAD

**Issue by wmarbut** [thymeleaf/thymeleaf#479]
Fragments declared within a template seem to be executed even when they are not called in thymeleaf 3 beta2.

**Example 1**

```
<html>
<head></head>
<body>
<p>I am some template stuff</p>
<p th:text="${somethingSpringy}"></p>
<div th:fragment="doSomething(withMe)">
    <p th:text="${withMe.andMe}"></p>
</div>
</body>
```

I get an error like this

```
Caused by: org.attoparser.ParseException: Exception evaluating SpringEL expression: "withMe.andMe" (template: "/mytemplate" - line 7, col XX)
```

**Example 2:** Or in this case

```
<html>
<head></head>
<body>
<p>I am some template stuff</p>
<p th:text="${somethingSpringy}"></p>
<div th:fragment="doSomething(withMe)">
    <p>you should never see me</p>
</div>
</body>
```

I get this

```
<p>I am some template stuff</p>
<p>Some spring variable</p>
<div>
    <p>you should never see me</p>
</div>
```

Even though I never called that fragment. This wasn't the behavior in thymeleaf 2.

**Comment by danielfernandez** [comment]
This has not changed in 3.0.
The presence of a `th:fragment` attribute does not mean that the markup section that contains such attribute does not have to be executed as a part of a containing, larger template. Executing your fragment of code should mean the execution of your fragment in all versions of Thymeleaf.
