### ISSUE TITLE
add formatCurrency() method to #numbers helper

### ISSUE THREAD

**Issue by kurtseebauer** [thymeleaf/thymeleaf#482]
Since currency-formatting is locale dependent (thousands and decimal separator and decimal digits) and the #numbers utility class already has the locale in it, I suggest the addition of a method 

String formatCurrency(Number number)

It's pretty inconvenient to find out the current locale and apply its settings to 
formatDecimal(target, minIntegerDigits, thousandsPointType, decimalDigits, decimalPointType)

Thanks for your work!

**Comment by danielfernandez** [comment]
Thanks, makes sense to me. I'm queueing this for future work, and opening it for contributions.

**Comment by dtrunk90** [comment]
Additionally I suggest another method: `formatPercent(Number target, Integer minIntegerDigits, Integer decimalDigits)`
