### ISSUE TITLE
Reflection issue with google app engine and Thymeleaf 2.1.4 and 3.0.0.b02

### ISSUE THREAD

**Issue by cornim** [thymeleaf/thymeleaf#484]
When accessing a function directly from a thymeleaf template via ognl a IllegalAccessException is thrown even though the function is public.
I've put together a sample application so you can reproduce the error:
https://github.com/cornim/TLBugExample.git

Please also note the following:
If the function is accessed via the property (i.e. ${item.name} instead of ${item.getName()}) no exception is thrown.
Also, if one sets OgnlRuntime.setSecurityManager(null); (see CtxListener.java) direct function access via ognl starts working, but that doesn't seem to be a sensible solution.

**Comment by danielfernandez** [comment]
Google App Engine poses important restrictions on the use of reflection, but unfortunately there is nothing we can do from the Thymeleaf side to modify the way OGNL (which is a separate, independent project) executes functions.

I would suggest using property access whenever possible. Maybe you could also try using Spring and the Thymeleaf-Spring integration packages and check if SpringEL (which replaces OGNL in Thymeleaf templates when Spring is used) also has this issue, but I cannot assure you it would work (again, we are talking about separate projects).
