### ISSUE TITLE
how to use th:data

### ISSUE THREAD

**Issue by zhanghqgit** [thymeleaf/thymeleaf#489]
for example ,add data-example attribute to a tag, not use th:attr, how to do this?

th:data='example=${*****}' can not parse.

thank you

**Comment by danielfernandez** [comment]
If you are using Thymeleaf 2.1, you have to either use `th:attr` (which apparently you don't want to) or use the _Data Attribute Dialect_: https://github.com/mxab/thymeleaf-extras-data-attribute

If you are using Thymeleaf 3.0, you can simply do `th:data-example="${...}"`
