### ISSUE TITLE
how to integration springboot with thymeleaf3

### ISSUE THREAD

**Issue by kings1990** [thymeleaf/thymeleaf#490]
my project based on springboot1.3.3
i update my thymeleaf from 2.1.3 to 3.0.0.BETA02 
but it went wrong 
Caused by: java.lang.NoClassDefFoundError: org/thymeleaf/resourceresolver/IResourceResolver

how to repair？

**Comment by kings1990** [comment]
springboot1.3.3 now don't support thymeleaf3 but support thymeleaf2.1.3
 so i just exclude thymeleaf and write ThymeleafConfig and SpringWebInitializer
then it can work with thymeleaf3
@SpringBootApplication(exclude={org.springframework.boot.autoconfigure.thymeleaf.ThymeleafAutoConfiguration.class})

**Comment by danielfernandez** [comment]
As you explain, Spring Boot is not yet updated to Thymeleaf 3 (which makes sense, given Thymeleaf 3 is still in BETA).
