### ISSUE TITLE
Inherit objects from parent layout when using layout decoration

### ISSUE THREAD

**Issue by Kerruba** [thymeleaf/thymeleaf#491]
Hi, 

I think would be nice to use variable inheritance within layout template, defining default variables in the base template that can be overridden in the decorating child template.
For example, I've a base template `base.html` which contains various layout fragments, one of which is the navigation bar. 
I would like to use a `currentPage` variable to set the active page in the navigation bar using a `.active` class on the element.
Right now I need to set `th:with="currentPage='pageName'"` on each child page to correctly setup the navigation, but it would be really useful to have a default value in the `base.html` template that is inherited in the child template and possibly overwritten by a more specific value.

There's an example that is even clearer (from my point of view):
In my site I've a series of pages dedicated to Help. 
In these pages I've two navigations: the primary one and a secondary one that let you move around the help pages.
I have setup two variables to define which is the current page globally on my site and which is the current page locally in my help pages.
If I want to go to the help home page, for example, here the variables I'm setting up:

```
th:with="currentPage='help', helpPage='home'"
```

If I want instead to go to a contact us page, here the corresponding variables

```
th:with="currentPage='help', helpPage='contactUs'"
```

I have to repeat the `currentPage` variable for all the help pages, even if it's the same. This is not particularly DRY. Maybe would be better to define a default `currentPage='help'` inside of the base layout (or a specific layout for all the help pages) and override it just if necessary.
Something like

``` html
<!-- __parent_help.html -->
<html th:with="currentPage='help'">
<!-- parent content -->
</html>

<!-- ** BELOW THE DECORATING PAGE -->

<!-- help_contactus layout:decorator="__parent_help.html"-->
<!-- No need to define currentPage because inherited form parent layout -->
<html th:with="helpPage='contactus' >
<!-- specific content -->
</html>
```

What do you think about that?

**Comment by Kerruba** [comment]
So I just found out that if you don't define any other variable in the child template, the child template is actually picking up the default value inside of parent... I'm missing something probably -_-'

**Comment by danielfernandez** [comment]
The Layout Dialect is a separate project, not part of the official Thymeleaf distribution. 
You should probably add your ticket here: https://github.com/ultraq/thymeleaf-layout-dialect
