### ISSUE TITLE
Angular directive cause org.thymeleaf.exceptions.TemplateInputException

### ISSUE THREAD

**Issue by glock42** [thymeleaf/thymeleaf#492]
I use `spring 4.2.5`,`thymeleaf 2.1.4`.The problem is that when I ues `Angular's directive`  in `Html`,will cause an Exception.

 `org.thymeleaf.exceptions.TemplateInputException`

Html code below

```
<input type="password" name="password" placeholder="Password" 
ng-minlength="6" ng-required="true" ensure-same required/>
```

The probelm is `ng-minlength` ,`ensure-same` and `required`. How to solve it?

**Comment by danielfernandez** [comment]
Thymeleaf 2.1.x uses an XML parser underneath, and therefore does not allow attributes with no value. So you'd have to write `ensure-same="ensure-same" required="required"`.

Please note that Thymeleaf 3.0 (already in version `3.0.0.BETA03`) includes a completely, fully-HTML5 compliant which allows you to write your code without modifications.
