### ISSUE TITLE
ServletContextTemplateResolver has no constructor with ZERO parameters

### ISSUE THREAD

**Issue by holmes200601** [thymeleaf/thymeleaf#503]
The class ServletContextTemplateResolver doesn't contain default constructor with no paramenter. So the configuration example of ServletContextTemplateResolver in thymeleaf-spring.pdf tutorial would not be valid. Please refer to the following picture.

![thymeleaf-issue](https://cloud.githubusercontent.com/assets/11832975/15598846/c2a2124e-2410-11e6-89f1-899be28c74e9.JPG)

It seems that ServletContextTemplateResolver was rewrited by someone in 3.0.0. While it did have an constructor with zero parameter.

**Comment by danielfernandez** [comment]
That is correct. The only tutorial that has been updated to 3.0 so far is the 'Extending Thymeleaf' one, so what you see at the 'Thymeleaf + Spring' tutorial is still 2.1.x code. 

As for the ServletContextTemplateResolver, it required a modification that removed its argument-less constructor. Please refer to the migration guide at http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html (section 2 - Configuration Changes) to see how to adapt your template resolver configuration to 3.0

**Comment by holmes200601** [comment]
Thanks for your email.

I have solved this issue by programly configing the ServletContextTemplateResolver.

Anyway, thanks for your quick response. Wish thymeleaf the most popular template-markup language.

Thanks and Regards,
Sampson
