### ISSUE TITLE
about variable definition

### ISSUE THREAD

**Issue by szhgoldeneye** [thymeleaf/thymeleaf#507]
can i use js variable in thymeleaf?
just as 

``` javascript
var url = "www.google.com";
...
<h1 th:text="{url}"></h1>
```

or how to define global variable in thymleaf
like 

``` html
<div th:with="url='www.google.com'">
```

but it is effective in this div only

that's my question,thx :）

**Comment by jmiguelsamper** [comment]
Hello,

No, that's not possible. Thymeleaf variables are server-side, while Javascript variables are client-side.

About the defining a 'global' variable, if we understand 'global' by the full page, you can put th:with in the body element.

Regards.

**Comment by szhgoldeneye** [comment]
@jmiguelsamper Thx for the answer first.
Actually i define the variable using th:with in a head html,and use th:replace to quote it in another html.
Is that means the variable defined in head.html only is effective in itself and is invalid in other htmls quoting it?
And if there is a way to make it 'global' in all htmls?
Thx again.

**Comment by jmiguelsamper** [comment]
I don't think there's a way to make it global. The best option is to set it on your controller.

**Comment by szhgoldeneye** [comment]
@jmiguelsamper  I got it.
Thx for your time.
