### ISSUE TITLE
Thymeleaf 3: Incompatibility with JRE 6 and JRE 7

### ISSUE THREAD

**Issue by tobiasflohre** [thymeleaf/thymeleaf#508]
I'm running Thymeleaf with JDK 7, and when I call `StandardCache.keySet` I get the following Exception:

```
java.lang.NoSuchMethodError: java.util.concurrent.ConcurrentHashMap.keySet()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
    at org.thymeleaf.cache.StandardCache$CacheDataContainer.keySet(StandardCache.java:354)
    at org.thymeleaf.cache.StandardCache.keySet(StandardCache.java:219)
```

This happens because Thymeleaf is compiled with Java 8. `KeySetView` is new in Java 8. For more information take a look at https://gist.github.com/AlainODea/1375759b8720a3f9f094.

Solution: compile Thymeleaf with JDK 7.

**Comment by tobiasflohre** [comment]
Another possible solution could be: not returning the keyset from the `ConcurrentHashMap` directly but creating a new `Set` with the keys provided in `StandardCache`.

**Comment by danielfernandez** [comment]
Oh! That is indeed an unfortunate change at the JavaSE runtime :(

Note this should only affect calls to `TemplateManager.clearCachesFor(template)`.

The easiest way to solve that is to simply add a cast, so that, at `StandardCache$CacheDataContainer`:

``` java
public Set<K> keySet() {
    return this.container.keySet();
}
```

Turns into:

``` java
public Set<K> keySet() {
    return ((Map<K,CacheEntry<V>>)this.container).keySet();
}
```

Indeed, if we compare the old bytecode:

```
public java.util.Set<K> keySet();
  Code:
     0: aload_0
     1: getfield      #6                  // Field container:Ljava/util/concurrent/ConcurrentHashMap;
     4: invokevirtual #17                 // Method java/util/concurrent/ConcurrentHashMap.keySet:()Ljava/util/concurrent/ConcurrentHashMap$KeySetView;
     7: areturn
```

With the new one:

```
public java.util.Set<K> keySet();
  Code:
     0: aload_0
     1: getfield      #6                  // Field container:Ljava/util/concurrent/ConcurrentHashMap;
     4: invokeinterface #17,  1           // InterfaceMethod java/util/Map.keySet:()Ljava/util/Set;
     9: areturn
```

We are not referencing the new return type in Java 8 anymore, so this issue should disappear.

**Comment by danielfernandez** [comment]
Already in `3.0.1-SNAPSHOT`
