### ISSUE TITLE
th:switch doesn't work with variable of Byte type

### ISSUE THREAD

**Issue by duyanhpro** [thymeleaf/thymeleaf#511]
This was observed in spring boot 1.3.5  & thymeleaf 2.1.4:
In spring mvc controller:
`Byte i = 1;
        model.addAttribute("mynumber", i);`
In template:
`<div th:switch="${mynumber}">
                <td th:case="'1'">Active</td>
                <td th:case="'0'">Disabled</td>
                <td th:case="*">Unknown status</td>
            </div>`
Or: 
`<div th:switch="${mynumber}">
                <td th:case="1">Active</td>
                <td th:case="0">Disabled</td>
                <td th:case="*">Unknown status</td>
            </div>`

Always return "Unknown status" regardless of mynumber value.
This works probably if change mynumber to Integer type.

Sorry the codes are in one line. Line-break is gone when I paste in the code tag.

Upd: Retest in a new project with Thymeleaf 3:  same issue.

**Comment by danielfernandez** [comment]
Confirmed. Somehow `Byte` wasn't being taken into consideration in `EvaluationUtils#evaluateAsNumber(...)`

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
