### ISSUE TITLE
URL expressions doesnt work with variables.

### ISSUE THREAD

**Issue by gochev** [thymeleaf/thymeleaf#512]
Based on the documentation here http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#dialects-the-standard-dialect

Expressions like: 

```
<!-- Will produce '/gtvg/order/3/details' (plus rewriting) -->
<a href="details.html" th:href="@{/order/{orderId}/details(orderId=${o.id})}">view</a>
```

should work however placing `{variable}` inside the `@{}` block doesnt work.

My snippet:

```
    <div data-th-each="event, status : ${page.content}">
                 <!-- this doesnt evaluate event.id -->
                <span><a href="home.html" data-th-href="@{/event/delete/{event.id}}">delete</a></span>
                <!-- this also doesnt evaluate event.id -->
                <span><a href="home.html" data-th-href="@{/event/delete/${event.id}}">delete</a></span>
        </div>
```

so the only way is to use `+`

```
                  <!-- this do work but is less than ideal -->
                  <span><a href="home.html" th:href="@{'/event/delete/'+${event.id}}">edit</a></span>
```

**Comment by gochev** [comment]
it is not because of the `data-th-href` of course ;) I tried with the html5 not valid way `th:href`  but it also doesn't work.

**Comment by danielfernandez** [comment]
Please note that when using URL variables, you should provide a value for them as a parameter to the link expression. So note how in:

``` html
<a href="details.html" th:href="@{/order/{orderId}/details(orderId=${o.id})}">view</a>
```

...the `{orderId}` variable is given a value as a parameter: `(orderId=${o.id})`.

If you want to simply append your variable without the need for appending it, you could use _literal substitutions_ (`|...|`), like:

``` html
<a href="home.html" data-th-href="@{|/event/delete/${event.id}|}">
```

By the way, the _Using Thymeleaf_ tutorial is not yet updated to 3.0, even if we have a work-in-progress version at the URL you point to. But please do not consider that tutorial _updated_ to 3.0. In fact, it shouldn't be linked anywhere on the website... did you get the link from thymeleaf.org?

**Comment by vignesh-vnix** [comment]
@danielfernandez Thanks a lot
