### ISSUE TITLE
How do I configure thymeleaf 3.0 with springMVC through xml?

### ISSUE THREAD

**Issue by sify21** [thymeleaf/thymeleaf#516]
I know it can be configured through java code, but I prefer the xml way. The official doc isn't updated, can you tell me how to do that?

**Comment by jmiguelsamper** [comment]
Hello, 

you can find examples at the end of the Migration Guide at http://www.thymeleaf.org/doc/articles/thymeleaf3migration.html

**Comment by sify21** [comment]
Thank you, it seems that I only need to change ServletContextTemplateResolver to SpringResourceTemplateResolver
