### ISSUE TITLE
Modify template modes amd add "Text" template mode

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#52]
In order to being able to process non-HTML email templates or maybe some other kinds of templates, it could be useful to add a  `"Text"` template mode that:
- Considers the entire template to be a Text node.
- Applies text inlining by default.

**Comment by danielfernandez** [comment]
When this is done, `org.thymeleaf.util.TemplateModeUtil` should be modified. See also this: https://github.com/thymeleaf/thymeleaf/issues/167

**Comment by jmiguelsamper** [comment]
As there are 3 possible values for the th:inline processor, maybe there should be 3 "text template modes", TEXT, JAVASCRIPT, DART.

**Comment by danielfernandez** [comment]
Given 3.0 will completely revamp the parsing and DOM system, it will be a much more reasonable point to modify the template mode system than 2.1. So this ticket has been moved to 3.0.

In fact, given the flexibility given by the new parser to be used in 3.0 (attoparser), we should study the possibility to establish only two template modes:
- Markup
- Text (which should not only be allowed to use on its own, but also enabled when `th:inline="text"`)

**Note 1**: Would _Markup_ be enough for HTML and XML? if not... should we drop the XML support altogether?
**Note 2**: Processors should be made available for **either** Markup **or** Text, or maybe both. For example, all HTML-attribute based thymeleaf attributes like `th:src`, `th:ref`, etc. would make no sense in _Text_. But `th:each` would.
**Note 3**: Syntax for _Text_ mode should be well integrated with (or be the same as) the syntax finally developed for #68 and maybe also #47.

**Comment by danielfernandez** [comment]
Developed as a part of the new Thymeleaf 3.0 architecture and template modes. See #391 and #395

**Comment by danielfernandez** [comment]
Already in `3.0.0-SNAPSHOT`
