### ISSUE TITLE
Script containing html not correctly processed

### ISSUE THREAD

**Issue by sorayasl** [thymeleaf/thymeleaf#522]
I'm migrating from thymeleaf 2.1.2 to 3.0.0 but have found a piece of code in a template which does not work due to thymeleaf not interpreting properly an script containing html (I'm usign it as a template for jquery-tmpl plugin).

Script containing html (used as a fragment): 

```
<script id="menuItemTemplate" type="text/x-jquery-tmpl"  th:fragment="menutmpl">  
        <div>
            <table border="0" cellpadding="0" cellspacing="0" width="236">
                <tr class="menuOption">
                    <td width="26" align="center" height="20">
                        {{if !url || url == "#"}}
                        <a href="#" 
                            onclick="javascript:showSwitch('${id}', 'minus${id}', 'plus${id}');return false;">
                            <img border="0" th:src="@{/images/bot_mas_02.gif}"
                                id="plus${id}" 
                                width="9" height="9" />
                            <img border="0" th:src="@{/images/bot_menos_02.gif}" 
                                id="minus${id}"
                                width="9" height="9" style="display: none;" />
                        </a>
                        {{/if}}
                    </td>
                    <td align="left" width="210" height="20">
                        <a class="grisb" href="${url}" 
                            onclick="javascript:showSwitch('${id}', 'minus${id}', 'plus${id}');return false;"
                            title="{{if descriptionEN}} ${descriptionEN}{{/if}}">
                            <span>${firstLevelNameEN}</span>
                        </a>
                    </td>
                </tr>
            </table>            
      </div>  
    </script>
```

The fragment above is being added to a template by means of:
`<script th:replace="layout/menu :: menutmpl"></script>`

Although the output is just:
`<script id="menuItemTemplate" type="text/x-jquery-tmpl">`  

That is, it is ending script output too early and starting with the next element in the template.

**Comment by danielfernandez** [comment]
Note this only happens when the fragment `<script>` lives inside the `<head>` element of the container template. 

The reason for this is that AttoParser is not considering this `<script>` as mere `CDATA` because it is a template, and therefore it's parsing its contents. And when it finds `<div>`, which is a body-only block element (in normal conditions), it auto-closes the `<head>`. And before auto-closing the `<head>`, it auto-closes the `<script>` too.

**Comment by danielfernandez** [comment]
Already in `3.0.2-SNAPSHOT`
