### ISSUE TITLE
spring boot combine thymeleaf cannot include css/js

### ISSUE THREAD

**Issue by szhupeng** [thymeleaf/thymeleaf#526]
I use spring boot and thymeleaf to build a project,but the css/js file include in html cannot load;
error:
Failed to load resource: the server responded with a status of 405 ()

**Comment by danielfernandez** [comment]
HTTP 405 is a `Method not allowed` error, so it seems there is something in the configuration of your Spring Boot app that prevents the use of one of the HTTP methods (`GET`, `POST`, `PUT`, etc.) you are using for loading some of your resources, or calling some of your APIs. This does not seem to have a relation to Thymeleaf.
