### ISSUE TITLE
Improve handling of Jackson initialisation errors fix don't take effect when an Error was thrown

### ISSUE THREAD

**Issue by anschnapp** [thymeleaf/thymeleaf#530]
Hi, 

i get an error on jackson initialization. (Thymeleaf Version 3.0.1.RELEASE)

My environment contains an old jackson library which i can't easily update.

I have seen you already have a ticket for jackson initialization problems

Related Ticket
https://github.com/thymeleaf/thymeleaf/issues/520

Related commit with fix
https://github.com/thymeleaf/thymeleaf/commit/69724d1db9c55ae95068fda7f73a609cdf9c7f35

Sadly the fix don't catch the exception which i get on the jackson initialization. I get an NoSuchMethodError on initialization which is from type Error. That's the reason why the catch(Exception...) {...} block will is not executed and therefore i have still a serious problem.

I would suggest to add at least NoSuchMethodError to the catch block. In a related post of this issue has there was also a NoSuchMethodError which occurs.
https://github.com/thymeleaf/thymeleaf-spring/issues/116

If you are fine with the suggested solution i can create a fix and a PR on my own if you like.

**Comment by anschnapp** [comment]
i have created a pull request with a fix which works inside my application

**Comment by danielfernandez** [comment]
Already in `3.0.2-SNAPSHOT`
