### ISSUE TITLE
custom IMessageResolver wired by spring is overwritten with default one

### ISSUE THREAD

**Issue by anschnapp** [thymeleaf/thymeleaf#533]
I have a custom IMessageResolver which i have set (with spring) as the message resolver for the SpringTemplateEngine.

But after the spring properties are set the method afterPropertiesSet inside of SpringTemplateEngine is triggered and overwrite the Resolver with a default one.

See this code snippet:

```
public void afterPropertiesSet() throws Exception {
...
if (messageSource != null) {
    final SpringMessageResolver springMessageResolver = new SpringMessageResolver();
    springMessageResolver.setMessageSource(messageSource);
    messageResolver = springMessageResolver;
} else {
    messageResolver = new StandardMessageResolver();
}
super.setMessageResolver(messageResolver);
```

**Comment by danielfernandez** [comment]
This is intended behaviour. The `SpringTemplateEngine` aims at full Spring integration and, as a part of this, message resolution is integrated with Spring's declared `MessageSource` beans, overriding the configurable behaviour present at `TemplateEngine` (which it extends). 

Actually, all it basically does is setting the `SpringStandardDialect` and setting the message resolution as you explain. It's just a utility class for Spring auto-configuration.

If you need to integrate only partially with Spring's infrastructure, I recommend you use `TemplateEngine` instead, and simply set the dialect to be `SpringStandardDialect` (and then set your own message resolution infrastructure).

**Comment by anschnapp** [comment]
Thanks for your info! I thought spring template engine is a must for working with spring and is highly customizable, maybe i should have take a deeper look in the javadocs... ;)
