### ISSUE TITLE
Fragment parameter validation not parametersAreSynthetic pattern.

### ISSUE THREAD

**Issue by naokism** [thymeleaf/thymeleaf#534]
Hi,

I think don't need this code.
Because , when it has many fragment parameters , I have to write much.
But Thymeleaf can write name based parameters.

I want to write only parameters required .

FragmentSignatureUtils#processParameters

``` java
        final List<String> parameterNames = fragmentSignature.getParameterNames();
        for (final String parameterName : parameterNames) {
            if (!specifiedParameters.containsKey(parameterName)) {
                throw new TemplateProcessingException(
                        "Cannot resolve fragment. Signature \"" + fragmentSignature.getStringRepresentation() +  "\" " +
                                "declares parameter \"" + parameterName + "\", which is not specified at the fragment " +
                                "selection.");
            }
        }
```

Thank you for your consideration.

**Comment by danielfernandez** [comment]
Sorry, could you elaborate a bit? I don't think I fully understand your issue…

If you want to specify less arguments than present in a fragment signature, reduce your fragment signature to include only the required ones, then call it with as many (named) parameters as you want. Only the ones present at the signature will be checked, as explained in a code comment just above the piece of code you pasted: https://github.com/thymeleaf/thymeleaf/blob/57bfde327bef60ce7c41dd72cdf67d80268afa4f/src/main/java/org/thymeleaf/standard/expression/FragmentSignatureUtils.java#L211-L213

**Comment by naokism** [comment]
I apologize if the explanation was hard to understand.

I am creating a common component. 

for example.
/component/textfield.html

``` html
<th:block th:fragment="textfield(name, defaulfValue , placeholder , customParameter1 , customParamter2)">
    <input type="text" class="form-control" th:name="${name}" th:placeholder="${placeholder}" th:value="${defaultValue}" c:param1="${customParameter1}" c:param2="${customParameter2}" >
</th:block>
```

This component has 5 pamameters.
I want use 3 parameters of these. However, this pattern will result in an error . ( call parameters < signature parameters)
I think this case may be permitted when dialect implement a null check.

``` html
<div th:include="~{/component/textfield :: textfield(name='loginId', placeholder='example',customParamter1='custom1') }"></div>
```

**Comment by danielfernandez** [comment]
I'm afraid that is actually the intent of the fragment specification signature: to work like a Java method call. So arguments specified there are required, just like in Java code.

Non-required attributes should not appear at the signature.

Thanks a lot for your comments. I'm closing this for now, please reopen if you find any issues with this approach.
