### ISSUE TITLE
Map multiple HTML files to single decoupled templates

### ISSUE THREAD

**Issue by alexaylwin** [thymeleaf/thymeleaf#537]
Hi there, this is a question regarding how to map more than one presentation template to a decoupled logic template. I have the following files for my templates:
- HtmlTemplate1.html
- HtmlTemplate2.html
- HtmlTemplate.th.xml

When the view is returned from a controller method (HtmlTemplate1 or HtmlTemplate2), I would like both to read HtmlTemplate.th.xml as the decoupled logic file. Does the StandardDecoupledTemplateLogicResolver provided by Thymeleaf support this, or do you suggest I create a new IDecoupledTemplateLogicResolver to implement this feature? An example where this would be used is adaptive web design, where I want to deliver different markup by device type.

**Comment by danielfernandez** [comment]
I'm afraid `StandardDecoupledTemplateLogicResolver` does not offer this, as it bases its search for _decoupled logic_ files in the names of the original templates (plus a suffix and/or a prefix). So it would always look for two different files in your case.

So yes, I think you should provide your own implementation to the `IDecoupledTemplateLogicResolver` interface in this case. Which should be easy to do, as it is a very simple interface...

**Comment by alexaylwin** [comment]
Thank you, I've extended it for my purposes.
