### ISSUE TITLE
Update ognl

### ISSUE THREAD

**Issue by Assumeru** [thymeleaf/thymeleaf#538]
I ran into an issue with varargs parameters using 3.0.1.RELEASE where ognl would select the wrong method out of:

```
public String format(String format)
public String format(String format, Object... args)
```

Using an expression like this:
`<p th:text="${obj.format('Hello world')}"></p>`

ognl attempts to use the second method and then proceeds to throw an ArrayIndexOutOfBoundsException because it's missing arguments.

After reducing the problem to a simple ognl call, I found the problem does not occur using ognl 3.1.10 (the latest version I found).

```
public static void main(String[] args) {
    Map<Object, Object> context = new HashMap<>();
    context.put("obj", new Variable());
    try {
        Object val = Ognl.getValue("obj.format('Hello world')", context, context);
        System.out.println(val);
    } catch (OgnlException e) {
        e.printStackTrace();
    }
}
```

I created a little Spring project that showcases the issue at https://github.com/Assumeru/thymeleaf-varargs
**Note:** that project uses SpEL by default. Uncomment line 36 in VarArgsConfig to use the standard dialect.

**Comment by danielfernandez** [comment]
Updated to OGNL 3.1.10. Actually, updating to a version of OGNL >= 3.1.5 was a pending task that would allow us get rid of a direct dependency on the Javassist library.

And given OGNL 3.1.10 depends on Javassist 3.20.0-GA, which is the minimal version we needed (older versions of Javassist didn't work well with Java 8), this change allows us to not even have to manage the dependency.

All tests pass with the new version of OGNL.

**Comment by danielfernandez** [comment]
Already in `3.0.2-SNAPSHOT`

**Comment by Assumeru** [comment]
Well that was quick. Awesome.
