### ISSUE TITLE
Thymeleaf 3 fails to parse JavaScript string containing start of comment

### ISSUE THREAD

**Issue by cplaetzinger** [thymeleaf/thymeleaf#541]
The following template code works fine in Thymeleaf 2.x but fails in 3.x
`<script th:inline="javascript">
        var options = {acceptedFiles: 'image/*'};
    </script>`

From the logs:
[thymeleaf_3.x_parseerror.txt](https://github.com/thymeleaf/thymeleaf/files/513312/thymeleaf_3.x_parseerror.txt)

**Comment by danielfernandez** [comment]
Confirmed, thanks. It seems `TextParser` is not taking literals into account when looking for comment opening/closing delimiters.

**Comment by danielfernandez** [comment]
Already in `3.0.3-SNAPSHOT`
