### ISSUE TITLE
Thymeleaf 3 rendering issue when having empty HTML comment in template

### ISSUE THREAD

**Issue by damienbeaufils** [thymeleaf/thymeleaf#542]
Hello,

I am migrating my web application from Thymeleaf 2.x to 3.0.2, and I encountered a strange issue with one of my templates: there was an empty HTML comment (**`<!---->`**) inside a fragment template and it was preventing the whole block and blocks after to be rendered correctly, like if the closing tag was not properly rendered.

I try to add this `<!---->` line inside differents fragments, and sometimes I had a `ParseException`, but sometimes not (no log or any exception thrown). So it just breaks fragments inside a template silently.

If I put just a space or any character between `<!--` and `-->`, it works fine. The issue is only when having this specific empty HTML comment `<!---->` inside a template.

Let me know if I can provide you any additional information.

Thank you for all you work on this framework!

**Comment by danielfernandez** [comment]
Thanks. Confirmed. This is an issue at the AttoParser side: attoparser/attoparser#14

Thymeleaf `3.0.3-SNAPSHOT` will update its dependency to `org.attoparser:attoparser:2.0.2-SNAPSHOT`, and a fixed AttoParser 2.0.2 version should be used in Thymeleaf 3.0.3.

**Comment by danielfernandez** [comment]
Already in `3.0.3-SNAPSHOT`
