### ISSUE TITLE
After fixes #438 and #377 the two argument sequence method should be adjusted for reverse sequences

### ISSUE THREAD

**Issue by PawelJagus** [thymeleaf/thymeleaf#544]
After fixes #377 and its port #438 all the reverse sequences done with the two argument version of NumberUtils.sequence method are broken. This method should be adjusted with a check if from > to then sequence(from, to, Integer.valueOf(-1)).

It is a pity that such a thing does not have a unit test.

**Comment by danielfernandez** [comment]
Confirmed. As you explain, the issue is `NumberUtils.sequence(from,to)` is always sending `1` as `step`, instead of checking if it has to send `-1` instead.

Workaround is to use the 3-arg version and manually specify a negative step of `-1`, like `#numbers.sequence(4, 1, -1)`

**Comment by danielfernandez** [comment]
Already in `3.0.3-SNAPSHOT`
