### ISSUE TITLE
Output text is changed(Thymeleaf3)

### ISSUE THREAD

**Issue by yKazihara** [thymeleaf/thymeleaf#546]
After I upgraded from 2 to 3, output text is changed.

```
public class Page {
  public String code;
}

```

```
public class SampleAction {
  ...
  Page page = new Page();
  page.code = "APPLE";
  ...
}
```

`<span th:text="${it.code}">ORANGE</span>`

・Thymeleaf 2.1.4.RELEASE
　APPLE // OK

・Thymeleaf 3.0.2.RELEASE
　701259 // hashCode?

Could you tell me why the output is changed?

**Comment by danielfernandez** [comment]
Nothing should have changed in your case. Are you completely sure that your expression in the second case includes the `.code` part? 

Also,  what is the environment? Are you using thymeleaf in a Spring app?

**Comment by yKazihara** [comment]
I don't use  thymeleaf in a Spring app.

I wrote another sample.
This Junit test was successful.

```
import static org.hamcrest.CoreMatchers.*;
import static org.hamcrest.MatcherAssert.*;

import org.junit.Test;
import org.thymeleaf.TemplateEngine;
import org.thymeleaf.context.Context;

public class Sample {

  public static class Page {
    public String name = "orange";
    public String code = "apple";
  }

  @Test
  public void test() {
    TemplateEngine engine = new TemplateEngine();

    Page page = new Page();
    Context context = new Context();
    context.setVariable("p", page);

    assertThat(engine.process("[[${p.name}]]", context), is("orange"));

    assertThat(engine.process("[[${p.code}]]", context), is(not("apple")));
    assertThat(engine.process("[[${p.code}]]", context),
        is(Integer.toString(page.hashCode())));
  }
}
```

**Comment by danielfernandez** [comment]
This is actually a bug in the OGNL expression language. OGNL is the expression language being used by Thymeleaf in non-Spring applications.  See jkuhnert/ognl#32

I'm leaving this open in order to update Thymeleaf's dependency to a future version of OGNL that might fix this.

**Comment by danielfernandez** [comment]
OGNL 3.1.12 released and Thymeleaf's 3.0 branch updated to use it.

**Comment by danielfernandez** [comment]
Already in `3.0.3-SNAPSHOT`

**Comment by yKazihara** [comment]
Thank you!
