### ISSUE TITLE
Javascript parsing issue for [[ ]]

### ISSUE THREAD

**Issue by ccit-spence** [thymeleaf/thymeleaf#548]
Thymeleaf Version: 3.0.0.RELEASE
Thymeleaf  Layout Dialect Version: 2.0.0
Spring Boot: 1.4.1.RELEASE

I have the following setup using the jQuery version of Datatables.

```
    <script th:inline="javascript">
        /*<![CDATA[*/
        $(document).ready(function() {
            $('#dataTables-example').DataTable({
                "responsive": true,
                "order": [[ 2, 'asc' ]],
                "columns": [
                    {"orderable": false,"searchable": false},
                    null,
                    null
                ]
            });
        });
        /*]]>*/
    </script>
```

The `"order": [[ 2, 'asc' ]],` is causing a 500 error.

**Comment by danielfernandez** [comment]
`[[...]]` is the expected envelope for inlined output expressions, which in this case `2, 'asc'` isn't.

The way to avoid Thymeleaf thinking this is an inlined expression and at the same time let your JS work just the same is to simply add a whitespace char between the brackets: `[ [2, 'asc'] ]`.

**Comment by ccit-spence** [comment]
That did the trick.  Thanks for the quick response.

**Comment by joshiste** [comment]
@danielfernandez is it possible to reconfigure the expected envelope for inlined output expressions?

**Comment by danielfernandez** [comment]
@joshiste no, it isn't. This is part of the core syntax of the text-based template modes.
