### ISSUE TITLE
Update doc links in the Standard-Dialect.xml definition file

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#555]
The `Standard-Dialect.xml` file used for IDE metadata still links all the dialect attributes to the Thymeleaf 2.1-version of the tutorials.

@ultraq could you take care of this please?

**Comment by ultraq** [comment]
Huh, well that was easy enough.  Since all of our titles stayed the same, I just had to replace the 2.1 with 3.0 in the URL and it all led to the right place.  Hopefully the Spring one is just as easy to do.
