### ISSUE TITLE
json conversion of java 8 localdatetime

### ISSUE THREAD

**Issue by taypo** [thymeleaf/thymeleaf#559]
When using javascript inlining, java 8 localdatetime types are serialized as follows:

`
"end":{
  "hour":22,
  "minute":27,
  "second":51,
  "nano":302000000,
  "dayOfYear":347,
  "dayOfWeek":"MONDAY",
  "month":"DECEMBER",
  "dayOfMonth":12,
  "year":2016,
  "monthValue":12,
  "chronology":{
    "id":"ISO",
    "calendarType":"iso8601"
  }
}
`

A similar problem with spring rest controllers are fixed with the following property
`spring.jackson.serialization.write-dates-as-timestamps=false`
and `jackson-datatype-jsr310`dependency.

Is there are solution for javascript inlined object serialization of thymeleaf?

Thanks

**Comment by danielfernandez** [comment]
Just for clarification: what version of Thymeleaf are we talking about? In Thymeleaf 3.0, if Jackson is present at the classpath it will be used for JS serialization… is this happening to you letting Thymeleaf delegate to Jackson in v3.0?

**Comment by taypo** [comment]
+--- org.springframework.boot:spring-boot-starter-thymeleaf: -> 1.4.2.RELEASE
|    +--- org.thymeleaf:thymeleaf-spring4:2.1.5.RELEASE -> 3.0.2.RELEASE
|    |    +--- org.thymeleaf:thymeleaf:3.0.2.RELEASE

I'm not sure about the delegation, or if `write-dates-as-timestamps` would effect the serialization from thymeleaf. I only mentioned it beacuse it fixed a similar problem of spring web mvc rest controllers.

**Comment by danielfernandez** [comment]
Please note that direct (yet optional) support for the serialisation of JSR310 artifacts has been added by means of #562
