### ISSUE TITLE
Create multi-element blocks with comments

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#56]
Currently, there is no way in Thymeleaf's Standar Dialects to specify a processor to be applied on a set of elements instead of a specific one.

For example, an iteration cannot be applied on _two tr's_ instead of just one. Which means some sort of interfaces cannot be created with thymeleaf unless we write invalid code like this:

```
<table>
  <tbody>
    <span th:each="p : ${products}" th:remove="tag">
      <tr><td>...</td></tr>
      <tr><td>...</td></tr>
    </span>
  </tbody>
</table>
```

The solution for this would be to add the possibility to specify _processable attributes_ in comments, which would be correctly processed by the parser and then turned into a new kind of _grouping node_, containing the specified attributes.

This would allow us to create valid prototyping code:

```
<table>
  <tbody>
    <!--BEGIN_BLOCK th:each="p : ${products}"  -->
      <tr><td>...</td></tr>
      <tr><td>...</td></tr>
    <!--END_BLOCK-->
  </tbody>
</table>
```

These block/group nodes would be simply ignored at output (if they have no attributes left).

**Comment by Infeligo** [comment]
I just ran into similar issue. I needed to iterate over 3 nested collections and display it as table data. That is, collection1 children were collection2 and collection2 chidlren were collection3. And it is collection3 children that I had to display as rows. If there were 2 collections, I could iterate over collection1 using `<tbody>` and collection2 over `<tr>`, but in case of 3 collections there's no valid solution.

**Comment by jirubio** [comment]
+1 for nested loops.
I needed to use the workround th:remove="tag" to accomplish this, wich is ugly and creates invalid markup.
Other alternative is to allow multiple th:each on a node.
Example:

```
<tr th:each="result : ${alignedMap}" th:each="desc : ${result.value}">
```

The result variable from the first loop is used for the second.
I think this syntax is nicer than introducing a fake comment.

**Comment by danielfernandez** [comment]
This is covered by the combination of #185 and #182.
