### ISSUE TITLE
Textual template modes closing tag broken in 3.0.3

### ISSUE THREAD

**Issue by yglodt** [thymeleaf/thymeleaf#563]
The following code inside a _<script type="text/javascript" th:inline="javascript">_ block stopped working with 3.0.3:
```
/*[# th:if="${user.admin}"]*/
    alert('Welcome admin');
/*[/]*/
```
In fact the closing tag leaves a stale
```
*/
```
which the JavaScript parser does not like.

In 3.0.2 it works.

**Comment by danielfernandez** [comment]
This works for me… let's see if we can find the difference in environment.
  - Please check that you are including version `2.0.2.RELEASE` of AttoParser in your classpath (if you are using Maven, Thymeleaf 3.0.3 should automatically ask for that version, but just in case).
  - Are you configuring in your template engine any other dialects besides the *SpringStandard* one?

**Comment by yglodt** [comment]
Yes it picks up version 2.0.2 of AttoParser. If I go back to Thymeleaf 3.0.2, AttoParser also goes back to 2.0.1.

Spring Boot autoconfigures Thymeleaf in my case, and adds the Spring Security dialect probably.

In application.properties I have:
```
spring.thymeleaf.cache=false
spring.thymeleaf.mode=HTML
```

What I did change is the versions and some additional dependencies:
```
	<properties>
		<thymeleaf.version>3.0.3.RELEASE</thymeleaf.version>
		<thymeleaf-layout-dialect.version>2.1.2</thymeleaf-layout-dialect.version>
	</properties>

        ...

	<dependency>
		<groupId>org.thymeleaf.extras</groupId>
		<artifactId>thymeleaf-extras-springsecurity4</artifactId>
		<version>3.0.1.RELEASE</version>
	</dependency>

	<dependency>
		<groupId>org.thymeleaf.extras</groupId>
		<artifactId>thymeleaf-extras-java8time</artifactId>
		<version>3.0.0.RELEASE</version>
	</dependency>
```

And I added an extra Bean:

```
	@Bean
	public UrlTemplateResolver urlTemplateResolver() {
		final UrlTemplateResolver urlTemplateResolver = new UrlTemplateResolver();
		urlTemplateResolver.setOrder(20);
		return urlTemplateResolver;
	}
```

```
```

**Comment by danielfernandez** [comment]
This is very strange… I've configured a Spring Boot 1.4.3 application with Thymeleaf 3.0.3 and exactly those four dialects (SpringStandard, SpringSecurity, Layout, Java8Time) in the same versions, and a `<script>` fragment containing your code, and I'm still unable to reproduce this. It works OK 100% of the times for me.

I need more info still: that fragment of JavaScript… is it all you have in your `<script>`? is there more JavaScript code before or after it? maybe some of that code contains the `/*` sequence inside a JavaScript literal or something similar?

It would be great if you could share your entire `<script>` but, if not, any additional data you give me should help. Or maybe try and remove some fragments of your script and see if you still experience this issue…

**Comment by yglodt** [comment]
Since I am not able to disclose the complete code, please check your Twitter private messages, there I sent you more information.

**Comment by yglodt** [comment]
Thanks!

**Comment by danielfernandez** [comment]
Confirmed and fixed.

This was actually caused by a quite complex interaction –and quite a large amount of bad luck :(–. As it happens, the textual parser uses buffers for parsing the textual structures (like e.g. the contents of inlined `<script>` tags) which size starts at 2Kbytes, and can grow during parsing if needed.

The problem however appeared when, during parsing, the parser ended the scanning of the whole 2048 bytes without finding a relevant structure to handle inside it, and at the end of the buffer it had found a text literal (`"..."` or `'...'`) which wasn't closed before the buffer ended. In such cases, this caused a sequence of bad state transitions at the parser which ended up with things like your strange `*/` hanging there without a reason.

So something strange, but indeed a bug. Now fixed.

**Comment by danielfernandez** [comment]
Already in `3.0.4-SNAPSHOT`

**Comment by wiecia** [comment]
I have the same issue. Unfortunately this is showstopper as i cannot upgrade my production neither with 3.0.3 with this bug nor with a snapshot. I need to revert to 3.0.2 for the time 3.0.4 is released. Glad you found and fixed that though
