### ISSUE TITLE
Proposal for extending th:attr support

### ISSUE THREAD

**Issue by arne-vandamme** [thymeleaf/thymeleaf#564]
This is not really a bug or issue but more of an idea to extend the behaviour of **th:attr**.
It might be handy if you could for example do **th:attr-href** or **th:attr-data-url**.  This would allow you to use dynamic attributes in more straightforward way, and you could repeat attributes on the same element.  I think it would improve readability over the current *th:attr* with a comma separated syntax.

I know most html attributes already have their own processor but this could definitely help in a context where you are using custom/non-data attributes.  Perhaps even more useful when processing regular xml?

Because *th:attr* is often used for conditional adding of attribute, a `null` value could signify not to add the attribute.

This approach should be sufficient for any attribute name but the prefixed ones (for which regular use would still suffice).  Or a some kind of replacement mechanism could be used, eg: `th:attr-xlink--href="@{url}"` would result in `xlink:href="/url"`.

I think this functionality could probably be added in a backward compatible way with only a minor performance impact?

As a sidenote, it could be a useful addition to extend the `AbstractAttributeTagProcessor` to support attributes names "starting with" instead of "equals".

**Comment by danielfernandez** [comment]
Thanks for your comments.

As for setting *any* attribute in a similar way to what you explain, note that Thymeleaf 3.0 has out-of-the-box support for this via the *default attribute processor*. See http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#setting-the-value-of-any-attribute-default-attribute-processor

As for repeating attributes in an element, though, note this is forbidden by both the XML and HTML5 specifications :)

**Comment by arne-vandamme** [comment]
Waw, even though I actually went looking for that functionality in the 3.0 documentation, I managed to miss it.  That basically does exactly what I proposed.

My text must not have been clear enough, but I never suggested actually meant to suggest repeating the _same_ attribute on an element.  No matter, you had already thought of the solution :-)

Thanks for your feedback & speedy reply !
