### ISSUE TITLE
Custom element name of the form {prefix}- causes parser error

### ISSUE THREAD

**Issue by prushforth** [thymeleaf/thymeleaf#570]
The specific message is "Element name cannot be null".   Can you suggest a workaround to create a custom element of that form, perhaps?

Thank you!

**Comment by danielfernandez** [comment]
If I understand correctly, what you want to create is an HTML/XML element that has no name, but has a prefix/namespace? If that's so, I'm afraid that would not be allowed (neither by Thymeleaf nor the HTML or XML specs).

Could you please add a bit more detail about why you specifically need something like that (and what version of Thymeleaf you are using)? there might be other ways…

**Comment by prushforth** [comment]
I have created a custom element called &lt;layer-&gt;&lt;/layer-&gt;, which is allowed per the custom element specification (at least I believe it is, I will double check).  When I try to put this element in my template, I get the parser error mentioned (in the exception).  If I put &lt;layer-foo&gt;&lt;/layer-foo&gt; I have no problem.

Double check: the [Custom Elements spec](https://www.w3.org/TR/custom-elements/) allows empty suffixes- here's the beginning  production:  [a-z] (PCENChar)* '-' (PCENChar)*

I am using Thymeleaf 3.0.3 with Spring 4.3.4.

Does that clarify?  Thank you.

**Comment by danielfernandez** [comment]
Oops yes, you are very right! It seems that asterisk there was missed when specifying how AttoParser should behave before this.

I've added a ticket at AttoParser, as this is the parser's responsibility. Thanks!

**Comment by prushforth** [comment]
Thank you!

**Comment by danielfernandez** [comment]
Re-labelled as a *problem*. Not an AttoParser issue, but Thymeleaf's own. There is a check at `HTMLElementName` which turns no-suffix element names into `null`, which is not allowed by the `ElementDefinition` mechanism. It seems turning these `null`s into empty strings should suffice, as is also done at the `TEXT` template modes for `[# ...]` elements.

**Comment by danielfernandez** [comment]
Already in `3.0.4-SNAPSHOT`

**Comment by prushforth** [comment]
Thank you very much for your help!  I will use the snapshot version for now.  Cheers!

**Comment by prushforth** [comment]
Ok the fix works for me, thank you and  I apologize for reporting that on a Friday afternoon.  Bon weekend!
