### ISSUE TITLE
Incorrect output in natural javascript template

### ISSUE THREAD

**Issue by gigermocas** [thymeleaf/thymeleaf#576]
[thymtester.zip](https://github.com/thymeleaf/thymeleaf/files/810610/thymtester.zip)

Moving one of my applications from 3.0.2 to 3.0.3 some pages stopped working, found that there were a problem with natural javascript templates, namely inline expressions:
The code:
`url: /*[[@{/data/mntagent/jobs/{jobId}/executions.json(jobId=${'1'})}]]*/ "/data/mntagent/jobs/{jobId}/executions.json"`
was being generated into
`url: /*"/data/mntagent/jobs/1/executions.json"*/ "/data/mntagent/jobs/{jobId}/executions.json"`
and not
`url: "/data/mntagent/jobs/1/executions.json"`
as intended

This does not happen in all cases, found that the amount of javascript code (ie, number of characters) influences the result, I attached a test case with the situation.

**Comment by danielfernandez** [comment]
This looks the same as #563 to me. Could you please check that this is fixed for you in `3.0.4-SNAPSHOT`?

**Comment by gigermocas** [comment]
Indeed it is, sorry I missed that
