### ISSUE TITLE
HTML email send from thymeleaf shows as plain text in email client

### ISSUE THREAD

**Issue by jiangchuan1220** [thymeleaf/thymeleaf#582]
My scenario is to send email from spring boot app using thymeleaf as template. The SMTP server is on Amazon. Currently I can send email from app with template and receive them in email client(Gmail).
The issue is when I try to use inlineimage template, which is html email, I received the email as plain text in Gmail as is shown below. How to make the email shown as html format?

![2](https://cloud.githubusercontent.com/assets/8613170/24206539/ccf19720-0f1e-11e7-9932-cef9bb3b5fec.png)

Thanks.

**Comment by destan** [comment]
if you could send your code we can provide more help. Are you sure that you set correct content type?

be sure you are using `setContent` instead of `setText`. See http://docs.oracle.com/javaee/6/api/javax/mail/internet/MimeMessage.html#setContent(java.lang.Object, java.lang.String)

```java
Message msg = new MimeMessage(session);
...
message.setContent("<h1>HTML content</h1>", "text/html");
```

**Comment by danielfernandez** [comment]
Note there is an article devoted to sending email with Spring and Thymeleaf, and a complete example application: http://www.thymeleaf.org/doc/articles/springmail.html and https://github.com/thymeleaf/thymeleafexamples-springmail

Even if the article and sample code use Spring, the basics on how email is handled will probably be useful to you. Most probably your issue is just a matter of setting the right content-type for the section of your multipart email that contains the HTML content.

**Comment by jiangchuan1220** [comment]
@destan , it is great. I used your solution, and it works well now. 
Also many thanks to @danielfernandez .

**Comment by jiangchuan1220** [comment]
I have another question when sending HTML email with attachments. My code is as follows:
````
            MimeMessage message = emailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);
            helper.setFrom(from);
            helper.setTo(to);
            helper.setSubject(subject);  
            FileSystemResource file = new FileSystemResource(new File(pathToAttachment));
            helper.addAttachment("Invoice", file);
            String content= mailContentBuilder.build(text, from); 
            message.setContent(content, "text/html");
            emailSender.send(message);
`````
In the email receiver, the email is shown as html but the attachment is not received.
If I delete the code:
````
message.setContent(content, "text/html");
````
The attachment can be received but the email is shown as plain text.
Which content type should I use in this situation?

**Comment by jiangchuan1220** [comment]
For the question above, I find that Multipart type is needed for html email with attachment. My code is as follows:
````
                        MimeMessage message = emailSender.createMimeMessage();
			MimeMessageHelper helper = new MimeMessageHelper(message, true);
			helper.setFrom(from);
			helper.setTo(to);
			helper.setSubject(subject);
			String content = mailContentBuilder.build(text, from);
			Multipart multipart = new MimeMultipart(); 
			// Create the attachment part
			BodyPart attachmentBodyPart = new MimeBodyPart();
			DataSource source = new FileDataSource(pathToAttachment);
			attachmentBodyPart.setDataHandler(new DataHandler(source));
			attachmentBodyPart.setFileName(new File(pathToAttachment).getName());
			multipart.addBodyPart(attachmentBodyPart);
			// Create the HTML Part
			BodyPart htmlBodyPart = new MimeBodyPart();
			htmlBodyPart.setContent(content, "text/html");
			multipart.addBodyPart(htmlBodyPart); // 6
			// Set the Multipart's to be the email's content
			message.setContent(multipart); 
			emailSender.send(message);
````

**Comment by destan** [comment]
Hi @jiangchuan1220 I'm glad my answer helped you. However I believe your second question belongs to places like stackoverflow since it's not relating to Thymeleaf.
