### ISSUE TITLE
Spring Boot Thymeleaf Layout Dialect Not Working

### ISSUE THREAD

**Issue by tianmingxing** [thymeleaf/thymeleaf#590]
My environment info:

software|version
------------ | -------------
spring boot|1.5.2.RELEASE
spring-boot-starter-thymeleaf|1.5.2.RELEASE
thymeleaf-layout-dialect|2.2.1&1.2.9

I found that the layout was not applied as instructed in the [documentation] (https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#template-layout).

I found that other people have the same [trouble](http://stackoverflow.com/questions/42029024/spring-boot-thymeleaf-layout-dialect-not-working) with me，at stackoverflow.

**Comment by danielfernandez** [comment]
Please note that the Layout Dialect is not a part of the Thymeleaf project. You should probably report your issue at https://github.com/ultraq/thymeleaf-layout-dialect

**Comment by day781227** [comment]
<thymeleaf.version>3.0.8.RELEASE</thymeleaf.version>
        <thymeleaf-layout-dialect.version>2.2.2</thymeleaf-layout-dialect.version>

try to add this.

**Comment by dmbuchta** [comment]
As another work around, add upgrade the version in your pom.xml
```        
    <dependency>
            <groupId>nz.net.ultraq.thymeleaf</groupId>
            <artifactId>thymeleaf-layout-dialect</artifactId>
            <version>2.3.0</version>
     </dependency>
```

**Comment by git-JaforIqbal** [comment]
> As another work around, add upgrade the version in your pom.xml
> 
> ```
>     <dependency>
>             <groupId>nz.net.ultraq.thymeleaf</groupId>
>             <artifactId>thymeleaf-layout-dialect</artifactId>
>             <version>2.3.0</version>
>      </dependency>
> ```

It works, thank you
