### ISSUE TITLE
How to call a static method ??

### ISSUE THREAD

**Issue by leavesgreen** [thymeleaf/thymeleaf#593]
For some reason , I want to call a static method in html template , I use the code just like the example:
` <p th:text="${@myapp.translator.Translator@translateToFrench('textVar')}">`
it's an ordinary OGNL expression, but it does not work. I got the error like this:
`org.springframework.expression.spel.SpelParseException: EL1041E:(pos 29): After parsing a valid expression, there is still more data in the expression: 'bean_ref(@)'`
so any help here to resolve the question when I call a static method , and  a method  of  a isntance?

**Comment by leavesgreen** [comment]
anyone can help? so much thanks.

**Comment by danielfernandez** [comment]
If you are using Thymeleaf with Spring, your expression language is not OGNL, but Spring's own (Spring EL or SpEL). You should have a look at the syntax here: https://docs.spring.io/spring/docs/current/spring-framework-reference/html/expressions.html

**Comment by leavesgreen** [comment]
@danielfernandez , thank you , but I am sorry I can't totally get the point. do you mean I can use SpEL in the Thymeleaf template engine?
we use spring-boot and Thymeleaf , I read the link you supplied but I only learn the SpEL is an dynamic expression define language, but how to use it in the html template, it  did not said clearly.
so can you offer me some example of this? thank you so much.

**Comment by saviola777** [comment]
I think you want to use ```T()``` with the full class name, like

```
${T(com.company.package.SomeClass).staticMethod()}
```

**Comment by leavesgreen** [comment]
@saviola777 ,thank you very much, it worked! 
so surprise because i tried last day  as @danielfernandez  said  the same but it did't  work;

**Comment by leavesgreen** [comment]
@saviola777 , can you help me more ?
how can I put a variable on as the static method params?  the variable is defined like this: `model.addAttribute("q",q);`
`<p th:text="${T(utils.ustr).test1(#q)}"></p> ` it indeed call the method , but the params is null.

**Comment by leavesgreen** [comment]
@saviola777 ,Thanks , I finally find the correct way , just write like this. `<p th:text="${T(utils.ustr).test1(q)}"></p>`

**Comment by ZakariaTo** [comment]
How Can i call a non static method in thymleaf ?? 
please help

**Comment by saviola777** [comment]
@MrNobody3 What have you tried so far? It should be as simple as `${obj.method()}` (or `${@bean.method()}` / `${#util.method()}`).

**Comment by ZakariaTo** [comment]
Thanks the first way work, but is it ok to pass a controller in the model attribute .

**Comment by saviola777** [comment]
That sounds like a bad idea, you should probably move your methods out of the controller (e.g., into a service).

**Comment by jonathansanchez** [comment]
@saviola777 how to pass a variable?

**Comment by saviola777** [comment]
What have you tried? It should work simply by including the variable name without anything else.

**Comment by jonathansanchez** [comment]
@saviola777 I tried 
`<th:block th:each="services : ${service}">
See more here: [[${T(com.example.myPackage.ServiceClient).create(${anotherGlobalVar})]]
</th:block>`

**Comment by saviola777** [comment]
No need to surround `anotherGlobalVar` with `${}`, just `[[${T(com.example.myPackage.ServiceClient).create(anotherGlobalVar)]]` should work.

**Comment by jonathansanchez** [comment]
Thanks @saviola777

**Comment by angsuman** [comment]
`[[${T(java.lang.System).currentTimeMillis()}]]` does not work. 
What works is (following OGNL format):
```
[[${@java.lang.System@currentTimeMillis()}]]
```

**Comment by kaibadash** [comment]
```java
[[${T(java.lang.Math).random() * 100}]]
```
works well.

**Comment by starxg** [comment]
```html
<th:block th:text="${@java.lang.System@currentTimeMillis()}"></th:block>
```
works well.

thymeleaf: `3.0.11.RELEASE`

**Comment by ptmxndys** [comment]
You need to use SpringTemplateEngine under thymeleaf-spring for template parsing.
If you do that, the following code will execute properly.
`<div th:text="${T(cn.hutool.core.text.NamingCase).toPascalCase('sys_user')}"></div>`
->
`<div>SysUser</div>`
