### ISSUE TITLE
Constant values in Javadoc for StandardCacheManager do not match implementation

### ISSUE THREAD

**Issue by pgpx** [thymeleaf/thymeleaf#595]
Some of the constant values in StandardCacheManager do not match the values specified in the Javadoc, for example DEFAULT_TEMPLATE_CACHE_INITIAL_SIZE has an actual value of 20, but the Javadoc says 10.

Fix in the PR is just to use {@value ...} Javadoc tags, so that the values are always in sync.

**Comment by pgpx** [comment]
Also found a few more comments where {@value} could be used.

**Comment by danielfernandez** [comment]
Closed by merging your PR
