### ISSUE TITLE
Numbers format thousands and decimal separator too strict.

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf#6]
It is not possible to define SPACE as thousands or decimal separator. There is no such possibility in NumberPointType enum.

**Comment by danielfernandez** [comment]
A new value, `'WHITESPACE'`, as a possible thousands/decimal point separator value.

See the associated tests, like https://github.com/thymeleaf/thymeleaf-tests/blob/master/src/test-21/resources/engine21/features/expression/numbers/numbers02.thtest

**Comment by martinmoserswiss** [comment]
Hello Daniel
Is it possible to use apostrophe (') to as a thousands seperator?
So it would be cool if you can decalre a APOSTROPHE in NumberPointType enum.
Or is there another way to acheive this?
