### ISSUE TITLE
java.lang.ClassNotFound while using this "org.thymeleaf.templateresolver.SpringResourceTemplateResolver"

### ISSUE THREAD

**Issue by pathfinder2104** [thymeleaf/thymeleaf#601]
Hello, 

I am new to Thymeleaf, I was going through the tutorials, http://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html and I found that above class didn't work as mentioned in the Chapter-2, using Spring’s XML-based configuration. 
```xml
<!-- SpringResourceTemplateResolver automatically integrates with Spring's own -->
<!-- resource resolution infrastructure, which is highly recommended.          -->
<bean id="templateResolver"
       class="org.thymeleaf.templateresolver.SpringResourceTemplateResolver">
  <property name="prefix" value="/WEB-INF/templates/" />
  <property name="suffix" value=".html" />
  <!-- HTML is the default value, added here for the sake of clarity.          -->
  <property name="templateMode" value="HTML" />
  <!-- Template cache is true by default. Set to false if you want             -->
  <!-- templates to be automatically updated when modified.                    -->
  <property name="cacheable" value="true" />
</bean>
    
<!-- SpringTemplateEngine automatically applies SpringStandardDialect and      -->
<!-- enables Spring's own MessageSource message resolution mechanisms.         -->
<bean id="templateEngine"
      class="org.thymeleaf.spring4.SpringTemplateEngine">
  <property name="templateResolver" ref="templateResolver" />
  <!-- Enabling the SpringEL compiler with Spring 4.2.4 or newer can speed up  -->
  <!-- execution in most scenarios, but might be incompatible with specific    -->
  <!-- cases when expressions in one template are reused across different data -->
  <!-- ypes, so this flag is "false" by default for safer backwards            -->
  <!-- compatibility.                                                          -->
  <property name="enableSpringELCompiler" value="true" />
</bean>

```
This "org.thymeleaf.templateresolver.SpringResourceTemplateResolver" in above statement is incorrect, it should be "org.thymeleaf.spring4.templateresolver.SpringResourceTemplateResolver".

Please correct it in the documentation. I want to correct it my self but couldn't find where to correct it.  If you can provide me a link to the repository containing the above mentioned documentation then I can correct it and raise a PR for this.

**Comment by danielfernandez** [comment]
Indeed that is incorrect. I'll take care of that, thanks.

**Comment by pathfinder2104** [comment]
@danielfernandez 
I can raise a PR for this. Is that ok?

**Comment by danielfernandez** [comment]
Sure, thanks! It's the `thymeleaf/thymeleaf-docs` repository.

**Comment by pathfinder2104** [comment]
I have raised a PR here is the link : [PR for this issue](https://github.com/thymeleaf/thymeleaf-docs/pull/49) please check and merge if you find it appropriate. Thanks :)

**Comment by danielfernandez** [comment]
PR merged, thanks!
