### ISSUE TITLE
Avoid outputting "]]>" inside javascript CDATA sections

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#61]
Currently, Thymeleaf allows that a script like this:

```
<script th:inline="javascript">
    /*<![CDATA[*/
    var example = /*[[${example}]]*/ "";
    /*]]>*/
</script>
```

When `example` is `"Be careful of </script> & ]]>!"` is output like:

```
<script>
    /*<![CDATA[*/
    var example = 'Be careful of <\/script> & ]]>!';
    /*]]>*/
</script>
```

...which means the `]]>` part could be understood as the end of the CDATA section by some browsers, and therefore even lead to some kinds of _script injection_.

This works alright in current versions of Chrome, Firefox, Opera and IE (v9), and also in IE6 (!!), but both IE7 and IE8 seem affected.

The XML specification states that the `]]>` string is simply forbidden inside a CDATA section, and so should never appear. And JavaScript does not allow the `>` sign to be escaped as `&gt;`, so if this occurred outside a text literal the solution would be to output it as:

```
]]]]><![CDATA[>
```

...which outputs the two brackets, ends the CDATA section, and then opens a new one starting with the more-than symbol.

**BUT** Thymeleaf has this problem **only inside literals**, and doing this inside a literal would change it completely, so probably the best possible _kind-of-escaping_ solution for thymeleaf would be to output `]]>` as a text append operation:

```
<script>
    /*<![CDATA[*/
    var example = 'Be careful of <\/script> & ]]' + '>!';
    /*]]>*/
</script>
```

**Comment by danielfernandez** [comment]
Another possibility for escaping `]]>` would be, simply:

```
<script>
    /*<![CDATA[*/
    var example = 'Be careful of <\/script> & ]]\>!';
    /*]]>*/
</script>
```

...but, not being `>` one of the characters that must be escaped in JavaScript... are we sure every browser understands `\>` correctly?

**Comment by asis** [comment]
"are we sure every browser understands {{whatever}} correctly?" => no :)

But according to the spec (http://es5.github.com/x7.html#x7.8.4) any escape sequence using a non-special character has the same value as the non-special character. So every browser _should_ understand it.

The "divide & conquer" :P option looks OK, but given the huge amount of javascript syntactic quirks... who knows ;) (by the way, the generated append operation should be wrapped in parentheses).

**Comment by danielfernandez** [comment]
Thanks.

Fixed using the `]]\>` escaping sequence, and added to 2.0.12-SNAPSHOT.
