### ISSUE TITLE
The entity name must immediately follow the '&' in the entity reference.

### ISSUE THREAD

**Issue by clayclayclay** [thymeleaf/thymeleaf#611]
Hi, all.
In my index.html file,  there is a js code snippet, just like below shown:
```
if ($(this).val() != $("#checkPasswords").val() && $("#checkPasswords").val() != "") {
    $("#curl-error").css('display', 'inline');
    isOk = false;
} else if ($(this).val() != "") {
    isOk = true;
    $("#curl-error").css('display', 'none');
}
```

But when I access the index.html, the console occured:
```
org.xml.sax.SAXParseException: The entity name must immediately follow the '&' in the entity reference.
```

Then, I replace it with `&amp;&amp;` and it did work. But the js code became some hard to read.

So could anyone give me some advice?

**Comment by danielfernandez** [comment]
Thymeleaf 2.1 uses an XML parser to process your template (v3.0 uses an HTML one, and this would not happen). So the XML parser does not know that the contents of your `<script>` should be processed as `CDATA` (i.e. ignored) and finds that your `&&` is indeed invalid HTML (it thinks it is an escape code).

The solution is to wrap your JavaScript code with `<![CDATA[...]]>`, like:

```html
<script>
// <![CDATA[
   ...your code here
// ]]>
</script>
```

That way you'll make the `CDATA` section *explicit* and the XML parser will understand that it does not have to worry about what is inside that block.

**Comment by clayclayclay** [comment]
@danielfernandez 
Thank, you. I have updated the thymeleaf version to 3.x and fixed the issue :)

**Comment by Natalli1812** [comment]
52 199 The entity name must immediately follow the '&' in the entity reference.Как можно исправить,чтобы не было ошибки.
