### ISSUE TITLE
How to reload templates without restarting the spring boot application?

### ISSUE THREAD

**Issue by seven-new-guy** [thymeleaf/thymeleaf#614]
I deploy my spring boot application with maven by `spring-boot:run` in `intellij-idea`. I must restart my application after I update the template files. Is there some methods that can update templates automatically instead of restarting the application?

I have already putted `spring-boot-devtools` in pom.xml:
```xml
        <!-- hot swap -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-devtools</artifactId>
            <version>1.3.0.RELEASE</version>
            <optional>true</optional>
        </dependency>
```

p.s: sorry, maybe there are some grammar errors. English isn't my native language.

**Comment by danielfernandez** [comment]
Spring Boot offers a `spring.thymeleaf.cache` configuration property which you can set to `false` if you want to disable the template cache so that templates can be modified on the fly.

Note however that Maven's `spring-boot:run` does run templates from the generated *überjar*, so I don't think this would work. However, if you run your application from IntelliJ IDEA by selecting the *application class* and choosing `Run...` (you seem to cite these two methods as the same thing but they are actually different ways to start your app), then you should be able to see changes in your templates simply by asking IntelliJ to build the project (`⌘+F9` in macOS, `Ctrl+F9`in Windows).

**Comment by Aim4dStars** [comment]
Yepp ⌘+F9 in macOS helped to reload although the spring.thymeleaf.cache=false did not help. Thanks

**Comment by samhela** [comment]
spring.thymeleaf.cache=false or Intellij Buil project `(Ctrl + F9) ` ddin't work either, I used used gradle bootRun

**Comment by sid-code** [comment]
@danielfernandez Your last paragraph worries me. Is there any way (maven or otherwise, I don't care anymore) to run a spring boot application through the CLI that allows for template reloading? I don't want to be tied to an IDE.

Every single google result for this question has answers only for IDE users.

**Comment by danielfernandez** [comment]
@sid-code `spring.thymeleaf.cache=false` will perfectly work, but only as long as you load your templates from outside the Spring Boot _überjar_, as of course the contents of such jar (and therefore any templates that would be loaded from there) cannot be changed in runtime. That was what my comment was about.

**Comment by sid-code** [comment]
@danielfernandez Thanks for the clarification. I wasn't understanding what was being put in the jar and what wasn't.

**Comment by cesar3030** [comment]
In order to have it working I had to:
 * Add to the application.propreties file: `spring.thymeleaf.cache=false`
 * Run the app in **Debug mode**
 * Click **Run > Reload Changed Classes** to apply the changes.

**Comment by attacomsian** [comment]
If you are still struggling with `spring-boot-devtools`, I recommend using Gulp to automate templates and resources reload. Following is a little Gulp task that does the magic for me:

 ```javascript
var gulp = require('gulp'), 
    watch = require('gulp-watch');

gulp.task('watch', function () {
    return watch('src/main/resources/**/*.*', () => {
            gulp.src('src/main/resources/**')
                //replace with build/resources/main/ for netBeans
                .pipe(gulp.dest('out/production/resources/')); 
    });
});

gulp.task('default', ['watch']);
```

I wrote a short [blog post](https://attacomsian.com/blog/spring-boot-auto-reload-thymeleaf-templates/) on this topic as well.

**Comment by wkaczurba** [comment]
If you are not using - disabling caching in the template resolver bean:

SpringResourceTemplateResolver templateResolver = new SpringResourceTemplateResolver();
...
templateResolver.setCacheable(false);

**Comment by walterwhites** [comment]
> In order to have it working I had to:
> 
> * Add to the application.propreties file: `spring.thymeleaf.cache=false`
> * Run the app in **Debug mode**
> * Click **Run > Reload Changed Classes** to apply the changes.

Thanks @wkaczurba

**Comment by rwenz3l** [comment]
I just wanted to add, that ***you can run*** `mvn spring-boot:run` and also serve the templates from your `src` directory or whatever:

As a Single Command:

```sh
mvn spring-boot:run \
-Dspring-boot.run.jvmArguments="-Dspring.thymeleaf.prefix=file:src/main/resources/templates/ -Dspring.thymeleaf.cache=false -Dspring.resources.static-locations=file:src/main/resources/static/ -Dspring.resources.cache-period=0"
```

But you can also specify them in a seperate development properties file (`application-develop.yaml`)
 and use `mvn spring-boot:run -Dspring-boot.run.profiles=default,develop`.

Here is my develop-yaml:

```yaml
spring:
  thymeleaf:
    check-template-location: true
    cache: false
    prefix: file:./src/main/resources/templates/
  resources:
    static-locations: file:./src/main/resources/static/
    cache-period: 0
```

**Comment by Partho99** [comment]
w

**Comment by vanduc1102** [comment]
I found from the tutorial here: https://attacomsian.com/blog/spring-boot-auto-reload-thymeleaf-templates
it works for me when i added both

```
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=file:src/main/resources/templates/
```

**Comment by karancontexio** [comment]
> I found from the tutorial here: https://attacomsian.com/blog/spring-boot-auto-reload-thymeleaf-templates
> it works for me when i added both
> 
> ```
> spring.thymeleaf.cache=false
> spring.thymeleaf.prefix=file:src/main/resources/templates/
> ```

This works for me thank you Intellij Idea

**Comment by a13a** [comment]
I had to add 
```
spring.web.resources.static-locations[0]=file:src/main/resources/static/
spring.web.resources.static-locations[1]=classpath:/static/
```

so that static resources would also be refreshed. Do not use this in production if you are not sure.

**Comment by kyungw00k** [comment]
@seven-new-guy 

  🚀 TFPP: Thymeleaf CLI Template Processor

  Built a CLI tool that brings Thymeleaf to your command line! Perfect for static site generation, config templating, and rapid prototyping.

  ⚡ One-line install:

```
curl -fsSL https://raw.githubusercontent.com/kyungw00k/tfpp/main/install.sh | sudo bash
```

  💡 Quick usage:

```
tfpp process template.html --var name="John" --data site.json
tfpp process-dir templates/ output/ --watch  # Live development mode
```

  ✨ Features:

  - JSON/YAML data binding
  - Multi-format support (HTML, CSS, JS, TEXT)
  - Watch mode for development
  - Zero configuration required

  Shows off Thymeleaf's versatility beyond web apps!

  GitHub: https://github.com/kyungw00k/tfpp
