### ISSUE TITLE
th:object can not post data to controller

### ISSUE THREAD

**Issue by Ahaochan** [thymeleaf/thymeleaf#618]
i have a controller
```java
// UserController
    @RequestMapping(value = "/admin/user/test", method = RequestMethod.GET)
    public ModelAndView test(){
        ModelAndView mv = new ModelAndView("admin/user/user_test");
        UserData userData = userService.selectById(100000L);
        System.out.println("get:"+userData.toString());
        mv.addObject("userDetailView", new UserDetailView(userData));
        return mv;
    }

    @RequestMapping(value = "/admin/user/test", method = RequestMethod.POST)
    public String test(UserData user){
        System.out.println("post:"+user.toString()); 
        return "redirect: /admin/user/test";
    }
```
```java
// UserDetailView
public class UserDetailView {
    private final UserData userData; // username and password field
    // getter and setter and constructor
}
```
```html
<form method="post" th:action="'/admin/user/test'"
                  th:object="${userDetailView.userData}">
    <label>username<input type="text" th:field="*{username}"/></label>
    <label>pw<input type="text" th:field="*{password}"/></label>
    <button type="submit">保存</button>
</form>
```

i input `http://localhost:8080/admin/user/test` in browser.
it show the field in form and output in console `get: UserData{username='admin1', password='admin1'}`
when i modify the form and click button to submit.
it output in console : `post: UserData{username='null', password='null'}`

and then i modify the controller code
```java
@RequestMapping(value = "/admin/user/test", method = RequestMethod.GET)
    public ModelAndView test(){
        ModelAndView mv = new ModelAndView("admin/user/user_test");
        UserData userData = userService.selectById(100000L);
        System.out.println("get:"+userData.toString());
        mv.addObject("data", userData); // here
        return mv;
    }
```
```html
<form method="post"  th:action="'/admin/user/test'"
                  th:object="${data}"><!--here-->
    <label>username<input type="text" th:field="*{username}"/></label>
    <label>pw<input type="text" th:field="*{password}"/></label>
    <button type="submit">save</button>
</form>
```

modify data and click button to submit
it output in console
```
get: UserData{username='admin1', password='admin1'}
post: UserData{username='111', password='222'}
```

why `th:object` can read data by `UserData` ( field of `UserDetailView`) but cannot write data to controller??
thank! i sorry my english :)

**Comment by danielfernandez** [comment]
I'm afraid this is a Spring MVC question, not really related to Thymeleaf. Yours is an issue with Spring form binding.

The problem is that Spring MVC requires that your form-backing bean (your `UserData` in this case) is a *first-level* variable in the model, which in your case, it isn't. Thymeleaf's user manual explains this here: http://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#handling-the-command-object

**Comment by pguevara2017** [comment]
You will have to use the th:action attribute and the Standard URL expression: @{...} for this.

`<form method="post" th:action="@{/admin/user/test}" th:object="${userDetailView.userData}">`
