### ISSUE TITLE
create a empty numbers.sequence

### ISSUE THREAD

**Issue by shuanshuan** [thymeleaf/thymeleaf#621]
```
int counter=...;
// if count=5;
for(int i=1; i<=5; i++}{
  System.out.print(i);
}
th:each="i:${#numbers.sequence( 1, counter)}" //1,2,3,4,5
th:each="i:${#numbers.sequence( 1, counter,1)}" //1,2,3,4,5
```
```
// if count=0; we have to do more job to handle this
// expected  result empty sequence
th:each="i:${#numbers.sequence( 1, counter)}"  //1,0
th:each="i:${#numbers.sequence( 1, counter,1)}" //error
```
Which integers are greater than 1 and less than 0 ? The answer is none, not wrong question. 

```
<thymeleaf.version>3.0.6.RELEASE</thymeleaf.version>
<thymeleaf-layout-dialect.version>2.1.1</thymeleaf-layout-dialect.version>
```
How can handle the counter<=0  to get the same result as the java code?  

In Java for-loop int i=1; i<=5; i++; we can set the sart value 1, the value changing rule i++ and the stop condition.

**Comment by danielfernandez** [comment]
What do you mean? I mean, what is what you are experiencing here, what would be the expected result that you are not getting or the issue that you are obtaining?

Also, please specify the version of Thymeleaf you are using.

**Comment by shuanshuan** [comment]
@danielfernandez updated my post!

**Comment by danielfernandez** [comment]
Understood. Seems reasonable to return an empty sequence in these cases.

**Comment by danielfernandez** [comment]
Already in `3.0.7-SNAPSHOT`
