### ISSUE TITLE
TEXT mode: Requiring a context variable to be present

### ISSUE THREAD

**Issue by Eichhrn** [thymeleaf/thymeleaf#624]
Hello,

using a TemplateEngine with a StringTemplateResolver in "TEXT" mode I'd like to process a text template, e.g. "Hello [(${username})]".

If my Context contains no mapping for username the template is still processed and [(${username})] is replaced with "". From using Thymeleaf in HTML mode I'm used to this throwing an exception. Is there any way already present to force this behaviour for TEXT mode as well? I only want to process templates that contain all the necessary context variables.

Thanks in advance!

**Comment by danielfernandez** [comment]
I might be misunderstanding your scenario, please give me more detail where possible… `[[${username}]]` can be used both in `HTML` and in `TEXT` template modes, and in both cases it behaves the same as `<th:block th:text="${username}" />`.

Anyway, there is no exception being thrown when the `username` variable does not exist in the context, no matter the template mode…

**Comment by Eichhrn** [comment]
Hi, thanks for the quick reply.

The exception is thrown if I process
```html
<td>Link: <a href="https://www.google.com/" style="color:#fd2d0d;"
th:href="${emailConfirmationURL}"><div th:replace="${emailConfirmationURL}"></div></a></td>
```
in `HTML` mode, which is of course not the same as `<th:block th:text="${username}" />`. Since I didn't get an exception without providing a value for emailConfirmationURL in the Context after I removed the th:replace, I assume only th:replace actually requires the variable to exist in the Context?

Does Thymeleaf have some concept for checking whether all variables that exist in a template are present in the Context, or do I need to check for that myself if I need this information?

**Comment by danielfernandez** [comment]
Correct, in the case of `th:replace`, it actually needs the value expression to return a valid fragment or an exception will be thrown. Also, since v3.0 results such as *empty fragment* (`~{}`) and *do nothing (`_`) are also accepted.

> Does Thymeleaf have some concept for checking whether all variables that exist in a template are present in the Context, or do I need to check for that myself if I need this information?

There is a `th:assert` attribute you can use to make sure specific variables exist (will throw an exception is assertions are not met). But if you mean something *automatic*, then no, there isn't. Actually, your template is processed as it is read from disk/cache, there are no previous passes, so there would not be an easy way to do that.

**Comment by danielfernandez** [comment]
Can I assume therefore that this ticket can now be closed?

**Comment by Eichhrn** [comment]
Yeah, thanks for your quick help, I appreciate it!

**Comment by edwardchanjw** [comment]
Sorry If i comment on following issue as it is closed

But I would like to enquiry and it is good to sharing ideas/tips on the same intentions or extending the use case for same case.
Hi all, can I asking few possible approach to check the all variables that exist in a template are present in the Context? Like extend IProcessorDialect  and check in doProcess or other easier approach?

**Comment by danielfernandez** [comment]
> Hi all, can I asking few possible approach to check the all variables that exist in a template are present in the Context?

Thymeleaf has no way of doing this, as the template is processed as it is read from disk/cache. Previous knowledge about required variables would require some kind of template pre-processing, which would affect performance and significantly modify the way the engine works now. Besides, thanks to pre-processing capabilities in Thymeleaf expressions and the possibility to use indexed variables in OGNL/SpEL (e.g. at iterations), it would not be possible to know all the data to be required at the context even during a template pre-processing phase.
