### ISSUE TITLE
Support JSON

### ISSUE THREAD

**Issue by edwardchanjw** [thymeleaf/thymeleaf#627]
Is that able to support json like following:
Any guidelines for how to extend thymeleaf for the purpose? or it is already supported?
or just which library convert them back to java POJO assumed the type retaining well.

For example Template with json

`	Tu quoque, <em>${item.stock.stockLocation}</em>!`

```
        String json = "{\"price\": 22, \"name\":  \"product name\",  \"stock\":  { \"stockLocation\":  \"location\"  }}";
        map = mapper.readValue(json, new TypeReference<Map<String, String>>(){});
```
```
        final Map<String, Object> modelObject = new HashMap<>();
        modelObject.put("item", map);
```

```
        final Context context = new Context();
        context.setVariables(modelObject);
```

Actually I am asking the same question in [Spring Boot Email Tools](https://github.com/ozimov/spring-boot-email-tools/issues/58)

**Comment by danielfernandez** [comment]
It depends on what you mean with *supporting JSON*.

1. If you mean making your controller layer directly return JSON instead of HTML, then you should be using a JSON serialization library (like Jackson) instead of Thymeleaf. If you are using Spring MVC/Spring Boot, this JSON support is built-in and you wouldn't need to add Thymeleaf at all to your project.

2. If you mean returning HTML but with a  `<script>` tag that contains something like: `var json = "{ ...some JSON object...}";`, then you can use `<script th:inline="javascript">` and make use of the Thymeleaf JavaScript inlining capabilities explained here: http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#javascript-inlining

**Comment by edwardchanjw** [comment]
I mean returning HTML with the replaced ognl/spel of ${item.stock.stockLocation} in the microservices
by directly using the JSON String, or JSON Object that received over REST API. 
I know this question is seem too simple for versatile Java Developer, I just want to know how many different approach to support type conversion or even that any expression language support JSON as alternative of ognl etc.

I mention my intention in [Spring Boot Email Tools](https://github.com/ozimov/spring-boot-email-tools/issues/58) that any direction to implement in their tools to have a open source of basic feature for following tools.

The use case is to use develop microservices for Email template like [Sparkpost's Email Templates] https://www.sparkpost.com/features/email-templates/ or [Shoptify customize Email Template](https://help.shopify.com/manual/sell-online/notifications/edit-template#customize-specific-email-templates)

**Comment by danielfernandez** [comment]
> I mean returning HTML with the replaced ognl/spel of ${item.stock.stockLocation}
> in the microservices by directly using the JSON String, or JSON Object that received
> over REST API.

Understood. But in that case, I believe your question has nothing to do with Thymeleaf itself. You seem to need a way to consume a JSON endpoint (your *"REST API"*) and then do something with the result (in this case, put some part of it into a Thymeleaf context).

If you are using Spring, I think you should have a look at the `RestTemplate` class. But anyway, Thymeleaf is just a view layer, a template engine… so there is nothing it can do to help you *consume* web services. You'd probably need to ask in your web framework's forums.

I'm therefore closing this. Please re-open it if there is anything I might be leaving out.
