### ISSUE TITLE
Cannot test Thymeleaf decoupled logic

### ISSUE THREAD

**Issue by djkeh** [thymeleaf/thymeleaf#629]
Hi,
I encountered a problem when I tried to decouple the template logic and test using Spring MockMvc.
Spring MockMvc was the testing object, so I thought this is related to `thymeleaf-spring` project.
But looking at it, Spring MockMvc runs properly with normal Thymeleaf attributes like this:

```html
<!-- original html template -->
<div th:text"Thymeleaf test">Test</div>

<!-- MockMvc response -->
<div>Thymeleaf test</div>
```

I'm still confusing a little bit but, I think this issue is directly related to Thymeleaf core as well.
So the brief is:

* Thymeleaf engine is running properly, and Thymeleaf attribute is processed as expected through Spring MockMvc test
* **Decoupled Thymeleaf logic is not processed.**

If this is of concern of the Thymeleaf core, the detailed report is in the `thymeleaf-spring` issue. Here's the link:

https://github.com/thymeleaf/thymeleaf-spring/issues/152

Please have a look. Thanks.

**Comment by danielfernandez** [comment]
This is an issue with the user's Spring testing setup. Closing, dealt with at #152

**Comment by djkeh** [comment]
Thank you for the consideration.
