### ISSUE TITLE
JavaScript inliner doesn’t recognize regular expression literals

### ISSUE THREAD

**Issue by astiob** [thymeleaf/thymeleaf#630]
[`TextParser`](https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/templateparser/text/TextParser.java) attempts to partly parse JavaScript to handle situations such as strings containing tag markers. Unfortunately, it does not parse JavaScript regular expression literals.

In particular, when it encounters a quotation mark, it decides that it starts a string literal and waits for another quotation mark to end the string literal. However, the original quotation mark may be part of a regular expression, in which case it need not be balanced. For example, the following line of JavaScript breaks the parser:

```js
words = text.match(/"[^"]+"|[^ ]+/g)
```

After this line, the parser thinks it is inside a string literal (opened by the last `"`). Since Thymeleaf 3.0.4 (I think), this eventually results in a `org.thymeleaf.templateparser.text.TextParseException: Incomplete structure`, but I imagine that in earlier versions this simply silently broke inlining.

Workarounds:

  * Include a “closing” quotation mark in a comment:

    ```js
    words = text.match(/"[^"]+"|[^ ]+/g) // "
    words = text.match(/"[^"]+"|[^ ]+/g /*"*/)
    ```

    (You might think that Thymeleaf should ignore this quotation mark as it’s inside a comment, but remember Thymeleaf thinks it’s still inside a string literal: it doesn’t notice when the comment starts.)

  * Escape the unpaired quotation mark in the regular expression:

    ```js
    words = text.match(/"[^\"]+"|[^ ]+/g)
    ```

**Comment by astiob** [comment]
Oh, and there’s another form of string literals nowadays: [template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals). They aren’t handled by Thymeleaf either.

**Comment by danielfernandez** [comment]
Thanks @astiob. Both issues are confirmed. I've created a new ticket for template literals at #643

**Comment by danielfernandez** [comment]
Already in `3.0.8-SNAPSHOT`
