### ISSUE TITLE
Problems with single quotes in messages

### ISSUE THREAD

**Issue by jambonnade** [thymeleaf/thymeleaf#631]
There is a problem with messages when they contain single quotes (or if they must not contain single quotes it should be mentioned in documentation). The messages are defined in .properties resource bundles

a) If there is a single quote before an argument placeholder {0}, the placeholder is ignored and not replaced by the value
`my.message=Blabla bla'bla. bla : <strong>{0}</strong>.`

`<p th:utext="#{my.message('anything')}">(message)</p>`
outputs
`<p>Blabla bla'bla. bla : <strong>{0}</strong>.</p>`

b) If there is two single quotes in one message containing a placeholder, they seem stripped
`my.message=Blablabla bla'bla, <a href="{0}">blabla bla'bla</a>.`

`<div th:utext="#{my.message('anything')}">(message)</div>`
outputs
`<div>Blablabla blabla, <a href="anything">blabla blabla</a>.</div>`

The workaround is to use &amp;apos;

Thymeleaf version is the one provided with spring boot version 1.5.6.RELEASE

**Comment by danielfernandez** [comment]
Actually, Thymeleaf (and also Spring, who is in charge if you are using this in a Spring-based application) uses Resource Bundles in `.properties` files by means of the standard mechanism defined in the `java.text.MessageFormat` class of the JDK, as is documented in the user tutorial.

See this for more info: https://docs.oracle.com/javase/8/docs/api/java/text/MessageFormat.html
