### ISSUE TITLE
[Improvement] Throwing exception when parser-level comment block is not closed

### ISSUE THREAD

**Issue by MasatoshiTada** [thymeleaf/thymeleaf#632]
When parser-level comment block is not closed, rest of contents are not output because Thymeleaf treat them as comment.
Example is below.

- Thymeleaf template

```html
<p>FOO1</p>
<!--/* This comment is not closed because "*/" is missing -->
<p>FOO2</p>
<p>FOO3</p>
<p>FOO4</p>
```

- Output HTML

```html
<p>FOO1</p>
```

I wondered that Thymeleaf did anomalous behavior without any errors and stacktraces.
This will make developers very confusing.
(In fact, my colleague was so confused!)

In that case, I think that it is appropriate to raise an exception.
I appreciate your serious consideration for my proposal.

# Environment
- Thyeleaf 3.0.7.RELEASE
- Spring MVC 4.3.x
- Tomcat 8.5.x

**Comment by danielfernandez** [comment]
Already in `3.0.8-SNAPSHOT`

**Comment by MasatoshiTada** [comment]
Thanks! I’m looking forward to 3.0.8!
