### ISSUE TITLE
th:href variable substitution requires different syntax than docs

### ISSUE THREAD

**Issue by konrad-garus** [thymeleaf/thymeleaf#637]
I've been following the [docs on link URLs](http://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#link-urls), but I could not get it to work with variables as described there.

Neither of the following worked for me:

```
<link rel="stylesheet" th:href="@{${myBase}/report-css/report.css}"></link>
<link rel="stylesheet" th:href="@{{myBase}report-css/report.css}"></link>
```

However, this one does:

```
<link rel="stylesheet" th:href="@{${myBase} + '/report-css/report.css'}"></link>
```

The docs appear to be misleading here. Am I doing something wrong? 

FWIW, I'm on 3.0.7, calling it directly like this:

```
ClassLoaderTemplateResolver cltr = new ClassLoaderTemplateResolver();
cltr.setPrefix("/templates/report/");
cltr.setSuffix(".html");

TemplateEngine templateEngine = new TemplateEngine();
templateEngine.setTemplateResolver(cltr);

WebContext context = new WebContext(request, response, servletContext);
context.setVariable("myBase", "/my/path");

templateEngine.process("my_template", context);
```

**Comment by danielfernandez** [comment]
Link expressions allow the path to be obtained from an expression, like `${myUrl}`:
```html
<link rel="stylesheet" th:href="@{${myUrl}}"></link>
```
Or like `${myBase} + '/report-css/report.css'` in your:
```html
<link rel="stylesheet" th:href="@{${myBase} + '/report-css/report.css'}"></link>
```
Or like `|${myBase}/report-css/report.css|` (note the `|...|` for literal substitution) in:
```html
<link rel="stylesheet" th:href="@{|${myBase}/report-css/report.css|}"></link>
```
But note that your original expression `${myBase}/report-css/report.css` is not a valid expression.

Further references:
   * http://www.thymeleaf.org/doc/articles/standarddialect5minutes.html
   * http://www.thymeleaf.org/doc/articles/standardurlsyntax.html

**Comment by konrad-garus** [comment]
Ah, now I understand the difference. Thanks!
