### ISSUE TITLE
Increase Jackson dependency version to >= 2.9.1

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#638]
According to https://github.com/FasterXML/jackson-databind/issues/1020#issuecomment-328201622, a new configuration method `withColonInTimeZone(boolean)` was added to `StdDateFormat` that could allow Thymeleaf to drop its own serializer implementation.

Note this was added in Jackson 2.9.1, which is only from Sep 2017, so it would be a bad idea to force a dependency version update in 3.0.x. This 2.9.1 version is the one already used by the current snapshots of Spring Boot 2.0.

This should therefore be queued for 3.1.

**Comment by ultraq** [comment]
Given all the Jackson updates we're making because of security vulnerabilities (#720, #762), we'll have the version of Jackson that includes this new feature in the 3.0.x branch already! 😆

**Comment by danielfernandez** [comment]
Base Jackson dependency version already is 2.11.3 for the core. Closing this.
