### ISSUE TITLE
JacksonThymeleafISO8601DateFormat is not threadsafe

### ISSUE THREAD

**Issue by pwandl** [thymeleaf/thymeleaf#639]
I recently encountered an issue with the Javascript Serializer which crashed while serializing dates due to synchronization issues.

A comment in JacksonThymeleafISO8601DateFormat correctly states that Jackson has to handle the synchronization of the DateFormats, but I think the Thymeleaf DateFormat breaks this mechanism.
As far as i know, Jackson relies on `clone` to avoid issues with non-threadsafe date formats, but when cloning the JacksonThymeleafISO8601DateFormat, all clones reference to the same SimpleDateFormat instance, which is obviously not thread safe.

I'd suggest to either fix the clone to avoid sharing a single SimpleDateFormat instance or using a threadsafe DateFormat.

**Comment by danielfernandez** [comment]
Confirmed and fixed. Indeed `clone()` wasn't being properly implemented there. Good catch, thanks a lot.

**Comment by danielfernandez** [comment]
Already in `3.0.8-SNAPSHOT`
