### ISSUE TITLE
Decoupled template removes tags when used with th:if statement 

### ISSUE THREAD

**Issue by kowalczm** [thymeleaf/thymeleaf#640]
Hi Team,
I'm using decoupled templates (3.0.7) and I have following test.th.xml file:
```xml
<?xml version="1.0"?>
<thlogic>
	<attr sel="Jobs" th:object="${jobsSettings}" th:if="${jobsSettings} != null">
		<attr sel="/JobThreads" th:text="*{getString('$.threads')}" />
		<attr sel="/JobFlags/UseMemoryInfo" th:value="*{memory}" />
		<attr sel="/JobFlags/CreateMakeGraph" th:value="*{createMakeGraph}" />
	</attr>
</thlogic>
```
Add when the logic th:if is evaluated to 'false'  the <Jobs> tag  is removed from my test.xml.
I would expect that above logic preserve my current <Jobs> tag in test.xml template file

**Comment by danielfernandez** [comment]
I'm not sure I understand the issue you describe…

Every attribute in an `<attr>` specification is *copied* to the selected tags in the template (in your case I assume that's `test.xml` during parsing. Then, during execution the template is executed exactly as if the template and the decoupled logic file had been merged from the beginning in a single file.

So the behaviour you describe for your `th:if` sounds exactly like it should work... if `th:if`evaluates to `false`, then the entire element selected by that `Jobs` selector (which I assume will be all `<Jobs>...</Jobs>` elements in your XML file) will disappear.

**Comment by kowalczm** [comment]
Yes, I have figured it out. Thank you. I have found also NO OP - '_' in order to keep 'default' content when expression evaluates to null. Another question from my side would be about supporting in Thymeleaf json objects  in 'variable expression' sth like: ^{store.book[*].author} where path 'store.book[*].author' would be JsonPath expression. Would be great feature to support it be default
