### ISSUE TITLE
Update slf4j-api version[1.6.6 released in June, 2012] used in thymeleaf lib to latest 1.7.25

### ISSUE THREAD

**Issue by skale1990** [thymeleaf/thymeleaf#641]
Update slf4j-api version[1.6.6 released in June, 2012] used in thymeleaf lib to latest 1.7.25.

Current version used - slf4j-api version[1.6.6 released in June, 2012]
new version available - slf4j-api version[1.7.25 released in Mar, 2017]

**Comment by danielfernandez** [comment]
Already in `3.0.8-SNAPSHOT`
