### ISSUE TITLE
Thymeleaf Erro tag

### ISSUE THREAD

**Issue by Elton-Santos** [thymeleaf/thymeleaf#642]
Please, How I can resoulver this?

The value of attribute "th:if" associated with an element type "li" must not contain the '<' character.

```
<th:block th:each="p : ${#numbers.sequence(1, pagina.total)}" th:with="numeroPagina = ${p - 1} ">
            <li th:if="${(p + 1 >= paginaAtual and p - 1 <= paginaAtual + 2)}"
                th:class="${paginaAtual == numeroPagina} ? 'active deep-purple darken-4' : 'waves-effect' ">
                
                <a th:href="${pagina.urlParaPagina(numeroPagina)}" th:text="${p}">1</a>
            </li>
</th:block>
```

**Comment by danielfernandez** [comment]
I assume you are using Thymeleaf 2.1.

HTML attribute values should not contain unescaped `<` characters. Use `&lt;` (escaped equivalent) instead.

Note that Thymeleaf 3.0 uses a more lenient parser and would allow you to use that char (even if you really shouldn't :)).
