### ISSUE TITLE
In StandardCacheManager cache report, Hit ratio is always 0.00 if not hit all...

### ISSUE THREAD

**Issue by yoshikawaa** [thymeleaf/thymeleaf#646]
#### Version
3.0.8.RELEASE

#### Problem
At `StandardCacheManager` cache report, there is a problem that the hit ratio and miss ratio are not calculated correctly.

```console
[THYMELEAF][*][*][*][CACHE_REPORT]        2 elements |            2 puts |            8 gets |            6 hits |            2 misses | 0.00 hit ratio | 1.00 miss ratio - [TEMPLATE_CACHE]
```
* hit ratio is always `0.00` if not hit all.
* miss ratio is always `1.00`.

#### Cause
At [StandardCache.java#L334-L340](https://github.com/thymeleaf/thymeleaf/blob/thymeleaf-3.0.8.RELEASE/src/main/java/org/thymeleaf/cache/StandardCache.java#L334-L340)

```java
long hitCount = getHitCount();
long missCount = getMissCount();
long putCount = getPutCount();
long getCount = getGetCount();

double hitRatio = hitCount / getCount; // calculation mistake...
double missRatio = 1 - hitRatio;
```
The division result of long is stored in double...

#### Solution

```java
double hitRatio = (double) hitCount / (double) getCount;
```

Please consider it.

**Comment by danielfernandez** [comment]
Already in `3.0.9-SNAPSHOT`
