### ISSUE TITLE
one column in the table shows object:object

### ISSUE THREAD

**Issue by CARRYME0820** [thymeleaf/thymeleaf#652]
one column in the table shows object:object, how can I acquire an attribute from object? Thank you!
```html
<th id="blogtype"
						lay-data="{field:'blogtype', width:100, templet: '#blogtype'}">博客</th>
		<script th:inline="javascript" type="text/javascript" id="blogtype">  
              {{#  if( d.blogtype!= null){ }}  
                  {{ d.blogtype.blogName }} 
                   {{#  }  }}  
       
          </script>
```

**Comment by danielfernandez** [comment]
Could you clarify your question a bit more, please? Apart from that `th:inline`, nothing in your sample code is actually Thymeleaf code, but probably some other template engine… so I'm not sure about what is your Thymeleaf-related question here.

**Comment by CARRYME0820** [comment]
@danielfernandez  My code is 
```html
<tr>
      <th ....>创建时间</th>
      <th ....>博客内容</th>
      <th id="blogtype" lay-data="{field:'blogtype', width:100, templet: '#blogtype'}">博客名</th>
</tr>
```
a data returned by "field:'blogtype'" is object, I want to get one attribute of object and put it in  
```html
<th id="blogtype" lay-data="{field:'blogtype', width:100, templet: '#blogtype'}">博客名</th>
```
I am sure that I use the Thymeleaf template engine. Thx!

**Comment by danielfernandez** [comment]
Unfortunately I'm not sure what you mean, but I'm completely sure this is not Thymeleaf code:
```
{{#  if( d.blogtype!= null){ }}
    {{ d.blogtype.blogName }}
{{#  }  }}
```
Please have a look at this article: http://www.thymeleaf.org/doc/articles/standarddialect5minutes.html as it contains the basics of Thymeleaf expressions, in case it helps.

**Comment by danielfernandez** [comment]
Okay, now I've properly formatted your two messages above and made the HTML display properly, it makes a bit more sense. If I understand OK, that JavaScript code has nothing to do with all of this, and all you want is to output a property from an object. That can be as simple as `<th th:text="${object.property}">`, but please refer to the linked article above as well as the tutorials in http://www.thymeleaf.org/documentation.html, as this is very basic stuff and I think you'll benefit from having a look at the basics.

**Comment by CARRYME0820** [comment]
@danielfernandez   the data that "th:field" receive is object, but I only want to get one property in object.

**Comment by danielfernandez** [comment]
What `th:field`? There is no `th:field` in your code…

Again, please read the docs. I would start by the *Using Thymeleaf* tutorial linked here: http://www.thymeleaf.org/documentation.html
