### ISSUE TITLE
spEl error

### ISSUE THREAD

**Issue by mangodai** [thymeleaf/thymeleaf#654]
For SUGGESTIONS:

Please describe the problem that you are trying to solve in the maximum
detail possible.

```java
// service 
msg = messageService.getNews(option);
map.put("message", msg); // when msg is null
```
When message is null that i would to do like this. Otherwise, Thymeleaf throw a exception.
```html
< th:block th:if="${message != null}">  
   <div  th:text=${message.msg}>
   <div>
< /th:block>
```

but, I don't need do complicated step in jsp EL.
```
<div>
   ${message.msg}
</div>
```

So, do you hava better way?

**Comment by h2m** [comment]
Hi @mangodai ,
isn't all you want to do safe navigation using `?.` : `${message?.msg}`?
Best Marc

**Comment by danielfernandez** [comment]
Thanks @h2m, that is a good option. Alternatively, you could also use something more verbose like `th:text="${message} ? ${message.msg}"`
