### ISSUE TITLE
Method contains cannot be found on kotlin.collections.EmptySet type

### ISSUE THREAD

**Issue by shenliuyang** [thymeleaf/thymeleaf#656]
EL1004E: Method call: Method contains(org.appsugar.archetypes.entity.Role) cannot be found on kotlin.collections.EmptySet type

`<input type="checkbox" th:checked="${user.roles.contains(role)}" /> <span th:text="${role.name}"/>`

When user.roles are not empty  work fine.

thymeleaf version 3.

spring-boot  2.0M7 

kotlin version 1.2

**Comment by shenliuyang** [comment]
use ${#sets.contains(user.roles,role)}  fix it

**Comment by crux** [comment]
any idea why? contains sounds like a perfectly valid method to be called on an empty list.
