### ISSUE TITLE
Does thymeleaf's "th:replace" work in JQuery's html() function ？

### ISSUE THREAD

**Issue by Ngone51** [thymeleaf/thymeleaf#659]
Hi, I try to use thymeleaf's template function in JQuery like this:

```
$('.class-name').html('<div th:replace="template/search"></div>');
```

Then, I expect to get a  complete page with "template/search"'s content in it.
But, obviously, it din't work.

So, I'd like to know that whether I made a mistake or thymeleaf can not be used like this.
Thanks!

**Comment by tamb** [comment]
With Thymeleaf 3 you can process that external JS file through Thymeleaf and this will work,  However, to dynamically add Thymeleaf templates/fragments to an already rendered page, you would need to make an AJAX call to the server.  Remember, Thymeleaf is server-side rendered and is delivered as HTML. 
 
To admins:  I would mark this as Closed.
