### ISSUE TITLE
"org.thymeleaf.util.DateUtils#formatDate" is thread-unsafe ?

### ISSUE THREAD

**Issue by kazukazu** [thymeleaf/thymeleaf#66]
"DateUtils#formatDate" is using a  "SimpleDateFormat"(not thread-safe API).

I think thread-unsafe, because SimpleDateFormat instance are cached in static variables and not synchronized.

Please confirm you.

**Comment by danielfernandez** [comment]
Fixed in https://github.com/thymeleaf/thymeleaf/commit/93cacf1c4f3d5e0737a603ca6e9e267c8aaef604

Added to 2.0.12-SNAPSHOT.

Thanks.
