### ISSUE TITLE
Directly support iterating over streams

### ISSUE THREAD

**Issue by hamishlawson** [thymeleaf/thymeleaf#660]
Streams are not currently one of the things that _th:each_ can iterate over. While it is possible to call iterator() on the stream before passing it to Thymeleaf, it would be neater if Thymeleaf was able to handle streams directly.

**Comment by danielfernandez** [comment]
I'm queueing this for Thymeleaf 3.1, which will have a Java 8 baseline.

**Comment by garretwilson** [comment]
Yes, please add this. In the source code it's as simple as wrapping an `Iterable` around `Stream.iterator()`, which with lambda notation is even simpler:

```java
stream::iterator
```

Of course there will be a little extra code if Thymeleaf is using reflection, but the basic idea is the same.

Thymeleaf should really be supporting common Java 8 constructs in 2020!

I naively tried to iterate over a stream in Thymeleaf and got:

> `java.util.stream.ReferencePipeline$Head@xxxxxxxxx`

No error message on the screen. No error message in the Spring logs, even in debug mode!
