### ISSUE TITLE
Are text templates "Natural"?

### ISSUE THREAD

**Issue by evbo** [thymeleaf/thymeleaf#668]
I'm interested in migrating from Apache Velocity to thymeleaf for its "Natural Template" processing philosophy. However, I'm not seeing how this philosophy is fulfilled for text "*.txt" file templates?

It would be great if either:

- Text template syntax was resolvable by a community edition IDE plugin (e.g. Intellij) in order to generate a real-time "preview" mode without the need for a server to be restarted to get the generated text result.

- Or if an approach existed for generating Natural Templates consisting of XML or HTML that would ultimately be rendered as text with all markup removed. This way you get immediately viewable XML/HTML output but text rendering when served.

Do either of these features exist or are they close to existing in the near term? I scoured the documentation and youtube tutorials but couldn't find them. The regular text templating looks great, but I'm not seeing how it is "Natural".

**Comment by danielfernandez** [comment]
No, `TEXT` mode templates aren't *natural*, that's a feature that applies to `HTML`,`XML`, `JAVASCRIPT` and `CSS` template modes, as the idea is that with natural templates the template itself is a *valid document*, and there isn't really anything such as a *valid .txt file*, there are no validity rules to be applied to simple text files, no syntax to honor. Text files are syntax-free.

> Text template syntax was resolvable by a community edition IDE plugin (e.g. Intellij) in order to generate a real-time "preview" mode without the need for a server to be restarted to get the generated text result.

The IntelliJ IDEA plugin for Thymeleaf is not developed by the Thymeleaf team, but by JetBrains themselves, so maybe this is something that could be asked directly to them...

> Or if an approach existed for generating Natural Templates consisting of XML or HTML that would ultimately be rendered as text with all markup removed. This way you get immediately viewable XML/HTML output but text rendering when served.

This could be done by applying a large amount of `th:remove="tag"` attributes on your HTML tags, but to be honest I think the result would be quite ugly... another possibility would be to create regular HTML templates, but add a custom Thymeleaf *post-processor* that would strip all HTML tags and only leave the result.

But again, the issue with this is that `.txt` files are just that, text, and everything in there should be visible... so the templating artifacts have to be visible too. There are no validity or syntax rules for mere `.txt` files, so there is no way the *natural templates* concept can apply...
