### ISSUE TITLE
Is there any way to render thymeleaf tag dynamically which is coming from back-end?

### ISSUE THREAD

**Issue by chandrasekhar4u** [thymeleaf/thymeleaf#671]
I am getting thymeleaf tag from back-end inside json content, is there any way to process the tag and render on screen, which is coming from back-end at run time?
```
{ 
"title" : "Page Title",
"text" : "blah blah blah blah <div th:include=\"include::include\">my content</div>"
}
```
Please find more details in SOF [Question](https://stackoverflow.com/q/48897065/1213738).

**Comment by danielfernandez** [comment]
If you read that JSON from Java, you will need to parse that JSON, extract the Thymeleaf part, and then render it calling a `TemplateEngine` object.

If you read that JSON from JavaScript, then I'm afraid your possibilities are scarce given Thymeleaf is a server-side template engine. Anyway, there is a prototype for what may one day become an official JavaScript version of Thymeleaf here: https://github.com/ultraq/thymeleafjs

**Comment by chandrasekhar4u** [comment]
Hi @danielfernandez,
Thank you for the reply.

I read json from JAVA, do we have any examples to use TemplateEngine to render from Back-end at run time? Please let me know if there are any references.

**Comment by danielfernandez** [comment]
If you are using Spring, simply injecting a `SpringTemplateEngine` instance and calling one of its `process(...)` methods will do.

If you are not using Spring, you can create your own instance of `TemplateEngine` and call its methods. note however that it is recommended to keep that instance from execution to execution (they are quite heavy).

The GTVG sample application does use the `TemplateEngine` instance directly without Spring intervention. For example: https://github.com/thymeleaf/thymeleafexamples-gtvg/blob/3.0-master/src/main/java/thymeleafexamples/gtvg/web/controller/HomeController.java#L47

**Comment by chandrasekhar4u** [comment]
@danielfernandez I am using spring,
Do I need to extract thymeleaf tag and process it and put it back or I can just pass complete json string to process(...) Method?

**Comment by danielfernandez** [comment]
The `process(...)` method will either return you a `String`, or write to the `java.io.Writer` object you specify. Once you've your result, you can do what you need with it... I don't know if you need to replace the value in your JSON or whatever.
