### ISSUE TITLE
Improve use of abbreviation on template names in logs and exceptions

### ISSUE THREAD

**Issue by pfurbacher** [thymeleaf/thymeleaf#676]
Enhancement/Functionality Change: remove ```LoggingUtils.loggifyTemplateName()``` completely. There is no overriding need to elide fully qualified template filenames. Eliding them makes debugging unnecessarily harder, especially in the case of exceptions.

Description of the problem: 

```TemplateManager.resolveTemplate()``` calls ```LoggingUtils.loggifyTemplateName()``` in the exception handling block when it doesn't find a specified template. If the FQN (fully qualified path name) is long, the path is elided, thereby significantly crippling the ability of the programmer to understand why the resolver failed. An exception log message should give the programmer maximum info, so eliding the most relevant part of that message, the FQN, is probably the worst thing that could be done here. 

But I have to ask: why should **any** portion of **any** log message be programmatically elided? Doing so suggests that there's a max number of characters per log message, but that's certainly not the case, because the elision is being applied only to the ```templateName```, not the entire message. The purpose of logging is to expose information; if some of it is elided, what value does it have?

In my case, the classpath template resolvers (one with a pattern for ```html```, another for ```txt```) aren't finding templates which are absolutely, positively, on the classpath. But because of the elided message, I cannot tell what Thymeleaf's classpath resolver thinks it is looking for. (I have found that the Thymeleaf classpath resolver is problematic but I don't have a clear, reproducible example of where it fails. An issue for another day.)

Resolution: remove ```LoggingUtils.loggifyTemplateName()``` completely from the core codebase. Almost all the cases in the codebase involve logging at the ```trace``` level, but at least in one case, it is used in exception logging. There's really no advantage in **any case** for eliding the FQN of the template file.

**Comment by pfurbacher** [comment]
In my first comment, I mistakenly focused on long, *fully qualified* template filenames when I should have just written *long* template filenames (where *long* means greater than the 80 characters allowed in ```LoggingUtils.loggifyTemplateName()```, which even for template files on the classpath is easy to exceed, depending on package naming and nesting of templates).

If one is using a file resolver, it's very easy to exceed the 80 character length imposed in ```LoggingUtils.loggifyTemplateName()```. Hence, my request remains valid either way -- template paths should never be elided because doing so removes vital debugging info.

**Comment by danielfernandez** [comment]
Thanks for your message and your suggestions.

There are indeed reasons to abbreviate data going through the logs, even in TRACE level. Log cluttering is a potential issue for software diagnostics, and many frameworks abbreviate some types of data, being file paths and class names (packages) the most common.

As for the reason for the *template* being abbreviated in logs, it's precisely that: that what is abbreviated is the *template*, not specifically the *template name* or *template file* (the method name in `loggifyTemplateName(String template)` is actually misleading).

Thymeleaf template resolution is a generic extension point, and as such many mechanisms can be used for template resolution (even custom ones, created by users). And the `template` as a field is the input to that resolution mechanism, so it can be literally anything that can be expressed in a `String` and that can serve to identify a template. It is true that the template resolvers most used (directly) by users are file- or classpath-based, but Thymeleaf also includes out of the box a `StringTemplateResolver` which resolves the `String template` parameter itself as the template *contents* (not its name or its file path). This type of resolution is actually quite used internally by fragment expressions.

So even without taking into account that possible customized template resolution mechanisms could use very large `String`s as template identifiers, the `StringTemplateResolver` itself could cause huge log lines containing entire templates or large fragments of them. And that is actually one of the main reasons why that *loggify* mechanism needs to exist.

This said, there are indeed a series of improvements that could be done to the existing mechanism:

  * Remove the abbreviation mechanism from the throwing of `TemplateInputException`. You are right that in the case of an exception it makes little sense to abbreviate anything.
  * Increase the *no-modify* size to 120 characters. Could be a better working limit that would avoid abbreviation in many cases.
  * For those that are > 120 chars, rebalance the weights of the portions being preserved before and after the ellipsis (also noting that by changing from 80 to 120 we would have additional space), so probably a good measure could be to take the first 35 and the last 80 characters.

**Comment by danielfernandez** [comment]
Already in `3.0.10-SNAPSHOT`
