### ISSUE TITLE
How to access properties file in javascript for i18n

### ISSUE THREAD

**Issue by sachinavinaw** [thymeleaf/thymeleaf#677]
Hi,

I am new to thymeleaf.

I have a question. I want to access properties file for i18n initialization in my javascript file. There are some dynamic values created on runtime using javascript so I need to access properties file.

Code Snippet:
application.properties file::

`spring.messages.basename=lang/pMessageResource, lang/ErrorMessages, lang/commonMessageResource`

In javascript::

```javascript
 $.i18n.properties({
        name: 'pMessageResource',
        path: contextPath+'/lang',
        mode: 'both',
        language: lang,
        async: true,
        callback: function () {

        }
    });
```
Please tell me how is that possible.

Thanks in advance.

**Comment by danielfernandez** [comment]
I'm not really sure I understand your question, but I'm afraid there is no direct communication between message bundles in the Java side in a Spring application and JavaScript code running on the client browsers, at least through the template engine. Please note (just to make clear) that Thymeleaf runs on the Java server side, not JavaScript.

I'm not sure about the use or purpose of that `$.i18n.properties(...)`, but anyway I'm afraid the only way Thymeleaf could help here would be using [JavaScript inlining](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#javascript-inlining) somehow… and yet I don't think that would be a really clean solution. We are probably talking about a scenario completely unrelated to Thymeleaf as a template engine here, but please don't hesitate giving me more detail if I'm missing the link to Thymeleaf in your scenario…

**Comment by danielfernandez** [comment]
Closed due to user inactivity.
