### ISSUE TITLE
Thymeleaf js stitching html

### ISSUE THREAD

**Issue by ghost** [thymeleaf/thymeleaf#685]
I have such a problem. I need to add html syntax in js. He looks like this.

If I need to add a jump controller method and add parameters in the href, how do I need to write? Or is there a better way for thymeleaf to implement this function?

**Comment by ghost** [comment]
![qq 20180428141505](https://user-images.githubusercontent.com/23186004/39392805-2e228b1e-4aef-11e8-8023-039d06d72fb3.png)

**Comment by 0nebean** [comment]
maybe you can try this technology stack
http://aui.github.io/art-template/index.html
thymeleaf tag and thymeleaf-extras-springsecurity sec tag can work on it too!
![image](https://user-images.githubusercontent.com/37864816/39683672-6fa6e0f2-51e9-11e8-8b55-57f4c04375e0.png)
one line code to call,elegant and simple
![image](https://user-images.githubusercontent.com/37864816/39683685-7c1085fa-51e9-11e8-9ac7-8c5a0dcb2ff9.png)

**Comment by danielfernandez** [comment]
For this kind of scenarios I would recommend the use of a `<template>` HTML tag, or `<script type="text/template">`. Thymeleaf can be used to process both types of tags as HTML.
