### ISSUE TITLE
New feature: Let use the dates.format method with i18n through a Spring MVC object Model

### ISSUE THREAD

**Issue by manueljordan** [thymeleaf/thymeleaf#686]
All is explained here:

[Thymeleaf: how use the dates.format method with i18n through object model](https://stackoverflow.com/questions/50079050/thymeleaf-how-use-the-dates-format-method-with-i18n-through-object-model)

Assuming there is no a current support for this scenario: the goal is add this feature for the `dates.format` method and the other versions too accomplish my request.

Thus from a `@Controller` with

* `model.addAttribute("dateFormatPattern", "date.format.pattern");`

I want change from

* `"${#dates.format(persona.fecha, #messages.msg('date.format.pattern'))}"`

to 

* `"${#dates.format(persona.fecha, #messages.msg(dateFormatPattern))}"`

Consider the scenario is where there is a high potential possibility to change `date.format.pattern` value to other and thus it to be reflected through many views (`html` files about reports where the `Date` field is used) than the `dateFormatPattern` key instead.

Thus if `date.format.pattern` is changed to `date.format.abc.pattern` it should be in the server side, not for each `.html` file. Therefore `dateFormatPattern` (the _key_ of the attribute) remains without changes

Thank you

**Comment by danielfernandez** [comment]
This line you mention yourself works as you seem to expect:
```
${#dates.format(persona.fecha, #messages.msg(dateFormatPattern))}
```
I'm therefore closing this. Please feel free to reopen if I'm missing anything.

**Comment by manueljordan** [comment]
No, you understood wrong.

* `"${#dates.format(persona.fecha, #messages.msg('date.format.pattern'))}"` Works
* `${#dates.format(persona.fecha, #messages.msg(dateFormatPattern))}` does not work

From `model.addAttribute("dateFormatPattern", "date.format.pattern");` I want work around through the key `dateFormatPattern` and not _directly_ through the value `date.format.pattern`

**Comment by danielfernandez** [comment]
> * `${#dates.format(persona.fecha, #messages.msg(dateFormatPattern))}` does not work

This does work for me (being `dateFormatPattern` a context variable that contains the name of an externalized message such as `'date.format.pattern'`). Could you please specify what is the error you are receiving and, also, the version of Thymeleaf you are using?

**Comment by manueljordan** [comment]
Yes, it works how is expected. Not sure what was wrong. Ok. Closed this issue.
