### ISSUE TITLE
Bug when used with easyUI?

### ISSUE THREAD

**Issue by diorslau** [thymeleaf/thymeleaf#699]
When using easyUI to set up cloumns:[[]], does themeleaf parse the wrong report because of the problem of the symbol [[]]?

**Comment by diorslau** [comment]
It has nothing to do with easyUI, because it declares a VAR = [[]] in JS; after such variable, it is wrong.

**Comment by wwwqyhme** [comment]
try to disable inline like this
```html
<script th:inline="none">
var v = [[]];
</script>
```

**Comment by diorslau** [comment]
@mhlx  thanks
