### ISSUE TITLE
Possibility to define custom global formatter.

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf#7]
It would be nice to have opportunity to define global formatter according to Java type. For example define your own formatter for every java.util.Date that you don't have to use #dates.format for every Date.

**Comment by danielfernandez** [comment]
As a documentation comment, when this is evaluated, think about adding an attribute to the standard dialect like "th:date-format" that allows the establishment of such formats (besides allowing a programmatic Java configuration, which would be default).

**Comment by danielfernandez** [comment]
Since the release of Thymeleaf 2.1, this is covered by the integration with the Spring conversion service. See http://www.thymeleaf.org/whatsnew21.html#spconv
