### ISSUE TITLE
Selector add # and $ like th:insert="content::#${showtype}. 

### ISSUE THREAD

**Issue by fanqie03** [thymeleaf/thymeleaf#700]
I want to use select by variable value,bur show wrong
`<div class="col-md-6" th:insert="content::#${showtype}"></div>`

org.thymeleaf.exceptions.TemplateInputException: Error resolving fragment: "~{content :: '#${showtype}'}": template or fragment could not be resolved (template: "show" - line 52, col 26)

how could i deal with it

**Comment by fanqie03** [comment]
my solution is:

                         <div class="col-md-6" th:switch="${showtype}">
				<div th:case="safe-composite">
					<div th:replace="content::#safe-composite"></div>
				</div>
				<div th:case="transparent-composite">
					<div th:replace="content::#transparent-composite"></div>
				</div>
				<div th:case="spring">
					<div th:replace="content::#spring"></div>
				</div>
				
				<div th:case="hibernate">
					<div th:replace="content::#hibernate"></div>
				</div>
				<div th:case="abstract-factory">
					<div th:replace="content::#abstract-factory"></div>
				</div>
				<div th:case="factory-method">
					<div th:replace="content::#factory-method"></div>
				</div>
				<div th:case="simple-factory">
					<div th:replace="content::#simple-factory"></div>
				</div>
				<div th:case="singleton">
					<div th:replace="content::#singleton"></div>
				</div>
				<div th:case="multiton">
					<div th:replace="content::#multiton"></div>
				</div>
				<div th:case="class-adapter">
					<div th:replace="content::#class-adapter"></div>
				</div>
				<div th:case="object-adapter">
					<div th:replace="content::#object-adapter"></div>
				</div>
			</div>

**Comment by wwwqyhme** [comment]
try this
```html
<div th:with="showtype_id=~{content::'#'+${showtype}}">
<div class="col-md-6"  th:insert="${showtype_id}"></div>
</div>
```
