### ISSUE TITLE
Fragment with List as input

### ISSUE THREAD

**Issue by majestade** [thymeleaf/thymeleaf#702]
Hello. I am trying to insert a fragment in my page and i have two inputs, a String and a List.
I have already debugged the code so i know the list i'm passing has all the values i want. But when i render the page where my replacement is... i get an error
Can you help please!? Thanks!!

Fragment code:

```
<div th:fragment="message (input, list)">
<p>Hello...<span th:text="${input}"></span></p>
	<div th:if="${not #lists.isEmpty(list)}">
        <table class="table table-striped">
           <tr>
               <th>Name</th>
               <th>Description</th>
           </tr>
           <tr th:each="meter : ${list}">
           	   <td th:text="${meter.name}"></td>
           	   <td th:text="1"></td>
      	   </tr>
       	</table>
	</div>
</div>
```

Replacement code:
```
<div th:replace="fragments/test :: message (input='Pedro', list='${meters}')"/>
```
Error message:
Exception evaluating SpringEL expression: "meter.name" (fragments/test:10)

**Comment by ultraq** [comment]
Are you able to view the stack trace behind the error?  There might be something in there that's more helpful as to why `meter.name` wasn't able to be evaluated.  Some reasons might be that `meter` is `null` or there is no corresponding accessor to the "name" property (eg: no `getName` method or publicly visible `name` field).

**Comment by wwwqyhme** [comment]
`list='${meters}' ` is recognized  as String ,try `list = ${meters}`

**Comment by danielfernandez** [comment]
@mhlx's answer seems the reason to me. I'm therefore closing this, please reopen if needed.
