### ISSUE TITLE
Need Help，something with  ${}

### ISSUE THREAD

**Issue by MJ1997** [thymeleaf/thymeleaf#728]
` <a class="btn btn-sm btn-primary apage"  th:href="@{/admin/users/?page=}+${curpage+1)}">Next </a>`      
` <a class="btn btn-sm btn-primary apage"  th:href="@{/admin/users/?page=}+${curpage-(-1)}">Next </a>`      
i just want to 1+1 =2 ,but the result always is 11 .   help~

**Comment by ultraq** [comment]
Also, not specifically a thymeleaf-spring issue, so gonna try new Transfer feature and move it to general thymeleaf.

**Comment by ultraq** [comment]
Old issue w/ no follow-up from OP, so closing.
