### ISSUE TITLE
StackOverflowError error with upgrade from 2.1.5 to 3.11 (with Spring)

### ISSUE THREAD

**Issue by gsender** [thymeleaf/thymeleaf#731]
I tried to upgrade my application from Spring boot 1.4.7.RELEASE to Spring boot 2.0.7 This also upgraded Thymeleaf from 2.1.5 to 3.11.. With the new version I get an StackOverflowError with my templates. 

My template starts with (login.html):

 ```
<!DOCTYPE html>
 <html xmlns:th="http://www.thymeleaf.org" th:include="blanktemplate :: page(#{login.titel})">
```
 later I define some fragments: 

```
<div th:fragment="head">
	<script type="text/javascript">
		$(function() {
			$("#signbutton").button();
		});
	</script>
</div>

```

the file _blanktemplate.html_ then references these fragments.

```
...
<title th:text="${pageTitle}">ThymeLeaf Title</title>

<link rel="shortcut icon" href="/images/favicon.ico" th:href="@{/favicon.ico}" type="image/x-icon" />
 
<!-- Hier wirden Kopfelemente aus der Seite ins Template übernommen -->
<th:block th:include="this :: head"></th:block>

</head>
```

I have added both files in full lenght. 

If I remove the _th_include:_ in the 2nd line, then the file is processed without error (although no usefull format).

Is this a bug (because it worked with 2.0) or should I do this differently?

Thanks

[blanktemplate.html.txt](https://github.com/thymeleaf/thymeleaf/files/2737378/blanktemplate.html.txt)
[login.html.txt](https://github.com/thymeleaf/thymeleaf/files/2737379/login.html.txt)

**Comment by ultraq** [comment]
Does it work if you change the name of your fragment from `head` to anything else, and then update your `th:include` to point to the updated fragment name?  My initial suspicion is that the `th:include="this :: head"` is causing an infinite loop as `this :: head` could also resolve to the `<head>` element of your template which then tries to include itself and so on.

The right-hand side of the fragment selector syntax is a kind of hybrid fragment name + CSS selector + XPath selector thing which is briefly mentioned in the docs on template layout (https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#fragment-specification-syntax) but then expanded upon in the Appendix (https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#appendix-c-markup-selector-syntax).

Fragment selectors were something that was reworked between Thymeleaf 2 and 3, which could explain why the behaviour was changed.

**Comment by gsender** [comment]
YES, you nailed it. changing the reference/name for the fragments to "kopf" (german for head) fixed the problem. Thanks!!
