### ISSUE TITLE
Configuring TemplateEngine to ignore all <script>s

### ISSUE THREAD

**Issue by schoeneu** [thymeleaf/thymeleaf#734]
One of my applications has templates and contain `[[` and `]]` in `<script>` blocks. Since these templates are externally generated and automatically provided, the solution of adapting the template suggested in https://github.com/thymeleaf/thymeleaf/issues/432 is rather hard to do. Fortunately, the contents of the `<script>`s do not need to be templated, so I'm looking for a solution to just ignore all content of `<script>` blocks *in code* rather than *by editing the template*.

Is there an easy way to do this? (I do realize that this might be an antipattern and changing the templates is the preferred solution.)

**Comment by danielfernandez** [comment]
`th:inline="none"` should do the trick, see https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#disabling-inlining 

But you need to apply that attribute to the `<script>` blocks, so if you cannot change those, I'd suggest using the _decoupled templates_ feature that allows you to add processors (in this case, attributes) to your markup templates without actually modifying them: https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#decoupled-template-logic

**Comment by schoeneu** [comment]
Thanks - decoupled templates might do the trick! :)
