### ISSUE TITLE
Option to disable restricted mode

### ISSUE THREAD

**Issue by chrylis** [thymeleaf/thymeleaf#735]
I understand that restricted mode is something that you consider valuable, but (1) it is not mentioned _anywhere_ in the documentation, resulting in unexplained failure scenarios, and (2) there is no (known-to-me) workaround for the standard case of composing pages via Layout Dialect. The boilerplate tutorials for "how to write a Spring Security login form with Thymeleaf" just mysteriously don't work.

Access to `param` is a longstanding documented feature, and "restricted mode" breaks it in undocumented and unfixable ways.

**Comment by LuisV** [comment]
Is there an option for this yet? I was following the tutorials for request parameters but they now longer work.

**Comment by mikehearn** [comment]
Is this being ignored deliberately? :( I just hit this:

1. Surprising, not documented anywhere.
2. Irrelevant for my use case, where all inputs are trusted (not web serving but static file rendering).

@danielfernandez  Is there a way to disable this?

**Comment by danielfernandez** [comment]
The _restricted mode_ is a feature totally needed by Thymeleaf in order for this project not to be flooded with CVEs from security audits that declare vulnerabilities on Thymeleaf based on things that a template engine should IMHO not be validating at all :). So I'm terribly sorry, but it cannot be disabled, and my prediction is that it can probably get _worse_ with time. This is how software security works now.

**Comment by mikehearn** [comment]
It would at least be good to document what this mode is and what the rules are.
