### ISSUE TITLE
 in pure String template , how to use `th:include`?

### ISSUE THREAD

**Issue by zhangtianxiao** [thymeleaf/thymeleaf#738]
/*
            in pure String template , how to use `th:include`?
            Thanks
            * */
            String html = "<div th:include='fragment'></div>";
            TemplateEngine teg = new TemplateEngine();
            Context ctx = new Context(Locale.CHINESE, data);
            String process = teg.process(html, ctx);

**Comment by zhangtianxiao** [comment]
I think that `ctx` needs a base path, or a current template path,
`TemplateEngine` can find  file by fragment's value( relative path or absolute path)

**Comment by guchenjun** [comment]
你觉得你说得很有道理，Right.
