### ISSUE TITLE
Outdated OGNL dependency throws spurious messages System.err

### ISSUE THREAD

**Issue by jdhoek** [thymeleaf/thymeleaf#739]
Thymeleaf `3.0.11.RELEASE` depends on OGNL `3.1.12`. With Java 8 this version of OGNL has a bug (https://github.com/jkuhnert/ognl/issues/35) that causes it to throw messages on `System.err`:

> Two methods with same method signature but not providing classes assignable? "public abstract boolean java.util.List.isEmpty()" and "public boolean java.util.AbstractCollection.isEmpty()" please report!

This happens at each invocation of the Thymeleaf template engine, so the amount of output generated is considerable.

OGNL backported the fix for this bug to their `3.1.*` branch (https://github.com/jkuhnert/ognl/pull/41). Perhaps Thymeleaf could update to version `3.1.16` or newer?

**Comment by deved65** [comment]
If you are managing the ognl dependency manually, like I do using maven, you could try latest release of 3.1.x branch of OGNL which is currently 3.1.25. This appears to be working for me under Java 11. But I did not build the thymeleaf project against this version... thus did not run the complete unit/integration test of thyemleaf; it is just user experience.

**Comment by danielfernandez** [comment]
OGNL was updated to 3.1.26 by means of 2da733d (See #727).

As you mention, according to jkuhnert/ognl#41 the fix for this has been backported to the 3.1.x branch of OGNL, so this update should fix it for Thymeleaf too.

**Comment by qiushuei** [comment]
unsubscribe.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Daniel Fernández"<notifications@github.com&gt;; 
发送时间: 2020年11月17日(星期二) 上午6:57
收件人: "thymeleaf/thymeleaf"<thymeleaf@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: Re: [thymeleaf/thymeleaf] Outdated OGNL dependency throws spurious messages System.err (#739)






关闭#739.

—
您正在接收此消息，因为您订阅了此线程。
直接回复此邮件，在GitHub上查看，或取消订阅.
