### ISSUE TITLE
Performance degradation in Link URLs

### ISSUE THREAD

**Issue by marcelopbarros** [thymeleaf/thymeleaf#740]
While I was using URL links in a big table I could note that there is a huge performance degradation in `@{...}` syntax.

The example bellow illustrates the difference between using `@{...}` syntax and _string_ concatenation to generate 5000 objects with an URL. The _string_ concatenation test caches the _urlBase_ in `urlBase=@{/}` executing way faster then the other case.

```html
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
<body th:with="max=5000,urlBase=@{/}">

	<!-- Test 1 - Concatenate URL -->
	<script th:inline="javascript">var time1 = (/*[[${T(System).currentTimeMillis()}]]*/ '');</script>
	<div th:each="i:${#numbers.sequence(1, max)}" style="display: none;">
		<a th:href="|${urlBase}${i}|" th:text="${i}"></a>
	</div>
	<script th:inline="javascript">time1 = (/*[[${T(System).currentTimeMillis()}]]*/ '') - time1;</script>
	<script>document.write('<h3>Test1: ' + time1 + ' ms</h3>')</script>

	<!-- Test 2 - Generate URL -->
	<script th:inline="javascript">var time2 = (/*[[${T(System).currentTimeMillis()}]]*/ '');</script>
	<div th:each="i:${#numbers.sequence(1, max)}" style="display: none;">
		<a th:href="@{/${i}}" th:text="${i}"></a>
	</div>
	<script th:inline="javascript">time2 = (/*[[${T(System).currentTimeMillis()}]]*/ '') - time2;</script>
	<script>document.write('<h3>Test2: ' + time2 + ' ms</h3>')</script>
	
</body>
</html>
```

So, my point is: it'd be nice if **Thymeleaf** itself could cache the base URL and use, internally, the _string_ concatenation to generate URLs.

**Comment by danielfernandez** [comment]
With Thymeleaf 3.0.11, I'm getting these results the first time this is executed:
```
Test1: 201 ms
Test2: 118 ms
```
And then from then on, in subsequent executions something like...
```
Test1: 101 ms
Test2: 93 ms
```

I don't think these differences are significative or point to a performance issue. And in fact link expressions seem to get (very) slightly better performance... could you please specify which version of Thymeleaf you were using for these tests?

**Comment by marcelopbarros** [comment]
Hi @danielfernandez! Thank's for taking your time! I realize that my issue was really missing some data.

I was testing here again, and I realize the problem didn't occur in a new project, only in the one I work on. I looked for the cause and found that the performance drop only occurred if one of the Resource Handling Chain strategies were active. Thus, to demonstrate the problem, it would be necessary to include the information below in the application.properties:

```properties
spring.resources.chain.strategy.content.enabled = true
```

And this is how I start the environment:

```java
import static org.springframework.boot.SpringApplication.run;
import org.springframework.boot.autoconfigure.SpringBootApplication;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.servlet.config.annotation.ViewControllerRegistry;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;

@SpringBootApplication
public class PerformanceApplication {

	public static void main(String[] args) {
		run(PerformanceApplication.class, args);
	}

	@Configuration
	public static class WebConfig implements WebMvcConfigurer {

		@Override
		public void addViewControllers(ViewControllerRegistry registry) {
			registry.addViewController("/testing").setViewName("testing");
		}
	}
}
```

The performance drop was huge. In average:

> Test1: 79 ms
> Test2: 1149 ms

Looking what's the cause of the problem, I found that the performance drop occurred after [Thymeleaf LinkBuilder request the link encode](https://github.com/thymeleaf/thymeleaf/blob/3a8366126d51461e59bfdc5676fea334b1184a72/src/main/java/org/thymeleaf/linkbuilder/StandardLinkBuilder.java#L528). More specifically in the [ResourceUrlEncodingFilter](https://github.com/spring-projects/spring-framework/blob/241afeb1b74be954ddb43b8faba70b956c6c021d/spring-webmvc/src/main/java/org/springframework/web/servlet/resource/ResourceUrlEncodingFilter.java#L127) when call [ResourceUrlProvider getForLookupPath method](https://github.com/spring-projects/spring-framework/blob/fc5e3c335f2b7901d2bdfa2d783dec4352dde906/spring-webmvc/src/main/java/org/springframework/web/servlet/resource/ResourceUrlProvider.java#L217).

I've tested in **Spring Boot 2.2.11** and **2.3.5**, both with **Thymeleaf 3.0.11**.

**Comment by danielfernandez** [comment]
So it's a performance drop that can be justified on the encoding of the URL by the Spring resource infrastructure, right? whereas when the URL is built by mere appending of strings, such call to the Spring resource infrastructure never happens and therefore no performance drop is apparent.

So I'm going to close this ticket for not being imputable to Thymeleaf. But please don't hesitate to reopen if I'm missing something.
