### ISSUE TITLE
how to access model data from external javascript file?

### ISSUE THREAD

**Issue by qiudaozhang** [thymeleaf/thymeleaf#747]
thymeleaf  version :3.0.11.RELEASE

I use springboot and thymleaf, I add a attribute in the model.
![Snipaste_2019-05-30_17-30-56](https://user-images.githubusercontent.com/34365540/58623541-ca5f6980-8300-11e9-85c0-1ab3889c6d71.jpg)

and import the javascript file like this ,
![image](https://user-images.githubusercontent.com/34365540/58623630-fe3a8f00-8300-11e9-8b24-706820925421.png)
, in external file i use like this 
![image](https://user-images.githubusercontent.com/34365540/58623742-3f32a380-8301-11e9-882f-ddf8ae194506.png)
it can't work.

I use it like this . it can work i know .
![image](https://user-images.githubusercontent.com/34365540/58623840-72753280-8301-11e9-9eb7-d518e8adf1bd.png)

So , my question is ,how to access the model data in external javascript file

**Comment by SylvainAssemat** [comment]
Hi

I used to do it with this syntax from an .html file in "templates" root folder

```
      <script th:inline="javascript"
              th:insert="~{../static/js/test.js}">
            </script>
```
other alternative : 

```
      <script th:inline="javascript">
            /*<![CDATA[*/
            /*[+ [# th:insert="~{../static/js/common.js}"        /] +]*/
            /*]]>*/
      </script>
```

@danielfernandez , is this a better way to do it ?

What about the use of "module" approach ES6 in external js file calling like above ?
`import { myfunction} from '/js/test.js';`
I can not find any example or possibilities in the 3.1 documentation.

Maybe a work in progress ?
