### ISSUE TITLE
Block "javascript:" scheme in Link Expressions

### ISSUE THREAD

**Issue by alanfranz** [thymeleaf/thymeleaf#754]
Hello Thymeleavers,
I've got a doubt about what I'd consider a surprising behaviour for Thymeleaf URL handling.

Let's go straight to an example: if I write something like that in a template:

```
<a href="" data-th-href="@{${name}}">clickme</a>
```

Then, if my *name* parameter contains a valid URL with a ```javascript``` scheme, like ```javascript: alert('hello world');``` , this could result in a code injection if the name parameter is not sanitized. Tested on Thymeleaf 3.0.11.

Of course, the behaviour is totally correct - ```javascript: alert('hello world');``` is a valid URL after all - so why am I in doubt? Because:

* as per #705 (and other restricted execution context discussions), Thymeleaf seems to take security very seriously. In a on* attribute I cannot use variables that return non-boolean, non-number expressions, but then I can blindly inject javascript-schemed URLs anywhere;
* As per documentation, the Link Expression syntax - https://www.thymeleaf.org/doc/articles/standardurlsyntax.html - **seems to be quite bound to http/https**.  Even the doc says that ```absolute urls [...] start by specifying a protocol name (http:// or https://)```. What if they don't start with http or https? The link expression syntax is quite useless in that context, but no error is reported.
* The chance of having a non-http or non-https scheme seems to never be discussed in the docs, so, maybe this could be an oversight?

I'm not sure what the solution could and should be; of course, there's always the chance that somebody inserts data in an href (or other attributes that accept URLs) WITHOUT the link expression syntax... and I'm not sure what's the right thing to do in that case, even though the scenario looks quite similar to #705. If Thymeleaf intentionally leaves out such kinds of protection from URL attributes, the documentation should be very clear about that.

But, I believe that, for the way Link Expressions work, they should produce an error if the resulting scheme is not http or https. They just don't seem intended for that purpose.

Bye!

**Comment by alanfranz** [comment]
Hello @danielfernandez (I'm tagging you because you seem to be the lead developer AND the latest committer on StandardLinkBuilder.java as well), **I wouldn't push this if I didn't think this could be a security problem** as well as a functional one.

I can code and submit a patch if you feel my intentions are viable, I'd need a bit of feeback on this. The patch may be to the software or to the docs.

I did a bit of research about URLs, it seems that the reference RFCs are https://www.ietf.org/rfc/rfc1738.txt along with https://tools.ietf.org/html/rfc3986 , and there's the working group at https://url.spec.whatwg.org/ .

Now, as I stated in the previous ticket: it seems to me, according both to the documentation and to thymeleaf source code (i.e. check StandardLinkBuilder.java) and tests (https://github.com/thymeleaf/thymeleaf-tests/blob/3.0-spring51/src/test/java/org/thymeleaf/linkbuilder/LinkBuilderTest.java) that the link expression message was created for http/https URLs, with a "special provision" for the ```mailto:``` scheme. The tests don't even test URLs with any scheme, they seem to rely on the "default" behaviour.

So, **my impression is that those two schemes are the only ones that were considered when creating and testing the link expression language**. Other schemes seem to be an accidental fit.

What about other schemes? Is it really meaningful to try processing any URL scheme with the current StandardBuildLinker logic? For the records, a ```javascript:``` URL is currently categorized as BASE_RELATIVE . 

My 2c:
* only enable schemes that are safe and/or for which the expression message makes sense. http, https, and mailto are prime examples. Maybe some other schemes could still make sense (ftp? websocket? others?), but many others won't; I think a whitelist approach would work better.
* Allow users to hook someway in the mechanism, in order to make other schemes work.
* Update docs.

**Comment by danielfernandez** [comment]
Please note that totally avoiding scenarios such as your example in which the `name` variable might contain a `javascript:...` link is out of reach for a template engine:
```html
<a href="" data-th-href="@{${name}}">clickme</a>
```
Thymeleaf can make sure that the `javascript:` scheme is not used in the base of a link expression (`@{...}`) and that looks helpful, but nothing can stop a developer from writing things like this:
```html
<a href="" data-th-href="${name}">clickme</a>
```
Sanitizing context variables (_model attributes_ in Spring jargon) cannot be the responsibility of the template engine. Note that context variables are _not_ direct user input: they have been explicitly added to the context at the controller level, and the template engine should not be policing the actions expliclty taken at the controller.

Thymeleaf takes this kind of protection as far as possible with the _restricted expression evaluation mode_ (see #809) which disallows certain executions and accesses in certain contexts (for instance, no access to request parameters –direct user input– in link expressions).

As for allowing certain schemes only in link expressions: I see your point. However the original reason for the existence of link expressions is to make all published URLs go through the `HttpServletResponse#encodeURL(...)` mechanism. Most implementations of this mechanism (including e.g. Tomcat's) only pay attention to `http` and `https` schemes, but this is an extensible mechanism that is used in some contexts for complex resource link management, caching, redirection policies, etc. and a whitelisting policy on schemes could harm some of these potential uses, when what we are really interested on is in avoiding –and only to some extent– the unwanted execution of javascript code.

So I believe forbidding `javascript` schemes in the base of link expressions (`@{...}`) will be a good addition, and that's what will be implemented.

**Comment by alanfranz** [comment]
> Thymeleaf can make sure that the `javascript:` scheme is not used in the base of a link expression (`@{...}`) and that looks helpful, but nothing can stop a developer from writing things like this:
> 
> ```
> <a href="" data-th-href="${name}">clickme</a>
> ```
> 
> Sanitizing context variables (_model attributes_ in Spring jargon) cannot be the responsibility of the template engine.

Of course. In fact I've never cited non-link expressions - that's not something that the template engine could and should act upon. My only surprise was in link expressions.
 
> So I believe forbidding `javascript` schemes in the base of link expressions (`@{...}`) will be a good addition, and that's what will be implemented.

OK, seems reasonable. I'd probably like the documentation to explain the behaviour with a bit more detail, I'll try contributing a PR soon. URLs are an easy attack vector sometimes.

Thanks for your interest.
