### ISSUE TITLE
Incorrect parsing of self closing tags

### ISSUE THREAD

**Issue by calum-hl** [thymeleaf/thymeleaf#755]
After upgrading to Thymeleaf 3 (as part of a Spring Boot upgrade), we are experiencing an issue, which might be due to the new parsing engine?

Thymeleaf: 2.1.5
`<span class="icon view-icon"/> <span th:text="#{someExpression}"/>`

Thymeleaf: 3.0.11
`<span class="icon view-icon"/> <span th:text="#{someExpression}"/>`
renders as incorrectly as 
```
<span class="icon view-icon"> <span>Text</span>
        </span>
```

Work around:
Changing it to:
`<span class="icon view-icon"> </span> <span th:text="#{someExpression}"/>`
causes it to render correctly as 
`<span class="icon view-icon"> </span> <span>Text</span>`

**Comment by ultraq** [comment]
While I'm not intimate with the HTML parser of Thymeleaf, I do believe what you've experienced is the switch from Thymeleaf 2's XML-based parsing engine to Thymeleaf 3's HTML one which, while closer to the HTML spec, may have some surprises for those more used to XML.

For example, the `<span>` element in the HTML spec defines that neither the start nor end tags can be omitted:

> **Tag omission in text/html:**
>   Neither tag is omissible.

Source: https://html.spec.whatwg.org/multipage/text-level-semantics.html#the-span-element

Therefore, the element cannot be self-closed and so `<span/>` is invalid HTML.

So Thymeleaf 3 will try to balance the tags in some way, which in this case ends up with something you didn't want.  Writing out the necessary end tags would be the most HTML-spec compliant solution, but your workaround of writing just that first `</span>` with Thymeleaf's tag balancing can can do the trick too.
