### ISSUE TITLE
Getting null with Selection Variable Expressions.

### ISSUE THREAD

**Issue by kreuzman** [thymeleaf/thymeleaf#76]
`<div th:object="${someObject}" th:remove="tag">
     <div th:text="*{getter}"/>
</div>`

With this code above I getting null while accessing *{getter}. That's happening because of th:remove="tag". Working well in version 2.0.8.

**Comment by danielfernandez** [comment]
Hi,

This is already solved in 2.0.13-SNAPSHOT. See the last messages in http://forum.thymeleaf.org/th-object-and-th-remove-in-one-tag-td3771071.html

Thanks,
Daniel.

**Comment by kreuzman** [comment]
Hi,

thanks I missed topic in forum.

Thanks for reply.
Michal
