### ISSUE TITLE
关于Thymeleaf 3.0.11.RELEASE版本,IFragmentSpec接口找不到问题

### ISSUE THREAD

**Issue by xhc-code** [thymeleaf/thymeleaf#761]
您好，我在thyme leaf中遇到关于渲染模板片段的接口在3.11版本不存在的问题，请问，在Thymeleaf 3.0.11.RELEASE版本中，找不到org.thymeleaf.fragment.IFragmentSpec接口及相关实现，但在Thymeleaf3的文档中有进行此接口的使用说明(https://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#rendering-template-fragments)
，是此接口移动到其他扩展包？还是进行重新命名了？我在Thymeleaf 2.1.6.RELEASE版本中可以查找到IFragmentSpec接口及其相关实现。请问是什么原因呢？

**Comment by starSmallDream** [comment]
请问是说明原因呢？  ==》 请问是什么原因呢？

**Comment by frostblazergit** [comment]
translate:

```
Hello, I encountered a problem in the thyme leaf that the interface for rendering template fragments does not exist in version 3.11.
In the version of Thymeleaf 3.0.11.RELEASE, the org.thymeleaf.fragment.IFragmentSpec interface and related implementations were not found, but there are instructions for using this interface in the Thymeleaf3 documentation (https://www.thymeleaf.org/doc/tutorials/3.0/thymeleafspring.html#rendering-template-fragments).
Is this interface moving to other extensions? Renamed?
I can find the IFragmentSpec interface and its related implementation in the Thymeleaf 2.1.6.RELEASE version.
What is the reason?
```

Removal of classes? #502 

https://github.com/thymeleaf/thymeleaf/issues/502#issuecomment-221976843

Please use English.

**Comment by danielfernandez** [comment]
All `process(...)` methods in `TemplateEngine` in 3.0.x include a `templateSelectors` argument that allows the specification of a template fragment (or several), so that only those are executed.
