### ISSUE TITLE
how to return html in json object?

### ISSUE THREAD

**Issue by CoderOverflow** [thymeleaf/thymeleaf#767]
Controller returns "foo::table_refresh" which can get a html data to refresh a table with Ajax. I wonder how to make this html data into an object and return it from controller.
Class ResultObject {
String data = "foo::table_refresh";
}
@RestController
@RequestMapping(value="Test")
Public ResultObject test(){
ResultObject to = new ResultObject();
return ro;
}

**Comment by ultraq** [comment]
One way I can think of doing would be to invoke rendering yourself by calling Thymeleaf's template engine directly, then saving the result in whatever object you're planning to return.  Something like:

```java
@RequestMapping(value = 'test')
public String test(HttpServletRequest request, HttpServletResponse response,
  @Autowired SpringTemplateEngine templateEngine) {

  String html = templateEngine.process('your-html-page', new WebExpressionContext(templateEngine.getConfiguration(), request, response, request.getServletContext()));
  ResultObject result = new ResultObject();
  result.data = html;
  return result;
}
```

**Comment by ultraq** [comment]
Not sure if correctly answered, but no follow-up from the OP, so closing.
