### ISSUE TITLE
Syntax Highlighting in IntelliJ

### ISSUE THREAD

**Issue by tamb** [thymeleaf/thymeleaf#768]
I'm pretty desperate for syntax highlighting and I haven't been able to find any plugins.  It would really help with the readability and debugging the html attributes.

**Comment by ultraq** [comment]
IntelliJ has built-in support for Thymeleaf, though as noted on their help page it is only present in the Ultimate edition: https://www.jetbrains.com/help/idea/thymeleaf.html  It looks pretty much like their standard HTML/XML editors combined, with some content assist under some circumstances.
