### ISSUE TITLE
th:text does not escape 0x1f (UNIT SEPARATOR) character for xml/html

### ISSUE THREAD

**Issue by lgawron** [thymeleaf/thymeleaf#769]
0x1f character (UNIT SEPARATOR) is not allowed for xml/html documents yet the value is not escaped thus rendering the generated xml unparseable. 

If you do not treat this as bug, as there is no clear escape replacement for 0x1f (as with " > <) is there any way to plug in some additional escaping logic into the engine?

**Comment by danielfernandez** [comment]
Thymeleaf makes use of Unbescape's _Level1_ HTML escaping, as explained [here](https://www.unbescape.org/apidocs/unbescape/1.1.6.RELEASE/org/unbescape/html/HtmlEscapeLevel.html).

I've added this to Unbescape here: https://github.com/unbescape/unbescape/issues/29
