### ISSUE TITLE
thymeleaf 自定义标签

### ISSUE THREAD

**Issue by ztg-zlu** [thymeleaf/thymeleaf#771]
自定义标签，不可以直接写成，html模板吗？我记得，jsp可以直接写html.tag，这样的，不用在后台写。

还有一个问题，
`<div th:replace="common/common::xmSelect(参数1,参数2,参数3,参数4)`
这样写，也太长了，能不能简化成
`<th:replace="xmSelect(参数1,参数2,参数3,参数4)`

把片段，放入一个规定的路径中，这样，就可以，不用写路径了

**Comment by mgl-pub** [comment]
good
