### ISSUE TITLE
JDK 1.8 upgrade

### ISSUE THREAD

**Issue by srbala** [thymeleaf/thymeleaf#773]
Question/Feature regarding JDK support

Any plans to upgrade base JDK support to 1.8, might be with Thymeleaf 3.1.X or 4..x series and continued support for JDK 1.6 on Thymeleaf 3.0.x series. That gives option to make Spring 5 as prime candidate support

**Comment by jmiguelsamper** [comment]
Hi,

Thymeleaf works smoothly with any modern Java version and also with Spring 5.

Support for older versions does not prevent using the library with newer versions.
