### ISSUE TITLE
#messages.msgOrNull(key) is not returning null when a message for the specified key is not found - Spring

### ISSUE THREAD

**Issue by antemooo** [thymeleaf/thymeleaf#776]
The main problem is when using `#messages.msgOrNull(key)` it is returning `???key???` which means that is working exactly like `#messages.msg(key)` 

it should however  return **null** if the key is not found. as stated in the documentation 

https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#messages-1

**Comment by danielfernandez** [comment]
Sorry, none of our tests in 3.0.12 or 3.0.13 show this behaviour. I've re-tested in a web application both with and without Spring just in case, and it seems to be working as expected.

Please reopen with a working example if you are still experiencing this issue.

**Comment by yanegorz** [comment]
@danielfernandez 
Would it be possible to point which test covers the #messages.msgOrNull(key) utility?
It is my understanding that the test routine should give me some advice on what I am doing wrong, since I am experiencing the same issue.
