### ISSUE TITLE
elvis operator error

### ISSUE THREAD

**Issue by sysmat** [thymeleaf/thymeleaf#781]
* Version of Thymeleaf 3.0.11.RELEASE
* Environment: no Spring, stand alone, java 8, ClassLoaderTemplateResolver, TemplateEngine
* java Simple pojo:

```java
public class User {
        private String title;               
}

```
* html 

```html
<h1 th:text="${user?.title}">
      Hello, World!
</h1>

```

* error:
`org.thymeleaf.exceptions.TemplateProcessingException: Exception evaluating OGNL expression: "user?.title" (template: "user" - line 20, col 17)
`

**Comment by danielfernandez** [comment]
Your `User` class needs a getter for the `title` property. If not, this being a private property, the expression engine cannot access it.
