### ISSUE TITLE
Bug in numbers.formatInteger and numbers.formatDecimal

### ISSUE THREAD

**Issue by mahozad** [thymeleaf/thymeleaf#782]
<h1>Description</h1>

  * Thymeleaf v3.0.11.RELEASE
  * Spring Boot v2.1.0.RELEASE (irrelevant to the bug)
  * JDK v12.0.2 (Java 11 or higher)

# Update 2020-11-17

There might be other subtle problems as well. For example thousands separators are not the same in different European countries and I think Thymeleaf does not produce correct formatting in this case either. So by fixing [The issue]() and also doing the following, all (or most of) the problems may be resolved.

Note that there was also a bug in Java [`DateTimeFormatter`](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/time/format/DateTimeFormatter.html) class. I filed an issue [here](https://bugs.java.com/bugdatabase/view_bug?bug_id=8243162) and the bug was [fixed](https://bugs.java.com/bugdatabase/view_bug?bug_id=8244245) in [Java 15](https://www.oracle.com/java/technologies/javase/15-relnote-issues.html#JDK-8244245).

In addition to the fix for [The issue](), any `DateTimeFormatter` creation should be accompanied by **`localizedBy(locale)`**:
  - `DateTimeFormatter`#`withLocale(locale)` should be replaced with `DateTimeFormatter`#**`localizedBy(locale)`**
  - `DateTimeFormatter.ofPattern(...);` etc.  should be accompanied by `.localizedBy(locale)` like this:
```DateTimeFormatter.ofPattern(...).localizedBy(locale);```

Also note that for [The issue](), if Java version is < 15, then the problem may still exist unless JDK developers backport the `DateTimeFormatter` fix to earlier Java versions.

# The issue

`${#numbers.formatInteger}` and `${#numbers.formatDecimal}` do not work correctly for locales other than `en_US`. This is also true for **numbers** returened by `${#temporals.format()}` (for example year).

Steps to reproduce the bug:

1. Somehow set the locale that Thymeleaf uses to `fa` (Persian language)
    - Note: Creating Persian locale:  `Locale locale = Locale.forLanguageTag("fa");`
2. Output a text in an element with `th:text="${#numbers.formatInteger(1234, 1)}"`
3. The result should be **۱۲۳۴** but it is **1234**

An easier way to see the bug:
```java
public static void main(String[] args) {
    Locale locale = Locale.forLanguageTag("fa");
    DecimalFormat format = (DecimalFormat) NumberFormat.getNumberInstance(locale);
    // TODO: Replace Locale.US below with locale and see what happens
    format.setDecimalFormatSymbols(new DecimalFormatSymbols(Locale.US));
    System.out.println(format.format(2020));
}
```

This bug has not been detected probably because languages such as English, French, Spanish and... use the same symbols and characters to represent numbers. Languages such as Persian, Arabic and maybe some others [use different symbols and characters to represent numbers](https://en.wikipedia.org/wiki/Eastern_Arabic_numerals).

# The origin of the bug and the solution

The problem is in the following line which sets the locale to `Locale.US` (intentional or just a mistake?) :

https://github.com/thymeleaf/thymeleaf/blob/3a8366126d51461e59bfdc5676fea334b1184a72/src/main/java/org/thymeleaf/util/NumberUtils.java#L226

It can be easily resolved by modifying the above line to use the `locale` parameter of the function:

https://github.com/thymeleaf/thymeleaf/blob/6903e0a5c545b054a3e60544d214c3d753f7035c/src/main/java/org/thymeleaf/util/NumberUtils.java#L226

@danielfernandez, @ultraq

**Comment by mahozad** [comment]
The issue was updated. Please see the top section of the issue.

**Comment by danielfernandez** [comment]
This is already in `3.0.12-SNAPSHOT`.

Note however that the Thymeleaf core does not create any instances of `DateTimeFormatter` because its code is Java6-compatible. I suggest you create an equivalent ticket at the https://github.com/thymeleaf/thymeleaf-extras-java8time subproject so that this can be correctly dealt with at the `java.time`-related artifacts, which will be part of the core in a future version.

**Comment by mahozad** [comment]
OK, thank you.
