### ISSUE TITLE
constructor ServletContextTemplateResolver in class org.thymeleaf.templateresolver.ServletContextTemplateResolver cannot be applied to given types

### ISSUE THREAD

**Issue by yahyadev69** [thymeleaf/thymeleaf#786]
Hell everybody , 

I start my first project  spring. 

I want to configure my  thymeleaf resolver for relate views and model.

I follow this documenattion to do that :

https://www.baeldung.com/thymeleaf-in-spring-mvc

in the bean ServletContextTemplateResolver i have a missing argument problem.

    @Bean  
    @Description("Thymeleaf Template Resolver")
    public ServletContextTemplateResolver templateResolver() {
        ServletContextTemplateResolver templateResolver;
        templateResolver = new ServletContextTemplateResolver();// here 
        templateResolver.setPrefix("/WEB-INF/views/");
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode("HTML5");

        return templateResolver;
    }

My question : what is the missed arguement in this classe  (new ServletContextTemplateResolver())  ?

I hope your isolation goes well,

Thank you and

**Comment by ultraq** [comment]
Looking at the docs for `ServletContextTemplateResolver` https://www.thymeleaf.org/apidocs/thymeleaf/3.0.11.RELEASE/org/thymeleaf/templateresolver/ServletContextTemplateResolver.html), it looks like the only constructor is one that takes a `ServletContext` object.

As for where to get that object to pass into the constructor, I believe one is already registered as a Spring bean by default (either a feature of Spring or Spring Boot), so can be accessed by adding it as a parameter to your method:

```java
@Bean
public ServletContextTemplateResolver templateResolver(ServletContext servletContext) {
  ServletContextTemplateResolver templateResolver = new ServletContextTemplateResolver(servletContext);
  ...
  return templateResolver;
}
```

**Comment by yahyadev69** [comment]
Thank you @ultraq for your answer.

Finally I use the following configurator ThymeleafViewResolver.

I find it on github . 

i use the maven dependancy : 
```
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-thymeleaf</artifactId>
		</dependency>
```

Now i can run my project.

```java
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.context.annotation.Description;
import org.springframework.web.servlet.ViewResolver;
import org.springframework.web.servlet.config.annotation.WebMvcConfigurer;
import org.thymeleaf.spring5.SpringTemplateEngine;
import org.thymeleaf.spring5.view.ThymeleafViewResolver;
import org.thymeleaf.templateresolver.ClassLoaderTemplateResolver;

@Configuration
public class AppConf implements WebMvcConfigurer {

    @Bean
    @Description("Thymeleaf template resolver serving HTML 5")
    public ClassLoaderTemplateResolver templateResolver() {

        ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();

        templateResolver.setPrefix("templates/");
        templateResolver.setCacheable(false);
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode("HTML5");
        templateResolver.setCharacterEncoding("UTF-8");

        return templateResolver;
    }

    @Bean
    @Description("Thymeleaf template engine with Spring integration")
    public SpringTemplateEngine templateEngine() {

        SpringTemplateEngine templateEngine = new SpringTemplateEngine();
        templateEngine.setTemplateResolver(templateResolver());

        return templateEngine;
    }

    @Bean
    @Description("Thymeleaf view resolver")
    public ViewResolver viewResolver() {

        ThymeleafViewResolver viewResolver = new ThymeleafViewResolver();

        viewResolver.setTemplateEngine(templateEngine());
        viewResolver.setCharacterEncoding("UTF-8");

        return viewResolver;
    }

   /* @Override
    public void addViewControllers(ViewControllerRegistry registry) {
        registry.addViewController("/").setViewName("index");
    }
    */
}
```

**Comment by Ornelio-Chauque** [comment]
@yahyadev69 thanks.

Changing the ServletContextTemplateResolver to ClassLoaderTemplateResolver on the configuration class worked for me.

From:
`@Bean
    public ServletContextTemplateResolver templateResolver(ServletContext servletContext){
        ServletContextTemplateResolver templateResolver = new ServletContextTemplateResolver(servletContext);
        templateResolver.setPrefix("/WEB-INF/templates/");
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode(TemplateMode.HTML);
        return templateResolver;
    }`
_________________________________________________________________
To:
` @Bean
    @Description("Thymeleaf template resolver serving HTML 5")
    public ClassLoaderTemplateResolver templateResolver() {

        ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();

        templateResolver.setPrefix("templates/");
        templateResolver.setCacheable(false);
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode("HTML5");
        templateResolver.setCharacterEncoding("UTF-8");

        return templateResolver;
    }`

**Comment by Ornelio-Chauque** [comment]
@yahyadev69 thanks.

Changing the ServletContextTemplateResolver to ClassLoaderTemplateResolver on the configuration class worked for me.

From:

`@Bean
    public ServletContextTemplateResolver templateResolver(ServletContext servletContext){
        ServletContextTemplateResolver templateResolver = new ServletContextTemplateResolver(servletContext);
        templateResolver.setPrefix("/WEB-INF/templates/");
        templateResolver.setSuffix(".html");
        templateResolver.setTemplateMode(TemplateMode.HTML);
        return templateResolver;
    }`

To:

` @bean
@description("Thymeleaf template resolver serving HTML 5")
public ClassLoaderTemplateResolver templateResolver() {

    ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();

    templateResolver.setPrefix("templates/");
    templateResolver.setCacheable(false);
    templateResolver.setSuffix(".html");
    templateResolver.setTemplateMode("HTML5");
    templateResolver.setCharacterEncoding("UTF-8");

    return templateResolver;
}`
