### ISSUE TITLE
unescape th:attr

### ISSUE THREAD

**Issue by caiqichang** [thymeleaf/thymeleaf#797]
```html
<div th:attr="v-show='disableList.indexOf(\''+  ${fieldName} +'\')>-1'" ></div>
```
the render result i want is:
```html
<div v-show="disableList.indexOf('sampleTime')>-1" ></div>
```
in fact, it is:
```html
<div v-show="disableList.indexOf(&#39;sampleTime&#39;)&gt;-1" ></div>
```
it works well, but can i unescape the content of th:attr ?

**Comment by ultraq** [comment]
Having a look through the Thymeleaf code, I think the attribute escaping happens on these lines: https://github.com/thymeleaf/thymeleaf/blob/3.0-master/src/main/java/org/thymeleaf/standard/processor/AbstractStandardMultipleAttributeModifierTagProcessor.java#L166-L167  Unfortunately, it doesn't look like it's configurable.

One idea that comes to mind: you could create a custom dialect with your own version of the `th:attr` processor, that does the same as the file above but doesn't escape the attribute value.  And then whenever you want to have unescaped attribute values, you use your custom processor instead.

**Comment by caiqichang** [comment]
@ultraq thank you, i will try it
