### ISSUE TITLE
Weird behaviour of fragments when using HTML tag name as fragment name

### ISSUE THREAD

**Issue by wimdeblauwe** [thymeleaf/thymeleaf#799]
Using Spring Boot 2.3.1 with Thymeleaf 3.0.11.

Declare 2 fragments like this:

```
<td th:fragment="td(contents)"
            th:with="primary=${primary?: false}"
            class="px-6 py-4 whitespace-no-wrap text-sm leading-5 text-gray-500"
            th:classappend="${primary?'font-medium text-gray-900':''}"
            th:text="${contents}">
            Table data contents
        </td>
<td th:fragment="tdWithLink(linkText, linkUrl)"
            class="px-6 py-4 whitespace-no-wrap text-right text-sm leading-5 font-medium">
            <a th:href="${linkUrl}"
               th:text="${linkText}"
               class="text-indigo-600 hover:text-indigo-900">Edit</a>
        </td>
```

Use them like this:

```
                            <tr class="bg-white" th:each="user : ${users}">
                                <td th:replace="fragments/table :: td(contents=${user.userName.fullName},primary=true)"></td>
                                <td th:replace="fragments/table :: td(${user.gender})"></td>
                                <td th:replace="fragments/table :: td(${user.birthday})"></td>
                                <td th:replace="fragments/table :: td(${user.email.asString()})"></td>
                                <td th:replace="fragments/table :: tdWithLink('Edit', '#')"></td>
                            </tr>
```

The resulting HTML will output _both_ fragments for each line where they are used. So there will be 10 `<td>` elements in the output instead of the expected 5.

However, when changing the fragment names from `td` to `tada` and `tdWithLink` to `tadaWithLink`, things start to work normal again.

**Comment by ultraq** [comment]
Hi there, so the fragment selector syntax is described in detail in this section of the docs: https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#appendix-c-markup-selector-syntax  One thing it mentions is that it's also a CSS selector, so looking for the fragment `td` is the same as the CSS selector `td` which is all elements named `td`, hence the behaviour you're seeing.

**Comment by leccelecce** [comment]
Is there any way to disable this behaviour? I've just been bitten by this as well. It feels unnecessary to also apply a CSS selector if there is a defined fragment in the template using th:fragment. Wouldn't clearer behaviour be either to stop searching using the CSS selector if a matching fragment has been found, or have some kind of syntax that can optionally be used to specifically only match a fragment and nothing else?

**Comment by ultraq** [comment]
It doesn't look like this is configurable.  I had a quick browse at how fragments are pulled out of templates, and in this part of the codebase it starts to lean on the Attoparser dependency, from which the CSS selector syntax that people are encountering is derived from (see: https://www.attoparser.org/apidocs/attoparser/2.0.5.RELEASE/org/attoparser/select/package-summary.html).

I think if we need to make this configurable, it will need to start in that project.  These lines in particular looked rather promising: https://github.com/attoparser/attoparser/blob/d2e8c1d822e290b0ce0242aff6e56ebdb9ca74b0/src/main/java/org/attoparser/select/MarkupSelectorItems.java#L43-L46  And then from there expose that as an option that can be configured in Thymeleaf.
