### ISSUE TITLE
Using the FileTemplateResolver for multiple nested directories

### ISSUE THREAD

**Issue by p10r** [thymeleaf/thymeleaf#802]
Hello,

while using thymeleaf I had the idea that I would like to try out having the templates sitting right beside the corresponding controllers to have it grouped by feature. The result looks like that:
```
├── routes
│   ├── index
│   │   ├── index.html
│   │   └── IndexController.kt
│   ├── lights
│   │   └── lights.html
│   └── watering
│       ├── rooms
│       │   ├── no-sensors-found.html
│       │   ├── room-sensor-details.html
│       │   └── rooms.html
│       ├── sensors
│       │   └── sensors.html
│       ├── watering.html
│       └── WateringController.kt
```
Then I tried picking up the templates with a FileTemplateResolver:
```
addTemplateResolver(FileTemplateResolver().apply {
                prefix = "/pathToRoutes/routes/"
                suffix = ".html"
                characterEncoding = "utf-8"
            })
```
which leads to the following error: 
```
Caused by: java.io.FileNotFoundException: /pathToRoutes/routes/index.html
```

I also tried adding a `FileTemplateResolver` for every nested directory (`/index`, `/lights`, `watering/rooms` etc.) but it seems like it always defaults to the first resolver.

```
listOf("watering/sensors/", "watering/rooms/", "watering/", "lights/", "index/").forEach { route ->
            addTemplateResolver(FileTemplateResolver().apply {
                prefix = "/pathToRoutes/routes/$route"
                suffix = ".html"
                characterEncoding = "utf-8"
            })
        }
```
which leads to:
```
Caused by: java.io.FileNotFoundException: /pathToRoutes/routes/watering/sensors/index.html
```

I must have missed something in the docs. Any suggestions would be great, thanks a lot!

**Comment by ultraq** [comment]
If the templates are in the same directories as the code, then would they be in the classpath?  I'm wondering then if the `ClassLoaderTemplateResolver` might have a better chance of working.

https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#template-resolvers

**Comment by p10r** [comment]
I actually tried that, but it seems like its not picked up, that's why I tried to use the FileTemplateResolver.
Just tried again, here you can see my structure and the corresponding build output:
![image](https://user-images.githubusercontent.com/23278849/95001480-b568a980-05ca-11eb-9b60-a751b83b7edb.png)

I tried all kinds of prefixes, but I think I have a wrong understanding there:
```
setTemplateResolver(ClassLoaderTemplateResolver().apply {
            prefix = "/classes/kotlin/main/de/p10r/web"
            suffix = ".html"
            characterEncoding = "utf-8"
        })
```

**Comment by ultraq** [comment]
OK, given your screenshot and config, it doesn't look like the HTML files are included alongside your compiled Kotlin files.  I suspect they're inside the resources directory instead.

For a `FileTemplateResolver`, assuming that the working directory of a running project is the same as the root directory of your project, I think you need a prefix pointing to build/resources instead:

```kotlin
setTemplateResolver(FileTemplateResolver().apply (
  // Please fix if the structure in the resources directory is different
  prefix = "build/resources/main/de/p10r/web/"
  suffix = ".html"
})
```

For a `ClassLoaderTemplateResolver`, then build/resources should be a part of the classpath already, so only the package in the path should do:

```kotlin
setTemplateResolver(ClassLoaderTemplateResolver().apply (
  // I think the leading / is necessary, otherwise it'll try load resources relative to the template resolver package
  prefix = "/de/p10r/web/"
  suffix = ".html"
})
```

(Apologies for any incorrect code, I'm not good with Kotlin!)

**Comment by p10r** [comment]
Sorry, should have posted the whole directory. Unfortunately the file is not picked up at all.

![image](https://user-images.githubusercontent.com/23278849/95021664-a2111900-0672-11eb-897c-7ffd61d6086b.png)

**Comment by ultraq** [comment]
Oh, if the HTML files don't even end up in the build directory, then that's more of a build tool issue.  I'm guessing you're using Gradle since I can see a directory with that name in the screenshot.  One thing I've had to do in the past when putting resource files alongside source files is update my gradle configuration with something like this:

```
sourceSets {
  main {
    resources {
      source 'source/main/java'
      exclude '**/*.java'
    }
  }
}
```

That's for if the Java source directory is at src/main/java, so update as necessary for your Kotlin source directory.  It might also need some conversion if using a `build.gradle.kts` file instead.

With that, then building the project should bring your HTML files over, and then hopefully then the file/classloader template resolver suggestions before will start to work.

**Comment by p10r** [comment]
That was it! Thanks a lot for your help!
