### ISSUE TITLE
'!=', '%', '&&', '(', '*', '+', '+=', '-', '.', '/', <, <=, '==', '>', '>=', '?', '?.', '?:', and, div, eq, ge, gt, le, lt, mod, ne, or or '||' expected

### ISSUE THREAD

**Issue by BigGitWorld** [thymeleaf/thymeleaf#804]
Hi.
I'm using Thymeleaf version **3.0.11**. 
when I use the ``th:onClick`` :
```
th:onclick="myFunction(this.getAttribute('data-name'))"
```
I receive the below Intellij IDEA error in end of the ``myFunction``:
```
'!=', '%', '&&', '(', '*', '+', '+=', '-', '.', '/', <, <=, '==', '>', '>=', '?', '?.', '?:', and, div, eq, ge, gt, le, lt, mod, ne, or or '||' expected
```
Code works, but I'd like to know why Intellij IDEA shows this error/warning.
What is the problem?

**Comment by ultraq** [comment]
I tried adding a `th:onclick` attribute to some Thymeleaf projects using IntelliJ, and neither of them gave me a warning.  If I tried adding exactly the same code as in your post, then I would get JavaScript warnings for 'this/getAttribute cannot be resolved', which makes sense.  This was using IntelliJ IDEA Ultimate 2020.2.3.  I also tried turning off the Thymeleaf plugin just to see what would happen, and it warned that "th:onclick is not allowed here".

So I'm not able to replicate this unfortunately.  Your code example looks like a valid value for th:onclick, though it looks like the IDE is interpreting it as a Thymeleaf expression for some reason, so I'm not sure what might be going on here.  You might get better answers asking at the IntelliJ support community: https://intellij-support.jetbrains.com/hc/en-us/community/topics/200382555-IntelliJ-IDEA-Users
