### ISSUE TITLE
is Thymeleaf SEO friendly when we return HTML fragments to the client?

### ISSUE THREAD

**Issue by BigGitWorld** [thymeleaf/thymeleaf#806]
Hi.

It seems my question is not related to the Thymeleaf nature.
But I'm confused about this issue and there is not any good article about it.

I'm going to build a **E-commerce web site as a Single page app** by the Thymeleaf as template engine.
But I don't have enough information about SEO by javascript.

**My Questions:**
I'm going to change main content (div HTML) of my pages by the AJAX load function ``$(#tag-id).load('url')``.
So that I'm using Thymeleaf fragments in the server side and return them as ``return value of controller methods in spring mvc``.
So my Question is:
Is it SEO friendly?I think it is. Because Thymeleaf uses SSR (Server side rendering) and provide a final static HTML in the server and deliver it to the client.

Can anyone please clarify me?

**Comment by BigGitWorld** [comment]
No answer?

**Comment by ultraq** [comment]
As an HTML template engine, any website built w/ Thymeleaf is only as SEO-friendly as you choose to make it.  In your example of building a SPA where you fetch content rendered on the server by Thymeleaf via an XHR request and update your main content area with it, if the returned HTML fragment has a good document outline and uses good headers and descriptions, then that's a 👍 for the SEO of the page.  However, if it's a badly constructed fragment with `<div>`s for everything and no clear outline, than that's a 👎 for the SEO of the page.

So a server-rendered HTML fragment won't automatically be any more or less SEO-friendly than JavaScript that emits the same HTML.

Aside from that, the biggest things to be concerned about with SEO for a single page app will be those things outside of Thymeleaf's control and inside your SPA code instead.  Like updating URLs for different pages/views, updating document titles, or handling error situations.

**Comment by BigGitWorld** [comment]
> if the returned HTML fragment has a good document outline and uses good headers and descriptions, then that's a +1 for the SEO of the page. However, if it's a badly constructed fragment with `<div>`s for everything and no clear outline, than that's a -1 for the SEO of the page.

I'm changing main-content section of pages by AJAX and SSR(by Thymeleaf), because re-loading full page is very bad idea for my scenario. As you said, I have a well-structured HTML file (including  meta tag, title for every fragments).
But although I have a ``<head>`` section in my fragments, but title of my SPA does not change automatically and need to use the below javascript code to change it.

```
var newTitle = $(responseHtml).filter('title').text();
document.title = newTitle;
```
Is it bad for SEO or not?

myFragment.html File:
```
<!DOCTYPE html>
<html lang="en" xmlns:th="http://www.thymeleaf.org">
<head>
    <title> New Title of fragment </title>
</head>
<body>
    <!-- fragment new content(this section will be placed at 'div-main-content' element by ajax.load -->
    <div>
        new content of my fragment
    </div>
</body>
</html>
```

> Aside from that, the biggest things to be concerned about with SEO for a single page app will be those things outside of Thymeleaf's control and inside your SPA code instead. Like updating URLs for different pages/views, updating document titles, or handling error situations.

I handle error cases in the server side by an interceptor that checks incoming request is AJAX or not. and for AJAX calls, I use appropriate error status code and therefore corresponding error HTML fragment will be returned to the client.
But for updating URLs what is best practice?Do I have to use History API in the (javascript) client side?

**Comment by ultraq** [comment]
> But although I have a <head> section in my fragments, but title of my SPA does not change automatically and need to use the below javascript code to change it.
> 
> ```
> var newTitle = $(responseHtml).filter('title').text();
> document.title = newTitle;
> ```
> 
> Is it bad for SEO or not?

Having a title that corresponds to the content being displayed is good for SEO.

Having a URL that corresponds to the content being displayed is also good for SEO.  Search bots will use the URL to tell whether or not the page is actually different, so to your question:

> But for updating URLs what is best practice?Do I have to use History API in the (javascript) client side?

I believe that is the only option for a SPA - any other attempt to change the URL outside of the history API will result in a call to the server and your app won't be "single page" any more.

---
As you can see, these concerns are outside of what Thymeleaf provides (HTML templating), so I'm going to close this issue.  You can find more information on what good SEO practices are for SPAs on websites dedicated to this topic.
