### ISSUE TITLE
Add support for OSGi

### ISSUE THREAD

**Issue by benfortuna** [thymeleaf/thymeleaf#808]
Instead of relying on the servicemix bundle Thymeleaf can support OSGi directly using the bndtool to generate the JAR manifest.

This pull request adds support for OSGi manifest headers: #807

==== from #839 ======

@benfortuna
benfortuna commented on 2 Jul

Problem statement: currently to include thymeleaf in OSGi runtimes we need to use wrapper implementations such as the servicemix bundle. There are issues with the reliability of the servicemix bundle that could be fixed by native OSGi support in this project's release artefacts.

Solution: Add the bndtool to generate the JAR manifest including OSGi headers. The work is already done and available in this pull request: #807 .

The only change is to the JAR manifest file, so should be a low impact change. Please take this into consideration or provide feedback to objections. Many thx.

**Comment by benfortuna** [comment]
Any thoughts or feedback on this?

**Comment by danielfernandez** [comment]
Sorry, OSGi support was evaluated in the past and declined. Conclusions of such evaluation still stand. Thanks a lot for your contribution, though.

See https://github.com/thymeleaf/thymeleaf/pull/280#issuecomment-50977114
