### ISSUE TITLE
Is Thymeleaf dead?

### ISSUE THREAD

**Issue by gkaur2294** [thymeleaf/thymeleaf#812]
Not able to see any new version after 2018. Could you please share about next plans? 

Since [766](https://github.com/thymeleaf/thymeleaf/issues/766) is closed, I created new issue to understand the future plan. This might help more people to adopt Thymeleaf.

**Comment by kumarsen26** [comment]
Yes, your inputs will help us to plan our migration better.

**Comment by danielfernandez** [comment]
This repository has commits from 3 days ago :)

Plase have a look here https://github.com/thymeleaf/thymeleaf/milestone/24 and https://github.com/thymeleaf/thymeleaf-spring/milestone/21

**Comment by kumarsen26** [comment]
Thank you 

> This repository has commits from 3 days ago :)
> 
> Plase have a look here https://github.com/thymeleaf/thymeleaf/milestone/24 and https://github.com/thymeleaf/thymeleaf-spring/milestone/21

Thank you @danielfernandez .. This will help more developers using Thymeleaf 👍

**Comment by marccollin** [comment]
seem like forum at http://forum.thymeleaf.org/ is closed.

Is there any schedule for next version of thymeleaf?
Any plan for thymeleaf 4, any feature?

**Comment by danielfernandez** [comment]
> seem like forum at http://forum.thymeleaf.org/ is closed.

Yes, the forum is closed due to excessive spam and security issues at nabble (where the forum is hosted). It will be removed in the near future.

> Is there any schedule for next version of thymeleaf?

https://github.com/thymeleaf/thymeleaf/milestone/24
https://github.com/thymeleaf/thymeleaf-spring/milestone/21
