### ISSUE TITLE
Request - iterating over i18n keys with spring boot integration / looking for a DRY way to show repeating text blocks

### ISSUE THREAD

**Issue by ottlinger** [thymeleaf/thymeleaf#814]
I'm using Thymeleaf in conjunction with SpringBoot 2.4.1 and would like to iterate over i18n keys in the following manner:

```
        <div th:each="number : ${#numbers.sequence( 0, 2, 1)}">
            <div class="jumbotron jumbotron-fluid">
                <div class="container">
                    <p th:text="${number}"></p>
                    <h1 th:text="#{'greeting.header'+[number]}" class="display-4"></h1>
                    <i class="fas fa-lock fa-10x"></i>
                </div>
            </div>
        </div>
```

In order to show multiple headlines/paragraphs I created the message properties:
* greeting.header0
* greeting.header1
* greeting.header2 a.s.o
and would like to iterate over them.

All things I find via search engines just show how to iterate over maps and their entries, but no-one seems to have run into the issue I now experience.

Above code does not show any i18n keys - it only renders:
```
welcomepage.header[number]_en
```

if English is selected as a language.

Is there an existing way to iterate over i18n keys or a different way to access the counter variable from the iteration and use it to access i18n keys?

Thanks for any help & suggestions - 
feel free to get in touch if anything is unclear what I want to achieve.

**Comment by pawel-napieracz** [comment]
This working for me: `<h1 th:text="#{'greeting.header.'+__${number}__}" class="display-4"></h1>`

**Comment by ottlinger** [comment]
@pawel-napieracz thanks - this helped. 
Is there a documention I can add this example to make it useful for other people stumbling upon this?

It's fantastic that I can do this with Thymeleaf 🥇

**Comment by wimdeblauwe** [comment]
I wonder if the pre-processing is really needed. I would think that this should also work:

    <h1 th:text="#{'greeting.header.' + ${number}}" class="display-4"></h1>

**Comment by ottlinger** [comment]
Both solutions are working - thanks.

**Comment by ottlinger** [comment]
As people can search this issue for solutions I'm going to close the issue - thanks again for your help and patience.
