### ISSUE TITLE
Thymeleaf expression cache bug in restricted expression evaluation mode 

### ISSUE THREAD

**Issue by didiez** [thymeleaf/thymeleaf#819]
After #809 we have noticed an odd behaviour due to some unsafe expressions we were using in our templates. 
The errors caused by these expressions (`ThymeleafProcessingException`) were raised intermittently. We had a hard time reproducing the issue. Those errors were more frequent under high load so we dug deeper.

The problem seems to be related with the expression cache. Once an expression is cached, it will be evaluated even in an insecure context (i.e: `th:data-*`). 
If we disable this cache with `templatEngine.setCacheManager(null)`, everything works as expected, raising an error everytime an insecure expression is used in restricted evaluation mode.

I have isolated the bug in a sample application: https://github.com/didiez/thymeleaf-cache-el-bug

Tested versions:
- thymeleaf: `3.0.12`
- spring-boot: `2.4.2`

**Comment by danielfernandez** [comment]
This should be fixed in `3.0.14.RELEASE`
