### ISSUE TITLE
Support Formatter in th:data attributes

### ISSUE THREAD

**Issue by membersound** [thymeleaf/thymeleaf#825]
For complex objects a `Formatter` can be registered to pretty print objects as follows:

```
@Component //using spring-boot here
public class ExampleFormatter extends org.springframework.format.Formatter<Object> {
          //...
}
```

This works fine:
```
<div th:text="${{row.example}}"/>
```

But often I'd like to make use of the `th:data-*` tag, which does not work:
```
<div th:data-example="${{row.example}}"/>
```

A workaround is to use the `th:attr` tag, but which requires all formatted data attributes being added as csv line, which is quite ugly:
```
<div th:attr="data-example=${{row.example}},data-more=${{row.more}}"/>
```

It would be great if the `th:data-*` field could also support the `Formatter` interface.

**Comment by danielfernandez** [comment]
Conversion should work for `th:data-*` attributes, and none of our tests show it doesn't. Nevertheless, I've re-tested it on both Spring-based and non-Spring applications and I've verified it works for me. Please reopen with a working example showcasing the issue if it still persists for you.
