### ISSUE TITLE
html/xml comment blocks not support [[]] or [()]

### ISSUE THREAD

**Issue by Jason-purse** [thymeleaf/thymeleaf#826]
when I use the html/xml comment blocks ,find it not support  [[]] or [()], 

If these two symbols appear in this comment block, they will be interpreted and executed by the template engine. If the variable does not respond, it will cause an null exception, and it is not text-inlining or javascript...inling, I am confused, can 
No answer this doubt

eg.  will throw null exception;

I need help!

**Comment by Jason-purse** [comment]
eg .   "

**Comment by Jason-purse** [comment]
eg.   "\\<!-- [[user.name]] or [(user.password)]--\\>" will throw null exception;

**Comment by trinhnx** [comment]
That is inlining expression, and afaik, Thymeleaf gonna process it even it is in documented block
you can try add the tag to disable inline
see
https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#disabling-inlining

**Comment by danielfernandez** [comment]
As @trinhnx explained, this collides with inlining syntax and therefore it is executed as such.
