### ISSUE TITLE
ClassLoaderTemplateResolver ignores leading '/'

### ISSUE THREAD

**Issue by Lesurglesum** [thymeleaf/thymeleaf#831]
Hello,
currently I am trying to use HTML templates with the `ClassLoaderTemplateResolver` and 'absolute' paths and failing. No matter what I try, only relative paths are processed and a FileNotFoundException with **no** leading '/' is thrown. I want to use the `ClassLoaderTemplateResolver` because I want to keep the templates inside the jar.

```
ClassLoaderTemplateResolver templateResolver = new ClassLoaderTemplateResolver();
templateResolver.setTemplateMode(TemplateMode.HTML);
templateResolver.setPrefix("/templates/html/");
templateResolver.setSuffix(".html");

TemplateEngine templateEngine = new TemplateEngine();
templateEngine.setTemplateResolver(templateResolver);

[...]

templateEngine.process("messagePage", messageContext, writer);

==> org.thymeleaf.exceptions.TemplateInputException: An error happened during template parsing (template: "messagePage.html")
==> java.io.FileNotFoundException: ClassLoader resource "templates/html/messagePage.html" could not be resolved
```

Walking in with the debugger I've found out that `TemplateResourceUtils.cleanPath(path)` in `class ClassLoaderTemplateResource` seems to remove all leading '/'.
What are my other options? (Putting the template files next to the .class files is not wanted.)

Tthymeleaf version: 3.0.9

Thanks in advance!

**Comment by ultraq** [comment]
Having a look at the `ClassLoaderTemplateResolver` code, if you don't include which classloader to use in the constructor, it defaults to the classloader returned by `Thread.currentThread().getContextClassloader()`  You can follow the code down from here: https://github.com/thymeleaf/thymeleaf/blob/309b9f298e03cd069a6eea526bec298cfbec4a4a/src/main/java/org/thymeleaf/templateresource/ClassLoaderTemplateResource.java#L123-L127

Javadocs for Thread.getContextClassloader: https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Thread.html#getContextClassLoader()

I don't imagine that classloader has a notion of relative paths, so everything is probably assumed to be an absolute path and might explain why Thymeleaf cleans leading `/`s.

So if your templates live in a `templates/html` directory inside a jar that is accessible by that classloader (usually the case if the jar is on the same classpath as the running application), Thymeleaf should be able to find it.  However, if that jar is loaded by some other mechanism or isn't in the classpath, you might need to specify a classloader that can access that jar.

**Comment by xtianus** [comment]
In `templateResolver.setPrefix();` I use neither leading nor trailing slashes and it works:

`resolver.setPrefix("net/yadaframework/views");`

All my view names are always absolute then: "/my/view/name"

This was the only way to make it work for me (did so in an old Thymeleaf version and stuck to it).

**Comment by danielfernandez** [comment]
The `ClassLoaderTemplateResolver` always considers paths to start at one of the entries of the class path of the class loader being used for resolving the resources. There is no such thing as _relative_ resources in a class-loader-based resolution. So your `/some/resource" will be equivalent to `some/resource`, and will result in a folder called `some` being searched in all the folders configured as class path of the class loader.
