### ISSUE TITLE
Context not available to compute Template Resource

### ISSUE THREAD

**Issue by Gitanshu3** [thymeleaf/thymeleaf#837]
In Thymeleaf 3.0 TemplatePrcoessingParameters class is removed that helped in providing the Context(where you can manipulate the local variables) while overriding getResourceAsStream method to compute the Template resources by implementing IResourceResolver interface.

In return, thymeleaf 3.0 still allows one to override computeTemplateResource method to return ITemplateResource where one has to provide a Reader along with the resource to be read or just the location from where thymleaf can fetch the resource.

 My problem is, earlier we had the context where we can modify local variables of the context and compute the resources accordingly with the modified variables and now there is only one way to compute the custom(user provided) template resource that is to override that ComputeTemplateResource method that doesn't even provide any details of the context/local variables of the tag it is processing. How does my custom template resolver deal in this situation ? 

for reference i have attached the screenshots. 

![image](https://user-images.githubusercontent.com/47892269/121487429-b373a780-c9ef-11eb-951a-9fe81b12dd29.png)

![image](https://user-images.githubusercontent.com/47892269/121489730-fe8eba00-c9f1-11eb-9915-386620f4d9af.png)

**Comment by danielfernandez** [comment]
In Thymeleaf 3.0, for the sake of the new resource architecture which allows for better caching and sharing of resources, template resolution had to be decoupled from the context being used for specific executions at the resolution step.

So the context for a specific resolution is no longer a valid input for the resolution of a template.
