### ISSUE TITLE
Enhancement: Native support for OSGi

### ISSUE THREAD

**Issue by benfortuna** [thymeleaf/thymeleaf#839]
Problem statement: currently to include thymeleaf in OSGi runtimes we need to use wrapper implementations such as the servicemix bundle. There are issues with the reliability of the servicemix bundle that could be fixed by native OSGi support in this project's release artefacts.

Solution: Add the bndtool to generate the JAR manifest including OSGi headers. The work is already done and available in this pull request: #807 .

The only change is to the JAR manifest file, so should be a low impact change. Please take this into consideration or provide feedback to objections. Many thx.

**Comment by eaglerainbow** [comment]
Same as or at least related to #808?

**Comment by benfortuna** [comment]
Indeed it is a duplicate. I can't recall why a new issue was created, I'll merge into the original the issue.
