### ISSUE TITLE
The th:with statement, the declared variable is within its scope, what if the value of this variable is changed? I want to judge whether the current loop has a state condition for the result, but the scope of the variable declared by th:with is bound to the location where it is added, and it cannot modify the wider variable with the same name; may I ask, it is designed like this Or has there been a history of decision-making?

### ISSUE THREAD

**Issue by xhc-code** [thymeleaf/thymeleaf#840]
The th:with statement, the declared variable is within its scope, what if the value of this variable is changed? I want to judge whether the current loop has a state condition for the result, but the scope of the variable declared by th:with is bound to the location where it is added, and it cannot modify the wider variable with the same name; may I ask, it is designed like this Or has there been a history of decision-making?

**Comment by xhc-code** [comment]
The th:with statement, the declared variable is within its scope, what if the value of this variable is changed? I want to determine whether the current loop has a state condition for the result, but the scope of the variable declared by th:with is bound to the position where it is joined, and I cannot modify the scope of the declaration using th:with The value of the variable; is it the design or the history of decision-making?

**Comment by danielfernandez** [comment]
Yes, this is by design. Variables have a value in a scope defined by the structure tree of markup.
