### ISSUE TITLE
Difference in th:replace vs th:insert when using variables

### ISSUE THREAD

**Issue by wimdeblauwe** [thymeleaf/thymeleaf#847]
Suppose `todos` is a model attribute that has a `List` of `TodoItemDto` instances.

This works:
```
<ul class="todo-list" th:remove="all-but-first">
  <li th:each="item : ${todos}" th:insert="~{fragments :: todoItem(item)}">
  </li>
</ul>
```

Given `fragments.html` contains this:

```
<li th:fragment="todoItem(item)">
    <div class="view">
        <label th:text="${item.title}">Taste JavaScript</label>
    </div>
</li>
```

However, when using `th:replace` instead of `th:insert` like this:

```
<ul class="todo-list" th:remove="all-but-first">
  <li th:each="item : ${todos}" th:replace="~{fragments :: todoItem(item)}">
  </li>
</ul>
```

Then I get an error:

> Property or field 'title' cannot be found on object of type 'java.lang.String' - maybe not public or not valid?

Any idea why this is?

What I find also strange is that it also does _not_ work with `th:insert` if I rename `item` to `myItem` when calling the fragment (without changing anything to the fragment):

```
<ul class="todo-list" th:remove="all-but-first">
  <li th:each="myItem : ${todos}" th:insert="~{fragments :: todoItem(myItem)}">
  </li>
</ul>
```

This gives the same error that `title` cannot be found on object of type `String`.

For my usecase, I would really like to use `th:replace` to have cleaner HTML output if possible.

**Comment by wimdeblauwe** [comment]
Reading up on [Attribute Precedence](https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#attribute-precedence), I think I can answer my own question.

`th:insert` and `th:replace` have the highest precedence, `th:each` is lower.

**With th:insert**

So, when using `th:insert`, the following is happening.

Start with the actual template:
```
<ul class="todo-list" th:remove="all-but-first">
  <li th:each="item : ${todos}" th:insert="~{fragments :: todoItem(item)}">
  </li>
</ul>
```

First, the `th:insert` is processed, so we get:
```
<ul class="todo-list" th:remove="all-but-first">
  <li th:each="item : ${todos}">
    <li>
      <div class="view">
        <label th:text="${item.title}">Taste JavaScript</label>
      </div>
    </li>
  </li>
</ul>
```

Next, the `th:each` is processed, and `item` in `th:each` matches with the `item` that is used in the fragment and things work.

**With th:replace**

In contrast, using `th:replace`, we get this in the first "step" of the processing:

```
<ul class="todo-list" th:remove="all-but-first">
    <li>
      <div class="view">
        <label th:text="${item.title}">Taste JavaScript</label>
      </div>
    </li>
</ul>
```

Because the HTML element in the main file is _replaced_ with the content of the fragment, the `th:each` is no longer there, and the `th:text=${item.title}` can no longer work.

**Solution**

Given that, I should probably use this construct instead:

```
<ul class="todo-list" th:remove="all-but-first">
  <li th:each="item : ${todos}" th:insert="~{fragments :: todoItem(item)}" th:remove="tag">
  </li>
</ul>   
```

Note the extra `th:remove="tag"` attribute. As `th:remove` has a lower precedence than `th:each`, it will remove the extra tag that normally would remain because `th:insert` is used.

So it first goes to this:

```
<ul class="todo-list" th:remove="all-but-first">
  <li th:each="item : ${todos}" th:remove="tag">
    <li>
      <div class="view">
        <label th:text="${item.title}">Taste JavaScript</label>
      </div>
    </li>
  </li>
</ul>
```

Then to this:

```
<ul class="todo-list" th:remove="all-but-first">
  <li  th:remove="tag">
    <li>
      <div class="view">
        <label>Item Title 1</label>
      </div>
    </li>
  </li>
  <li  th:remove="tag">
    <li>
      <div class="view">
        <label>Item Title 2</label>
      </div>
    </li>
  </li>
</ul>
```

And finally to:

```
<ul class="todo-list" th:remove="all-but-first">
    <li>
      <div class="view">
        <label>Item Title 1</label>
      </div>
    </li>
    <li>
      <div class="view">
        <label>Item Title 2</label>
      </div>
    </li>
</ul>
```
(Note that `th:remove="tag"` means _Remove the containing tag, but do not remove its children._)

Would be good if somebody from the team could confirm if my reasoning is correct or not.

**Comment by ultraq** [comment]
Hey there 👋  So yes, what you've discovered is exactly right: `th:replace` replaces the entire DOM node before `th:each` runs, giving you the error that you encountered.

Using `th:remove="tag"` is one solution to this to clean up the HTML after all of the fragments have been included and iterations run.  Another one might be to use Thymeleaf's `<th:block>` element which acts as a place to have attribute processors, and then removes itself as if it had `th:remove="tag"` on it.  Because it's an element, it can change how your HTML templates will look which might make things cleaner or messier depending on one's tastes!  But the option is there should people wish to use it.

Small section on `<th:block>` in the docs here: https://www.thymeleaf.org/doc/tutorials/3.0/usingthymeleaf.html#synthetic-thblock-tag

**Comment by wimdeblauwe** [comment]
I am writing a blog post to explain all this in more detail, but I can't seem to be able to combine a fragment with `th:block`.

So this works:

```
    <ul>
        <th:block th:each="user : ${users}">
            <li>
                <div th:text="${user.name}"></div>
                <div th:text="${user.country}"></div>
            </li>
        </th:block>
    </ul>
```

But if I do this:

```
    <ul>
        <th:block th:each="user : ${users}">
            <li th:replace="fragments :: userInfo(user)">
            </li>
        </th:block>
    </ul>
```

Then I get:
> Property or field 'name' cannot be found on object of type 'java.lang.String'

Replacing `th:replace` with `th:insert` gives no difference, both result in the same error.

**Comment by wimdeblauwe** [comment]
For clarity, this was the fragment I was using:

```
<div th:fragment="userInfo(user)">
    <div th:text="${user.name}"></div>
    <div th:text="${user.country}"></div>
</div>
```

What I found that does work, is using pre-processing.

Change the fragement to:

```
<div th:fragment="userInfoUsingVariableName(userVariableName)">
    <div th:text="${__${userVariableName}__.name}"></div>
    <div th:text="${__${userVariableName}__.country}"></div>
</div>
```

And use it like this:
```
    <ul>
        <th:block th:each="user : ${users}">
            <li th:insert="fragments :: userInfoUsingVariableName('user')">
            </li>
        </th:block>
    </ul>
```

Note how I pass `'user'` string into the fragment, which has to match with the name of the iteration variable `user` that is used in the `th:each`.

Would you say that using the pre-processing approach is recommended if you want to use `th:block` ?

**Comment by wimdeblauwe** [comment]
To be honest, I still don't understand why this does not work:

```
<ul>
        <th:block th:each="user : ${users}">
            <li th:replace="fragments :: userInfo(user)">
            </li>
        </th:block>
    </ul>
```

How does Thymeleaf handle processing of child elements? I would expect the `<li th:replace...` element to be processed first. If that is the case, then it should work, no?

**Comment by wimdeblauwe** [comment]
Looking through [the docs on fragments](https://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#parameterizable-fragment-signatures) in more detail, I see that my example should be:

```
    <ul>
        <th:block th:each="user : ${users}">
            <li th:insert="fragments :: userInfo(${user})">
            </li>
        </th:block>
    </ul>
```

Note how I replaced `user` with `${user}` in the `th:replace` attribute value.

**Comment by wimdeblauwe** [comment]
I published a blog post about this now: https://www.wimdeblauwe.com/blog/2021/09/14/thymeleaf-iteration-and-fragments/

**Comment by ultraq** [comment]
Nice 🙂  And yeah I got a bit stuck figuring out why what you had a few posts back didn't work, but good to see you've figured it out!
