### ISSUE TITLE
shiro conflict with layui template 

### ISSUE THREAD

**Issue by lqxue575** [thymeleaf/thymeleaf#849]
hello,
   
i am using layui framework for web UI,and using shiro for the security framework, i found that the  shiro conflict with layui template when the use DO NOT has the permission.
the code as below,when user does not have caigou:add permission will cause the issue:

<script  type="text/html" id="operation">
    
    {{# if(d.addman =='[[${_humanId}]]' && d.state<=0){ }}
    
    <a class="layui-btn layui-btn-xs layui-btn-normal" lay-event="edit" shiroX:hasPermission="caigou:add"><i  class="fa fa-edit" ></i>Modify</a>
    <a class="layui-btn layui-btn-xs layui-btn-danger" lay-event="remove" shiroX:hasPermission="caigou:remove"><i  class="fa fa-remove"></i>Del</a>
    {{# } }}
</script>

and i also found it because the "<=" cause the issue, maybe a match bug.

**Comment by danielfernandez** [comment]
Sorry, I'm afraid that doesn't look like Thymeleaf code, so most probably this has been reported here in error.
