### ISSUE TITLE
Unexpected result from subtraction using nulls

### ISSUE THREAD

**Issue by northcoder-repo** [thymeleaf/thymeleaf#850]
I am using Thymeleaf  version 3.0.12.RELEASE with Java 16.

There is no Spring or SpEL involved.

I have a question regarding the following two scenarios:

### Scenario One

The Java model:

```java
Map<String, Object> model = new HashMap<>();
model.put("foo", null);
model.put("bar", null);
```

The Thymeleaf template:

```html
<!DOCTYPE html>
<html xmlns:th="http://www.thymeleaf.org">
    <head>
        <title>Demo</title>
        <meta charset="UTF-8">
    </head>
    <body>
        <div th:text="${foo} - ${bar}"></div>
    </body>
</html>
```
The outcome: 

Upon attempting to render the template, the following exception is thrown:

    org.thymeleaf.exceptions.TemplateProcessingException: Cannot execute subtraction: operands are "null" and "null"

This is _as expected_ - no problems here.

### Scenario Two

Using the same model, but altering the `<div>` in the template to be as follows:

```html
<div th:text="${foo - bar}"></div>
```

Expected outcome: same as for scenario one.

Actual outcome: No exception is thrown. HTML is rendered as follows:  `<div>0</div>`

**Questions** 

1) Is this the expected behavior? 

2) Why is there this difference between these two approaches, which I expected to be equivalent?

Many thanks for your help and for all things Thymeleaf.

---

**Update**

This can be boiled down to an even simpler demo, using the following:

```html
<!-- throws TemplateProcessingException -->
<div th:text="${null} - ${null}"></div>

<!-- evaluates to <div>0</div> -->
<div th:text="${null - null}"></div>
```

**Comment by danielfernandez** [comment]
In this expression, the subtraction is executed by Thymeleaf:
```
<!-- throws TemplateProcessingException -->
<div th:text="${null} - ${null}"></div>
```
In this one, the subtraction is performed by the expression language because of being inside of `${ ... }`, which from your result I take is OGNL. Thymeleaf here is consistent with SpringEL instead, which would raise an exception if you executed this with it:
```
<!-- evaluates to <div>0</div> -->
<div th:text="${null - null}"></div>
```
