### ISSUE TITLE
3.1.0.M1 any migration guied

### ISSUE THREAD

**Issue by sysmat** [thymeleaf/thymeleaf#869]
SUGGESTIONS: 3.1.0.M1 
- has any migration guied 
- 3.0.14.RELEASE should have marked deprecated(ServletContextTemplateResolver )

Regards, Tomaž

**Comment by sysmat** [comment]
any progress on that?

**Comment by danielfernandez** [comment]
Closing this as migration guide was published at https://www.thymeleaf.org/doc/articles/thymeleaf31whatsnew.html
