### ISSUE TITLE
Inclusion mechanism similar to .jspx

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#87]
A new mechanism of code inclusion could be developed in a similar way to .jspx tags, so that a fragment of markup is parsed and executed with a closed context (receiving parameters for its execution), in a reusable manner.

**Comment by danielfernandez** [comment]
See http://today.java.net/pub/a/today/2003/11/14/tagfiles.html

**Comment by tadas-subonis** [comment]
+1 . Also, see http://www.jangod.org/userguide.html#tag-inheritance - same concept.

**Comment by danielfernandez** [comment]
This is now covered by the feature defined at #181. Closing this one.
