### ISSUE TITLE
Using fragments in xml environments should include the missing xml namespaces in the corresponding tags

### ISSUE THREAD

**Issue by ManuelPetermann** [thymeleaf/thymeleaf#884]
When i am inserting an xml fragment from another file/place into the template where some or all of the namespaces are not defined, the  namespaces should be automatically copied over to the corresponding element.

I tried hacking this by writing all the missing namespaces into a contextvar as a string but thymeleaf is complaining:
Could not parse as assignation sequence: "__${importantNamespaces}__"

The value of this context variable is exactly:
`'xmlns:fu'="http://www.fubar.com/fu/V1.00",'xmlns:bar'="http://www.fubar.com/bar/V1.00"`

```
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
    <core:fubar xmlns:core="http://www.fubar.com/veryImportant/V1.00"
                                  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                                  xmlns:th="http://www.thymeleaf.org" th:attr="__${importantNamespaces}__">
```

Any chance one of those two issues can be fixed?

**Comment by danielfernandez** [comment]
Thymeleaf is not an XML document object model library, so something like keeping accountancy of the namespaces being inserted from external documents should not be its responsibility.

Your `th:attr` method works, but you need to take into account that the way to specify text literals in Thymeleaf expressions is with single quotes `'`, not double `"`, so it should be: 

```
 'xmlns:fu'='http://www.fubar.com/fu/V1.00','xmlns:bar'='http://www.fubar.com/bar/V1.00'
```
