### ISSUE TITLE
Url with pathvariable

### ISSUE THREAD

**Issue by emilime** [thymeleaf/thymeleaf#89]
Add support to pathvariable style to URL syntax, like spring:url tag, example:

``` html
    <a th:href="@{/order/details/{id}/{action}(id=3,action='show_all')}"> 
```

output:

``` html
<a href="/order/details/3/show_all"> 
```

**Comment by danielfernandez** [comment]
You should be able to do this already by appending strings:

``` html
<a th:href="@{'/order/details/' + ${id} + '/' + ${action}}"> 
```

Would that be what you need?

**Comment by emilime** [comment]
I think it would be useful to have a method like this:

``` html
 <a th:href="@{/order/details/{id}/{action}(Object)}">
```

(where Object has properties "id" and "action") which output the url as "/order/details/3/show_all".

What do you think?

**Comment by kreuzman** [comment]
Hi,

I think that standardized syntax for this would be nice syntax sugar. If you building long URL you easily make a mistake in joining (e.g. you forget `'`). Also with more parameters it's nice to see all parameters on one place (after URL).

For me this looks cleaner

``` html
<a th:href="@{/order/details/{id}/{action}(id=3,action='show_all')}">
```

than this (which I currently doing a lot :-)

``` html
<a th:href="@{'/order/details/' + ${id} + '/' + ${action}}"> 
```

But it's just my personal feeling and I'm ok with both in the end (The most important is that it works well).

Regards
Michal

**Comment by petejohanson** [comment]
I would appreciate a simpler approach/syntax for this as well. String concatentation works, but isn't ideal, IMHO.

**Comment by usethe4ce** [comment]
An important difference that I would expect is how strings are treated: simple concatenation should build up a raw URL, while the Thymeleaf parameter syntax should perform URL escaping.

**Comment by sunil0791** [comment]
There is one thing that i noticed in  org.thymeleaf.standard.expression.LinkedExpression.java class.
Initial i had not applied pathvariable concept to my web application. When i changed it to use pathvariable, the css and js location where in pathvariable loaction and were not being found(which were actually under root context).
Let me explain it with example:
Consider my root Context path is /Core.
i had user th:href="@{js/script.js}".(In firebug, the location was Core/js/scipt.js which is correct).
After applying pathvariable concept. (In firebug, the location was Core/{pathvariable}/js/scipt.js which is incorrect).

Then i found that,

> > if the linkexpression starts with /, the context path is added in prefix.
> > if the linkexpression starts with ~/, the context path is not added in prefix.

But, in my case i expected it to start with context path.
Is it possible to check for something like 
if({not start with /} and NOT[{indexof("http")} or{indexof("www")}]{
Add Context path in prefix of linkexpression.
}

**Comment by opensource21** [comment]
@sunil0791 I think you describe a complete different issue. Would be cleaner to have there an own ticket. For me the behavior you describe looks more like a bug than an enhancement. Have you try to fix it with `__${pathvariable}__`.

**Comment by opensource21** [comment]
I would appreciate this enhancement too. I would prefer the following behavior, which includes the ones which is described above.
Add support to pathvariable style to URL syntax, like spring:url tag, example:

```
<a th:href="@{/order/details/{id}/{action}(id=3,action='show_all', futherParam='foo')}"> 
```

output:

```
<a href="/order/details/3/show_all&furtherParam='foo'"> 
```

**Comment by danielfernandez** [comment]
This is covered by Thymeleaf 2.1's support of _literal substitutions_, which can be used inside `@{...}` expressions. See http://www.thymeleaf.org/whatsnew21.html#lsub

**Comment by opensource21** [comment]
It's not really a solution of what I wanted, because I want to reuse the Strings I used at controller side. In the current situation I must define the URL twice.

**Comment by danielfernandez** [comment]
Could you please ellaborate a bit more on why this does not fulfill your needs?

Do I understand correctly if I think you want to pass `"/order/details/{id}/{action}"` as a context variable from the controller and then reuse it at your template with different values for filling those `id` and `action` values?

If so, you could still do this by using Thymeleaf's preprocessing and writing your String like `"/order/details/${id}/${action}"` into the `myUrl` variable, using it this way:

``` xml
<a th:with="id=3,action='show_all'" th:href="@{|__${myUrl}__|(futherParam='foo')}"> 
```

It's not exactly the same syntax as the _Spring PathVariable_ one, but it's something you can do now...

Anyway, I'm reopening this in order to evaluate it (specifically the Path Variable syntax) for next versions.

**Comment by opensource21** [comment]
Thanks for reopen it. What I do is to put all URLs into the message-source so I can get them with #('url.myUrl). At the moment I manipulate the string, so that the normal message-source parameters work, but I got problems to combine this with furtherParam. This should solved now. How ever the normal message-source parameters don't allow named parameter. But I can try to use the new syntax in the message source.

**Comment by opensource21** [comment]
Today I switched in my project to the new syntax and everything is fine. You can see it in action at https://github.com/opensource21/fuwesta. The URLs are defined in [Class URL](https://github.com/opensource21/fuwesta/blob/master/fuwesta-sample/src/main/java/de/ppi/samples/fuwesta/frontend/URL.java). The information is put into the [MessageSource](https://github.com/opensource21/fuwesta/blob/master/fuwesta-sample/src/main/java/de/ppi/samples/fuwesta/config/WebMvcConfig.java#L113).

How it used you can see at the tests in [hrefWithNamedParamsFromMessage.thtest](https://github.com/opensource21/fuwesta/blob/master/fuwesta-core/src/test/resources/thymeleaf/div/hrefWithNamedParamsFromMessage.thtest).

I hope now is the idea clear. However the possible improvements are small `|__#{url.xxx}__|` is not very elegant, but I don't now a better solution. Pherhaps an preprocessor which translate `th:mref="url.xxx"` to `th:href="@{|__#{url.xxx}__|}"`

**Comment by danielfernandez** [comment]
This has been implemented in 2.1.3-SNAPSHOT. Will be available in Thymeleaf 2.1.3.

See this test: https://github.com/thymeleaf/thymeleaf-tests/blob/20140309/src/test-21/resources/engine21/features/link/link05.thtest

**Comment by rohtakdev** [comment]
edit - Works, just tested it!
can we also use this with th:src="@{...}" ?

**Comment by jmiguelsamper** [comment]
Yes, you can use a @{...} expression in any attribute processor.

**Comment by rohtakdev** [comment]
Thank you for your reply. One more question, i could not get the above behavior when i was using it inside a custom attribute.
like <option th:attr="data-img-src=@{...}" />
basically i wanted to use jquery plugin - http://rvera.github.io/image-picker/ and way it works is to specify an option tag like below -
<option
          data-img-src='http://www.example.com/image.jpg'
          data-img-label='Just an image!'
          value='42'
        >

**Comment by jmiguelsamper** [comment]
You need a processor for that data-img-src attribute. You can use https://github.com/mxab/thymeleaf-extras-data-attribute

**Comment by danielfernandez** [comment]
...or also simply use `th:attr`:

``` html
    <option ... th:attr="data-img-src=@{...}" ... >
```

**Comment by JetForMe** [comment]
This is not working as I would expect in 2.1.5. I have code like this:

```
<tr th:each="user : ${users}">
	<td><a th:href="@{/users/{user.id}}" th:text="${user.first}">First</a></td>
</tr>
```
And I want it to render a URL like `/users/1`, but instead I get `/users/{user.id}`. If I use string concatenation, it works correctly, but that is terribly cumbersome and hard to read.

**Comment by kazuki43zoo** [comment]
Probably, it work fine to change as follow:

```html
<tr th:each="user : ${users}">
	<td><a th:href="@{/users/{id}(id=${user.id})}" th:text="${user.first}">First</a></td>
</tr>
```

See http://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#link-urls for details.

**Comment by JetForMe** [comment]
Yes, that appears to work, but it's still extraordinarily verbose. Why the resistance to simply supporting `th:href="@{/users/{user.id}}"`? That seems to be the most natural way of expressing it.

**Comment by tholu** [comment]
I would also love a less verbose way, like @JetForMe suggested. 👍

**Comment by danielfernandez** [comment]
@JetForMe @tholu plese note that, as of today, Thymeleaf should allow you to use a literal substitution there like `th:href="@{|/users/${user.id}|}`
