### ISSUE TITLE
Avoid formatting time or date when using formatstyle with temporals that don't contain them

### ISSUE THREAD

**Issue by lmartelli** [thymeleaf/thymeleaf#893]
I am using `#temporals` to format a LocalDate and it insists on also formatting the time 👍🏻 

`${#temporals.format(period.start,'MEDIUM')}`

I believe it is because `org.thymeleaf.extras.java8time.util.TemporalFormattingUtils#defaultOrPatternFormatted()` uses `DateTimeFormatter.ofLocalizedDateTime()`. There should probably be some common logic with `org.thymeleaf.extras.java8time.util.TemporalObjects#formatterFor()` 

```
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf</artifactId>
            <version>3.0.11.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf</groupId>
            <artifactId>thymeleaf-spring5</artifactId>
            <version>3.0.11.RELEASE</version>
        </dependency>
        <dependency>
            <groupId>org.thymeleaf.extras</groupId>
            <artifactId>thymeleaf-extras-java8time</artifactId>
            <version>3.0.4.RELEASE</version>
        </dependency>
```

**Comment by danielfernandez** [comment]
This should be fixed by thymeleaf/thymeleaf-extras-java8time#34
