### ISSUE TITLE
Removed Comments Leaving Empty Lines

### ISSUE THREAD

**Issue by evoelise** [thymeleaf/thymeleaf#895]
We have a lot of comment our HTML templates and we use Thymeleaf to exclude these from the generated HTML.

For example: `<!--/* I'm a comment in source HTML and should not be in rendered HTML */ -->`

In our opinion comments should be completely removed from the rendered HTML however when the HTML is rendered blank lines and also a load of spaces are left behind in the HTML.

This is especially egregious when `<th:block>`s are used as these should remove the entire block from the rendered HTML but the empty lines and spaces from removed comment are left behind. In some of our pages with a lot of optional content we end up with multiple MB HTML pages where over 90% of the page is spaces and line breaks.  

I am sure we could write a PostProcessor to remove the white space after processing but again that is less efficient as it is extra processing (and more memory used) we need to do - when all this white space could have been removed during rendering.

This is related to issue #108

We are using latest version of Thymeleaf

**Comment by danielfernandez** [comment]
Everything between `<!--\*` and `*/-->` is removed as per specification (note your code sample is incorrect as is incudes a white space in `*/ -->`.

But if you add a newline character after you `*/-->`, that newline char is _outside_ the comment and therefore will not be removed. Equivalently, if you indent your comments and add tabs or spaces before your `<!--/*`, those indentation artifacts are outside the comment and therefore will not be removed either.

So this:
```html
    <!--/* Something here */-->
    <!--/* Something else */-->
```
Will result in two empty lines with 4 spaces before a line feed each. But this will not:

```html
<!--/* 
            Something here
            Something else
*/-->
```
