### ISSUE TITLE
Support XSD Schema and XML Namespaces

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#9]
From: http://sourceforge.net/tracker/?func=detail&aid=3406107&group_id=509826&atid=2072662

It is common for XML-based component frameworks to use XSD schemas for validation (and code-assistance), along with the schema's target namespace to identify elements and attributes over which that namespace applies. Accordingly, it would be useful to register dialects that are bound the namespace or schemaLocation, and have the actual prefix used only as a pseudonym for that namespace, rather than the differentiator itself.

Compelling reasons include:
a) The prefix is not always known upfront when parsing XML. Consider XML generation for webservice invocations; the prefix is often generated, e.g. ns0, ns1, ... nsN. The schema however will be known upfront.
b) A page author may choose the prefix per-page, rather than having the prefix hard-coded (avoiding ns-collisions when multiple dialects are used within that page)
c) Different dialects per schema version. If the dialect is registered to the versioned schema location (http://x.y.z/schemas/my-schema-1.0.xsd), a smooth migration can be offered when that schema evolves to version 2.0, by having dialects registered for that version specifically.

**Comment by amr** [comment]
I will work on a PR for adding a note of this to the docs as I wasted few hours debugging why my `t:text` wasn't actually doing anything. The problem was that I prefixed Thymeleaf as `t` instead of `th`

**Comment by danielfernandez** [comment]
@amr sorry, this ticket is quite outdated. Thymeleaf 3.0 will actually remove markup validation support (not even DTD-based), as very few people actually use it, and it adds an important load of complexity to the parsing system. So there is little use in adding this XSD Schema support in the near future. I'm closing this ticket as declined.
