### ISSUE TITLE
Web Flow view support for Spring Framework 6

### ISSUE THREAD

**Issue by rstoyanchev** [thymeleaf/thymeleaf#900]
Web Flow is getting upgraded to Spring Framework 6, Java 17+ and Jakarta EE. The main branch is already building with that after https://github.com/spring-projects/spring-webflow/pull/109. It would be great to re-introduce [FlowAjaxThymeleafView](https://github.com/thymeleaf/thymeleaf-spring/blob/3.1-master/thymeleaf-spring5/src/main/java/org/thymeleaf/spring5/webflow/view/FlowAjaxThymeleafView.java) in the `thymeleaf-spring6` module, especially given the lack of compatible Tiles support.

In the mean time, the Web Flow booking-mvc sample has been upgraded to use thymeleaf-6, replacing Tiles with Thymeleaf. The sample contains [these classes](https://github.com/spring-projects/spring-webflow-samples/tree/main/booking-mvc/src/main/java/org/thymeleaf/spring6/view) temporarily, and it's all working with them in place.

**Comment by danielfernandez** [comment]
Thanks @rstoyanchev. Transferring issue to the `thymeleaf` project because `thymeleaf-spring` and many other repos are in process of being unified here for 3.1.
