### ISSUE TITLE
side effects of th:block

### ISSUE THREAD

**Issue by liunancun** [thymeleaf/thymeleaf#903]
![image](https://user-images.githubusercontent.com/12378933/184791677-3461114b-fcf0-40eb-8c7e-1eebd8d01d88.png)

As shown in the figure, after using the th:block tag, IDEA will prompt that the xml format does not conform to the xsd specification.

![image](https://user-images.githubusercontent.com/12378933/184791937-0c0a6100-5628-41df-8044-9fb877c54d95.png)

As shown in the figure, after using the comment syntax, there will be an error that the amazonTemplate variable cannot be parsed.

**Comment by danielfernandez** [comment]
IntelliJ IDEA's Thymeleaf plugin is not managed by the Thymeleaf project, but by Jetbrains.
