### ISSUE TITLE
Circular reference in pom files

### ISSUE THREAD

**Issue by ygogolitsyn** [thymeleaf/thymeleaf#908]
The current 3.1-master branch of thymeleaf contains circular reference and cannot be build with Maven by running "mvn clean package". Here is the error message:

C:\OpenSourceWork\thymeleaf>mvn clean package
[INFO] Scanning for projects...
[ERROR] [ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.thymeleaf.testing:thymeleaf-testing:3.1.0-SNAPSHOT'}' and 'Vertex{label='org.thymeleaf:thymeleaf:3.1.0-SNAPSHOT'}' introduces to cycle in the graph org.thymeleaf:thymeleaf:3.1.0-SNAPSHOT --> org.thymeleaf.testing:thymeleaf-testing:3.1.0-SNAPSHOT --> org.thymeleaf:thymeleaf:3.1.0-SNAPSHOT @
[ERROR] The projects in the reactor contain a cyclic reference: Edge between 'Vertex{label='org.thymeleaf.testing:thymeleaf-testing:3.1.0-SNAPSHOT'}' and 'Vertex{label='org.thymeleaf:thymeleaf:3.1.0-SNAPSHOT'}' introduces to cycle in the graph org.thymeleaf:thymeleaf:3.1.0-SNAPSHOT --> org.thymeleaf.testing:thymeleaf-testing:3.1.0-SNAPSHOT --> org.thymeleaf:thymeleaf:3.1.0-SNAPSHOT -> [Help 1]

**Comment by danielfernandez** [comment]
Unfortunately there is no way to make Maven test lib modules after building the testing libraries, so tests finally had to be kept in separate modules in the multiproject. This is therefore fixed now.
