### ISSUE TITLE
Ability to access "request" instance from WebContext

### ISSUE THREAD

**Issue by petejohanson** [thymeleaf/thymeleaf#91]
Te new WebVariablesMap class provides access to a "params", "session" and "application" variables, which is handy, but I need to access properties of the request object itself.

I know I can manually add the request to my variables on a case-by-case basis, but what do people think about adding it in WebContext/WebVariablesMap automatically?

If yes, I'm happy to submit a pull request.

Thanks.

**Comment by danielfernandez** [comment]
Hi,

The `HttpServletRequest` object is always added, and can be accessed from standard expressions as `#httpServletRequest`. So, for example, you coud have:

``` java
    <tr th:each="cookie : ${#httpServletRequest.cookies}">
```

And you can call any method (not only getters):

``` java
    <span th:text="${#httpServletRequest.isRequestedSessionIdFromCookie()}">
```

Is this what you were looking for?

**Comment by petejohanson** [comment]
That's it exactly! I had tried simply `${httpServletRequest.servletPath}` previously, I forgot to include the `#`.

Thanks.
