### ISSUE TITLE
When using the preprocessing expression and dates.format at the same time, the date is added by 1 day

### ISSUE THREAD

**Issue by xg578962913** [thymeleaf/thymeleaf#911]
The date is 2022/09/27、
My HTML looks like this
date1  Use the preprocessing expression to get the value of field   (The date has been increased by one day)
date2  get the value through object.field (normal)
```
      <span id="tri_Form01/field01">
            <label>date1</label>
             [[${#dates.format('__${tutorialAppForm.dateField}__', 'yyyy/MM/dd')}]]
        </span>
        <br />
        <span id="tri_Form01/field02">
            <label>date2</label>
             [[${#dates.format(tutorialAppForm.dateField, 'yyyy/MM/dd')}]]
        </span>
```
My controller
```
    @GetMapping(value = "test")
    public String action01(TutorialAppForm form, Model model, HttpSession session) {
		Date date =  new Date();
		form.setDateField(date);
//		SimpleDateFormat timeformat1 = new SimpleDateFormat("yyyy/MM/dd");
//		String st = timeformat1.format(date);
//		System.out.println(st);
        return "test";
    }
```
The value of the date object is 2022/09/27
![image](https://user-images.githubusercontent.com/24224600/192760332-8174b1ec-91d4-4f24-a9eb-c79166053f94.png)
And the date obtained through SimpleDateFormat in Java is also 2022/09/27

 in Browser
![image](https://user-images.githubusercontent.com/24224600/192760582-f71053a8-f15d-42f4-9524-42c359620faf.png)
The date of date1 becomes 28
For the same object, the date increases by one day. Why

**Comment by danielfernandez** [comment]
This expression:
```
[[${#dates.format('__${tutorialAppForm.dateField}__', 'yyyy/MM/dd')}]]
```
…is getting an object of type `java.util.Date`, printing it as a String by using its `.toString()` method, which will use the operating systems, default timezone configuration, and then passing it to the `#dates.format` function which expects a `Date` argument, not a `String`. So the wrong formatting finally obtained is the result of bad handling of data types resulting in unexpected formatting results.
