### ISSUE TITLE
Integrate thymeleaf-extras-java8time module into core

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#912]
Given the minimum JDK requirements in Thymeleaf 3.1.0 will be increased to JDK 8, we should integrate the `thymeleaf-extras-java8time` module into the core, thus making the `#temporals` object accessible in the Standard dialects.

**Comment by JohnNiang** [comment]
Hi, I had tried to search the related PR and commit about this issue, but nothing I could find. I would appreciate it if you tell me the specific PR or commit.

BTW, I encountered a problem about thymeleaf-extras-java8time module in Spring Boot 3.0.0-RC1.

```bash
package org.thymeleaf.extras.java8time.dialect does not exist
```

**Comment by danielfernandez** [comment]
Thymeleaf's core (`thymeleaf`artifact) now includes the `#temporals` expression utility object in its Standard Dialect without any additional artifacts. Package `org.thymeleaf.extras.java8time.dialect` does no longer exist.

**Comment by JohnNiang** [comment]
Thank @danielfernandez for quick reply. I got the related commit at <https://github.com/thymeleaf/thymeleaf/commit/c79acde3647ad6daa45d4662110e22ee18af6fbd>.
