### ISSUE TITLE
Typo in release notes of 3.1.0.RC1

### ISSUE THREAD

**Issue by wimdeblauwe** [thymeleaf/thymeleaf#919]
The release notes of 3.1.0.RC1 have "3.0.1..." instead of "3.1.0....":

<img width="912" alt="image" src="https://user-images.githubusercontent.com/1115823/196475664-63e748f3-8204-47be-ac5b-c3f969fa8c7b.png">

**Comment by ultraq** [comment]
Haha, good spotting!  I'll fix those up right now
