### ISSUE TITLE
Add HTML5 data-* attribute support instead of th prefix

### ISSUE THREAD

**Issue by choreo** [thymeleaf/thymeleaf#93]
Add  "data-*" attribute instead of the th prefix when template mode is HTML5, to make Thymeleaf compatible with HTML5 validation.  Namespaces are not valid for html5.

Including dialect prefix in the attribute might be a good idea, such as 'data-th-text="${foobar}"' so one can make custom  dialects with its own prefix.

**Comment by paulkuhn12** [comment]
+1

**Comment by mxab** [comment]
hey, not sure if it's exactly what you want but I wrote a dialect for that

https://github.com/mxab/thymeleaf-extras-data-attribute

**Comment by jhcao23** [comment]
thymeleaf is a straightforward templating engine, so I assume we can just put data-whatever attribute in the html 5 tag.

**Comment by restfulhead** [comment]
+1 Please support data attribute

**Comment by mxab** [comment]
has anyone tried https://github.com/mxab/thymeleaf-extras-data-attribute ? :)

**Comment by emilime** [comment]
+1

**Comment by noelob** [comment]
@mxab i've tried it, works great!

**Comment by danielfernandez** [comment]
This has been implemented as follows:
- Every attribute with name `data-{prefix}-{name}` will be considered equivalent to `{prefix}:{name}` as long as `{prefix}` corresponds to the prefix of a configured dialect. For example, `data-th-text="..."` can be now used interchangeabily with `th:text="..."`. This follows the HTML5 standard for custom attributes.
- Every element (tag) with name `{prefix}-{name}` will be considered equivalent to `{prefix}:{name}` as long as `{prefix}` corresponds to the prefix of a configured dialect. For example, `<th-block ...>` can be now used interchangeabily with `<th:block ...>`. This follows the W3C _Custom Elements_ specification: https://dvcs.w3.org/hg/webcomponents/raw-file/tip/spec/custom/index.html.

Correctly matching these attributes is the responsibility of the `IProcessorMatcher` objects used by the dialects' processors. As long as these processors use the out-of-the-box implementations called `AttributeNameProcessorMatcher` and `ElementNameProcessorMatcher`, this feature will be automatically available.

**Comment by danielfernandez** [comment]
Updated 2.1.0-SNAPSHOT.

Also, a new milestone version 2.1.0-m3 has been pushed to the Central maven repositories, including this feature (and the rest of the features already implemented for 2.1.0).

**Comment by emilime** [comment]
@danielfernandez so, which is the proper way to write a custum data attribute in 2.1? I mean something like data-pippo="..." (where value of the attribute could be a variable)

**Comment by danielfernandez** [comment]
@emilime custom data attributes (i.e. attributes not included in any thymeleaf dialect) can be set using `th:attr` or the new `data-th-attr` syntax. Like:

``` html
<div data-th-attr="data-pippo=${myvalue}">...</div>
```

Note that the `data-{prefix}-{name}` syntax is new in 2.1, but doing this was already possible in 2.0 using the namespaced `{prefix}:{name}`:

``` html
<div th:attr="data-pippo=${myvalue}">...</div>
```

**Comment by emilime** [comment]
yes I know th:attr, I was hoping for something less verbose with this new feature :)

**Comment by jomski2009** [comment]
This does not work when one needs multiple data attributes on an html tag. Please reopen and consider that use case.,

**Comment by danielfernandez** [comment]
@jomski2009 what do you mean?

**Comment by jomski2009** [comment]
I attempted to do the following...

```
<a href="#" data-th-attr="data-groupid=${somevalue}" data-th-attr="data-groupname=${someothervalue}></a>. 
```

This throws an exception.

**Comment by danielfernandez** [comment]
HTML forbids repeated attributes, so that code is not correct. However, `th:attr` and `data-th-attr` allow you to specify several attributes separated by commas, like:

``` html
<a href="#" 
   data-th-attr="data-groupid=${somevalue},
                 data-groupname=${someothervalue}">...</a>
```

**Comment by danielfernandez** [comment]
Also, if you prefer a different option, there is a dialect in the ecosystem which will allow you to specify any `data-*` attribute without using `data-th-attr`: http://www.thymeleaf.org/ecosystem.html#dataattrdialect

**Comment by jomski2009** [comment]
Ok. the comma was what I was missing. I'll give that a shot.

**Comment by ghost** [comment]
Hi  I have a requirement to give multiple values to attributes. its with the combination of angular and thymleaf with spring mvc. 
<div id="zipLookup" ng-controller="AddressManagementCtrl" data-th-attr="data-data=*{primary.zipcode}, *{primary.county},*{primary.city},*{primary.street1},*{primary.street2}">

the intention is the after document should look something like this:
here zipcode, state,county,city,addressline1,addressline2 are properties of bean.
data-data='{
          "zipCode": "90292",
          "state": "CA",
          "county": "--",
          "city": "Marina",
          "addressLine1": "...",
          "addressLine2": "..."
      }'>
I'm kind of new to thymeleaf and angular js. can some one help? is there a way to implement this?

**Comment by jzaruba** [comment]
I was hoping for something like

``` html
<a th-data-yin="#{message.yin}" th-data-yang="#{message.yang}"/>
```

or

``` html
<a data-th-yin="#{message.yin}" data-th-yang="#{message.yang}"/>
```

**Comment by tejas619** [comment]
For <iframe id="id1" data-host="hostname"></iframe> 
How do I insert variable in the data-host attribute of thr iframe tag?
data-host-th-text=${var} is not working for me.

**Comment by danielfernandez** [comment]
@tejas619 if you are using Thymeleaf 3, either `th:data-host="${var}"` or `data-th-data-host="${var}"` should work for you. If you are using a previous version, then `th:attr="data-host=${var}"` or `data-th-attr="data-host=${var}"`

**Comment by tejas619** [comment]
Worked for me. Thanks @danielfernandez

**Comment by ayoubAnbara** [comment]
Hello @choreo ,
If I build a web application for the public, I mean I want to have a good score in SEO, do you recommend using **data-** prefix for attribute names instead of using just **th:*** ?
PS:
When I use **th:*** , I see that the render HTML page does not contain this prefix, it is a valid HTML page.
