### ISSUE TITLE
html attribute contains & ' , not work

### ISSUE THREAD

**Issue by lcak00** [thymeleaf/thymeleaf#935]
I want 
```
<a href="#" data-bind="attr:{href:'query?users=${users}&whseid=${whseid}&id='+ID'}" > ..
```
render to
```
<a href="#" data-bind="attr:{href:'query?users=xxx&whseid=xxx&id='+ID'}" > ..
```
i try'd 
`th:data-bind='${"attr:{href:''query?users="+${users}+"&whseid="+${whseid}+"&id=''+ID''}"}'`
or
`th:data-bind="|attr:{href:'query?users=${users}&whseid=${whseid}&id='+ID'}|"`
but not work, 
it seems hard

**Comment by danielfernandez** [comment]
Please note that if the value of one of your HTML attributtes (like `th:data-bind`) is surrounded by single quotes, you need to escape any internal single quotes. And the same with double quotes. This is per the HTML specification.
