### ISSUE TITLE
`ExpressionUtils` should not reject data types in java.sql.*

### ISSUE THREAD

**Issue by kaonashi97** [thymeleaf/thymeleaf#936]
Hi,

I'm using Thymeleaf in my application. Given the following: the entities are read from database using Hibernate. In my case, the entity classes are provided by another team. So I have no direct control over these entities. For simplicity I'm using the entities in my model. So I can use them in my HTML templates. (The UI only reads the entities from the database).

In #871 the access to the SQL type classes `Date`, `Time` and `Timestamp` was restricted.

Given the following template:
```html
<!-- ... -->
<tbody>
    <tr th:each="chain : ${chains}">
        <!-- ... -->
        <td th:text="${chain.id}"></td>
        <td th:data-sort="${chain.creationDate.getTime()}">
            <span th:text="${#calendars.format(chain.creationDate,'dd.MM.YYYY HH:mm:ss')}"></span>
        </td>
        <!-- ... -->
    </tr>
</tbody>
<!-- ... -->
```

Given the following JPA entity:
```java
import java.io.Serializable;
import java.sql.Timestamp;

@Entity
@Table(name = "CHAIN")
public class Chain implements Serializable {
    // ...
    @Column(name = "creation_date")
    private Timestamp creationDate;
    // ...
}
```

When running the application I get the following error:
`Calling method 'getTime' is forbidden for type 'class java.sql.Timestamp' in Thymeleaf expressions. Blocked classes are: [com.sun.*, jakarta.*, java.*, javax.*, jdk.*, org.ietf.jgss.*, org.omg.*, org.w3c.dom.*, org.xml.sax.*, sun.*]. Allowed classes are: [java.lang.Boolean, java.lang.Byte, java.lang.Character, java.lang.Double, java.lang.Enum, java.lang.Float, java.lang.Integer, java.lang.Iterable, java.lang.Long, java.lang.Math, java.lang.Number, java.lang.Short, java.lang.String, java.math.BigDecimal, java.math.BigInteger, java.math.RoundingMode, java.time.*, java.util.ArrayList, java.util.Calendar, java.util.Calendar, java.util.Collection, java.util.Date, java.util.Enumeration, java.util.HashMap, java.util.HashSet, java.util.Iterator, java.util.LinkedHashMap, java.util.LinkedHashSet, java.util.LinkedList, java.util.List, java.util.Locale, java.util.Map, java.util.Map$Entry, java.util.Optional, java.util.Properties, java.util.Set, java.util.stream.Stream].`

Is there a chance, to allow the following classes as well:

* `java.sql.Date`
* `java.sql.Time`
* `java.sql.Timestamp`

~Kaonashi

**Comment by danielfernandez** [comment]
Date/Time related classes in `java.sql` should be harmless. Makes sense to allow them IMO.
