### ISSUE TITLE
Thymeleaf not removing <html> tags from generated content

### ISSUE THREAD

**Issue by KrunchMuffin** [thymeleaf/thymeleaf#942]
Could anyone please explain this to me? I don't get it. Everything is as it should be. More concerned with the <HTML> and <doctype> tags not being removed.

![image](https://user-images.githubusercontent.com/1037197/213817469-fb1fc243-2db4-4497-876a-101561b0ed3a.png)

**Comment by danielfernandez** [comment]
Closing this as no further explanation has been provided about what result is expected and/or what did the original template look like and why its rendition was being considered incorrect. Please reopen if further detail can be added.
