### ISSUE TITLE
Thymeleaf (sometimes?) calls an isX() method for a non-boolean field

### ISSUE THREAD

**Issue by NadChel** [thymeleaf/thymeleaf#953]
I have this code in my view
```html
<form th:action="@{/save-user}" th:object="${user}" method="post">
<!-- some other forms -->
<input type="hidden" th:field="*{enabled}" />
```
`enabled` is a field of the type `byte` that stores either zero or one (it's necessary for Spring Security purposes)
```java
@Entity
@Table(name = "users")
public class User implements UserDetails {
// ...
    @Column
    private byte enabled;
// ...
    public byte getEnabled() {
        return enabled;
    } // I have a getter for the field
```
The `User` class also has this method
```java
    @Override
    public boolean isEnabled() {
        return enabled == 1;
    }
```
As you see, it returns a `boolean`

I noticed that when I use this expression `th:field="*{enabled}"`, Thymeleaf for some reason calls that `boolean` method instead of calling a getter for the `enabled` field

![2023-03-31_14-17-23](https://user-images.githubusercontent.com/121400546/229114517-9bce9bf5-3fec-4fbe-89ac-c0043f61ba8f.png)

It causes an error
```
ERROR 5880 --- [nio-8080-exec-6] o.a.c.c.C.[.[.[/].[dispatcherServlet]    : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.thymeleaf.exceptions.TemplateProcessingException: Error during execution of processor 'org.thymeleaf.spring5.processor.SpringInputGeneralFieldTagProcessor' (template: "user-update-info" - line 53, col 34)] with root cause

java.lang.IllegalArgumentException: Source to convert from must be an instance of [@javax.persistence.Column byte]; instead it was a [java.lang.Boolean]
```
I know I can call the getter explicitly (in my opinion, it makes the code a bit uglier)

![2023-03-31_14-18-03](https://user-images.githubusercontent.com/121400546/229114573-cb057e8c-23bc-44ae-8f61-54f334db8aca.png)

but it still looks like something that needs to be fixed

**Comment by danielfernandez** [comment]
Form-binding is not actually performed by Thymeleaf but by Spring. Also, what you describe looks like expected behaviour given `is*` methods are one of the correct naming strategies for _getter_ methods of boolean fields, so I think it's normal that Spring identifies that one as the method to be called, judging that the bean property to be set is of type boolean instead of byte.

I suggest you avoid keeping both `get*` and `is*` methods for the same property in a form-bound object.
