### ISSUE TITLE
`content()` causes `StackOverflow` when used by itself

### ISSUE THREAD

**Issue by slava110** [thymeleaf/thymeleaf#957]
## Versions
Spring version: **3.1.0-SNAPSHOT**
Thymeleaf version: **3.1.1.RELEASE**

# Problem
Hi. I wanted to create some kind of 'wrapper' fragment for elements. However, it's throwing `StackOverflowException` on parsing. Looks like `content()` only works in combination with other selectors (for example `div/content()`). Is it a bug or is it intended?

# Example code
**index.html**
```html
<div th:replace="~{fragments/container:: container(content=~{ :: content() }">
    <div class="item">
        <h1>Test content</h1>
    </div>
    <p>Cool!</p>
</div>
```

**fragments/container.html**
```html
<body th:fragment="container(content)">
    <p>Some text above</p>
    <div th:replace="${content}"></div>
    <p>Some text below</p>
</body>
```

## Expected output
**index.html**
```html
<body>
    <p>Some text above</p>
    <div class="item">
        <h1>Test content</h1>
    </div>
    <p>Cool!</p>
    <p>Some text below</p>
</body>
```
## Error
![image](https://user-images.githubusercontent.com/26705162/236921324-bab201dc-b4d4-4b88-b7d0-e5a1d771db9b.png)

**Comment by duoduobingbing** [comment]
This rightfully causes a `StackOverflowException` because `content()` selects the entire element including its outer tags.

`~{ :: content() }` will resolve to (including `th:replace=...`)
```html
<div th:replace="~{fragments/container:: container(content=~{ :: content() }">
    <div class="item">
        <h1>Test content</h1>
    </div>
    <p>Cool!</p>
</div>
```

Thus in the first iteration it becomes:
```html
<body>
    <p>Some text above</p>
       <div th:replace="~{fragments/container:: container(content=~{ :: content() }">
         <div class="item">
           <h1>Test content</h1>
         </div>
        <p>Cool!</p>
       </div>
    <p>Some text below</p>
</body>
```

And then `th:replace="..."` will be re-resolved over and over.

## Fix
This is why `<div th:replace="~{fragments/container:: container(content=~{ :: /div/content() }">` works, because this resolves to 
```html
    <div class="item">
        <h1>Test content</h1>
    </div>
    <p>Cool!</p>
``` 
excluding the `th:replace`

**Comment by danielfernandez** [comment]
@duoduobingbing 's explanation is correct. Alternatively you could also set `th:ref="parent"` in your `<div th:replace=...>` and then use the expression `~{::parent/content()}`
