### ISSUE TITLE
th:field does not work with `input type="date"` and `java.time.LocalDate`

### ISSUE THREAD

**Issue by MasatoshiTada** [thymeleaf/thymeleaf#964]
# Version of Thymeleaf (and any involved extensions) you are using.
- thymeleaf-spring6 3.1.1.RELEASE

# Environment: versions of Spring, Spring Boot, or any other relevant libraries.
- spring-boot-starter-thymeleaf 3.1.2
- JDK 17
- Web browser: Microsoft Edge 114.0.1823.82, Safari 16.5.2
- macOS Ventura 13.4.1 (c)

# Detailed steps to reproduce your issue.
(1) Create a form class that has a `LocalDate` field.

```java
import java.time.LocalDate;

public record SampleForm(String name, LocalDate birthday) {
}
```

(2) Create a controller.

```java
    @GetMapping("/")
    public String index(Model model) {
        model.addAttribute("sampleForm", new SampleForm("John Smith", LocalDate.of(2001, 1, 1)));
        return "index";
    }
```

(3) Create a corresponding view which has `<input type="date" th:field="*{fieldName}">`.

```html
    <form th:object="${sampleForm}">
        <input type="text" name="name" th:field="*{name}">
        <input type="date" name="birthday" th:field="*{birthday}">
    </form>
```

(4) Run the app and access it from a browser. `value` should be `2001-01-01` but it is `2001/01/01`.

<img width="1232" alt="screenshot" src="https://github.com/thymeleaf/thymeleaf/assets/7044137/8d4f24ad-4751-46b4-9323-15fcd3722648">

# Any possible workarounds you may have found.
Use `th:value` instead.

# Reproducible app
https://github.com/MasatoshiTada/thymeleaf-localdate-sample

Run `ThymeleafLocaldateSampleApplication` and access to http://localhost:8080/

**Comment by MasatoshiTada** [comment]
`spring.mvc.format.date=iso` is also workaround.
But this property is not for output.
I think any date values should be always formatted to `yyyy-mm-dd` for `input type="date"`.

**Comment by danielfernandez** [comment]
Actually, Thymeleaf doesn't not control how the values of form fields are rendered in `th:field`. Value rendering is delegated to Spring's _property editor_ infrastructure, which is why setting a Spring property works for you.
