### ISSUE TITLE
Add th:else in th:if block

### ISSUE THREAD

**Issue by morellik** [thymeleaf/thymeleaf#976]
Using Thymeleaf more and more times I'd use th:if with some conditions and reversed conditions to simulate the else.

Can you implement a th:else instruction?

**Comment by jmiguelsamper** [comment]
Hello Morellink, thanks for your suggestion.

While Thymeleaf does not have a _th:else_ option, it has two similar options, which are _th:unless_ and _th:case="*"_. You can read about them at https://www.thymeleaf.org/doc/tutorials/3.1/usingthymeleaf.html#conditional-evaluation

The more natural way is using _th:unless_ but it is true that you have to repeat the condition twice in your code, as in:

```
<div th:if="${condition}">CONDITION MATCHES</div>
<div th:unless="${condition}">OTHERWISE</div>
```

I usually use this without a lot of hassle.

Anyway, if you don't want to repeat the condition, for most cases you could use a switch statement, as in:

```
<div th:switch="${whatever}">
   <div th:case="value">CONDITION MATCHES</div>
   <div th:case="*">OTHERWISE</div>
</div>
```

We will take into account your suggestion if the template language is expanded in the future.
