### ISSUE TITLE
Restricted types no longer usable with th:with in 3.1.2

### ISSUE THREAD

**Issue by wimdeblauwe** [thymeleaf/thymeleaf#977]
In my book Taming Thymeleaf, I use th:with like this:

```
th:with="urlBuilder=${T(org.springframework.web.servlet.support.ServletUriComponentsBuilder)}"
```

This worked until the upgrade of Spring Boot 3.0.10 that uses Thymeleaf 3.1.2. I could not find something in [the release notes](https://github.com/thymeleaf/thymeleaf/milestone/69?closed=1) that describes this change. There is https://github.com/thymeleaf/thymeleaf/issues/966 but that is about `org.springframework.util`, but this class is not in that package.

Is the behaviour of 3.1.2 intentional? Can I no longer use `th:with` like this?

**Comment by danielfernandez** [comment]
Unfortunately that's correct. Classes in `org.springframework.web` and several other packages were forbidden as a part of general security-strengthening measures in 3.1.2.

Note however that there is a `#mvc` expression utility object precisely related to URL building in Spring MVC applications and which might fit your needs: https://www.thymeleaf.org/doc/tutorials/3.1/thymeleafspring.html#building-uris-to-controllers

**Comment by wimdeblauwe** [comment]
I was not able to use `#mvc` for my use case. See https://www.wimdeblauwe.com/blog/2023/10/19/taming-thymeleaf-update-for-thymeleaf-3.1.2/ for details on how it fixed it if you are interested.
