### ISSUE TITLE
Ability to reuse variables in th:with

### ISSUE THREAD

**Issue by danielfernandez** [thymeleaf/thymeleaf#98]
See http://forum.thymeleaf.org/Reusing-variables-from-the-same-th-with-td4025255.html

This would allow refactorization of th:with expressions, and could significantly reduce the length of the expressions declared there.

**Comment by rymsha** [comment]
One more way to "reduce" the length of expressions would be to allow more than one th:with in one tag. (maybe it should be a separate issue?)

**Comment by ugate** [comment]
+1

I'd deprecate `th:with` in favor of `th:var` to clarify its intent
