### ISSUE TITLE
GraalVM potential missing reachability metadata

### ISSUE THREAD

**Issue by francis-a** [thymeleaf/thymeleaf#987]
Thank you for providing GraalVM reachability metadata to https://github.com/oracle/graalvm-reachability-metadata.

I believe the published metadata may be missing a class accessed via reflection:

```
  {
    "name": "org.thymeleaf.engine.IterationStatusVar",
    "allDeclaredConstructors": true,
    "allPublicConstructors": true,
    "allDeclaredMethods": true,
    "allPublicMethods": true,
    "allDeclaredClasses": true,
    "allPublicClasses": true
  }
```

I noticed this when using iterator status (specifically `last`) in a template: https://www.thymeleaf.org/doc/tutorials/2.1/usingthymeleaf.html#keeping-iteration-status

Updating my projects local metadata with this value fixed the issue.

**Comment by exoego** [comment]
I've created a PR for this issue: https://github.com/oracle/graalvm-reachability-metadata/pull/526

**Comment by exoego** [comment]
https://github.com/oracle/graalvm-reachability-metadata/releases/tag/0.3.10
The change was released.

**Comment by francis-a** [comment]
Thanks @exoego, I will close out this issue
